import { makeSpline } from '../splineAuthoring';

const BURNING_AT_BOTH_ENDS_FIRE = {
  splines: [
    makeSpline({
      name: 'Top Wick Fire',
      type: 'Fire',
      fireType: 'Classic',
      tension: 0.5,
      closed: false,
      fireWidth: 0.8,
      fireHeight: 2.0,
      fireDepth: 0.725,
      fireSliceSpacing: 0.05,
      fireMagnitude: 0.5,
      fireLacunarity: 4.0,
      fireGain: 0.0,
      fireTintColor: '#ffffff',
      fireSaturation: 1.0,
      fireBrightness: 1.5,
      fireAnimated: true,
      fireAnimSpeed: 0.5,
      pos: [0.06, 3.21, 0.06],
      points: [
        [0, 0, 0],
        [0.01, 0.31, 0],
        [0.02, 0.65, 0],
        [0.02, 1.01, 0],
      ],
    }),
    makeSpline({
      name: 'Bottom Wick Fire',
      type: 'Fire',
      fireType: 'Classic',
      tension: 0.5,
      closed: false,
      fireWidth: 0.8,
      fireHeight: 2.0,
      fireDepth: 0.725,
      fireSliceSpacing: 0.05,
      fireMagnitude: 0.5,
      fireLacunarity: 4.0,
      fireGain: 0.0,
      fireTintColor: '#ffffff',
      fireSaturation: 1.0,
      fireBrightness: 1.5,
      fireAnimated: true,
      fireAnimSpeed: 0.5,
      pos: [0.06, -3.21, 0.06],
      points: [
        [0, 0, 0],
        [0.01, -0.31, 0],
        [0.02, -0.65, 0],
        [0.02, -1.01, 0],
      ],
    }),
    makeSpline({
      name: 'Top Wick Smoke',
      type: 'Smoke',
      smokeType: 'Volumetric',
      tension: 0.3,
      closed: false,
      volParticleCount: 8000,
      volColor: '#b8b8b8',
      volOpacity: 0.01,
      volSize: 1,
      volBlendMode: 'Normal',
      volSpread: 0.35,
      volSpringK: 1.2,
      volDamping: 0.06,
      volTurbulence: 2,
      volTurbulenceSpeed: 0.25,
      volMaxDrift: 2.4,
      flowSpeed: 0.04,
      fadeRate: 4,
      pos: [0.18, 3.34, 0.088],
      points: [
        [0, 0, 0],
        [0, 0.75, 0],
        [0, 1.5, 0],
        [0, 2.25, 0],
        [0, 3, 0],
      ],
    }),
    makeSpline({
      name: 'Bottom Wick Smoke',
      type: 'Smoke',
      smokeType: 'Volumetric',
      tension: 0.3,
      closed: false,
      volParticleCount: 8000,
      volColor: '#b8b8b8',
      volOpacity: 0.01,
      volSize: 1,
      volBlendMode: 'Normal',
      volSpread: 0.35,
      volSpringK: 1.2,
      volDamping: 0.06,
      volTurbulence: 2,
      volTurbulenceSpeed: 0.25,
      volMaxDrift: 2.4,
      flowSpeed: 0.04,
      fadeRate: 4,
      pos: [0.18, -3.34, 0.088],
      points: [
        [0, 0, 0],
        [0, -0.75, 0],
        [0, -1.5, 0],
        [0, -2.25, 0],
        [0, -3, 0],
      ],
    }),
  ],
};

export default BURNING_AT_BOTH_ENDS_FIRE;
