import { makeSpline } from '../splineAuthoring';

const FLYING_HIGH_FIRE = {
  splines: [
    makeSpline({
      name: 'Left Engine Main Fire',
      type: 'Fire',
      fireType: 'Classic',
      tension: 0.25,
      closed: false,
      fireWidth: 0.5,
      fireHeight: 1.8,
      fireDepth: 0.5,
      fireSliceSpacing: 0.08,
      fireMagnitude: 1.6,
      fireBrightness: 2.2,
      fireSaturation: 0.9,
      fireAnimated: true,
      fireAnimSpeed: 0.85,
      fireTintColor: '#ffcc44',
      pos: [-1.8, 0.0, 0.3],
      points: [
        [0, 0, 0],
        [-0.2, 0.5, -1.1],
        [-0.4, 1.2, -2.4],
        [-0.4, 2, -3.9],
      ],
    }),
    makeSpline({
      name: 'Right Engine Main Fire',
      type: 'Fire',
      fireType: 'Classic',
      tension: 0.25,
      closed: false,
      fireWidth: 0.5,
      fireHeight: 1.8,
      fireDepth: 0.5,
      fireSliceSpacing: 0.08,
      fireMagnitude: 1.6,
      fireBrightness: 2.2,
      fireSaturation: 0.9,
      fireAnimated: true,
      fireAnimSpeed: 0.75,
      fireTintColor: '#ffcc44',
      pos: [1.8, 0.0, 0.3],
      points: [
        [0, 0, 0],
        [0.2, 0.5, -1.1],
        [0.4, 1.2, -2.4],
        [0.4, 2, -3.9],
      ],
    }),
    makeSpline({
      name: 'Left Wing Secondary Fire',
      type: 'Fire',
      fireType: 'Classic',
      tension: 0.25,
      closed: false,
      fireWidth: 0.35,
      fireHeight: 1.2,
      fireDepth: 0.35,
      fireSliceSpacing: 0.1,
      fireMagnitude: 1.4,
      fireBrightness: 1.8,
      fireAnimated: true,
      fireAnimSpeed: 1.1,
      fireTintColor: '#ff8833',
      pos: [-1.4, 0.3, -0.2],
      points: [
        [0, 0, 0],
        [-0.1, 0.5, -0.9],
        [-0.2, 1.0, -1.8],
      ],
    }),
    makeSpline({
      name: 'Right Wing Secondary Fire',
      type: 'Fire',
      fireType: 'Classic',
      tension: 0.25,
      closed: false,
      fireWidth: 0.35,
      fireHeight: 1.2,
      fireDepth: 0.35,
      fireSliceSpacing: 0.1,
      fireMagnitude: 1.4,
      fireBrightness: 1.8,
      fireAnimated: true,
      fireAnimSpeed: 1.0,
      fireTintColor: '#ff8833',
      pos: [1.4, 0.3, -0.2],
      points: [
        [0, 0, 0],
        [0.1, 0.5, -0.9],
        [0.2, 1.0, -1.8],
      ],
    }),
    makeSpline({
      name: 'Left Engine Smoke Trail',
      type: 'Smoke',
      smokeType: 'Particle',
      tension: 0.25,
      closed: false,
      particleCount: 500,
      particleSize: 90,
      particleColor: '#1f1c1a',
      opacity: 0.35,
      flowSpeed: 0.25,
      springK: 0.008,
      damping: 0.965,
      turbulence: 0.35,
      turbulenceSpeed: 0.6,
      buoyancy: 0.12,
      rotSpeed: 0.15,
      fadeRate: 0.4,
      spawnSpread: 0.6,
      blendMode: 'Normal',
      growth: 2.5,
      fadeExponent: 1.4,
      attractorStrength: 0,
      attractorRadius: 0,
      maxDrift: 10,
      pos: [-1.8, -0.1, 0.3],
      points: [
        [0, 0, 0],
        [-0.2, 0.7, -1.8],
        [-0.4, 1.7, -3.8],
        [-0.2, 3.1, -5.8],
        [0.2, 5.1, -7.8],
      ],
    }),
    makeSpline({
      name: 'Right Engine Smoke Trail',
      type: 'Smoke',
      smokeType: 'Particle',
      tension: 0.25,
      closed: false,
      particleCount: 500,
      particleSize: 90,
      particleColor: '#1f1c1a',
      opacity: 0.35,
      flowSpeed: 0.25,
      springK: 0.008,
      damping: 0.965,
      turbulence: 0.35,
      turbulenceSpeed: 0.6,
      buoyancy: 0.12,
      rotSpeed: 0.15,
      fadeRate: 0.4,
      spawnSpread: 0.6,
      blendMode: 'Normal',
      growth: 2.5,
      fadeExponent: 1.4,
      attractorStrength: 0,
      attractorRadius: 0,
      maxDrift: 10,
      pos: [1.8, -0.1, 0.3],
      points: [
        [0, 0, 0],
        [0.2, 0.7, -1.8],
        [0.4, 1.7, -3.8],
        [0.2, 3.1, -5.8],
        [-0.2, 5.1, -7.8],
      ],
    }),
  ],
};

export default FLYING_HIGH_FIRE;
