import * as THREE from 'three';

import { normalizeSplinePreset } from '../../components/elements/splineGroup/splineDefaults';

const V = (x, y, z) => new THREE.Vector3(x, y, z);
const E = (x, y, z) => new THREE.Euler(x, y, z);

const P = (x, y, z) => ({
  position: V(x, y, z),
  rotation: E(0, 0, 0),
  scale: V(1, 1, 1),
});

const FLYING_HIGH_FIRE = {
  splines: [
    {
      name: 'Left Engine Main Fire',
      type: 'Fire',
      fireType: 'Classic',
      tension: 0.25,
      closed: false,
      fireWidth: 0.5,
      fireHeight: 1.8,
      fireDepth: 0.5,
      fireSliceSpacing: 0.08,
      fireMagnitude: 1.6,
      fireBrightness: 2.2,
      fireSaturation: 0.9,
      fireAnimated: true,
      fireAnimSpeed: 0.85,
      fireTintColor: '#ffcc44',
      points: [
        P(-1.8, 0.0, 0.3),
        P(-2.0, 0.5, -0.8),
        P(-2.2, 1.2, -2.1),
        P(-2.2, 2.0, -3.6),
      ],
    },
    {
      name: 'Right Engine Main Fire',
      type: 'Fire',
      fireType: 'Classic',
      tension: 0.25,
      closed: false,
      fireWidth: 0.5,
      fireHeight: 1.8,
      fireDepth: 0.5,
      fireSliceSpacing: 0.08,
      fireMagnitude: 1.6,
      fireBrightness: 2.2,
      fireSaturation: 0.9,
      fireAnimated: true,
      fireAnimSpeed: 0.75,
      fireTintColor: '#ffcc44',
      points: [
        P(1.8, 0.0, 0.3),
        P(2.0, 0.5, -0.8),
        P(2.2, 1.2, -2.1),
        P(2.2, 2.0, -3.6),
      ],
    },
    {
      name: 'Left Wing Secondary Fire',
      type: 'Fire',
      fireType: 'Classic',
      tension: 0.25,
      closed: false,
      fireWidth: 0.35,
      fireHeight: 1.2,
      fireDepth: 0.35,
      fireSliceSpacing: 0.1,
      fireMagnitude: 1.4,
      fireBrightness: 1.8,
      fireAnimated: true,
      fireAnimSpeed: 1.1,
      fireTintColor: '#ff8833',
      points: [P(-1.4, 0.3, -0.2), P(-1.5, 0.8, -1.1), P(-1.6, 1.3, -2.0)],
    },
    {
      name: 'Right Wing Secondary Fire',
      type: 'Fire',
      fireType: 'Classic',
      tension: 0.25,
      closed: false,
      fireWidth: 0.35,
      fireHeight: 1.2,
      fireDepth: 0.35,
      fireSliceSpacing: 0.1,
      fireMagnitude: 1.4,
      fireBrightness: 1.8,
      fireAnimated: true,
      fireAnimSpeed: 1.0,
      fireTintColor: '#ff8833',
      points: [P(1.4, 0.3, -0.2), P(1.5, 0.8, -1.1), P(1.6, 1.3, -2.0)],
    },
    {
      name: 'Left Engine Smoke Trail',
      type: 'Smoke',
      smokeType: 'Particle',
      tension: 0.25,
      closed: false,
      particleCount: 500,
      particleSize: 90,
      particleColor: '#1f1c1a',
      opacity: 0.35,
      flowSpeed: 0.25,
      springK: 0.008,
      damping: 0.965,
      turbulence: 0.35,
      turbulenceSpeed: 0.6,
      buoyancy: 0.12,
      rotSpeed: 0.15,
      fadeRate: 0.4,
      spawnSpread: 0.6,
      blendMode: 'Normal',
      growth: 2.5,
      fadeExponent: 1.4,
      attractorStrength: 0,
      attractorRadius: 0,
      maxDrift: 10,
      points: [
        P(-1.8, -0.1, 0.3),
        P(-2.0, 0.6, -1.5),
        P(-2.2, 1.6, -3.5),
        P(-2.0, 3.0, -5.5),
        P(-1.6, 5.0, -7.5),
      ],
    },
    {
      name: 'Right Engine Smoke Trail',
      type: 'Smoke',
      smokeType: 'Particle',
      tension: 0.25,
      closed: false,
      particleCount: 500,
      particleSize: 90,
      particleColor: '#1f1c1a',
      opacity: 0.35,
      flowSpeed: 0.25,
      springK: 0.008,
      damping: 0.965,
      turbulence: 0.35,
      turbulenceSpeed: 0.6,
      buoyancy: 0.12,
      rotSpeed: 0.15,
      fadeRate: 0.4,
      spawnSpread: 0.6,
      blendMode: 'Normal',
      growth: 2.5,
      fadeExponent: 1.4,
      attractorStrength: 0,
      attractorRadius: 0,
      maxDrift: 10,
      points: [
        P(1.8, -0.1, 0.3),
        P(2.0, 0.6, -1.5),
        P(2.2, 1.6, -3.5),
        P(2.0, 3.0, -5.5),
        P(1.6, 5.0, -7.5),
      ],
    },
  ],
};

FLYING_HIGH_FIRE.splines = FLYING_HIGH_FIRE.splines.map(normalizeSplinePreset);

export default FLYING_HIGH_FIRE;
