import { makeSpline } from '../splineAuthoring';

const POLICE_PRESENCE_FIRE = {
  splines: [
    makeSpline({
      name: 'Windshield Fire',
      type: 'Fire',
      fireType: 'Classic',
      tension: 0.5,
      closed: false,
      fireWidth: 1.2,
      fireDepth: 0.8,
      fireHeight: 2.8,
      fireAnimated: true,
      fireAnimSpeed: 0.6,
      fireMagnitude: 1.5,
      fireBrightness: 1.6,
      pos: [0.6, 1.1, -4.0],
      points: [
        [0, 0, 0],
        [-0.1, 0.8, -0.1],
        [-0.2, 1.7, -0.2],
      ],
    }),
    makeSpline({
      name: 'Driver Window Fire',
      type: 'Fire',
      fireType: 'Classic',
      tension: 0.5,
      closed: false,
      fireWidth: 0.6,
      fireDepth: 0.5,
      fireHeight: 1.8,
      fireAnimated: true,
      fireAnimSpeed: 0.5,
      fireMagnitude: 1.3,
      fireBrightness: 1.4,
      pos: [0.0, 1.0, -4.72],
      points: [
        [0, 0, 0],
        [-0.2, 0.7, -0.18],
        [-0.35, 1.3, -0.38],
      ],
    }),
    makeSpline({
      name: 'Passenger Window Fire',
      type: 'Fire',
      fireType: 'Classic',
      tension: 0.5,
      closed: false,
      fireWidth: 0.6,
      fireDepth: 0.5,
      fireHeight: 1.8,
      fireAnimated: true,
      fireAnimSpeed: 0.55,
      fireMagnitude: 1.3,
      fireBrightness: 1.4,
      pos: [0.0, 1.0, -3.28],
      points: [
        [0, 0, 0],
        [-0.2, 0.7, 0.18],
        [-0.35, 1.3, 0.38],
      ],
    }),
    makeSpline({
      name: 'Hood Fire',
      type: 'Fire',
      fireType: 'Classic',
      tension: 0.5,
      closed: false,
      fireWidth: 0.9,
      fireDepth: 0.7,
      fireHeight: 1.5,
      fireAnimated: true,
      fireAnimSpeed: 0.45,
      fireMagnitude: 1.1,
      fireBrightness: 1.3,
      pos: [1.4, 0.85, -4.0],
      points: [
        [0, 0, 0],
        [0.1, 0.55, 0],
        [0.2, 1.15, 0],
      ],
    }),
    makeSpline({
      name: 'Roof Fire',
      type: 'Fire',
      fireType: 'Classic',
      tension: 0.5,
      closed: false,
      fireWidth: 1.0,
      fireDepth: 0.9,
      fireHeight: 2.2,
      fireAnimated: true,
      fireAnimSpeed: 0.55,
      fireMagnitude: 1.4,
      fireBrightness: 1.5,
      pos: [-0.4, 1.25, -4.0],
      points: [
        [0, 0, 0],
        [-0.2, 0.75, -0.1],
        [-0.4, 1.65, -0.3],
      ],
    }),
    makeSpline({
      name: 'Smoke Column',
      type: 'Smoke',
      smokeType: 'Particle',
      tension: 0.5,
      closed: false,
      particleCount: 400,
      particleSize: 70,
      particleColor: '#161616',
      opacity: 0.09,
      growth: 3.5,
      fadeExponent: 1.3,
      springK: 1.0,
      flowSpeed: 0.12,
      damping: 0.93,
      attractorStrength: 0,
      attractorRadius: 0,
      maxDrift: 4.0,
      turbulence: 0.6,
      turbulenceSpeed: 0.35,
      buoyancy: 0.8,
      rotSpeed: 0.2,
      fadeRate: 1.5,
      spawnSpread: 0.9,
      blendMode: 'Normal',
      pos: [0.3, 1.8, -4.0],
      points: [
        [0, 0, 0],
        [-0.2, 1.4, -0.1],
        [-0.5, 3.2, -0.3],
        [-0.9, 5.7, -0.5],
        [-1.3, 8.2, -0.8],
      ],
    }),
  ],
};

export default POLICE_PRESENCE_FIRE;
