// Keys match the Leva schema in useSceneControls 1:1.
export const DEFAULT_PRESET = 'Paper';

const SHARED = {
  buildIn: true,
  cardBob: 0,
  cardBobRate: 0.6,
  cardFloatJitter: 0,
  cardStack: 1,
  cardStackGap: 8,
  densityFalloff: 2,
  easing: 'smooth',
  edgeRadius: 1,
  emergeStyle: 'rise',
  glowMode: 'reference',
  groundPattern: 'none',
  landAreaDivisor: 9,
  neonChance: 0.1,
  neonFlicker: 0,
  neonFlickerRate: 8,
  overshoot: 1.7,
  patternScale: 16,
  patternStrength: 0.6,
  patternWidth: 0.12,
  pedestalDepth: 160,
  pitEvery: 3,
  pitStyle: 'shaft',
  pitTerraceInset: 3,
  rebuildOrder: 'sequential',
  splitJitter: 0.5,
  stairAreaDivisor: 8,
  stairDirection: 'random',
  stairTaperWall: false,
  streetGap: 4,
  subdivisionDepth: 2,
  towerAreaDivisor: 30,
  towerBandStrength: 0.25,
  towerBanding: 0,
  towerBreathe: 0,
  towerBreatheRate: 0.5,
  towerCenterBias: 0,
  towerHeightCurve: 1,
  towerHeightRange: 300,
  towerMinHeight: 20,
  buildSeconds: 8,
  cameraMode: 'orbit',
  cameraProjection: 'orthographic',
  cardThickness: 0.6,
  citySize: 12,
  honorSeedZoom: true,
  minTowerFootprint: 6,
  neonThickness: 0.5,
  orbitAutoRotate: true,
  orbitAutoRotateSpeed: 0.35,
  pitLayerDepth: 10,
  pitLayers: 10,
  pitLineWidth: 0.12,
  plazaLift: 1,
  rebuildSeconds: 6,
  referenceHeight: 900,
  revealBand: 0.3,
  rollingRebuild: true,
  stairAlphaStep: 0.15,
  stairDrop: 4,
  stairTaperScale: 0,
  towerHeightScale: 1,
  towerShadows: true,
};

export const PRESETS = {
  Paper: {
    ...SHARED,
    backgroundColor: '#fcfcfc',
    cameraFrustumHeight: 13,
    glowFloorColor: '#3c3c44',
    lightAmbientIntensity: 1.68,
    lightSunIntensity: 1.46,
    neonIntensity: 1.15,
    cardColor: '#fcfcfc',
    cardEdgeColor: '#fcfcfc',
    groundColor: '#fcfcfc',
    patternColor: '#d8d8d8',
    pedestalColor: '#fcfcfc',
    towerBaseColor: '#000000',
    neonAmberColor: '#ffcc00',
    neonCyanColor: '#00ffcc',
    neonMagentaColor: '#ff0066',
    pitColor: '#050505',
    pitFloorColor: '#000000',
    pitRimColor: '#bfbfbf',
    pitStrataColor: '#3a3a3a',
    pitStrataStrength: 0.5,
    postBloomStrength: 0.35,
    postBloomThreshold: 0.85,
    postGrainAmount: 0.063,
    postInkColor: '#000000',
    postInkStrength: 0.25,
    pulseDepth: 0.35,
    pulseRate: 1.1,
    riserShade: 0.8,
    ringColor: '#00aaff',
    ringIntensity: 1.8,
    seed: 2,
    stairHighColor: '#c8c8c8',
    stairLowColor: '#050505',
    towerBlend: 'ink',
    towerColor: '#000000',
    towerInk: 1,
    wellFalloff: 0.7,
    wellFloorColor: '#050505',
    wellWallColor: '#d6d6d6',
  },
  Night: {
    ...SHARED,
    backgroundColor: '#05070a',
    cameraFrustumHeight: 11,
    glowFloorColor: '#0a1420',
    lightAmbientIntensity: 1.2,
    lightSunIntensity: 1.94,
    neonIntensity: 3.6,
    cardColor: '#1a2230',
    cardEdgeColor: '#2b3a52',
    groundColor: '#121821',
    patternColor: '#1c2633',
    pedestalColor: '#121821',
    towerBaseColor: '#1d3a66',
    neonAmberColor: '#ffb000',
    neonCyanColor: '#00ffd5',
    neonMagentaColor: '#ff2a7a',
    pitColor: '#010203',
    pitFloorColor: '#000000',
    pitRimColor: '#1a222c',
    pitStrataColor: '#2b3540',
    pitStrataStrength: 0.4,
    postBloomStrength: 1.1,
    postBloomThreshold: 0.45,
    postGrainAmount: 0.1,
    postInkColor: '#67788c',
    postInkStrength: 0.45,
    pulseDepth: 0.7,
    pulseRate: 1.8,
    riserShade: 0.7,
    ringColor: '#28c8ff',
    ringIntensity: 5,
    seed: 7,
    stairHighColor: '#2b3540',
    stairLowColor: '#020305',
    towerBlend: 'glow',
    towerColor: '#6fa8ff',
    towerHeightScale: 1.4,
    towerInk: 1.2,
    wellFalloff: 0.8,
    wellFloorColor: '#020305',
    wellWallColor: '#1f2833',
  },
};

export function getPresetControls({ presetSnapshot }) {
  return { ...presetSnapshot };
}
