// Fluid config for Cardinals.
// debugXxx color/size fields drive the geometry marker layer.
// The shader debug flags (debugAutoSplat, debugCursor, etc.) stay false so
// the display shader does not render its own marker pass.

const SHARED = {
  paused: false,
  inputMode: 'pointer',
  autoSplat: true,
  autoSplatCount: 4,
  autoSplatStarts: [
    { x: 0.2, y: 0.2 },
    { x: 0.8, y: 0.2 },
    { x: 0.2, y: 0.8 },
    { x: 0.8, y: 0.8 },
  ],
  randomSplatStrength: 1,
  stationarySplatsEnabled: false,
  stationarySplatCount: 0,
  stationarySplats: [],
  debugCursor: false,
  debugAutoSplat: false,
  debugStationarySplat: false,
  debugRandomBurst: false,
  debugContactFadeDuration: 0.28,
  // Geometry marker appearance — shared defaults (Cardinals / Bluejays).
  debugAutoColor: '#000000',
  debugAutoWidth: 0.0375,
  debugAutoHeight: 0.0375,
  debugPointerColor: '#ffffff',
  debugPointerWidth: 0.024,
  debugPointerHeight: 0.024,
};

export const CARDINALS_PRESETS = {
  Cardinals: {
    ...SHARED,
    pressureRelax: 0.84,
    pressureIterations: 14,
    vorticity: 2,
    velocityDissipation: 0.4,
    densityDissipation: 1.6,
    splatRadius: 0.0022,
    autoSplatRadius: 0.0022,
    stationarySplatRadius: 0.0022,
    randomSplatRadius: 0.0022,
    splatForce: 4200,
    autoSplatForce: 4200,
    stationarySplatForce: 4200,
    dyeStrength: 2.5,
    autoSplatStrength: 0.24,
    autoSplatDyeStrength: 0.24,
    autoSplatRate: 25,
    autoSplatRange: 1,
    autoSplatBurst: 1,
    randomSplatDyeStrength: 2.5,
    randomSplatForce: 4200,
    shading: true,
    bloom: true,
    bloomResolution: 0.2,
    bloomIterations: 4,
    bloomIntensity: 0.5,
    bloomThreshold: 0.62,
    bloomSoftKnee: 0.7,
    sunrays: true,
    sunraysResolution: 0.16,
    sunraysWeight: 0.9,
    colorA: '#ff6d6d',
    colorB: '#ff0000',
    colorC: '#7b0000',
    colorful: true,
    colorUpdateSpeed: 20,
    colorCycleSpeed: 0.55,
    bgA: '#4b4b4b',
    bgB: '#797979',
    dithering: true,
    ditherStrength: 2.85,
    ditherScale: 1,
    brightness: 1.05,
    contrast: 1.16,
    saturation: 1.2,
    blendMode: 0,
  },

  // Ink on cream paper — multiply blend, no glow effects, dark ink tones.
  Magpies: {
    ...SHARED,
    pressureRelax: 0.88,
    pressureIterations: 26,
    vorticity: 18,
    velocityDissipation: 0.42,
    densityDissipation: 0.85,
    splatRadius: 0.0013,
    autoSplatRadius: 0.0013,
    stationarySplatRadius: 0.0013,
    randomSplatRadius: 0.0013,
    splatForce: 9000,
    autoSplatForce: 9000,
    stationarySplatForce: 9000,
    dyeStrength: 2.2,
    autoSplatStrength: 0.6,
    autoSplatDyeStrength: 0.6,
    autoSplatRate: 100,
    autoSplatRange: 1,
    autoSplatBurst: 2,
    randomSplatDyeStrength: 2.2,
    randomSplatForce: 9000,
    shading: false,
    bloom: false,
    bloomResolution: 0.22,
    bloomIterations: 4,
    bloomIntensity: 0.4,
    bloomThreshold: 0.7,
    bloomSoftKnee: 0.7,
    sunrays: false,
    sunraysResolution: 0.16,
    sunraysWeight: 0.8,
    colorA: '#000000',
    colorB: '#585858',
    colorC: '#8d8d8d',
    colorful: true,
    colorUpdateSpeed: 12,
    colorCycleSpeed: 0,
    bgA: '#fafaf9',
    bgB: '#f5f5f4',
    dithering: false,
    ditherStrength: 0.3,
    ditherScale: 1,
    brightness: 1,
    contrast: 1.15,
    saturation: 0.8,
    blendMode: 1,
    // Geometry markers — dark ink color, slightly smaller squares.
    debugAutoColor: '#111827',
    debugAutoWidth: 0.025,
    debugAutoHeight: 0.025,
    debugPointerColor: '#111827',
    debugPointerWidth: 0.025,
    debugPointerHeight: 0.025,
  },

  // Blue jays colorway — same dynamics as Cardinals but in indigo/blue.
  Bluejays: {
    ...SHARED,
    pressureRelax: 0.84,
    pressureIterations: 14,
    vorticity: 2,
    velocityDissipation: 0.4,
    densityDissipation: 1.6,
    splatRadius: 0.0022,
    autoSplatRadius: 0.0022,
    stationarySplatRadius: 0.0022,
    randomSplatRadius: 0.0022,
    splatForce: 4200,
    autoSplatForce: 4200,
    stationarySplatForce: 4200,
    dyeStrength: 2.5,
    autoSplatStrength: 0.24,
    autoSplatDyeStrength: 0.24,
    autoSplatRate: 25,
    autoSplatRange: 1,
    autoSplatBurst: 1,
    randomSplatDyeStrength: 2.5,
    randomSplatForce: 4200,
    shading: true,
    bloom: true,
    bloomResolution: 0.2,
    bloomIterations: 4,
    bloomIntensity: 0.5,
    bloomThreshold: 0.62,
    bloomSoftKnee: 0.7,
    sunrays: true,
    sunraysResolution: 0.16,
    sunraysWeight: 0.9,
    colorA: '#4d90ff',
    colorB: '#1a5eff',
    colorC: '#0a2e99',
    colorful: true,
    colorUpdateSpeed: 20,
    colorCycleSpeed: 0.55,
    bgA: '#4b4b4b',
    bgB: '#797979',
    dithering: true,
    ditherStrength: 2.85,
    ditherScale: 1,
    brightness: 1.05,
    contrast: 1.16,
    saturation: 1.2,
    blendMode: 0,
    // Geometry markers — dark navy auto squares, white cursor square.
    debugAutoColor: '#000022',
  },
};

export const PRESET_NAMES = Object.keys(CARDINALS_PRESETS);
export const DEFAULT_PRESET = 'Cardinals';
