const OCEAN_HEIGHT_GLSL = [
  'uniform float uTime;',
  'uniform float uSwellAmplitude;',
  'uniform float uSwellFrequency;',
  'uniform float uSwellSpeed;',
  'uniform float uChopAmplitude;',
  'uniform float uChopFrequency;',
  'uniform float uChopSpeed;',
  'uniform float uDetailAmplitude;',
  'uniform float uDetailFrequency;',
  'uniform float uDetailSpeed;',
  'uniform float uNormalEpsilon;',
  'uniform sampler2D uInteractionHeightmap;',
  'uniform float uInteractionBounds;',
  '',
  'const int SWELL_COUNT = 3;',
  'const int CHOP_COUNT = 3;',
  'const int DETAIL_COUNT = 3;',
  'vec4 swellWaves[SWELL_COUNT];',
  'vec4 chopWaves[CHOP_COUNT];',
  'vec4 detailWaves[DETAIL_COUNT];',
  '',
  'void initOceanWaves() {',
  '  swellWaves[0] = vec4(0.86, 0.51, 0.42, 1.0);',
  '  swellWaves[1] = vec4(-0.34, 0.94, 0.66, 0.72);',
  '  swellWaves[2] = vec4(0.57, -0.82, 0.92, 0.48);',
  '',
  '  chopWaves[0] = vec4(0.91, -0.21, 1.55, 1.0);',
  '  chopWaves[1] = vec4(-0.72, -0.69, 2.1, 0.65);',
  '  chopWaves[2] = vec4(0.18, 0.98, 2.65, 0.4);',
  '',
  '  detailWaves[0] = vec4(-0.9, 0.43, 4.2, 1.0);',
  '  detailWaves[1] = vec4(0.49, 0.87, 5.1, 0.58);',
  '  detailWaves[2] = vec4(-0.17, -0.98, 6.6, 0.32);',
  '}',
  '',
  'float sampleBaseOceanHeight(vec2 xz) {',
  '  float height = 0.0;',
  '',
  '  for (int i = 0; i < SWELL_COUNT; i++) {',
  '    vec2 direction = normalize(swellWaves[i].xy);',
  '    float theta =',
  '      dot(direction, xz) * swellWaves[i].z * uSwellFrequency +',
  '      uTime * uSwellSpeed * (0.55 + float(i) * 0.23);',
  '    height += sin(theta) * swellWaves[i].w * uSwellAmplitude;',
  '  }',
  '',
  '  for (int i = 0; i < CHOP_COUNT; i++) {',
  '    vec2 direction = normalize(chopWaves[i].xy);',
  '    float theta =',
  '      dot(direction, xz) * chopWaves[i].z * uChopFrequency +',
  '      uTime * uChopSpeed * (0.55 + float(i) * 0.23);',
  '    height += sin(theta) * chopWaves[i].w * uChopAmplitude;',
  '  }',
  '',
  '  for (int i = 0; i < DETAIL_COUNT; i++) {',
  '    vec2 direction = normalize(detailWaves[i].xy);',
  '    float theta =',
  '      dot(direction, xz) * detailWaves[i].z * uDetailFrequency +',
  '      uTime * uDetailSpeed * (0.55 + float(i) * 0.23);',
  '    height += sin(theta) * detailWaves[i].w * uDetailAmplitude;',
  '  }',
  '',
  '  return height;',
  '}',
  '',
  'float sampleInteractiveHeight(vec2 xz) {',
  '  vec2 uv = vec2(',
  '    xz.x / uInteractionBounds + 0.5,',
  '    0.5 - xz.y / uInteractionBounds',
  '  );',
  '',
  '  if (uv.x < 0.0 || uv.x > 1.0 || uv.y < 0.0 || uv.y > 1.0) {',
  '    return 0.0;',
  '  }',
  '',
  '  return texture2D(uInteractionHeightmap, uv).x;',
  '}',
  '',
  'float sampleOceanHeight(vec2 xz) {',
  '  return sampleBaseOceanHeight(xz) + sampleInteractiveHeight(xz);',
  '}',
].join('\n');

const OCEAN_NORMAL_GLSL = [
  'vec3 sampleOceanNormal(vec2 xz) {',
  '  float epsilon = max(uNormalEpsilon, 0.01);',
  '  float left = sampleOceanHeight(xz - vec2(epsilon, 0.0));',
  '  float right = sampleOceanHeight(xz + vec2(epsilon, 0.0));',
  '  float back = sampleOceanHeight(xz - vec2(0.0, epsilon));',
  '  float front = sampleOceanHeight(xz + vec2(0.0, epsilon));',
  '',
  '  return normalize(vec3(left - right, front - back, epsilon * 2.0));',
  '}',
].join('\n');

export default {
  OCEAN_HEIGHT_GLSL,
  OCEAN_NORMAL_GLSL,
};
