// Preset snapshots for the scene. Keys here must match the Leva schema built
// in useSceneControls 1:1 — no reshaping between a preset and the controls it
// applies (see docs/scene-conventions.md, "Controls & presets").
export const DEFAULT_PRESET = 'Default';

export const PRESETS = {
  Default: {
    cameraMode: 'orbit',
    cameraAutoFit: true,
    fixedBehavior: 'single',
    fixedShotHeroDesktopPosition: {
      x: 0,
      y: 4,
      z: 14,
    },
    fixedShotHeroDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    fixedShotHeroDesktopFov: 45,
    fixedShotHeroMobilePosition: {
      x: 0,
      y: 4,
      z: 14,
    },
    fixedShotHeroMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    fixedShotHeroMobileFov: 45,
    orbitAutoRotate: true,
    orbitAutoRotateSpeed: 8,
    orbitDesktopPosition: {
      x: 0,
      y: 4,
      z: 14,
    },
    orbitDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitDesktopPivot: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitDesktopFov: 45,
    orbitMobilePosition: {
      x: 0,
      y: 5,
      z: 18,
    },
    orbitMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitMobilePivot: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitMobileFov: 55,
    splineDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineDesktopFov: 45,
    splineMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineMobileFov: 45,
    splineOrientationMode: 'target',
    splineForwardDistance: 1,
    splinePosition: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineScale: {
      x: 1,
      y: 1,
      z: 1,
    },
    splineDuration: 30,
    splineTension: 0.5,
    splineClosed: true,
    splineShowPath: false,
    operatorMoveSpeed: 6,
    operatorLiftSpeed: 6,
    operatorBoostMultiplier: 2,
    operatorPointerLookSensitivity: 0.003,
    operatorStickLookSpeed: 2.5,
    operatorZoomSpeed: 24,
    operatorMinFov: 20,
    operatorMaxFov: 80,
    mode: 'Strange Attractors',
    attractorType: 'Thomas Labyrinth',
    thomasB: 0.1,
    particleCount: 2500,
    sakuraRatio: 0.35,
    stepSize: 0.1,
    speed: 0.39,
    worldScale: 1.25,
    leafScale: 0.25,
    sakuraScale: 8,
    orientationJitter: 1,
    showFieldLines: true,
    fieldLineSpeed: 1,
    fieldLineCount: 100,
    fieldLineColor: '#8fffaf',
    fieldLineOpacity: 0.8,
    fieldLineFade: 3,
    attractorCount: 3,
    showAttractorMarkers: false,
    attractorStrength: 4,
    spinStrength: 4.85,
    maxSpeed: 11.3,
    damping: 0.395,
    animateAttractors: true,
    animateSpeed: 1,
    godraysEnabled: true,
    godraysColor: '#ffd27a',
    godraysPosition: { x: 0, y: 1, z: 0 },
    godraysIntensity: 30,
    godraysBlendColor: '#ffffff',
    godraysVolumeSize: 15,
    godraysDensity: 0.7,
    godraysMaxDensity: 0.5,
    godraysDistanceAttenuation: 2,
    godraysRaymarchSteps: 120,
    godraysBlur: true,
    godraysEdgeRadius: 5,
    godraysEdgeStrength: 5,
    bonsaiVisible: true,
    bonsaiPosition: { x: 0, y: -23, z: 0 },
    bonsaiScale: 20,
    bonsaiRotationY: 0,
    bonsaiShowPot: false,
    bonsaiShowStalk: false,
    bonsaiShowBud: false,
    bonsaiShowFlower: false,
    skyboxVisible: true,
    skyboxScale: 1,
    skyboxRotationY: 0,
  },
  Clover: {
    cameraMode: 'orbit',
    cameraAutoFit: true,
    fixedBehavior: 'single',
    fixedShotHeroDesktopPosition: {
      x: 0,
      y: 4,
      z: 14,
    },
    fixedShotHeroDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    fixedShotHeroDesktopFov: 45,
    fixedShotHeroMobilePosition: {
      x: 0,
      y: 4,
      z: 14,
    },
    fixedShotHeroMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    fixedShotHeroMobileFov: 45,
    orbitAutoRotate: true,
    orbitAutoRotateSpeed: 5,
    orbitDesktopPosition: {
      x: 0,
      y: 4,
      z: 14,
    },
    orbitDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitDesktopPivot: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitDesktopFov: 45,
    orbitMobilePosition: {
      x: 0,
      y: 5,
      z: 18,
    },
    orbitMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitMobilePivot: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitMobileFov: 55,
    splineDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineDesktopFov: 45,
    splineMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineMobileFov: 45,
    splineOrientationMode: 'target',
    splineForwardDistance: 1,
    splinePosition: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineScale: {
      x: 1,
      y: 1,
      z: 1,
    },
    splineDuration: 30,
    splineTension: 0.5,
    splineClosed: true,
    splineShowPath: false,
    operatorMoveSpeed: 6,
    operatorLiftSpeed: 6,
    operatorBoostMultiplier: 2,
    operatorPointerLookSensitivity: 0.003,
    operatorStickLookSpeed: 2.5,
    operatorZoomSpeed: 24,
    operatorMinFov: 20,
    operatorMaxFov: 80,
    mode: 'Strange Attractors',
    attractorType: 'Four-Wing Butterfly',
    thomasB: 0.1,
    butterflyA: 0.2,
    butterflyB: 0.01,
    butterflyC: -0.4,
    particleCount: 200,
    sakuraRatio: 0.35,
    stepSize: 0.1,
    speed: 0.39,
    worldScale: 2.5,
    leafScale: 0.25,
    sakuraScale: 8,
    orientationJitter: 1,
    showFieldLines: true,
    fieldLineSpeed: 0.18999999999999995,
    fieldLineCount: 100,
    fieldLineColor: '#8fffaf',
    fieldLineOpacity: 0.8,
    fieldLineFade: 10,
    attractorCount: 3,
    showAttractorMarkers: false,
    attractorStrength: 4,
    spinStrength: 4.85,
    maxSpeed: 11.3,
    damping: 0.395,
    animateAttractors: true,
    animateSpeed: 1,
    godraysEnabled: true,
    godraysColor: '#ffd27a',
    godraysPosition: { x: 0, y: 1, z: 0 },
    godraysIntensity: 30,
    godraysBlendColor: '#ffffff',
    godraysVolumeSize: 15,
    godraysDensity: 0.7,
    godraysMaxDensity: 0.5,
    godraysDistanceAttenuation: 2,
    godraysRaymarchSteps: 120,
    godraysBlur: true,
    godraysEdgeRadius: 5,
    godraysEdgeStrength: 5,
    bonsaiVisible: true,
    bonsaiPosition: { x: 0, y: -23, z: 0 },
    bonsaiScale: 20,
    bonsaiRotationY: 0,
    bonsaiShowPot: false,
    bonsaiShowStalk: false,
    bonsaiShowBud: false,
    bonsaiShowFlower: false,
    skyboxVisible: true,
    skyboxScale: 1,
    skyboxRotationY: 0,
  },
  Tangled: {
    cameraMode: 'orbit',
    cameraAutoFit: true,
    fixedBehavior: 'single',
    fixedShotHeroDesktopPosition: {
      x: 0,
      y: 4,
      z: 14,
    },
    fixedShotHeroDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    fixedShotHeroDesktopFov: 45,
    fixedShotHeroMobilePosition: {
      x: 0,
      y: 4,
      z: 14,
    },
    fixedShotHeroMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    fixedShotHeroMobileFov: 45,
    orbitAutoRotate: true,
    orbitAutoRotateSpeed: 5,
    orbitDesktopPosition: {
      x: 0,
      y: 4,
      z: 14,
    },
    orbitDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitDesktopPivot: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitDesktopFov: 45,
    orbitMobilePosition: {
      x: 0,
      y: 5,
      z: 18,
    },
    orbitMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitMobilePivot: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitMobileFov: 55,
    splineDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineDesktopFov: 45,
    splineMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineMobileFov: 45,
    splineOrientationMode: 'target',
    splineForwardDistance: 1,
    splinePosition: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineScale: {
      x: 1,
      y: 1,
      z: 1,
    },
    splineDuration: 30,
    splineTension: 0.5,
    splineClosed: true,
    splineShowPath: false,
    operatorMoveSpeed: 6,
    operatorLiftSpeed: 6,
    operatorBoostMultiplier: 2,
    operatorPointerLookSensitivity: 0.003,
    operatorStickLookSpeed: 2.5,
    operatorZoomSpeed: 24,
    operatorMinFov: 20,
    operatorMaxFov: 80,
    mode: 'Strange Attractors',
    attractorType: 'Thomas Labyrinth',
    thomasB: 0.19,
    butterflyA: 0.2,
    butterflyB: 0.01,
    butterflyC: -0.4,
    particleCount: 2500,
    sakuraRatio: 0.35,
    stepSize: 0.05,
    speed: 0.5,
    worldScale: 2.25,
    leafScale: 0.25,
    sakuraScale: 8,
    orientationJitter: 1,
    showFieldLines: true,
    fieldLineSpeed: 2,
    fieldLineCount: 300,
    fieldLineColor: '#8fffaf',
    fieldLineOpacity: 0.36000000000000004,
    fieldLineFade: 3,
    attractorCount: 3,
    showAttractorMarkers: false,
    attractorStrength: 4,
    spinStrength: 4.85,
    maxSpeed: 11.3,
    damping: 0.395,
    animateAttractors: true,
    animateSpeed: 1,
    godraysEnabled: true,
    godraysColor: '#ffd27a',
    godraysPosition: { x: 0, y: 1, z: 0 },
    godraysIntensity: 30,
    godraysBlendColor: '#ffffff',
    godraysVolumeSize: 15,
    godraysDensity: 0.7,
    godraysMaxDensity: 0.5,
    godraysDistanceAttenuation: 2,
    godraysRaymarchSteps: 120,
    godraysBlur: true,
    godraysEdgeRadius: 5,
    godraysEdgeStrength: 5,
    bonsaiVisible: true,
    bonsaiPosition: { x: 0, y: -23, z: 0 },
    bonsaiScale: 20,
    bonsaiRotationY: 0,
    bonsaiShowPot: false,
    bonsaiShowStalk: false,
    bonsaiShowBud: false,
    bonsaiShowFlower: false,
    skyboxVisible: true,
    skyboxScale: 1,
    skyboxRotationY: 0,
  },
  'Physical Attraction': {
    cameraMode: 'orbit',
    cameraAutoFit: true,
    fixedBehavior: 'single',
    fixedShotHeroDesktopPosition: {
      x: 0,
      y: 4,
      z: 14,
    },
    fixedShotHeroDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    fixedShotHeroDesktopFov: 45,
    fixedShotHeroMobilePosition: {
      x: 0,
      y: 4,
      z: 14,
    },
    fixedShotHeroMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    fixedShotHeroMobileFov: 45,
    orbitAutoRotate: true,
    orbitAutoRotateSpeed: 8,
    orbitDesktopPosition: {
      x: 0,
      y: 4,
      z: 14,
    },
    orbitDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitDesktopPivot: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitDesktopFov: 45,
    orbitMobilePosition: {
      x: 0,
      y: 5,
      z: 18,
    },
    orbitMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitMobilePivot: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitMobileFov: 55,
    splineDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineDesktopFov: 45,
    splineMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineMobileFov: 45,
    splineOrientationMode: 'target',
    splineForwardDistance: 1,
    splinePosition: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineScale: {
      x: 1,
      y: 1,
      z: 1,
    },
    splineDuration: 30,
    splineTension: 0.5,
    splineClosed: true,
    splineShowPath: false,
    operatorMoveSpeed: 6,
    operatorLiftSpeed: 6,
    operatorBoostMultiplier: 2,
    operatorPointerLookSensitivity: 0.003,
    operatorStickLookSpeed: 2.5,
    operatorZoomSpeed: 24,
    operatorMinFov: 20,
    operatorMaxFov: 80,
    mode: 'Physical Attractors',
    attractorType: 'Thomas Labyrinth',
    thomasB: 0.1,
    butterflyA: 0.2,
    butterflyB: 0.01,
    butterflyC: -0.4,
    particleCount: 4501,
    sakuraRatio: 0.35,
    stepSize: 0.1,
    speed: 2.2600000000000002,
    worldScale: 1.25,
    leafScale: 0.25,
    sakuraScale: 8,
    orientationJitter: 1,
    showFieldLines: true,
    fieldLineSpeed: 1,
    fieldLineCount: 100,
    fieldLineColor: '#8fffaf',
    fieldLineOpacity: 0.8,
    fieldLineFade: 3,
    attractorCount: 3,
    showAttractorMarkers: false,
    attractorStrength: 4,
    spinStrength: 4.85,
    maxSpeed: 11.3,
    damping: 0.28,
    animateAttractors: true,
    animateSpeed: 1,
    godraysEnabled: true,
    godraysColor: '#ffd27a',
    godraysPosition: {
      x: 0,
      y: 1,
      z: 0,
    },
    godraysIntensity: 30,
    godraysBlendColor: '#ffffff',
    godraysVolumeSize: 15,
    godraysDensity: 0.7,
    godraysMaxDensity: 0.5,
    godraysDistanceAttenuation: 2,
    godraysRaymarchSteps: 120,
    godraysBlur: true,
    godraysEdgeRadius: 5,
    godraysEdgeStrength: 5,
    bonsaiVisible: true,
    bonsaiPosition: {
      x: 0,
      y: -23,
      z: 0,
    },
    bonsaiScale: 20,
    bonsaiRotationY: 0,
    bonsaiShowPot: false,
    bonsaiShowStalk: false,
    bonsaiShowBud: false,
    bonsaiShowFlower: false,
    skyboxVisible: true,
    skyboxScale: 1,
    skyboxRotationY: 0,
  },
};

// Companion fn to usePresetsFolder. Given the snapshot for the preset being
// applied, return the control values to set. Override this when a preset
// needs to derive values rather than apply the snapshot verbatim.
export function getPresetControls({ presetSnapshot }) {
  return { ...presetSnapshot };
}
