/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx public/models/snickers.glb --output public/models/__Snickers.generated.jsx --root public/models --shadows --exportdefault --printwidth 120 --precision 3 --transform --resolution 256 --format webp --keepmeshes --keepmaterials
Files: /Users/brettmcgillis/dev/eye-candy/public/models/snickers.glb [845.77KB] > /Users/brettmcgillis/dev/eye-candy/public/models/snickers.glb [19.44KB] (98%)
Author: Polza (https://sketchfab.com/8.in.glasses)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/snickers-free-c5c716bba063443da8d6112ff1bd7123
Title: Snickers (FREE)
*/
import React from 'react';

import { useGLTF } from '@react-three/drei';

import { modelFile } from '../../../utils/appUtils';

export default function Snickers(props) {
  const { nodes, materials } = useGLTF(modelFile('snickers.glb'));
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_4.geometry}
        material={materials.snickers}
        position={[0, 0.531, 2.006]}
      />
    </group>
  );
}

useGLTF.preload(modelFile('snickers.glb'));
