/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx public/models/snickers.glb --output public/models/__Snickers.generated.jsx --root public/models --shadows --exportdefault --printwidth 120 --precision 3 --transform --resolution 256 --format webp --keepmeshes --keepmaterials
Files: /Users/brettmcgillis/dev/eye-candy/public/models/snickers.glb [845.77KB] > /Users/brettmcgillis/dev/eye-candy/public/models/snickers.glb [19.44KB] (98%)
Author: Polza (https://sketchfab.com/8.in.glasses)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/snickers-free-c5c716bba063443da8d6112ff1bd7123
Title: Snickers (FREE)
*/
import React, { useEffect, useMemo } from 'react';

import { createInstances, useGLTF } from '@react-three/drei';

import { modelFile } from '@utils/appUtils';
import bakeInstancedGeometry from '@utils/instancedGeometry';

const SNICKERS_MODEL_PATH = '/snickers.glb';
const SNICKERS_MODEL_FILE = modelFile(SNICKERS_MODEL_PATH);
const SNICKERS_MATERIAL_NAME = 'snickers';
const SNICKERS_TRANSFORM_CHAIN = [{ position: [0, 0.531, 2.006] }];

const [SnickersInstancesRoot, SnickersInstanceRoot] = createInstances();

function useSnickersModel() {
  const { nodes, materials } = useGLTF(SNICKERS_MODEL_FILE);

  return {
    baseGeometry: nodes.Object_4.geometry,
    sourceMaterial: materials[SNICKERS_MATERIAL_NAME],
  };
}

function useSnickersGeometry(baseGeometry) {
  const geometry = useMemo(
    () => bakeInstancedGeometry(baseGeometry, SNICKERS_TRANSFORM_CHAIN),
    [baseGeometry]
  );

  useEffect(() => {
    return () => {
      geometry.dispose?.();
    };
  }, [geometry]);

  return geometry;
}

export function SnickersInstances({ children, material, ...props }) {
  const { baseGeometry, sourceMaterial } = useSnickersModel();
  const geometry = useSnickersGeometry(baseGeometry);
  const instanceMaterial = useMemo(
    () => material ?? sourceMaterial.clone(),
    [material, sourceMaterial]
  );

  useEffect(() => {
    if (material) {
      return undefined;
    }

    return () => {
      instanceMaterial.dispose?.();
    };
  }, [instanceMaterial, material]);

  return (
    <SnickersInstancesRoot
      geometry={geometry}
      material={instanceMaterial}
      {...props}
    >
      {children}
    </SnickersInstancesRoot>
  );
}

export function SnickersInstance(props) {
  return <SnickersInstanceRoot {...props} />;
}

export function Snickers(props) {
  const { baseGeometry, sourceMaterial } = useSnickersModel();
  const geometry = useSnickersGeometry(baseGeometry);

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={geometry}
        material={sourceMaterial}
      />
    </group>
  );
}

useGLTF.preload(SNICKERS_MODEL_FILE);

export default Snickers;
