import React from 'react';

import { useGLTF } from '@react-three/drei';

import { modelFile } from '@utils/appUtils';

export default function Skull({
  showCranium,
  showLeftZygomatic,
  showOccipital,
  showRightLacrimal,
  showRightMaxilla,
  showRightNasal,
  showRightPalatine,
  showRightParietal,
  showRightTemporal,
  showRightZygomatic,
  showSphenoid,
  showTeeth,
  showVomer,
  showEthmoid,
  showFrontal,
  showInferiorConchae,
  showLeftLacrimal,
  showLeftMaxilla,
  showLeftNasal,
  showLeftPalatine,
  showLeftParietal,
  showLeftTemporal,
  showMandible,
  showMandibleBone,
  showMandibleTeeth,
  ...props
}) {
  const { nodes, materials } = useGLTF(modelFile(`Skull.glb`));

  return (
    <group {...props} dispose={null}>
      <group
        position={[-0.249, 5.881, 0.961]}
        rotation={[-2.352, 0.002, -0.08]}
      >
        <group
          position={[-0.418, -1.66, 0.931]}
          rotation={[-0.154, 0.022, 0.045]}
          visible={showMandible}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Lower_teeth.geometry}
            material={materials.phong3}
            visible={showMandibleTeeth}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mandible.geometry}
            material={materials.lambert5}
            visible={showMandibleBone}
          />
        </group>
        <group visible={showCranium}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Left_zygomatic.geometry}
            material={materials.lambert5}
            visible={showLeftZygomatic}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Occipital.geometry}
            material={materials.lambert5}
            visible={showOccipital}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Right_lacrimal.geometry}
            material={materials.lambert5}
            visible={showRightLacrimal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Right_max.geometry}
            material={materials.lambert5}
            visible={showRightMaxilla}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Right_nasal.geometry}
            material={materials.lambert5}
            visible={showRightNasal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Right_palatine.geometry}
            material={materials.lambert5}
            visible={showRightPalatine}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Right_Parietal.geometry}
            material={materials.lambert5}
            visible={showRightParietal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Right_temporal.geometry}
            material={materials.lambert5}
            visible={showRightTemporal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Right_zygomatic.geometry}
            material={materials.lambert5}
            visible={showRightZygomatic}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Sphenoid.geometry}
            material={materials.lambert5}
            visible={showSphenoid}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Teeth.geometry}
            material={materials.phong3}
            visible={showTeeth}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Vomer.geometry}
            material={materials.lambert5}
            visible={showVomer}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Ethmoid.geometry}
            material={materials.lambert5}
            visible={showEthmoid}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Ethmoid_1.geometry}
            material={materials.lambert5}
            visible={showEthmoid}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Frontal.geometry}
            material={materials.lambert5}
            visible={showFrontal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Inferior_conchae.geometry}
            material={materials.lambert5}
            visible={showInferiorConchae}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Left_lacrimal.geometry}
            material={materials.lambert5}
            visible={showLeftLacrimal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Left_maxilla.geometry}
            material={materials.lambert5}
            visible={showLeftMaxilla}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Left_maxilla_1.geometry}
            material={materials.lambert5}
            visible={showLeftMaxilla}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Left_nasal.geometry}
            material={materials.lambert5}
            visible={showLeftNasal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Left_palatine.geometry}
            material={materials.lambert5}
            visible={showLeftPalatine}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Left_parietal.geometry}
            material={materials.lambert5}
            visible={showLeftParietal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Left_temporal.geometry}
            material={materials.lambert5}
            visible={showLeftTemporal}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload(modelFile(`Skull.glb `));
