import React from 'react';

import { useGLTF } from '@react-three/drei';

import skull from '../../../models/Skull.gltf';

export function Skull({
  showCranium,
  showLeftZygomatic,
  showOccipital,
  showRightLacrimal,
  showRightMaxilla,
  showRightNasal,
  showRightPalatine,
  showRightParietal,
  showRightTemporal,
  showRightZygomatic,
  showSphenoid,
  showTeeth,
  showVomer,
  showEthmoid,
  showFrontal,
  showInferiorConchae,
  showLeftLacrimal,
  showLeftMaxilla,
  showLeftNasal,
  showLeftPalatine,
  showLeftParietal,
  showLeftTemporal,
  showMandible,
  showMandibleBone,
  showMandibleTeeth,
  ...props
}) {
  const { nodes, materials } = useGLTF(skull);

  return (
    <group {...props} dispose={null}>
      <group
        position={[-0.249, 5.881, 0.961]}
        rotation={[-2.352, 0.002, -0.08]}
      >
        <group
          position={[-0.418, -1.66, 0.931]}
          rotation={[-0.154, 0.022, 0.045]}
          visible={showMandible}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Lower_teeth_1.geometry}
            material={materials.phong3}
            visible={showMandibleTeeth}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mandible_2.geometry}
            material={materials.lambert5}
            visible={showMandibleBone}
          />
        </group>
        <group visible={showCranium}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Left_zygomatic_1.geometry}
            material={materials.lambert5}
            visible={showLeftZygomatic}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Occipital_1.geometry}
            material={materials.lambert5}
            visible={showOccipital}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Right_lacrimal_1.geometry}
            material={materials.lambert5}
            visible={showRightLacrimal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Right_max_1.geometry}
            material={materials.lambert5}
            visible={showRightMaxilla}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Right_nasal_1.geometry}
            material={materials.lambert5}
            visible={showRightNasal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Right_palatine_1.geometry}
            material={materials.lambert5}
            visible={showRightPalatine}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Right_Parietal_1.geometry}
            material={materials.lambert5}
            visible={showRightParietal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Right_temporal_1.geometry}
            material={materials.lambert5}
            visible={showRightTemporal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Right_zygomatic_1.geometry}
            material={materials.lambert5}
            visible={showRightZygomatic}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Sphenoid_1.geometry}
            material={materials.lambert5}
            visible={showSphenoid}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Teeth_1.geometry}
            material={materials.phong3}
            visible={showTeeth}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Vomer_1.geometry}
            material={materials.lambert5}
            visible={showVomer}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Ethmoid_1.geometry}
            material={materials.lambert5}
            visible={showEthmoid}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Ethmoid_2.geometry}
            material={materials.lambert5}
            visible={showEthmoid}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Frontal_1.geometry}
            material={materials.lambert5}
            visible={showFrontal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Inferior_conchae_1.geometry}
            material={materials.lambert5}
            visible={showInferiorConchae}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Left_lacrimal_1.geometry}
            material={materials.lambert5}
            visible={showLeftLacrimal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Left_maxilla_1.geometry}
            material={materials.lambert5}
            visible={showLeftMaxilla}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Left_maxilla_2.geometry}
            material={materials.lambert5}
            visible={showLeftMaxilla}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Left_nasal_1.geometry}
            material={materials.lambert5}
            visible={showLeftNasal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Left_palatine_1.geometry}
            material={materials.lambert5}
            visible={showLeftPalatine}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Left_parietal_1.geometry}
            material={materials.lambert5}
            visible={showLeftParietal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Left_temporal_1.geometry}
            material={materials.lambert5}
            visible={showLeftTemporal}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/Skull.gltf');
