// Preset snapshots for the scene. Keys here must match the Leva schema built
// in useSceneControls 1:1 — no reshaping between a preset and the controls it
// applies (see docs/scene-conventions.md, "Controls & presets"). Only the
// keys a preset actually wants to override need to be listed (SceneTemplate's
// Default preset is the same partial-object style).

export const DEFAULT_PRESET = '001';

export const PRESETS = {
  '001': {
    cameraMode: 'orbit',
    cameraAutoFit: true,
    fixedBehavior: 'single',
    fixedShotDefaultDesktopPosition: {
      x: 0,
      y: 0,
      z: 5,
    },
    fixedShotDefaultDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    fixedShotDefaultDesktopFov: 50,
    fixedShotDefaultMobilePosition: {
      x: 0,
      y: 0,
      z: 5,
    },
    fixedShotDefaultMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    fixedShotDefaultMobileFov: 50,
    orbitAutoRotate: false,
    orbitAutoRotateSpeed: 3,
    orbitEnablePan: true,
    orbitMinPolarAngle: 0,
    orbitMaxPolarAngle: 180,
    orbitAzimuthUnlimited: true,
    orbitMinAzimuthAngle: -180,
    orbitMaxAzimuthAngle: 180,
    orbitMinDistance: 0,
    orbitMaxDistanceUnlimited: true,
    orbitMaxDistance: 100,
    orbitDesktopPosition: {
      x: 0,
      y: 4,
      z: 22,
    },
    orbitDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitDesktopPivot: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitDesktopFov: 42,
    orbitMobilePosition: {
      x: 0,
      y: 6,
      z: 28,
    },
    orbitMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitMobilePivot: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitMobileFov: 50,
    splineDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineDesktopFov: 50,
    splineMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineMobileFov: 50,
    splineOrientationMode: 'target',
    splineForwardDistance: 1,
    splinePosition: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineScale: {
      x: 1,
      y: 1,
      z: 1,
    },
    splineDuration: 30,
    splineTension: 0.5,
    splineClosed: true,
    splineShowPath: false,
    operatorMoveSpeed: 6,
    operatorLiftSpeed: 6,
    operatorBoostMultiplier: 2,
    operatorPointerLookSensitivity: 0.003,
    operatorStickLookSpeed: 2.5,
    operatorZoomSpeed: 24,
    operatorMinFov: 20,
    operatorMaxFov: 80,
    seed: 676050,
    bundleCount: 12,
    strandsPerBundle: 50,
    steps: 2000,
    startSpread: 0.35,
    coeffRange: 1.6,
    freq: 0.6,
    growthDuration: 15,
    evolutionSpeed: 0,
    monochrome: true,
    inkColor: '#1f1f1f',
    palette: 'Random',
    flatten: 0,
    backgroundColor: '#f4efe4',
    // Bundle Editor overrides, keyed by bundle index — not a Leva control,
    // but included here (and in the copy button's output) so a preset can
    // round-trip however many bundles have been art-directed. Example shape:
    // { 2: { colorOverride: true, color: '#ff00aa', visible: true,
    //        growthDelay: 1.5 } }
    overrides: {},
  },
  '002': {
    cameraMode: 'orbit',
    cameraAutoFit: true,
    fixedBehavior: 'single',
    fixedShotDefaultDesktopPosition: {
      x: 0,
      y: 0,
      z: 5,
    },
    fixedShotDefaultDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    fixedShotDefaultDesktopFov: 50,
    fixedShotDefaultMobilePosition: {
      x: 0,
      y: 0,
      z: 5,
    },
    fixedShotDefaultMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    fixedShotDefaultMobileFov: 50,
    orbitAutoRotate: true,
    orbitAutoRotateSpeed: 3,
    orbitEnablePan: true,
    orbitMinPolarAngle: 0,
    orbitMaxPolarAngle: 180,
    orbitAzimuthUnlimited: true,
    orbitMinAzimuthAngle: -180,
    orbitMaxAzimuthAngle: 180,
    orbitMinDistance: 0,
    orbitMaxDistanceUnlimited: true,
    orbitMaxDistance: 100,
    orbitDesktopPosition: {
      x: 0,
      y: 4,
      z: 22,
    },
    orbitDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitDesktopPivot: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitDesktopFov: 42,
    orbitMobilePosition: {
      x: 0,
      y: 6,
      z: 28,
    },
    orbitMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitMobilePivot: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitMobileFov: 50,
    splineDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineDesktopFov: 50,
    splineMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineMobileFov: 50,
    splineOrientationMode: 'target',
    splineForwardDistance: 1,
    splinePosition: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineScale: {
      x: 1,
      y: 1,
      z: 1,
    },
    splineDuration: 30,
    splineTension: 0.5,
    splineClosed: true,
    splineShowPath: false,
    operatorMoveSpeed: 6,
    operatorLiftSpeed: 6,
    operatorBoostMultiplier: 2,
    operatorPointerLookSensitivity: 0.003,
    operatorStickLookSpeed: 2.5,
    operatorZoomSpeed: 24,
    operatorMinFov: 20,
    operatorMaxFov: 80,
    seed: 373667,
    bundleCount: 17,
    strandsPerBundle: 50,
    steps: 500,
    startSpread: 0.35,
    coeffRange: 1.6,
    freq: 0.6,
    minSpread: 1.5,
    growthDuration: 0.5,
    evolutionSpeed: 0,
    monochrome: false,
    inkColor: '#1f1f1f',
    palette: 'Ameena',
    flatten: 0,
    backgroundColor: '#000000',
  },
  '003': {
    cameraMode: 'orbit',
    cameraAutoFit: true,
    fixedBehavior: 'single',
    fixedShotDefaultDesktopPosition: {
      x: 0,
      y: 0,
      z: 5,
    },
    fixedShotDefaultDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    fixedShotDefaultDesktopFov: 50,
    fixedShotDefaultMobilePosition: {
      x: 0,
      y: 0,
      z: 5,
    },
    fixedShotDefaultMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    fixedShotDefaultMobileFov: 50,
    orbitAutoRotate: false,
    orbitAutoRotateSpeed: 3,
    orbitEnablePan: true,
    orbitMinPolarAngle: 0,
    orbitMaxPolarAngle: 180,
    orbitAzimuthUnlimited: true,
    orbitMinAzimuthAngle: -180,
    orbitMaxAzimuthAngle: 180,
    orbitMinDistance: 0,
    orbitMaxDistanceUnlimited: true,
    orbitMaxDistance: 100,
    orbitDesktopPosition: {
      x: 0,
      y: 4,
      z: 22,
    },
    orbitDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitDesktopPivot: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitDesktopFov: 42,
    orbitMobilePosition: {
      x: 0,
      y: 6,
      z: 28,
    },
    orbitMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitMobilePivot: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitMobileFov: 50,
    splineDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineDesktopFov: 50,
    splineMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineMobileFov: 50,
    splineOrientationMode: 'target',
    splineForwardDistance: 1,
    splinePosition: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineScale: {
      x: 1,
      y: 1,
      z: 1,
    },
    splineDuration: 30,
    splineTension: 0.5,
    splineClosed: true,
    splineShowPath: false,
    operatorMoveSpeed: 6,
    operatorLiftSpeed: 6,
    operatorBoostMultiplier: 2,
    operatorPointerLookSensitivity: 0.003,
    operatorStickLookSpeed: 2.5,
    operatorZoomSpeed: 24,
    operatorMinFov: 20,
    operatorMaxFov: 80,
    seed: 819941,
    bundleCount: 13,
    strandsPerBundle: 50,
    steps: 800,
    startSpread: 0.37,
    coeffRange: 1.6,
    freq: 0.6,
    framingShape: 'cube',
    boundRadius: 40,
    boundWidth: 40,
    boundHeight: 40,
    minSpread: 1.5,
    growthDuration: 0.5,
    evolutionEnabled: false,
    evolutionSpeed: 3,
    smoothRespawns: true,
    trailFade: true,
    monochrome: false,
    inkColor: '#1f1f1f',
    palette: 'Pure Lust',
    flatten: 0,
    backgroundColor: '#000000',
    showOverlay: true,
  },
};

// Companion fn to usePresetsFolder. Given the snapshot for the preset being
// applied, return the control values to set. Override this when a preset
// needs to derive values rather than apply the snapshot verbatim.
export function getPresetControls({ presetSnapshot }) {
  return { ...presetSnapshot };
}
