const BASE = {
  // Straight down on the bed, auto-rotate off: the point of the default framing
  // is to watch the field evolve as the flat 2D pattern the reference shader
  // draws, which a spinning camera would fight.
  cameraMode: 'orbit',
  orbitAutoRotate: false,
  orbitAutoRotateSpeed: 1.2,
  orbitDesktopPosition: { x: 0, y: 9.5, z: 0.01 },
  orbitDesktopTarget: { x: 0, y: 0, z: 0 },
  orbitDesktopPivot: { x: 0, y: 0, z: 0 },
  orbitDesktopFov: 46,
  orbitMobilePosition: { x: 0, y: 12, z: 0.01 },
  orbitMobileTarget: { x: 0, y: 0, z: 0 },
  orbitMobilePivot: { x: 0, y: 0, z: 0 },
  orbitMobileFov: 54,

  lightAmbientEnabled: true,
  lightAmbientColor: '#8fa8c4',
  lightAmbientIntensity: 0.25,
  lightHemiEnabled: true,
  lightHemiSkyColor: '#b7cbe4',
  lightHemiGroundColor: '#12161c',
  lightHemiIntensity: 0.4,
  lightKeyEnabled: true,
  lightKeyColor: '#eef4ff',
  lightKeyIntensity: 140,
  lightKeyPosition: { x: 3, y: 8, z: 4 },
  lightKeyTarget: { x: 0, y: 0, z: 0 },
  lightKeyAngle: 36,
  lightKeyPenumbra: 0.8,
  lightKeyDistance: 26,
  lightKeyDecay: 1.1,

  seed: 88121,
  bedCount: 220000,
  grainSize: 0.014,
  bedRadius: 3.4,
  bedThickness: 0.22,
  bedBaseY: 0.05,
  fieldHeightScale: 0.2,
  cullEnabled: false,
  cullThreshold: 0.4,
  cullSoftness: 0.08,
  grainRoughness: 0.4,
  grainMetalness: 0.15,
  grainColor: '#c9b493',
  grainPaletteMix: 0.4,
  grainColorB: '#a68a63',
  grainColorC: '#e6dcc8',
  grainPaletteSplitB: 0.55,
  grainPaletteSplitC: 0.85,
  grainRoll: 6,
  // Defaults reproduce the previous single-ramp look: bias 1 is an even spread
  // between the two multipliers.
  grainSizeMin: 0.55,
  grainSizeMax: 1.45,
  grainSizeCoarse: 1,
  paletteName: 'None',
  paletteMix: 0.6,
  paletteAdvect: 1,
  paletteShift: 0,
  fieldTint: 0.55,
  fieldTintColor: '#3d3226',

  postEnabled: true,
  postDofEnabled: true,
  postDofFocusMode: 'manual',
  postDofFocusDistance: 9.5,
  postDofFocalLength: 3,
  postDofBokehScale: 4,
  postDofFocusSmoothing: 6,

  // These five are the reference shader's own constants, transposed from its
  // normalised-UV domain to this texel-indexed one (its `pixelSize*4` gradient
  // taps and `pixelSize*8` advection scale become 4 and 8 texels directly).
  // `alwaysOn` matches its `iFrame < 10` full-frame noise seed, so the default
  // scene runs the same simulation the shader does rather than growing into it.
  decayRate: 0.002,
  reactionStrength: 0.047,
  noiseAmount: 0.0025,
  expansionStrength: 8,
  blurSpread: 1,
  growthMode: 'alwaysOn',
  boundaryBounce: false,
  fieldResolution: 384,
  seedRadius: 0.06,
  dropInterval: 6,
  dropFade: 1.5,
  followDrop: false,
  followDropDamping: 0.3,
  paletteRefresh: 0.008,
  fieldContrast: 10,

  backgroundColor: '#3a3a3a',
  floorColor: '#3a3a3a',
  floorCenterColor: '#3a3a3a',
  wallLowColor: '#3a3a3a',
  wallHighColor: '#3a3a3a',
  wallGradientStart: 0,
  wallGradientEnd: 0.8,
  floorHeight: -0.8,
  roomRadius: 12,
  roomHeight: 18,
  fogNear: 14,
  fogFar: 50,
};

export const DEFAULT_PRESET = 'Thick Bed';

export const PRESETS = {
  // A deep, generous field never approaches the floor at any camera angle —
  // culling stays off entirely, so the reaction-diffusion pattern only ever
  // shows as dune relief, never as a gap.
  'Thick Bed': { ...BASE },
  // Shallow field + field-driven culling: the RD pattern itself decides where
  // sand exists, so the studio floor shows through real gaps that trace the
  // pattern.
  'Thin Spread': {
    ...BASE,
    bedThickness: 0.05,
    bedBaseY: 0,
    fieldHeightScale: 0.08,
    cullEnabled: true,
    // The shaped field is centred on 0.5, so a threshold just under it clears
    // roughly a quarter to a third of the bed — enough floor to read, not so
    // much that the sand stops being the subject.
    cullThreshold: 0.4,
    cullSoftness: 0.07,
    fieldContrast: 14,
    // Keeps feeding the bed new seeds instead of resetting it, so the gaps
    // keep changing without the whole field flattening out.
    growthMode: 'seedDrops',
    seedRadius: 0.07,
    dropInterval: 5,
  },
  Gasoline: {
    cameraMode: 'spline',
    cameraAutoFit: false,
    fixedBehavior: 'single',
    fixedShotDefaultDesktopPosition: {
      x: 0,
      y: 0,
      z: 5,
    },
    fixedShotDefaultDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    fixedShotDefaultDesktopFov: 50,
    fixedShotDefaultMobilePosition: {
      x: 0,
      y: 0,
      z: 5,
    },
    fixedShotDefaultMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    fixedShotDefaultMobileFov: 50,
    orbitAutoRotate: false,
    orbitAutoRotateSpeed: 1.2,
    orbitEnablePan: true,
    orbitMinPolarAngle: 0,
    orbitMaxPolarAngle: 180,
    orbitAzimuthUnlimited: true,
    orbitMinAzimuthAngle: -180,
    orbitMaxAzimuthAngle: 180,
    orbitMinDistance: 0,
    orbitMaxDistanceUnlimited: true,
    orbitMaxDistance: 100,
    orbitDesktopPosition: {
      x: 0,
      y: 4.5,
      z: 4,
    },
    orbitDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitDesktopPivot: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitDesktopFov: 46,
    orbitMobilePosition: {
      x: 0,
      y: 4.5,
      z: 4,
    },
    orbitMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitMobilePivot: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitMobileFov: 54,
    splinePreset: 'Spiral Up',
    splineDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineDesktopFov: 15,
    splineMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineMobileFov: 50,
    splineOrientationMode: 'target',
    splineForwardDistance: 1,
    splinePosition: {
      x: 0,
      y: 1,
      z: 0,
    },
    splineScale: {
      x: 1,
      y: 1,
      z: 1,
    },
    splineDuration: 60,
    splineTension: 0.5,
    splineClosed: true,
    splineShowPath: false,
    operatorMoveSpeed: 6,
    operatorLiftSpeed: 6,
    operatorBoostMultiplier: 2,
    operatorPointerLookSensitivity: 0.003,
    operatorStickLookSpeed: 2.5,
    operatorZoomSpeed: 24,
    operatorMinFov: 20,
    operatorMaxFov: 80,
    lightEnabled: true,
    lightAmbientEnabled: true,
    lightAmbientColor: '#8fa8c4',
    lightAmbientIntensity: 0.25,
    lightHemiEnabled: true,
    lightHemiSkyColor: '#b7cbe4',
    lightHemiGroundColor: '#12161c',
    lightHemiIntensity: 0.4,
    lightKeyEnabled: true,
    lightKeyColor: '#eef4ff',
    lightKeyIntensity: 140,
    lightKeyPosition: {
      x: 3,
      y: 8,
      z: 4,
    },
    lightKeyTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    lightKeyAngle: 36,
    lightKeyPenumbra: 0.8,
    lightKeyDistance: 26,
    lightKeyDecay: 1.1,
    lightKeyCastShadow: true,
    lightKeyShadowMapSize: 2048,
    lightKeyShadowBias: -0.0004,
    lightKeyShadowNormalBias: 0,
    lightKeyShadowFar: 22,
    lightKeyDebug: false,
    paletteName: 'VividMemory8 (lospec)',
    paletteMix: 1,
    paletteAdvect: 0,
    paletteShift: 0,
    seed: 88121,
    bedCount: 500000,
    grainSize: 0.014,
    grainSizeMin: 0.55,
    grainSizeMax: 6.3500000000000005,
    grainSizeCoarse: 0.001,
    bedRadius: 2.4,
    bedThickness: 0.22,
    bedBaseY: 0.05,
    fieldHeightScale: 0.2,
    grainRoll: 6,
    fieldTint: 1,
    fieldTintColor: '#3d3226',
    cullEnabled: false,
    cullThreshold: 0.4,
    cullSoftness: 0.08,
    grainRoughness: 0.63,
    grainMetalness: 0.75,
    grainColor: '#c9b493',
    grainPaletteMix: 0.4,
    grainColorB: '#a68a63',
    grainColorC: '#e6dcc8',
    grainPaletteSplitB: 0.55,
    grainPaletteSplitC: 0.85,
    fieldResolution: 672,
    growthMode: 'seedDrops',
    boundaryBounce: true,
    seedRadius: 0.06,
    dropInterval: 2,
    dropFade: 1.2,
    followDrop: true,
    followDropDamping: 0.35,
    paletteRefresh: 0.008,
    fieldContrast: 9.5,
    decayRate: 0.008,
    reactionStrength: 0.047,
    noiseAmount: 0.0025,
    expansionStrength: 15.5,
    blurSpread: 1,
    backgroundColor: '#000000',
    floorColor: '#000000',
    floorCenterColor: '#000000',
    wallLowColor: '#000000',
    wallHighColor: '#000000',
    wallGradientStart: 0,
    wallGradientEnd: 0.8,
    floorHeight: -0.8,
    roomRadius: 12,
    roomHeight: 18,
    fogNear: 14,
    fogFar: 50,
    postEnabled: true,
    postDofEnabled: true,
    postDofFocusMode: 'target',
    postDofFocusDistance: 9.5,
    postDofFocalLength: 3,
    postDofBokehScale: 4,
    postDofFocusSmoothing: 3,
  },
  Two: {
    cameraMode: 'orbit',
    cameraAutoFit: false,
    fixedBehavior: 'single',
    fixedShotDefaultDesktopPosition: {
      x: 0,
      y: 0,
      z: 5,
    },
    fixedShotDefaultDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    fixedShotDefaultDesktopFov: 50,
    fixedShotDefaultMobilePosition: {
      x: 0,
      y: 0,
      z: 5,
    },
    fixedShotDefaultMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    fixedShotDefaultMobileFov: 50,
    orbitAutoRotate: true,
    orbitAutoRotateSpeed: 2,
    orbitEnablePan: true,
    orbitMinPolarAngle: 0,
    orbitMaxPolarAngle: 180,
    orbitAzimuthUnlimited: true,
    orbitMinAzimuthAngle: -180,
    orbitMaxAzimuthAngle: 180,
    orbitMinDistance: 0,
    orbitMaxDistanceUnlimited: true,
    orbitMaxDistance: 100,
    orbitDesktopPosition: {
      x: 0,
      y: 0.5,
      z: -4,
    },
    orbitDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitDesktopPivot: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitDesktopFov: 46,
    orbitMobilePosition: {
      x: 0,
      y: 0.5,
      z: -4,
    },
    orbitMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitMobilePivot: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitMobileFov: 46,
    splinePreset: 'Spiral Up',
    splineDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineDesktopFov: 15,
    splineMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineMobileFov: 50,
    splineOrientationMode: 'target',
    splineForwardDistance: 1,
    splinePosition: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineScale: {
      x: 1,
      y: 0.5,
      z: 1,
    },
    splineDuration: 60,
    splineTension: 0.5,
    splineClosed: true,
    splineShowPath: false,
    operatorMoveSpeed: 6,
    operatorLiftSpeed: 6,
    operatorBoostMultiplier: 2,
    operatorPointerLookSensitivity: 0.003,
    operatorStickLookSpeed: 2.5,
    operatorZoomSpeed: 24,
    operatorMinFov: 20,
    operatorMaxFov: 80,
    lightEnabled: true,
    lightAmbientEnabled: true,
    lightAmbientColor: '#8fa8c4',
    lightAmbientIntensity: 0.25,
    lightHemiEnabled: true,
    lightHemiSkyColor: '#b7cbe4',
    lightHemiGroundColor: '#12161c',
    lightHemiIntensity: 0.4,
    lightKeyEnabled: true,
    lightKeyColor: '#eef4ff',
    lightKeyIntensity: 140,
    lightKeyPosition: {
      x: 3,
      y: 8,
      z: 4,
    },
    lightKeyTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    lightKeyAngle: 36,
    lightKeyPenumbra: 0.8,
    lightKeyDistance: 26,
    lightKeyDecay: 1.1,
    lightKeyCastShadow: true,
    lightKeyShadowMapSize: 2048,
    lightKeyShadowBias: -0.0004,
    lightKeyShadowNormalBias: 0,
    lightKeyShadowFar: 22,
    lightKeyDebug: false,
    paletteName: 'Exophobia (lospec)',
    paletteMix: 1,
    paletteAdvect: 0,
    paletteShift: 0,
    seed: 88121,
    bedCount: 450000,
    grainSize: 0.008,
    grainSizeMin: 0.55,
    grainSizeMax: 1.45,
    grainSizeCoarse: 1,
    bedRadius: 3.4,
    bedThickness: 0.01,
    bedBaseY: 0.05,
    fieldHeightScale: 0.2,
    grainRoll: 6,
    fieldTint: 0.55,
    fieldTintColor: '#3d3226',
    cullEnabled: false,
    cullThreshold: 0.4,
    cullSoftness: 0.08,
    grainRoughness: 0.4,
    grainMetalness: 0.15,
    grainColor: '#c9b493',
    grainPaletteMix: 0.4,
    grainColorB: '#a68a63',
    grainColorC: '#e6dcc8',
    grainPaletteSplitB: 0.55,
    grainPaletteSplitC: 0.85,
    fieldResolution: 320,
    growthMode: 'alwaysOn',
    boundaryBounce: false,
    seedRadius: 0.06,
    dropInterval: 6,
    dropFade: 1.5,
    followDrop: false,
    followDropDamping: 0.3,
    paletteRefresh: 0.008,
    fieldContrast: 10,
    decayRate: 0.002,
    reactionStrength: 0.047,
    noiseAmount: 0.0025,
    expansionStrength: 8,
    blurSpread: 1,
    backgroundColor: '#3a3a3a',
    floorColor: '#3a3a3a',
    floorCenterColor: '#3a3a3a',
    wallLowColor: '#3a3a3a',
    wallHighColor: '#3a3a3a',
    wallGradientStart: 0,
    wallGradientEnd: 0.8,
    floorHeight: -0.8,
    roomRadius: 12,
    roomHeight: 18,
    fogNear: 14,
    fogFar: 50,
    postEnabled: true,
    postDofEnabled: true,
    postDofFocusMode: 'manual',
    postDofFocusDistance: 0.8999999999999986,
    postDofFocalLength: 3.5,
    postDofBokehScale: 4,
    postDofFocusSmoothing: 6,
  },
  Petri: {
    cameraMode: 'orbit',
    cameraAutoFit: false,
    fixedBehavior: 'single',
    fixedShotDefaultDesktopPosition: {
      x: 0,
      y: 0,
      z: 5,
    },
    fixedShotDefaultDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    fixedShotDefaultDesktopFov: 50,
    fixedShotDefaultMobilePosition: {
      x: 0,
      y: 0,
      z: 5,
    },
    fixedShotDefaultMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    fixedShotDefaultMobileFov: 50,
    orbitAutoRotate: false,
    orbitAutoRotateSpeed: 1.2,
    orbitEnablePan: true,
    orbitMinPolarAngle: 0,
    orbitMaxPolarAngle: 180,
    orbitAzimuthUnlimited: true,
    orbitMinAzimuthAngle: -180,
    orbitMaxAzimuthAngle: 180,
    orbitMinDistance: 0,
    orbitMaxDistanceUnlimited: true,
    orbitMaxDistance: 100,
    orbitDesktopPosition: {
      x: 0,
      y: 9.5,
      z: 0.01,
    },
    orbitDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitDesktopPivot: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitDesktopFov: 46,
    orbitMobilePosition: {
      x: 0,
      y: 12,
      z: 0.01,
    },
    orbitMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitMobilePivot: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitMobileFov: 54,
    splinePreset: 'Spiral Up',
    splineDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineDesktopFov: 15,
    splineMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineMobileFov: 50,
    splineOrientationMode: 'target',
    splineForwardDistance: 1,
    splinePosition: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineScale: {
      x: 1,
      y: 0.5,
      z: 1,
    },
    splineDuration: 60,
    splineTension: 0.5,
    splineClosed: true,
    splineShowPath: false,
    operatorMoveSpeed: 6,
    operatorLiftSpeed: 6,
    operatorBoostMultiplier: 2,
    operatorPointerLookSensitivity: 0.003,
    operatorStickLookSpeed: 2.5,
    operatorZoomSpeed: 24,
    operatorMinFov: 20,
    operatorMaxFov: 80,
    lightEnabled: true,
    lightAmbientEnabled: true,
    lightAmbientColor: '#8fa8c4',
    lightAmbientIntensity: 0.25,
    lightHemiEnabled: true,
    lightHemiSkyColor: '#b7cbe4',
    lightHemiGroundColor: '#12161c',
    lightHemiIntensity: 0.4,
    lightKeyEnabled: true,
    lightKeyColor: '#eef4ff',
    lightKeyIntensity: 140,
    lightKeyPosition: {
      x: 3,
      y: 8,
      z: 4,
    },
    lightKeyTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    lightKeyAngle: 36,
    lightKeyPenumbra: 0.8,
    lightKeyDistance: 26,
    lightKeyDecay: 1.1,
    lightKeyCastShadow: true,
    lightKeyShadowMapSize: 2048,
    lightKeyShadowBias: -0.0004,
    lightKeyShadowNormalBias: 0,
    lightKeyShadowFar: 22,
    lightKeyDebug: false,
    paletteName: 'Red Blood Pain (lospec)',
    paletteMix: 1,
    paletteAdvect: 0,
    paletteShift: 0,
    seed: 88121,
    bedCount: 220000,
    grainSize: 0.014,
    grainSizeMin: 0.55,
    grainSizeMax: 1.45,
    grainSizeCoarse: 1,
    bedRadius: 3.4,
    bedThickness: 0.05,
    bedBaseY: 0,
    fieldHeightScale: 0.08,
    grainRoll: 6,
    fieldTint: 0.55,
    fieldTintColor: '#3d3226',
    cullEnabled: true,
    cullThreshold: 0.4,
    cullSoftness: 0.07,
    grainRoughness: 0.4,
    grainMetalness: 0.15,
    grainColor: '#c9b493',
    grainPaletteMix: 0.4,
    grainColorB: '#a68a63',
    grainColorC: '#e6dcc8',
    grainPaletteSplitB: 0.55,
    grainPaletteSplitC: 0.85,
    fieldResolution: 384,
    growthMode: 'seedDrops',
    boundaryBounce: false,
    seedRadius: 0.07,
    dropInterval: 5,
    dropFade: 1.5,
    followDrop: false,
    followDropDamping: 0.3,
    paletteRefresh: 0.008,
    fieldContrast: 14,
    decayRate: 0.002,
    reactionStrength: 0.047,
    noiseAmount: 0.0025,
    expansionStrength: 8,
    blurSpread: 1,
    backgroundColor: '#3a3a3a',
    floorColor: '#3a3a3a',
    floorCenterColor: '#3a3a3a',
    wallLowColor: '#3a3a3a',
    wallHighColor: '#3a3a3a',
    wallGradientStart: 0,
    wallGradientEnd: 0.8,
    floorHeight: -0.8,
    roomRadius: 12,
    roomHeight: 18,
    fogNear: 14,
    fogFar: 50,
    postEnabled: true,
    postDofEnabled: true,
    postDofFocusMode: 'pointer',
    postDofFocusDistance: 9.5,
    postDofFocalLength: 3,
    postDofBokehScale: 4,
    postDofFocusSmoothing: 6,
  },
  Ocean: {
    cameraMode: 'orbit',
    cameraAutoFit: false,
    fixedBehavior: 'single',
    fixedShotDefaultDesktopPosition: {
      x: 0,
      y: 0,
      z: 5,
    },
    fixedShotDefaultDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    fixedShotDefaultDesktopFov: 50,
    fixedShotDefaultMobilePosition: {
      x: 0,
      y: 0,
      z: 5,
    },
    fixedShotDefaultMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    fixedShotDefaultMobileFov: 50,
    orbitAutoRotate: true,
    orbitAutoRotateSpeed: 1.2,
    orbitEnablePan: true,
    orbitMinPolarAngle: 0,
    orbitMaxPolarAngle: 180,
    orbitAzimuthUnlimited: true,
    orbitMinAzimuthAngle: -180,
    orbitMaxAzimuthAngle: 180,
    orbitMinDistance: 0,
    orbitMaxDistanceUnlimited: true,
    orbitMaxDistance: 100,
    orbitDesktopPosition: {
      x: 0,
      y: 7.5,
      z: 6,
    },
    orbitDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitDesktopPivot: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitDesktopFov: 46,
    orbitMobilePosition: {
      x: 0,
      y: 12,
      z: 0.01,
    },
    orbitMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitMobilePivot: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitMobileFov: 54,
    splinePreset: 'Spiral Up',
    splineDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineDesktopFov: 15,
    splineMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineMobileFov: 50,
    splineOrientationMode: 'target',
    splineForwardDistance: 1,
    splinePosition: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineScale: {
      x: 1,
      y: 0.5,
      z: 1,
    },
    splineDuration: 60,
    splineTension: 0.5,
    splineClosed: true,
    splineShowPath: false,
    operatorMoveSpeed: 6,
    operatorLiftSpeed: 6,
    operatorBoostMultiplier: 2,
    operatorPointerLookSensitivity: 0.003,
    operatorStickLookSpeed: 2.5,
    operatorZoomSpeed: 24,
    operatorMinFov: 20,
    operatorMaxFov: 80,
    lightEnabled: true,
    lightAmbientEnabled: true,
    lightAmbientColor: '#8fa8c4',
    lightAmbientIntensity: 0.25,
    lightHemiEnabled: true,
    lightHemiSkyColor: '#b7cbe4',
    lightHemiGroundColor: '#12161c',
    lightHemiIntensity: 0.4,
    lightKeyEnabled: true,
    lightKeyColor: '#eef4ff',
    lightKeyIntensity: 140,
    lightKeyPosition: {
      x: 3,
      y: 8,
      z: 4,
    },
    lightKeyTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    lightKeyAngle: 36,
    lightKeyPenumbra: 0.8,
    lightKeyDistance: 26,
    lightKeyDecay: 1.1,
    lightKeyCastShadow: true,
    lightKeyShadowMapSize: 2048,
    lightKeyShadowBias: -0.0004,
    lightKeyShadowNormalBias: 0,
    lightKeyShadowFar: 22,
    lightKeyDebug: false,
    paletteName: 'Deep Maze (lospec)',
    paletteMix: 1,
    paletteAdvect: 0,
    paletteShift: 0,
    seed: 88121,
    bedCount: 220000,
    grainSize: 0.014,
    grainSizeMin: 0.55,
    grainSizeMax: 1.45,
    grainSizeCoarse: 1,
    bedRadius: 3.4,
    bedThickness: 0.05,
    bedBaseY: 0.075,
    fieldHeightScale: 0.08,
    grainRoll: 6,
    fieldTint: 0.55,
    fieldTintColor: '#3d3226',
    cullEnabled: true,
    cullThreshold: 0.4,
    cullSoftness: 0.07,
    grainRoughness: 0.4,
    grainMetalness: 0.15,
    grainColor: '#c9b493',
    grainPaletteMix: 0.4,
    grainColorB: '#a68a63',
    grainColorC: '#e6dcc8',
    grainPaletteSplitB: 0.55,
    grainPaletteSplitC: 0.85,
    fieldResolution: 384,
    growthMode: 'alwaysOn',
    boundaryBounce: false,
    seedRadius: 0.07,
    dropInterval: 5,
    dropFade: 1.5,
    followDrop: false,
    followDropDamping: 0.3,
    paletteRefresh: 0.008,
    fieldContrast: 14,
    decayRate: 0.002,
    reactionStrength: 0.047,
    noiseAmount: 0.0025,
    expansionStrength: 8,
    blurSpread: 1,
    backgroundColor: '#3a3a3a',
    floorColor: '#3a3a3a',
    floorCenterColor: '#3a3a3a',
    wallLowColor: '#3a3a3a',
    wallHighColor: '#3a3a3a',
    wallGradientStart: 0,
    wallGradientEnd: 0.8,
    floorHeight: -0.8,
    roomRadius: 12,
    roomHeight: 18,
    fogNear: 14,
    fogFar: 50,
    postEnabled: true,
    postDofEnabled: true,
    postDofFocusMode: 'pointer',
    postDofFocusDistance: 9.5,
    postDofFocalLength: 3,
    postDofBokehScale: 4,
    postDofFocusSmoothing: 6,
  },
};

export function getPresetControls({ presetSnapshot }) {
  return { ...presetSnapshot };
}
