// Preset snapshots for the scene. Keys here must match the Leva schema built
// in useSceneControls 1:1 — no reshaping between a preset and the controls it
// applies (see docs/scene-conventions.md, "Controls & presets").
export const DEFAULT_PRESET = 'Default';

// Phase 1 ships only this one preset (core CA compute/growth/palette + the
// Windswept-style godray/light centerpiece). The other three from the
// original ask — Cloud + Flow Field, Fixed Megalith, Fixed With Growth
// Pockets — are explicitly Phase 2, tracked in todo.md, not implemented here.
export const PRESETS = {
  Default: {
    cameraMode: 'orbit',
    cameraAutoFit: true,
    fixedBehavior: 'single',
    fixedShotHeroDesktopPosition: { x: 64, y: 48, z: 96 },
    fixedShotHeroDesktopTarget: { x: 0, y: 0, z: 0 },
    fixedShotHeroDesktopFov: 45,
    fixedShotHeroMobilePosition: { x: 64, y: 48, z: 96 },
    fixedShotHeroMobileTarget: { x: 0, y: 0, z: 0 },
    fixedShotHeroMobileFov: 45,
    orbitAutoRotate: true,
    orbitAutoRotateSpeed: 4,
    orbitDesktopPosition: { x: 64, y: 48, z: 96 },
    orbitDesktopTarget: { x: 0, y: 0, z: 0 },
    orbitDesktopPivot: { x: 0, y: 0, z: 0 },
    orbitDesktopFov: 45,
    orbitMobilePosition: { x: 80, y: 60, z: 120 },
    orbitMobileTarget: { x: 0, y: 0, z: 0 },
    orbitMobilePivot: { x: 0, y: 0, z: 0 },
    orbitMobileFov: 55,
    splineDesktopTarget: { x: 0, y: 0, z: 0 },
    splineDesktopFov: 45,
    splineMobileTarget: { x: 0, y: 0, z: 0 },
    splineMobileFov: 45,
    splineOrientationMode: 'target',
    splineForwardDistance: 1,
    splinePosition: { x: 0, y: 0, z: 0 },
    splineScale: { x: 1, y: 1, z: 1 },
    splineDuration: 30,
    splineTension: 0.5,
    splineClosed: true,
    splineShowPath: false,
    operatorMoveSpeed: 6,
    operatorLiftSpeed: 6,
    operatorBoostMultiplier: 2,
    operatorPointerLookSensitivity: 0.003,
    operatorStickLookSpeed: 2.5,
    operatorZoomSpeed: 24,
    operatorMinFov: 20,
    operatorMaxFov: 80,
    // CA generation settings match ~/dev/examples/260708_AutomataChunks's own
    // DEFAULT_SETTINGS (types.ts) exactly, so the structure this preset grows
    // is the same one that reference renders — level 7 alone is a ~7.8x
    // instance-count jump from level 6 (2,146,689 vs 274,625), so watch frame
    // time if you dial it down for perf.
    level: 7,
    seed: 260708,
    baseFill: 'random',
    ruleMode: 'random',
    density: 0.34,
    beta: 0.56,
    magnetism: 0.1,
    flipChance: 0.02,
    removeStrays: true,
    cellSpacing: 0.6,
    cellScale: 0.6,
    growthEnabled: false,
    growthDurationSeconds: 3,
    growthJitter: 0.8,
    // 'state' colorMode + these three colors reproduces the reference's
    // per-state stateColors ['#fe6c6c', '#4fceee', '#fdbd81'] exactly — the
    // state colorMode only ever samples t at {0, 0.5, 1}, landing squarely on
    // paletteStart/Mid/End with no in-between blending.
    colorMode: 'state',
    paletteStart: '#ff0000',
    paletteMid: '#ffffff',
    paletteEnd: '#7c7c7c',
    paletteMidpoint: 0.5,
    // Lighting settings match ~/dev/examples/260708_AutomataChunks's own
    // DEFAULT_SETTINGS exactly — see components/LightRig.jsx.
    lightAzimuth: 25.65,
    lightElevation: 68.7,
    keyLightIntensity: 2.41,
    ambientIntensity: 0.3,
    rimLightIntensity: 0.49,
    bounceLightIntensity: 0.07,
    shadowIntensity: 1.08,
    shadowSoftness: 2.6,
    exposure: 0.7,
    backgroundColor: '#03040a',
    godraysEnabled: false,
    godraysColor: '#ffd27a',
    godraysPosition: { x: 0, y: 0, z: 0 },
    godraysIntensity: 20,
    godraysBlendColor: '#ffd27a',
    godraysVolumeSize: 80,
    godraysDensity: 0.7,
    godraysMaxDensity: 0.5,
    godraysDistanceAttenuation: 2,
    godraysRaymarchSteps: 60,
    godraysBlur: false,
    godraysEdgeRadius: 2,
    godraysEdgeStrength: 2,
  },
  1: {
    cameraMode: 'orbit',
    cameraAutoFit: true,
    fixedBehavior: 'single',
    fixedShotHeroDesktopPosition: {
      x: 64,
      y: 48,
      z: 96,
    },
    fixedShotHeroDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    fixedShotHeroDesktopFov: 45,
    fixedShotHeroMobilePosition: {
      x: 64,
      y: 48,
      z: 96,
    },
    fixedShotHeroMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    fixedShotHeroMobileFov: 45,
    orbitAutoRotate: true,
    orbitAutoRotateSpeed: 4,
    orbitDesktopPosition: {
      x: 64,
      y: 48,
      z: 96,
    },
    orbitDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitDesktopPivot: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitDesktopFov: 45,
    orbitMobilePosition: {
      x: 80,
      y: 60,
      z: 120,
    },
    orbitMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitMobilePivot: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitMobileFov: 55,
    splineDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineDesktopFov: 45,
    splineMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineMobileFov: 45,
    splineOrientationMode: 'target',
    splineForwardDistance: 1,
    splinePosition: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineScale: {
      x: 1,
      y: 1,
      z: 1,
    },
    splineDuration: 30,
    splineTension: 0.5,
    splineClosed: true,
    splineShowPath: false,
    operatorMoveSpeed: 6,
    operatorLiftSpeed: 6,
    operatorBoostMultiplier: 2,
    operatorPointerLookSensitivity: 0.003,
    operatorStickLookSpeed: 2.5,
    operatorZoomSpeed: 24,
    operatorMinFov: 20,
    operatorMaxFov: 80,
    level: 7,
    seed: 914774,
    baseFill: 'random',
    ruleMode: 'random',
    density: 0.34,
    beta: 0.56,
    magnetism: 0.1,
    flipChance: 0.02,
    removeStrays: true,
    cellSpacing: 0.6,
    cellScale: 0.6,
    growthEnabled: false,
    growthDurationSeconds: 3,
    growthJitter: 0.8,
    colorMode: 'state',
    paletteStart: '#ff0000',
    paletteMid: '#ffffff',
    paletteEnd: '#7c7c7c',
    paletteMidpoint: 0.5,
    lightAzimuth: 25.65,
    lightElevation: 68.7,
    keyLightIntensity: 2.41,
    ambientIntensity: 0.3,
    rimLightIntensity: 0.49,
    bounceLightIntensity: 0.07,
    shadowIntensity: 1.08,
    shadowSoftness: 2.6,
    exposure: 0.7,
    godraysEnabled: false,
    godraysColor: '#ffd27a',
    godraysIntensity: 20,
    godraysBlendColor: '#ffd27a',
    godraysVolumeSize: 80,
    godraysDensity: 0.7,
    godraysMaxDensity: 0.5,
    godraysDistanceAttenuation: 2,
    godraysRaymarchSteps: 60,
    godraysBlur: false,
    godraysEdgeRadius: 2,
    godraysEdgeStrength: 2,
  },
  'Fixed Megalith': {
    cameraMode: 'orbit',
    cameraAutoFit: true,
    fixedBehavior: 'single',
    fixedShotHeroDesktopPosition: {
      x: 64,
      y: 48,
      z: 96,
    },
    fixedShotHeroDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    fixedShotHeroDesktopFov: 45,
    fixedShotHeroMobilePosition: {
      x: 64,
      y: 48,
      z: 96,
    },
    fixedShotHeroMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    fixedShotHeroMobileFov: 45,
    orbitAutoRotate: true,
    orbitAutoRotateSpeed: 4,
    orbitDesktopPosition: {
      x: 64,
      y: 48,
      z: 96,
    },
    orbitDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitDesktopPivot: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitDesktopFov: 45,
    orbitMobilePosition: {
      x: 80,
      y: 60,
      z: 120,
    },
    orbitMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitMobilePivot: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitMobileFov: 55,
    splineDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineDesktopFov: 45,
    splineMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineMobileFov: 45,
    splineOrientationMode: 'target',
    splineForwardDistance: 1,
    splinePosition: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineScale: {
      x: 1,
      y: 1,
      z: 1,
    },
    splineDuration: 30,
    splineTension: 0.5,
    splineClosed: true,
    splineShowPath: false,
    operatorMoveSpeed: 6,
    operatorLiftSpeed: 6,
    operatorBoostMultiplier: 2,
    operatorPointerLookSensitivity: 0.003,
    operatorStickLookSpeed: 2.5,
    operatorZoomSpeed: 24,
    operatorMinFov: 20,
    operatorMaxFov: 80,
    level: 7,
    seed: 914774,
    baseFill: 'random',
    ruleMode: 'random',
    density: 0.34,
    beta: 0.56,
    magnetism: 0.1,
    flipChance: 0.02,
    removeStrays: true,
    cellSpacing: 0.6,
    cellScale: 0.6,
    growthEnabled: false,
    growthDurationSeconds: 3,
    growthJitter: 0.8,
    colorMode: 'state',
    paletteStart: '#ff0000',
    paletteMid: '#ffffff',
    paletteEnd: '#7c7c7c',
    paletteMidpoint: 0.5,
    lightAzimuth: 25.65,
    lightElevation: 68.7,
    keyLightIntensity: 2.41,
    ambientIntensity: 0.3,
    rimLightIntensity: 0.49,
    bounceLightIntensity: 0.07,
    shadowIntensity: 1.08,
    shadowSoftness: 2.6,
    exposure: 0.7,
    godraysEnabled: false,
    godraysColor: '#ffd27a',
    godraysIntensity: 20,
    godraysBlendColor: '#ffd27a',
    godraysVolumeSize: 80,
    godraysDensity: 0.7,
    godraysMaxDensity: 0.5,
    godraysDistanceAttenuation: 2,
    godraysRaymarchSteps: 60,
    godraysBlur: false,
    godraysEdgeRadius: 2,
    godraysEdgeStrength: 2,
  },
  2: {
    cameraMode: 'orbit',
    cameraAutoFit: true,
    fixedBehavior: 'single',
    fixedShotHeroDesktopPosition: {
      x: 64,
      y: 48,
      z: 96,
    },
    fixedShotHeroDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    fixedShotHeroDesktopFov: 45,
    fixedShotHeroMobilePosition: {
      x: 64,
      y: 48,
      z: 96,
    },
    fixedShotHeroMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    fixedShotHeroMobileFov: 45,
    orbitAutoRotate: true,
    orbitAutoRotateSpeed: 4,
    orbitDesktopPosition: {
      x: 64,
      y: 48,
      z: 96,
    },
    orbitDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitDesktopPivot: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitDesktopFov: 45,
    orbitMobilePosition: {
      x: 80,
      y: 60,
      z: 120,
    },
    orbitMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitMobilePivot: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitMobileFov: 55,
    splineDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineDesktopFov: 45,
    splineMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineMobileFov: 45,
    splineOrientationMode: 'target',
    splineForwardDistance: 1,
    splinePosition: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineScale: {
      x: 1,
      y: 1,
      z: 1,
    },
    splineDuration: 30,
    splineTension: 0.5,
    splineClosed: true,
    splineShowPath: false,
    operatorMoveSpeed: 6,
    operatorLiftSpeed: 6,
    operatorBoostMultiplier: 2,
    operatorPointerLookSensitivity: 0.003,
    operatorStickLookSpeed: 2.5,
    operatorZoomSpeed: 24,
    operatorMinFov: 20,
    operatorMaxFov: 80,
    level: 7,
    seed: 390287,
    baseFill: 'random',
    ruleMode: 'random',
    density: 0.34,
    beta: 0.56,
    magnetism: 0.1,
    flipChance: 0.02,
    removeStrays: true,
    cellSpacing: 0.6,
    cellScale: 0.6,
    growthEnabled: false,
    growthDurationSeconds: 3,
    growthJitter: 0.8,
    colorMode: 'state',
    paletteStart: '#ff0000',
    paletteMid: '#ffffff',
    paletteEnd: '#7c7c7c',
    paletteMidpoint: 0.5,
    lightAzimuth: 194.46,
    lightElevation: 20.730000000000004,
    keyLightIntensity: 2.41,
    ambientIntensity: 0.3,
    rimLightIntensity: 0.49,
    bounceLightIntensity: 0.07,
    shadowIntensity: 1.08,
    shadowSoftness: 2.6,
    exposure: 0.7,
    godraysEnabled: true,
    godraysColor: '#ffffff',
    godraysIntensity: 20,
    godraysBlendColor: '#ffffff',
    godraysVolumeSize: 80,
    godraysDensity: 0.7,
    godraysMaxDensity: 0.5,
    godraysDistanceAttenuation: 2,
    godraysRaymarchSteps: 60,
    godraysBlur: false,
    godraysEdgeRadius: 2,
    godraysEdgeStrength: 2,
  },
  Citadel: {
    cameraMode: 'orbit',
    cameraAutoFit: true,
    fixedBehavior: 'single',
    fixedShotHeroDesktopPosition: {
      x: 64,
      y: 48,
      z: 96,
    },
    fixedShotHeroDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    fixedShotHeroDesktopFov: 45,
    fixedShotHeroMobilePosition: {
      x: 64,
      y: 48,
      z: 96,
    },
    fixedShotHeroMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    fixedShotHeroMobileFov: 45,
    orbitAutoRotate: true,
    orbitAutoRotateSpeed: 16,
    orbitDesktopPosition: {
      x: 64,
      y: 48,
      z: 96,
    },
    orbitDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitDesktopPivot: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitDesktopFov: 45,
    orbitMobilePosition: {
      x: 80,
      y: 60,
      z: 120,
    },
    orbitMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitMobilePivot: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitMobileFov: 55,
    splineDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineDesktopFov: 45,
    splineMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineMobileFov: 45,
    splineOrientationMode: 'target',
    splineForwardDistance: 1,
    splinePosition: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineScale: {
      x: 1,
      y: 1,
      z: 1,
    },
    splineDuration: 30,
    splineTension: 0.5,
    splineClosed: true,
    splineShowPath: false,
    operatorMoveSpeed: 6,
    operatorLiftSpeed: 6,
    operatorBoostMultiplier: 2,
    operatorPointerLookSensitivity: 0.003,
    operatorStickLookSpeed: 2.5,
    operatorZoomSpeed: 24,
    operatorMinFov: 20,
    operatorMaxFov: 80,
    level: 7,
    seed: 508876,
    baseFill: 'random',
    ruleMode: 'random',
    density: 0.34,
    beta: 0.56,
    magnetism: 0.1,
    flipChance: 0.02,
    removeStrays: true,
    cellSpacing: 0.6,
    cellScale: 0.6,
    growthEnabled: false,
    growthDurationSeconds: 3,
    growthJitter: 1,
    colorMode: 'state',
    paletteStart: '#6f6f6f',
    paletteMid: '#ffffff',
    paletteEnd: '#000000',
    paletteMidpoint: 0.5,
    lightAzimuth: 194.46,
    lightElevation: 20.730000000000004,
    keyLightIntensity: 2.41,
    ambientIntensity: 0.3,
    rimLightIntensity: 0.49,
    bounceLightIntensity: 0.07,
    shadowIntensity: 1.08,
    shadowSoftness: 2.6,
    exposure: 0.7,
    godraysEnabled: true,
    godraysColor: '#ffffff',
    godraysIntensity: 20,
    godraysBlendColor: '#ffffff',
    godraysVolumeSize: 80,
    godraysDensity: 0.7,
    godraysMaxDensity: 0.5,
    godraysDistanceAttenuation: 2,
    godraysRaymarchSteps: 60,
    godraysBlur: false,
    godraysEdgeRadius: 2,
    godraysEdgeStrength: 2,
  },
  Colloseum: {
    cameraMode: 'orbit',
    cameraAutoFit: true,
    fixedBehavior: 'single',
    fixedShotHeroDesktopPosition: {
      x: 64,
      y: 48,
      z: 96,
    },
    fixedShotHeroDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    fixedShotHeroDesktopFov: 45,
    fixedShotHeroMobilePosition: {
      x: 64,
      y: 48,
      z: 96,
    },
    fixedShotHeroMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    fixedShotHeroMobileFov: 45,
    orbitAutoRotate: true,
    orbitAutoRotateSpeed: 16,
    orbitDesktopPosition: {
      x: 64,
      y: 48,
      z: 96,
    },
    orbitDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitDesktopPivot: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitDesktopFov: 45,
    orbitMobilePosition: {
      x: 80,
      y: 60,
      z: 120,
    },
    orbitMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitMobilePivot: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitMobileFov: 55,
    splineDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineDesktopFov: 45,
    splineMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineMobileFov: 45,
    splineOrientationMode: 'target',
    splineForwardDistance: 1,
    splinePosition: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineScale: {
      x: 1,
      y: 1,
      z: 1,
    },
    splineDuration: 30,
    splineTension: 0.5,
    splineClosed: true,
    splineShowPath: false,
    operatorMoveSpeed: 6,
    operatorLiftSpeed: 6,
    operatorBoostMultiplier: 2,
    operatorPointerLookSensitivity: 0.003,
    operatorStickLookSpeed: 2.5,
    operatorZoomSpeed: 24,
    operatorMinFov: 20,
    operatorMaxFov: 80,
    level: 7,
    seed: 88857,
    baseFill: 'random',
    ruleMode: 'random',
    density: 0.34,
    beta: 0.56,
    magnetism: 0.1,
    flipChance: 0.02,
    removeStrays: true,
    cellSpacing: 0.6,
    cellScale: 0.6,
    growthEnabled: false,
    growthDurationSeconds: 3,
    growthJitter: 1,
    colorMode: 'state',
    paletteStart: '#ffffff',
    paletteMid: '#ff0000',
    paletteEnd: '#000000',
    paletteMidpoint: 0.21999999999999997,
    lightAzimuth: 194.46,
    lightElevation: 20.730000000000004,
    keyLightIntensity: 2.41,
    ambientIntensity: 0.3,
    rimLightIntensity: 0.49,
    bounceLightIntensity: 0.07,
    shadowIntensity: 1.08,
    shadowSoftness: 2.6,
    exposure: 0.7,
    godraysEnabled: true,
    godraysColor: '#ffffff',
    godraysIntensity: 20,
    godraysBlendColor: '#ffffff',
    godraysVolumeSize: 80,
    godraysDensity: 0.7,
    godraysMaxDensity: 0.5,
    godraysDistanceAttenuation: 2,
    godraysRaymarchSteps: 60,
    godraysBlur: false,
    godraysEdgeRadius: 2,
    godraysEdgeStrength: 2,
  },
  Circuit: {
    cameraMode: 'orbit',
    cameraAutoFit: true,
    fixedBehavior: 'single',
    fixedShotHeroDesktopPosition: {
      x: 64,
      y: 48,
      z: 96,
    },
    fixedShotHeroDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    fixedShotHeroDesktopFov: 45,
    fixedShotHeroMobilePosition: {
      x: 64,
      y: 48,
      z: 96,
    },
    fixedShotHeroMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    fixedShotHeroMobileFov: 45,
    orbitAutoRotate: true,
    orbitAutoRotateSpeed: 16,
    orbitDesktopPosition: {
      x: 64,
      y: 48,
      z: 96,
    },
    orbitDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitDesktopPivot: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitDesktopFov: 45,
    orbitMobilePosition: {
      x: 80,
      y: 60,
      z: 120,
    },
    orbitMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitMobilePivot: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitMobileFov: 55,
    splineDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineDesktopFov: 45,
    splineMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineMobileFov: 45,
    splineOrientationMode: 'target',
    splineForwardDistance: 1,
    splinePosition: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineScale: {
      x: 1,
      y: 1,
      z: 1,
    },
    splineDuration: 30,
    splineTension: 0.5,
    splineClosed: true,
    splineShowPath: false,
    operatorMoveSpeed: 6,
    operatorLiftSpeed: 6,
    operatorBoostMultiplier: 2,
    operatorPointerLookSensitivity: 0.003,
    operatorStickLookSpeed: 2.5,
    operatorZoomSpeed: 24,
    operatorMinFov: 20,
    operatorMaxFov: 80,
    level: 7,
    seed: 662567,
    baseFill: 'random',
    ruleMode: 'random',
    density: 0.34,
    beta: 0.56,
    magnetism: 0.1,
    flipChance: 0.02,
    removeStrays: true,
    cellSpacing: 0.6,
    cellScale: 0.6,
    growthEnabled: false,
    growthDurationSeconds: 3,
    growthJitter: 1,
    colorMode: 'state',
    paletteStart: '#ffffff',
    paletteMid: '#ff0000',
    paletteEnd: '#000000',
    paletteMidpoint: 0.21999999999999997,
    lightAzimuth: 194.46,
    lightElevation: 20.730000000000004,
    keyLightIntensity: 2.41,
    ambientIntensity: 0.3,
    rimLightIntensity: 0.49,
    bounceLightIntensity: 0.07,
    shadowIntensity: 1.08,
    shadowSoftness: 2.6,
    exposure: 0.7,
    godraysEnabled: true,
    godraysColor: '#ffffff',
    godraysIntensity: 20,
    godraysBlendColor: '#ffffff',
    godraysVolumeSize: 80,
    godraysDensity: 0.7,
    godraysMaxDensity: 0.5,
    godraysDistanceAttenuation: 2,
    godraysRaymarchSteps: 60,
    godraysBlur: false,
    godraysEdgeRadius: 2,
    godraysEdgeStrength: 2,
  },
  Pyramid: {
    cameraMode: 'orbit',
    cameraAutoFit: true,
    fixedBehavior: 'single',
    fixedShotHeroDesktopPosition: {
      x: 64,
      y: 48,
      z: 96,
    },
    fixedShotHeroDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    fixedShotHeroDesktopFov: 45,
    fixedShotHeroMobilePosition: {
      x: 64,
      y: 48,
      z: 96,
    },
    fixedShotHeroMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    fixedShotHeroMobileFov: 45,
    orbitAutoRotate: true,
    orbitAutoRotateSpeed: 16,
    orbitDesktopPosition: {
      x: 64,
      y: 48,
      z: 96,
    },
    orbitDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitDesktopPivot: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitDesktopFov: 45,
    orbitMobilePosition: {
      x: 80,
      y: 60,
      z: 120,
    },
    orbitMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitMobilePivot: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitMobileFov: 55,
    splineDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineDesktopFov: 45,
    splineMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineMobileFov: 45,
    splineOrientationMode: 'target',
    splineForwardDistance: 1,
    splinePosition: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineScale: {
      x: 1,
      y: 1,
      z: 1,
    },
    splineDuration: 30,
    splineTension: 0.5,
    splineClosed: true,
    splineShowPath: false,
    operatorMoveSpeed: 6,
    operatorLiftSpeed: 6,
    operatorBoostMultiplier: 2,
    operatorPointerLookSensitivity: 0.003,
    operatorStickLookSpeed: 2.5,
    operatorZoomSpeed: 24,
    operatorMinFov: 20,
    operatorMaxFov: 80,
    level: 7,
    seed: 109895,
    baseFill: 'random',
    ruleMode: 'random',
    density: 0.34,
    beta: 0.56,
    magnetism: 0.1,
    flipChance: 0.02,
    removeStrays: true,
    cellSpacing: 0.6,
    cellScale: 0.6,
    growthEnabled: false,
    growthDurationSeconds: 3,
    growthJitter: 1,
    colorMode: 'state',
    paletteStart: '#ffffff',
    paletteMid: '#ff0000',
    paletteEnd: '#000000',
    paletteMidpoint: 0.21999999999999997,
    lightAzimuth: 194.46,
    lightElevation: 20.730000000000004,
    keyLightIntensity: 2.41,
    ambientIntensity: 0.3,
    rimLightIntensity: 0.49,
    bounceLightIntensity: 0.07,
    shadowIntensity: 1.08,
    shadowSoftness: 2.6,
    exposure: 0.7,
    godraysEnabled: true,
    godraysColor: '#ffffff',
    godraysIntensity: 20,
    godraysBlendColor: '#ffffff',
    godraysVolumeSize: 80,
    godraysDensity: 0.7,
    godraysMaxDensity: 0.5,
    godraysDistanceAttenuation: 2,
    godraysRaymarchSteps: 60,
    godraysBlur: false,
    godraysEdgeRadius: 2,
    godraysEdgeStrength: 2,
  },
  Spire: {
    cameraMode: 'orbit',
    cameraAutoFit: true,
    fixedBehavior: 'single',
    fixedShotHeroDesktopPosition: {
      x: 64,
      y: 48,
      z: 96,
    },
    fixedShotHeroDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    fixedShotHeroDesktopFov: 45,
    fixedShotHeroMobilePosition: {
      x: 64,
      y: 48,
      z: 96,
    },
    fixedShotHeroMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    fixedShotHeroMobileFov: 45,
    orbitAutoRotate: true,
    orbitAutoRotateSpeed: 16,
    orbitDesktopPosition: {
      x: 64,
      y: 48,
      z: 96,
    },
    orbitDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitDesktopPivot: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitDesktopFov: 45,
    orbitMobilePosition: {
      x: 80,
      y: 60,
      z: 120,
    },
    orbitMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitMobilePivot: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitMobileFov: 55,
    splineDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineDesktopFov: 45,
    splineMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineMobileFov: 45,
    splineOrientationMode: 'target',
    splineForwardDistance: 1,
    splinePosition: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineScale: {
      x: 1,
      y: 1,
      z: 1,
    },
    splineDuration: 30,
    splineTension: 0.5,
    splineClosed: true,
    splineShowPath: false,
    operatorMoveSpeed: 6,
    operatorLiftSpeed: 6,
    operatorBoostMultiplier: 2,
    operatorPointerLookSensitivity: 0.003,
    operatorStickLookSpeed: 2.5,
    operatorZoomSpeed: 24,
    operatorMinFov: 20,
    operatorMaxFov: 80,
    level: 7,
    seed: 289418,
    baseFill: 'random',
    ruleMode: 'random',
    density: 0.34,
    beta: 0.56,
    magnetism: 0.1,
    flipChance: 0.02,
    removeStrays: true,
    cellSpacing: 0.6,
    cellScale: 0.6,
    growthEnabled: false,
    growthDurationSeconds: 1,
    growthJitter: 1,
    colorMode: 'state',
    paletteStart: '#ffffff',
    paletteMid: '#ff0000',
    paletteEnd: '#000000',
    paletteMidpoint: 0.21999999999999997,
    lightAzimuth: 194.46,
    lightElevation: 20.730000000000004,
    keyLightIntensity: 2.41,
    ambientIntensity: 0.3,
    rimLightIntensity: 0.49,
    bounceLightIntensity: 0.07,
    shadowIntensity: 1.08,
    shadowSoftness: 2.6,
    exposure: 0.7,
    godraysEnabled: false,
    godraysColor: '#ffffff',
    godraysIntensity: 20,
    godraysBlendColor: '#ffffff',
    godraysVolumeSize: 80,
    godraysDensity: 0.7,
    godraysMaxDensity: 0.5,
    godraysDistanceAttenuation: 2,
    godraysRaymarchSteps: 60,
    godraysBlur: false,
    godraysEdgeRadius: 2,
    godraysEdgeStrength: 2,
  },
  Mountain: {
    cameraMode: 'orbit',
    cameraAutoFit: true,
    fixedBehavior: 'single',
    fixedShotHeroDesktopPosition: {
      x: 64,
      y: 48,
      z: 96,
    },
    fixedShotHeroDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    fixedShotHeroDesktopFov: 45,
    fixedShotHeroMobilePosition: {
      x: 64,
      y: 48,
      z: 96,
    },
    fixedShotHeroMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    fixedShotHeroMobileFov: 45,
    orbitAutoRotate: true,
    orbitAutoRotateSpeed: 16,
    orbitDesktopPosition: {
      x: 64,
      y: 48,
      z: 96,
    },
    orbitDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitDesktopPivot: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitDesktopFov: 45,
    orbitMobilePosition: {
      x: 80,
      y: 60,
      z: 120,
    },
    orbitMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitMobilePivot: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitMobileFov: 55,
    splineDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineDesktopFov: 45,
    splineMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineMobileFov: 45,
    splineOrientationMode: 'target',
    splineForwardDistance: 1,
    splinePosition: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineScale: {
      x: 1,
      y: 1,
      z: 1,
    },
    splineDuration: 30,
    splineTension: 0.5,
    splineClosed: true,
    splineShowPath: false,
    operatorMoveSpeed: 6,
    operatorLiftSpeed: 6,
    operatorBoostMultiplier: 2,
    operatorPointerLookSensitivity: 0.003,
    operatorStickLookSpeed: 2.5,
    operatorZoomSpeed: 24,
    operatorMinFov: 20,
    operatorMaxFov: 80,
    level: 7,
    seed: 295140,
    baseFill: 'random',
    ruleMode: 'random',
    density: 0.34,
    beta: 0.56,
    magnetism: 0.1,
    flipChance: 0.02,
    removeStrays: true,
    cellSpacing: 0.6,
    cellScale: 0.6,
    growthEnabled: false,
    growthDurationSeconds: 1,
    growthJitter: 1,
    colorMode: 'state',
    paletteStart: '#ffffff',
    paletteMid: '#ff0000',
    paletteEnd: '#000000',
    paletteMidpoint: 0.21999999999999997,
    lightAzimuth: 194.46,
    lightElevation: 20.730000000000004,
    keyLightIntensity: 2.41,
    ambientIntensity: 0.3,
    rimLightIntensity: 0.49,
    bounceLightIntensity: 0.07,
    shadowIntensity: 1.08,
    shadowSoftness: 2.6,
    exposure: 0.7,
    godraysEnabled: false,
    godraysColor: '#ffffff',
    godraysIntensity: 20,
    godraysBlendColor: '#ffffff',
    godraysVolumeSize: 80,
    godraysDensity: 0.7,
    godraysMaxDensity: 0.5,
    godraysDistanceAttenuation: 2,
    godraysRaymarchSteps: 60,
    godraysBlur: false,
    godraysEdgeRadius: 2,
    godraysEdgeStrength: 2,
  },
  Throne: {
    cameraMode: 'orbit',
    cameraAutoFit: true,
    fixedBehavior: 'single',
    fixedShotHeroDesktopPosition: {
      x: 64,
      y: 48,
      z: 96,
    },
    fixedShotHeroDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    fixedShotHeroDesktopFov: 45,
    fixedShotHeroMobilePosition: {
      x: 64,
      y: 48,
      z: 96,
    },
    fixedShotHeroMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    fixedShotHeroMobileFov: 45,
    orbitAutoRotate: true,
    orbitAutoRotateSpeed: 16,
    orbitDesktopPosition: {
      x: 64,
      y: 48,
      z: 96,
    },
    orbitDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitDesktopPivot: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitDesktopFov: 45,
    orbitMobilePosition: {
      x: 80,
      y: 60,
      z: 120,
    },
    orbitMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitMobilePivot: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitMobileFov: 55,
    splineDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineDesktopFov: 45,
    splineMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineMobileFov: 45,
    splineOrientationMode: 'target',
    splineForwardDistance: 1,
    splinePosition: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineScale: {
      x: 1,
      y: 1,
      z: 1,
    },
    splineDuration: 30,
    splineTension: 0.5,
    splineClosed: true,
    splineShowPath: false,
    operatorMoveSpeed: 6,
    operatorLiftSpeed: 6,
    operatorBoostMultiplier: 2,
    operatorPointerLookSensitivity: 0.003,
    operatorStickLookSpeed: 2.5,
    operatorZoomSpeed: 24,
    operatorMinFov: 20,
    operatorMaxFov: 80,
    level: 7,
    seed: 464204,
    baseFill: 'random',
    ruleMode: 'random',
    density: 0.34,
    beta: 0.56,
    magnetism: 0.1,
    flipChance: 0.02,
    removeStrays: true,
    cellSpacing: 0.6,
    cellScale: 0.6,
    growthEnabled: false,
    growthDurationSeconds: 1,
    growthJitter: 1,
    colorMode: 'state',
    paletteStart: '#ffffff',
    paletteMid: '#ff0000',
    paletteEnd: '#000000',
    paletteMidpoint: 0.21999999999999997,
    lightAzimuth: 194.46,
    lightElevation: 20.730000000000004,
    keyLightIntensity: 2.41,
    ambientIntensity: 0.3,
    rimLightIntensity: 0.49,
    bounceLightIntensity: 0.07,
    shadowIntensity: 1.08,
    shadowSoftness: 2.6,
    exposure: 0.7,
    godraysEnabled: false,
    godraysColor: '#ffffff',
    godraysIntensity: 20,
    godraysBlendColor: '#ffffff',
    godraysVolumeSize: 80,
    godraysDensity: 0.7,
    godraysMaxDensity: 0.5,
    godraysDistanceAttenuation: 2,
    godraysRaymarchSteps: 60,
    godraysBlur: false,
    godraysEdgeRadius: 2,
    godraysEdgeStrength: 2,
  },
  Complex: {
    cameraMode: 'orbit',
    cameraAutoFit: true,
    fixedBehavior: 'single',
    fixedShotHeroDesktopPosition: {
      x: 64,
      y: 48,
      z: 96,
    },
    fixedShotHeroDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    fixedShotHeroDesktopFov: 45,
    fixedShotHeroMobilePosition: {
      x: 64,
      y: 48,
      z: 96,
    },
    fixedShotHeroMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    fixedShotHeroMobileFov: 45,
    orbitAutoRotate: true,
    orbitAutoRotateSpeed: 16,
    orbitDesktopPosition: {
      x: 64,
      y: 48,
      z: 96,
    },
    orbitDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitDesktopPivot: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitDesktopFov: 45,
    orbitMobilePosition: {
      x: 80,
      y: 60,
      z: 120,
    },
    orbitMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitMobilePivot: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitMobileFov: 55,
    splineDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineDesktopFov: 45,
    splineMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineMobileFov: 45,
    splineOrientationMode: 'target',
    splineForwardDistance: 1,
    splinePosition: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineScale: {
      x: 1,
      y: 1,
      z: 1,
    },
    splineDuration: 30,
    splineTension: 0.5,
    splineClosed: true,
    splineShowPath: false,
    operatorMoveSpeed: 6,
    operatorLiftSpeed: 6,
    operatorBoostMultiplier: 2,
    operatorPointerLookSensitivity: 0.003,
    operatorStickLookSpeed: 2.5,
    operatorZoomSpeed: 24,
    operatorMinFov: 20,
    operatorMaxFov: 80,
    level: 7,
    seed: 238737,
    baseFill: 'random',
    ruleMode: 'random',
    density: 0.34,
    beta: 0.56,
    magnetism: 0.1,
    flipChance: 0.02,
    removeStrays: true,
    cellSpacing: 0.6,
    cellScale: 0.6,
    growthEnabled: false,
    growthDurationSeconds: 1,
    growthJitter: 1,
    colorMode: 'state',
    paletteStart: '#ffffff',
    paletteMid: '#ff0000',
    paletteEnd: '#000000',
    paletteMidpoint: 0.21999999999999997,
    lightAzimuth: 194.46,
    lightElevation: 20.730000000000004,
    keyLightIntensity: 2.41,
    ambientIntensity: 0.3,
    rimLightIntensity: 0.49,
    bounceLightIntensity: 0.07,
    shadowIntensity: 1.08,
    shadowSoftness: 2.6,
    exposure: 0.7,
    godraysEnabled: false,
    godraysColor: '#ffffff',
    godraysIntensity: 20,
    godraysBlendColor: '#ffffff',
    godraysVolumeSize: 80,
    godraysDensity: 0.7,
    godraysMaxDensity: 0.5,
    godraysDistanceAttenuation: 2,
    godraysRaymarchSteps: 60,
    godraysBlur: false,
    godraysEdgeRadius: 2,
    godraysEdgeStrength: 2,
  },
  Brutalist: {
    cameraMode: 'orbit',
    cameraAutoFit: true,
    fixedBehavior: 'single',
    fixedShotHeroDesktopPosition: {
      x: 64,
      y: 48,
      z: 96,
    },
    fixedShotHeroDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    fixedShotHeroDesktopFov: 45,
    fixedShotHeroMobilePosition: {
      x: 64,
      y: 48,
      z: 96,
    },
    fixedShotHeroMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    fixedShotHeroMobileFov: 45,
    orbitAutoRotate: true,
    orbitAutoRotateSpeed: 16,
    orbitDesktopPosition: {
      x: 64,
      y: 48,
      z: 96,
    },
    orbitDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitDesktopPivot: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitDesktopFov: 45,
    orbitMobilePosition: {
      x: 80,
      y: 60,
      z: 120,
    },
    orbitMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitMobilePivot: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitMobileFov: 55,
    splineDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineDesktopFov: 45,
    splineMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineMobileFov: 45,
    splineOrientationMode: 'target',
    splineForwardDistance: 1,
    splinePosition: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineScale: {
      x: 1,
      y: 1,
      z: 1,
    },
    splineDuration: 30,
    splineTension: 0.5,
    splineClosed: true,
    splineShowPath: false,
    operatorMoveSpeed: 6,
    operatorLiftSpeed: 6,
    operatorBoostMultiplier: 2,
    operatorPointerLookSensitivity: 0.003,
    operatorStickLookSpeed: 2.5,
    operatorZoomSpeed: 24,
    operatorMinFov: 20,
    operatorMaxFov: 80,
    level: 7,
    seed: 852010,
    baseFill: 'random',
    ruleMode: 'random',
    density: 0.34,
    beta: 0.56,
    magnetism: 0.1,
    flipChance: 0.02,
    removeStrays: true,
    cellSpacing: 0.6,
    cellScale: 0.6,
    growthEnabled: false,
    growthDurationSeconds: 1,
    growthJitter: 1,
    colorMode: 'state',
    paletteStart: '#ffffff',
    paletteMid: '#ff0000',
    paletteEnd: '#000000',
    paletteMidpoint: 0.21999999999999997,
    lightAzimuth: 194.46,
    lightElevation: 20.730000000000004,
    keyLightIntensity: 2.41,
    ambientIntensity: 0.3,
    rimLightIntensity: 0.49,
    bounceLightIntensity: 0.07,
    shadowIntensity: 1.08,
    shadowSoftness: 2.6,
    exposure: 0.7,
    godraysEnabled: false,
    godraysColor: '#ffffff',
    godraysIntensity: 20,
    godraysBlendColor: '#ffffff',
    godraysVolumeSize: 80,
    godraysDensity: 0.7,
    godraysMaxDensity: 0.5,
    godraysDistanceAttenuation: 2,
    godraysRaymarchSteps: 60,
    godraysBlur: false,
    godraysEdgeRadius: 2,
    godraysEdgeStrength: 2,
  },
  Bowl: {
    cameraMode: 'orbit',
    cameraAutoFit: true,
    fixedBehavior: 'single',
    fixedShotHeroDesktopPosition: {
      x: 64,
      y: 48,
      z: 96,
    },
    fixedShotHeroDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    fixedShotHeroDesktopFov: 45,
    fixedShotHeroMobilePosition: {
      x: 64,
      y: 48,
      z: 96,
    },
    fixedShotHeroMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    fixedShotHeroMobileFov: 45,
    orbitAutoRotate: true,
    orbitAutoRotateSpeed: 16,
    orbitDesktopPosition: {
      x: 64,
      y: 48,
      z: 96,
    },
    orbitDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitDesktopPivot: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitDesktopFov: 45,
    orbitMobilePosition: {
      x: 80,
      y: 60,
      z: 120,
    },
    orbitMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitMobilePivot: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitMobileFov: 55,
    splineDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineDesktopFov: 45,
    splineMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineMobileFov: 45,
    splineOrientationMode: 'target',
    splineForwardDistance: 1,
    splinePosition: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineScale: {
      x: 1,
      y: 1,
      z: 1,
    },
    splineDuration: 30,
    splineTension: 0.5,
    splineClosed: true,
    splineShowPath: false,
    operatorMoveSpeed: 6,
    operatorLiftSpeed: 6,
    operatorBoostMultiplier: 2,
    operatorPointerLookSensitivity: 0.003,
    operatorStickLookSpeed: 2.5,
    operatorZoomSpeed: 24,
    operatorMinFov: 20,
    operatorMaxFov: 80,
    level: 7,
    seed: 443518,
    baseFill: 'split',
    ruleMode: 'random',
    density: 0.34,
    beta: 0.56,
    magnetism: 0.1,
    flipChance: 0.02,
    removeStrays: true,
    cellSpacing: 0.6,
    cellScale: 0.6,
    growthEnabled: false,
    growthDurationSeconds: 1,
    growthJitter: 1,
    colorMode: 'state',
    paletteStart: '#ffffff',
    paletteMid: '#ff0000',
    paletteEnd: '#000000',
    paletteMidpoint: 0.21999999999999997,
    lightAzimuth: 194.46,
    lightElevation: 20.730000000000004,
    keyLightIntensity: 2.41,
    ambientIntensity: 0.3,
    rimLightIntensity: 0.49,
    bounceLightIntensity: 0.07,
    shadowIntensity: 1.08,
    shadowSoftness: 2.6,
    exposure: 0.7,
    godraysEnabled: false,
    godraysColor: '#ffffff',
    godraysIntensity: 20,
    godraysBlendColor: '#ffffff',
    godraysVolumeSize: 80,
    godraysDensity: 0.7,
    godraysMaxDensity: 0.5,
    godraysDistanceAttenuation: 2,
    godraysRaymarchSteps: 60,
    godraysBlur: false,
    godraysEdgeRadius: 2,
    godraysEdgeStrength: 2,
  },
  Undergrowth: {
    cameraMode: 'orbit',
    cameraAutoFit: true,
    fixedBehavior: 'single',
    fixedShotHeroDesktopPosition: {
      x: 64,
      y: 48,
      z: 96,
    },
    fixedShotHeroDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    fixedShotHeroDesktopFov: 45,
    fixedShotHeroMobilePosition: {
      x: 64,
      y: 48,
      z: 96,
    },
    fixedShotHeroMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    fixedShotHeroMobileFov: 45,
    orbitAutoRotate: true,
    orbitAutoRotateSpeed: 16,
    orbitDesktopPosition: {
      x: 64,
      y: 48,
      z: 96,
    },
    orbitDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitDesktopPivot: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitDesktopFov: 45,
    orbitMobilePosition: {
      x: 80,
      y: 60,
      z: 120,
    },
    orbitMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitMobilePivot: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitMobileFov: 55,
    splineDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineDesktopFov: 45,
    splineMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineMobileFov: 45,
    splineOrientationMode: 'target',
    splineForwardDistance: 1,
    splinePosition: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineScale: {
      x: 1,
      y: 1,
      z: 1,
    },
    splineDuration: 30,
    splineTension: 0.5,
    splineClosed: true,
    splineShowPath: false,
    operatorMoveSpeed: 6,
    operatorLiftSpeed: 6,
    operatorBoostMultiplier: 2,
    operatorPointerLookSensitivity: 0.003,
    operatorStickLookSpeed: 2.5,
    operatorZoomSpeed: 24,
    operatorMinFov: 20,
    operatorMaxFov: 80,
    level: 7,
    seed: 413646,
    baseFill: 'random',
    ruleMode: 'random',
    density: 0.34,
    beta: 0.56,
    magnetism: 0.1,
    flipChance: 0.02,
    removeStrays: true,
    cellSpacing: 0.6,
    cellScale: 0.6,
    growthEnabled: false,
    growthDurationSeconds: 1,
    growthJitter: 1,
    colorMode: 'state',
    paletteStart: '#ffffff',
    paletteMid: '#ff0000',
    paletteEnd: '#000000',
    paletteMidpoint: 0.21999999999999997,
    lightAzimuth: 194.46,
    lightElevation: 20.730000000000004,
    keyLightIntensity: 2.41,
    ambientIntensity: 0.3,
    rimLightIntensity: 0.49,
    bounceLightIntensity: 0.07,
    shadowIntensity: 1.08,
    shadowSoftness: 2.6,
    exposure: 0.7,
    godraysEnabled: false,
    godraysColor: '#ffffff',
    godraysIntensity: 20,
    godraysBlendColor: '#ffffff',
    godraysVolumeSize: 80,
    godraysDensity: 0.7,
    godraysMaxDensity: 0.5,
    godraysDistanceAttenuation: 2,
    godraysRaymarchSteps: 60,
    godraysBlur: false,
    godraysEdgeRadius: 2,
    godraysEdgeStrength: 2,
  },
  Antennae: {
    cameraMode: 'orbit',
    cameraAutoFit: true,
    fixedBehavior: 'single',
    fixedShotHeroDesktopPosition: {
      x: 64,
      y: 48,
      z: 96,
    },
    fixedShotHeroDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    fixedShotHeroDesktopFov: 45,
    fixedShotHeroMobilePosition: {
      x: 64,
      y: 48,
      z: 96,
    },
    fixedShotHeroMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    fixedShotHeroMobileFov: 45,
    orbitAutoRotate: true,
    orbitAutoRotateSpeed: 16,
    orbitDesktopPosition: {
      x: 64,
      y: 48,
      z: 96,
    },
    orbitDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitDesktopPivot: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitDesktopFov: 45,
    orbitMobilePosition: {
      x: 80,
      y: 60,
      z: 120,
    },
    orbitMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitMobilePivot: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitMobileFov: 55,
    splineDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineDesktopFov: 45,
    splineMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineMobileFov: 45,
    splineOrientationMode: 'target',
    splineForwardDistance: 1,
    splinePosition: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineScale: {
      x: 1,
      y: 1,
      z: 1,
    },
    splineDuration: 30,
    splineTension: 0.5,
    splineClosed: true,
    splineShowPath: false,
    operatorMoveSpeed: 6,
    operatorLiftSpeed: 6,
    operatorBoostMultiplier: 2,
    operatorPointerLookSensitivity: 0.003,
    operatorStickLookSpeed: 2.5,
    operatorZoomSpeed: 24,
    operatorMinFov: 20,
    operatorMaxFov: 80,
    level: 7,
    seed: 71607,
    baseFill: 'random',
    ruleMode: 'random',
    density: 0.34,
    beta: 0.56,
    magnetism: 0.1,
    flipChance: 0.02,
    removeStrays: true,
    cellSpacing: 0.6,
    cellScale: 0.6,
    growthEnabled: false,
    growthDurationSeconds: 1,
    growthJitter: 1,
    colorMode: 'state',
    paletteStart: '#ffffff',
    paletteMid: '#ff0000',
    paletteEnd: '#000000',
    paletteMidpoint: 0.21999999999999997,
    lightAzimuth: 194.46,
    lightElevation: 20.730000000000004,
    keyLightIntensity: 2.41,
    ambientIntensity: 0.3,
    rimLightIntensity: 0.49,
    bounceLightIntensity: 0.07,
    shadowIntensity: 1.08,
    shadowSoftness: 2.6,
    exposure: 0.7,
    godraysEnabled: false,
    godraysColor: '#ffffff',
    godraysIntensity: 20,
    godraysBlendColor: '#ffffff',
    godraysVolumeSize: 80,
    godraysDensity: 0.7,
    godraysMaxDensity: 0.5,
    godraysDistanceAttenuation: 2,
    godraysRaymarchSteps: 60,
    godraysBlur: false,
    godraysEdgeRadius: 2,
    godraysEdgeStrength: 2,
  },
  Ascent: {
    cameraMode: 'orbit',
    cameraAutoFit: true,
    fixedBehavior: 'single',
    fixedShotHeroDesktopPosition: {
      x: 64,
      y: 48,
      z: 96,
    },
    fixedShotHeroDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    fixedShotHeroDesktopFov: 45,
    fixedShotHeroMobilePosition: {
      x: 64,
      y: 48,
      z: 96,
    },
    fixedShotHeroMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    fixedShotHeroMobileFov: 45,
    orbitAutoRotate: true,
    orbitAutoRotateSpeed: 16,
    orbitDesktopPosition: {
      x: 64,
      y: 48,
      z: 96,
    },
    orbitDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitDesktopPivot: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitDesktopFov: 45,
    orbitMobilePosition: {
      x: 80,
      y: 60,
      z: 120,
    },
    orbitMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitMobilePivot: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitMobileFov: 55,
    splineDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineDesktopFov: 45,
    splineMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineMobileFov: 45,
    splineOrientationMode: 'target',
    splineForwardDistance: 1,
    splinePosition: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineScale: {
      x: 1,
      y: 1,
      z: 1,
    },
    splineDuration: 30,
    splineTension: 0.5,
    splineClosed: true,
    splineShowPath: false,
    operatorMoveSpeed: 6,
    operatorLiftSpeed: 6,
    operatorBoostMultiplier: 2,
    operatorPointerLookSensitivity: 0.003,
    operatorStickLookSpeed: 2.5,
    operatorZoomSpeed: 24,
    operatorMinFov: 20,
    operatorMaxFov: 80,
    level: 7,
    seed: 354538,
    baseFill: 'random',
    ruleMode: 'random',
    density: 0.34,
    beta: 0.56,
    magnetism: 0.1,
    flipChance: 0.02,
    removeStrays: true,
    cellSpacing: 0.6,
    cellScale: 0.6,
    growthEnabled: false,
    growthDurationSeconds: 1,
    growthJitter: 1,
    colorMode: 'state',
    paletteStart: '#ffffff',
    paletteMid: '#ff0000',
    paletteEnd: '#000000',
    paletteMidpoint: 0.21999999999999997,
    lightAzimuth: 194.46,
    lightElevation: 20.730000000000004,
    keyLightIntensity: 2.41,
    ambientIntensity: 0.3,
    rimLightIntensity: 0.49,
    bounceLightIntensity: 0.07,
    shadowIntensity: 1.08,
    shadowSoftness: 2.6,
    exposure: 0.7,
    backgroundColor: '#484848',
    godraysEnabled: false,
    godraysColor: '#ffffff',
    godraysPosition: {
      x: 0,
      y: 0,
      z: 0,
    },
    godraysIntensity: 20,
    godraysBlendColor: '#ffffff',
    godraysVolumeSize: 80,
    godraysDensity: 0.7,
    godraysMaxDensity: 0.5,
    godraysDistanceAttenuation: 2,
    godraysRaymarchSteps: 60,
    godraysBlur: false,
    godraysEdgeRadius: 2,
    godraysEdgeStrength: 2,
  },
  Cumulus: {
    cameraMode: 'orbit',
    cameraAutoFit: true,
    fixedBehavior: 'single',
    fixedShotHeroDesktopPosition: {
      x: 64,
      y: 48,
      z: 96,
    },
    fixedShotHeroDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    fixedShotHeroDesktopFov: 45,
    fixedShotHeroMobilePosition: {
      x: 64,
      y: 48,
      z: 96,
    },
    fixedShotHeroMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    fixedShotHeroMobileFov: 45,
    orbitAutoRotate: true,
    orbitAutoRotateSpeed: 16,
    orbitDesktopPosition: {
      x: 64,
      y: 48,
      z: 96,
    },
    orbitDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitDesktopPivot: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitDesktopFov: 45,
    orbitMobilePosition: {
      x: 80,
      y: 60,
      z: 120,
    },
    orbitMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitMobilePivot: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitMobileFov: 55,
    splineDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineDesktopFov: 45,
    splineMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineMobileFov: 45,
    splineOrientationMode: 'target',
    splineForwardDistance: 1,
    splinePosition: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineScale: {
      x: 1,
      y: 1,
      z: 1,
    },
    splineDuration: 30,
    splineTension: 0.5,
    splineClosed: true,
    splineShowPath: false,
    operatorMoveSpeed: 6,
    operatorLiftSpeed: 6,
    operatorBoostMultiplier: 2,
    operatorPointerLookSensitivity: 0.003,
    operatorStickLookSpeed: 2.5,
    operatorZoomSpeed: 24,
    operatorMinFov: 20,
    operatorMaxFov: 80,
    level: 7,
    seed: 419103,
    baseFill: 'random',
    ruleMode: 'random',
    density: 0.34,
    beta: 0.56,
    magnetism: 0.1,
    flipChance: 0.02,
    removeStrays: true,
    cellSpacing: 0.6,
    cellScale: 0.6,
    growthEnabled: false,
    growthDurationSeconds: 1,
    growthJitter: 1,
    colorMode: 'state',
    paletteStart: '#ffffff',
    paletteMid: '#ff0000',
    paletteEnd: '#000000',
    paletteMidpoint: 0.21999999999999997,
    lightAzimuth: 194.46,
    lightElevation: 20.730000000000004,
    keyLightIntensity: 2.41,
    ambientIntensity: 0.3,
    rimLightIntensity: 0.49,
    bounceLightIntensity: 0.07,
    shadowIntensity: 1.08,
    shadowSoftness: 2.6,
    exposure: 0.7,
    backgroundColor: '#484848',
    godraysEnabled: false,
    godraysColor: '#ffffff',
    godraysPosition: {
      x: 0,
      y: 0,
      z: 0,
    },
    godraysIntensity: 20,
    godraysBlendColor: '#ffffff',
    godraysVolumeSize: 80,
    godraysDensity: 0.7,
    godraysMaxDensity: 0.5,
    godraysDistanceAttenuation: 2,
    godraysRaymarchSteps: 60,
    godraysBlur: false,
    godraysEdgeRadius: 2,
    godraysEdgeStrength: 2,
  },
  // Phase 2: the standalone "keeps going, cells living and dying" preset
  // (utils/continuousCompute.js) — a classic 3D neighbor-counting Life-style
  // sim, seeded from one hierarchical resolve then evolving on its own from
  // there. `level` is deliberately lower than Default: continuous mode can't
  // use the one-time compaction trick (occupancy keeps changing every step),
  // so it always renders the full k^3 grid rather than only ever-occupied
  // cells — level 7's 2.1M instances would be a full-grid draw every tick,
  // not just a one-time cost.
  'Continuous CA': {
    cameraMode: 'orbit',
    cameraAutoFit: true,
    fixedBehavior: 'single',
    fixedShotHeroDesktopPosition: { x: 64, y: 48, z: 96 },
    fixedShotHeroDesktopTarget: { x: 0, y: 0, z: 0 },
    fixedShotHeroDesktopFov: 45,
    fixedShotHeroMobilePosition: { x: 64, y: 48, z: 96 },
    fixedShotHeroMobileTarget: { x: 0, y: 0, z: 0 },
    fixedShotHeroMobileFov: 45,
    orbitAutoRotate: true,
    orbitAutoRotateSpeed: 4,
    orbitDesktopPosition: { x: 64, y: 48, z: 96 },
    orbitDesktopTarget: { x: 0, y: 0, z: 0 },
    orbitDesktopPivot: { x: 0, y: 0, z: 0 },
    orbitDesktopFov: 45,
    orbitMobilePosition: { x: 80, y: 60, z: 120 },
    orbitMobileTarget: { x: 0, y: 0, z: 0 },
    orbitMobilePivot: { x: 0, y: 0, z: 0 },
    orbitMobileFov: 55,
    splineDesktopTarget: { x: 0, y: 0, z: 0 },
    splineDesktopFov: 45,
    splineMobileTarget: { x: 0, y: 0, z: 0 },
    splineMobileFov: 45,
    splineOrientationMode: 'target',
    splineForwardDistance: 1,
    splinePosition: { x: 0, y: 0, z: 0 },
    splineScale: { x: 1, y: 1, z: 1 },
    splineDuration: 30,
    splineTension: 0.5,
    splineClosed: true,
    splineShowPath: false,
    operatorMoveSpeed: 6,
    operatorLiftSpeed: 6,
    operatorBoostMultiplier: 2,
    operatorPointerLookSensitivity: 0.003,
    operatorStickLookSpeed: 2.5,
    operatorZoomSpeed: 24,
    operatorMinFov: 20,
    operatorMaxFov: 80,
    level: 5,
    seed: 424242,
    baseFill: 'random',
    ruleMode: 'random',
    density: 0.34,
    beta: 0.56,
    magnetism: 0.1,
    flipChance: 0.02,
    removeStrays: true,
    cellSpacing: 0.6,
    cellScale: 0.6,
    growthEnabled: false,
    growthDurationSeconds: 3,
    growthJitter: 0.8,
    continuousEnabled: true,
    continuousStepsPerSecond: 6,
    continuousSurviveMin: 3,
    continuousSurviveMax: 10,
    continuousBirthMin: 6,
    continuousBirthMax: 8,
    colorMode: 'state',
    paletteStart: '#ff0000',
    paletteMid: '#ffffff',
    paletteEnd: '#7c7c7c',
    paletteMidpoint: 0.5,
    lightAzimuth: 25.65,
    lightElevation: 68.7,
    keyLightIntensity: 2.41,
    ambientIntensity: 0.3,
    rimLightIntensity: 0.49,
    bounceLightIntensity: 0.07,
    shadowIntensity: 1.08,
    shadowSoftness: 2.6,
    exposure: 0.7,
    backgroundColor: '#03040a',
    godraysEnabled: false,
    godraysColor: '#ffd27a',
    godraysPosition: { x: 0, y: 0, z: 0 },
    godraysIntensity: 20,
    godraysBlendColor: '#ffd27a',
    godraysVolumeSize: 80,
    godraysDensity: 0.7,
    godraysMaxDensity: 0.5,
    godraysDistanceAttenuation: 2,
    godraysRaymarchSteps: 60,
    godraysBlur: false,
    godraysEdgeRadius: 2,
    godraysEdgeStrength: 2,
  },
  Osiris: {
    cameraMode: 'orbit',
    cameraAutoFit: true,
    fixedBehavior: 'single',
    fixedShotHeroDesktopPosition: {
      x: 64,
      y: 48,
      z: 96,
    },
    fixedShotHeroDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    fixedShotHeroDesktopFov: 45,
    fixedShotHeroMobilePosition: {
      x: 64,
      y: 48,
      z: 96,
    },
    fixedShotHeroMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    fixedShotHeroMobileFov: 45,
    orbitAutoRotate: true,
    orbitAutoRotateSpeed: 16,
    orbitDesktopPosition: {
      x: 64,
      y: 48,
      z: 96,
    },
    orbitDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitDesktopPivot: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitDesktopFov: 45,
    orbitMobilePosition: {
      x: 80,
      y: 60,
      z: 120,
    },
    orbitMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitMobilePivot: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitMobileFov: 55,
    splineDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineDesktopFov: 45,
    splineMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineMobileFov: 45,
    splineOrientationMode: 'target',
    splineForwardDistance: 1,
    splinePosition: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineScale: {
      x: 1,
      y: 1,
      z: 1,
    },
    splineDuration: 30,
    splineTension: 0.5,
    splineClosed: true,
    splineShowPath: false,
    operatorMoveSpeed: 6,
    operatorLiftSpeed: 6,
    operatorBoostMultiplier: 2,
    operatorPointerLookSensitivity: 0.003,
    operatorStickLookSpeed: 2.5,
    operatorZoomSpeed: 24,
    operatorMinFov: 20,
    operatorMaxFov: 80,
    level: 7,
    seed: 99945,
    baseFill: 'random',
    ruleMode: 'random',
    density: 0.34,
    beta: 0.56,
    magnetism: 0.1,
    flipChance: 0.02,
    removeStrays: true,
    cellSpacing: 0.6,
    cellScale: 0.6,
    growthEnabled: false,
    growthDurationSeconds: 1,
    growthJitter: 1,
    colorMode: 'state',
    paletteStart: '#ffffff',
    paletteMid: '#ff0000',
    paletteEnd: '#000000',
    paletteMidpoint: 0.21999999999999997,
    lightAzimuth: 194.46,
    lightElevation: 20.730000000000004,
    keyLightIntensity: 2.41,
    ambientIntensity: 0.3,
    rimLightIntensity: 0.49,
    bounceLightIntensity: 0.07,
    shadowIntensity: 1.08,
    shadowSoftness: 2.6,
    exposure: 0.7,
    backgroundColor: '#03040a',
    godraysEnabled: true,
    godraysColor: '#ffffff',
    godraysPosition: {
      x: 0,
      y: 0,
      z: 0,
    },
    godraysIntensity: 20,
    godraysBlendColor: '#ffffff',
    godraysVolumeSize: 80,
    godraysDensity: 0.7,
    godraysMaxDensity: 0.5,
    godraysDistanceAttenuation: 2,
    godraysRaymarchSteps: 60,
    godraysBlur: false,
    godraysEdgeRadius: 2,
    godraysEdgeStrength: 2,
    continuousEnabled: false,
    continuousStepsPerSecond: 6,
    continuousSurviveMin: 3,
    continuousSurviveMax: 10,
    continuousBirthMin: 6,
    continuousBirthMax: 8,
  },
  Hypercube: {
    cameraMode: 'orbit',
    cameraAutoFit: true,
    fixedBehavior: 'single',
    fixedShotHeroDesktopPosition: {
      x: 64,
      y: 48,
      z: 96,
    },
    fixedShotHeroDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    fixedShotHeroDesktopFov: 45,
    fixedShotHeroMobilePosition: {
      x: 64,
      y: 48,
      z: 96,
    },
    fixedShotHeroMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    fixedShotHeroMobileFov: 45,
    orbitAutoRotate: true,
    orbitAutoRotateSpeed: 16,
    orbitDesktopPosition: {
      x: 64,
      y: 48,
      z: 96,
    },
    orbitDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitDesktopPivot: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitDesktopFov: 45,
    orbitMobilePosition: {
      x: 80,
      y: 60,
      z: 120,
    },
    orbitMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitMobilePivot: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitMobileFov: 55,
    splineDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineDesktopFov: 45,
    splineMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineMobileFov: 45,
    splineOrientationMode: 'target',
    splineForwardDistance: 1,
    splinePosition: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineScale: {
      x: 1,
      y: 1,
      z: 1,
    },
    splineDuration: 30,
    splineTension: 0.5,
    splineClosed: true,
    splineShowPath: false,
    operatorMoveSpeed: 6,
    operatorLiftSpeed: 6,
    operatorBoostMultiplier: 2,
    operatorPointerLookSensitivity: 0.003,
    operatorStickLookSpeed: 2.5,
    operatorZoomSpeed: 24,
    operatorMinFov: 20,
    operatorMaxFov: 80,
    level: 7,
    seed: 113718,
    baseFill: 'random',
    ruleMode: 'random',
    density: 0.34,
    beta: 0.56,
    magnetism: 0.1,
    flipChance: 0.02,
    removeStrays: true,
    cellSpacing: 0.6,
    cellScale: 0.6,
    growthEnabled: false,
    growthDurationSeconds: 1,
    growthJitter: 1,
    colorMode: 'state',
    paletteStart: '#ffffff',
    paletteMid: '#ff0000',
    paletteEnd: '#000000',
    paletteMidpoint: 0.21999999999999997,
    lightAzimuth: 194.46,
    lightElevation: 20.730000000000004,
    keyLightIntensity: 2.41,
    ambientIntensity: 0.3,
    rimLightIntensity: 0.49,
    bounceLightIntensity: 0.07,
    shadowIntensity: 1.08,
    shadowSoftness: 2.6,
    exposure: 0.7,
    backgroundColor: '#03040a',
    godraysEnabled: true,
    godraysColor: '#ffffff',
    godraysPosition: {
      x: 0,
      y: 0,
      z: 0,
    },
    godraysIntensity: 20,
    godraysBlendColor: '#ffffff',
    godraysVolumeSize: 80,
    godraysDensity: 0.7,
    godraysMaxDensity: 0.5,
    godraysDistanceAttenuation: 2,
    godraysRaymarchSteps: 60,
    godraysBlur: false,
    godraysEdgeRadius: 2,
    godraysEdgeStrength: 2,
    continuousEnabled: false,
    continuousStepsPerSecond: 6,
    continuousSurviveMin: 3,
    continuousSurviveMax: 10,
    continuousBirthMin: 6,
    continuousBirthMax: 8,
  },
  'Hollow Rot': {
    cameraMode: 'orbit',
    cameraAutoFit: true,
    fixedBehavior: 'single',
    fixedShotHeroDesktopPosition: {
      x: 64,
      y: 48,
      z: 96,
    },
    fixedShotHeroDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    fixedShotHeroDesktopFov: 45,
    fixedShotHeroMobilePosition: {
      x: 64,
      y: 48,
      z: 96,
    },
    fixedShotHeroMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    fixedShotHeroMobileFov: 45,
    orbitAutoRotate: true,
    orbitAutoRotateSpeed: 16,
    orbitDesktopPosition: {
      x: 64,
      y: 48,
      z: 96,
    },
    orbitDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitDesktopPivot: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitDesktopFov: 45,
    orbitMobilePosition: {
      x: 80,
      y: 60,
      z: 120,
    },
    orbitMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitMobilePivot: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitMobileFov: 55,
    splineDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineDesktopFov: 45,
    splineMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineMobileFov: 45,
    splineOrientationMode: 'target',
    splineForwardDistance: 1,
    splinePosition: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineScale: {
      x: 1,
      y: 1,
      z: 1,
    },
    splineDuration: 30,
    splineTension: 0.5,
    splineClosed: true,
    splineShowPath: false,
    operatorMoveSpeed: 6,
    operatorLiftSpeed: 6,
    operatorBoostMultiplier: 2,
    operatorPointerLookSensitivity: 0.003,
    operatorStickLookSpeed: 2.5,
    operatorZoomSpeed: 24,
    operatorMinFov: 20,
    operatorMaxFov: 80,
    level: 7,
    seed: 749781,
    baseFill: 'random',
    ruleMode: 'random',
    density: 0.34,
    beta: 0.56,
    magnetism: 0.1,
    flipChance: 0.02,
    removeStrays: true,
    cellSpacing: 0.6,
    cellScale: 0.6,
    growthEnabled: false,
    growthDurationSeconds: 1,
    growthJitter: 1,
    colorMode: 'state',
    paletteStart: '#ffffff',
    paletteMid: '#ff0000',
    paletteEnd: '#000000',
    paletteMidpoint: 0.21999999999999997,
    lightAzimuth: 194.46,
    lightElevation: 20.730000000000004,
    keyLightIntensity: 2.41,
    ambientIntensity: 0.3,
    rimLightIntensity: 0.49,
    bounceLightIntensity: 0.07,
    shadowIntensity: 1.08,
    shadowSoftness: 2.6,
    exposure: 0.7,
    backgroundColor: '#03040a',
    godraysEnabled: true,
    godraysColor: '#ffffff',
    godraysPosition: {
      x: 0,
      y: 0,
      z: 0,
    },
    godraysIntensity: 20,
    godraysBlendColor: '#ffffff',
    godraysVolumeSize: 80,
    godraysDensity: 0.7,
    godraysMaxDensity: 0.5,
    godraysDistanceAttenuation: 2,
    godraysRaymarchSteps: 60,
    godraysBlur: false,
    godraysEdgeRadius: 2,
    godraysEdgeStrength: 2,
    continuousEnabled: false,
    continuousStepsPerSecond: 6,
    continuousSurviveMin: 3,
    continuousSurviveMax: 10,
    continuousBirthMin: 6,
    continuousBirthMax: 8,
  },
};

// Companion fn to usePresetsFolder. Given the snapshot for the preset being
// applied, return the control values to set. Override this when a preset
// needs to derive values rather than apply the snapshot verbatim.
export function getPresetControls({ presetSnapshot }) {
  return { ...presetSnapshot };
}
