const BASE_PRESET = {
  backgroundColor: '#140f24',
  ambientIntensity: 0.55,
  directionalIntensity: 1.35,
  rowSpacing: 2.8,
  columnSpacing: 2.4,
  glassColor: '#64b1ff',
  transmission: 1,
  thickness: 0.45,
  ior: 1.25,
  chromaticAberration: 0.045,
  explodeStrength: 0.3,
  pointerRadius: 0.45,
  falloff: 0.65,
  shakeAmount: 0.025,
  shakeSpeed: 18,
  returnSpeed: 10,
  motionBoost: 14,
  damping: 6,
  color: '#ffffff',
  roughness: 0.35,
  metalness: 0.15,
  materialType: 'Standard',
  shininess: 30,
  specular: '#111111',
  clearcoat: 0,
  clearcoatRoughness: 0,
  emissive: '#000000',
  emissiveIntensity: 0,
  sheen: 0,
  sheenRoughness: 1,
  sheenColor: '#ffffff',
  iridescence: 0,
  iridescenceIOR: 1.3,
  flatShading: false,
  wireframe: false,
};

const EXPLOSION_PRESETS = {
  Standard: {
    ...BASE_PRESET,
  },
  StandardWire: {
    ...BASE_PRESET,
    backgroundColor: '#0a0a0a',
    color: '#00ffaa',
    roughness: 0.5,
    metalness: 0.0,
    wireframe: true,
    glassColor: '#00ffaa',
    explodeStrength: 0.22,
    pointerRadius: 0.35,
    falloff: 0.9,
    shakeAmount: 0.015,
    shakeSpeed: 14,
    returnSpeed: 12,
    motionBoost: 10,
    damping: 8,
  },
  Physical: {
    ...BASE_PRESET,
    materialType: 'Physical',
    backgroundColor: '#0c0818',
    color: '#ffd1e8',
    roughness: 0.15,
    metalness: 0.6,
    clearcoat: 1,
    clearcoatRoughness: 0.05,
    sheen: 0.8,
    sheenRoughness: 0.3,
    sheenColor: '#ff88cc',
    iridescence: 0.9,
    iridescenceIOR: 1.8,
    emissive: '#220033',
    emissiveIntensity: 0.4,
    glassColor: '#c4a0ff',
    explodeStrength: 0.55,
    pointerRadius: 0.6,
    falloff: 0.5,
    shakeAmount: 0.04,
    shakeSpeed: 28,
    returnSpeed: 7,
    motionBoost: 22,
    damping: 4.5,
  },
  Phong: {
    ...BASE_PRESET,
    materialType: 'Phong',
    backgroundColor: '#0d1420',
    color: '#e0f0ff',
    shininess: 80,
    specular: '#4488ff',
    emissive: '#001133',
    emissiveIntensity: 0.3,
    glassColor: '#6699ff',
    explodeStrength: 0.38,
    pointerRadius: 0.5,
    falloff: 0.7,
    shakeAmount: 0.03,
    shakeSpeed: 22,
    returnSpeed: 9,
    motionBoost: 16,
    damping: 5.5,
  },
  Lambert: {
    ...BASE_PRESET,
    materialType: 'Lambert',
    backgroundColor: '#1a0f08',
    color: '#ffecd2',
    emissive: '#442200',
    emissiveIntensity: 0.5,
    glassColor: '#ffaa55',
    explodeStrength: 0.5,
    pointerRadius: 0.55,
    falloff: 0.55,
    shakeAmount: 0.045,
    shakeSpeed: 24,
    returnSpeed: 8,
    motionBoost: 20,
    damping: 5,
  },
  Toon: {
    ...BASE_PRESET,
    materialType: 'Toon',
    backgroundColor: '#1c0826',
    color: '#ff66aa',
    emissive: '#330044',
    emissiveIntensity: 0.6,
    glassColor: '#ff88cc',
    explodeStrength: 0.42,
    pointerRadius: 0.62,
    falloff: 0.45,
    shakeAmount: 0.05,
    shakeSpeed: 30,
    returnSpeed: 7,
    motionBoost: 24,
    damping: 4,
  },
  Basic: {
    ...BASE_PRESET,
    materialType: 'Basic',
    backgroundColor: '#000000',
    color: '#ff3333',
    glassColor: '#ff6666',
    ambientIntensity: 0,
    directionalIntensity: 0,
    explodeStrength: 0.18,
    pointerRadius: 0.32,
    falloff: 1.2,
    shakeAmount: 0.008,
    shakeSpeed: 10,
    returnSpeed: 16,
    motionBoost: 8,
    damping: 11,
  },
  Normal: {
    ...BASE_PRESET,
    materialType: 'Normal',
    backgroundColor: '#0a0a14',
    flatShading: true,
    glassColor: '#88aaff',
    explodeStrength: 0.34,
    pointerRadius: 0.44,
    falloff: 0.75,
    shakeAmount: 0.02,
    shakeSpeed: 19,
    returnSpeed: 11,
    motionBoost: 13,
    damping: 6.5,
  },
  Matcap: {
    ...BASE_PRESET,
    materialType: 'Matcap',
    backgroundColor: '#121212',
    color: '#ffcc44',
    flatShading: false,
    glassColor: '#ffdd88',
    explodeStrength: 0.26,
    pointerRadius: 0.4,
    falloff: 1.0,
    shakeAmount: 0.012,
    shakeSpeed: 12,
    returnSpeed: 14,
    motionBoost: 9,
    damping: 9,
  },
};
export default EXPLOSION_PRESETS;
