import { POOL_KEYS, sceneDefaults } from '@modules/kumiko';

const SCENE_DEFAULTS = sceneDefaults();

const only = (...keys) =>
  Object.fromEntries(POOL_KEYS.map((key) => [key, keys.includes(key)]));

export const DEFAULT_PRESET = 'Asanoha';

export const PRESETS = {
  Asanoha: {
    ...SCENE_DEFAULTS,
    seed: 'kumiko',
  },
  'Sakura Field': {
    ...SCENE_DEFAULTS,
    seed: 'sakura',
    ...only('useAsanoha', 'useSakura', 'useYaeZakura'),
    zoneMode: 'voronoi',
    zoneCount: 6,
    zoneMix: 0.08,
    palette: 'Kumiko Sakura',
    colorBy: 'zone',
  },
  'Kikko Rings': {
    ...SCENE_DEFAULTS,
    seed: 'kikko',
    ...only('useKikko', 'useShokko', 'useSixfold', 'useUroko'),
    zoneMode: 'rings',
    zoneCount: 5,
    symmetry: 'quad',
    palette: 'Kumiko Hinoki',
    colorBy: 'zone',
  },
  'Asanoha Mandala': {
    ...SCENE_DEFAULTS,
    seed: 'mandala',
    panelWidth: 900,
    panelHeight: 900,
    cellSize: 48,
    ...only(
      'useAsanoha',
      'useSakura',
      'useYaeZakura',
      'useKikko',
      'useSixfold'
    ),
    zoneMode: 'rings',
    zoneCount: 6,
    zoneMix: 0.35,
    symmetry: 'kaleido6',
    palette: 'Kumiko Sakura',
    colorBy: 'zone',
  },
  'Density Ramp': {
    ...SCENE_DEFAULTS,
    seed: 'ramp',
    tiling: 'triangle',
    gridRotation: 90,
    cellSize: 50,
    panelWidth: 900,
    panelHeight: 450,
    ...only(
      'useAsanoha',
      'useTsunoAsanoha',
      'useKikko',
      'useSixfold',
      'useUroko',
      'useMasu',
      'useSakura',
      'useYaeZakura',
      'usePinwheel',
      'useIzutsu',
      'useShokko',
      'usePlain'
    ),
    subdivide: 2,
    imageMode: 'halftone',
    sourceImage: 'textures/ramp.png',
    imageContrast: 1,
    colorTarget: 'none',
  },
  'Webcam Halftone': {
    ...SCENE_DEFAULTS,
    seed: 'mirror',
    panelWidth: 1600,
    panelHeight: 1200,
    borderWidth: 40,
    ...only(
      'useAsanoha',
      'useTsunoAsanoha',
      'useKikko',
      'useSixfold',
      'useUroko',
      'useMasu',
      'useSakura',
      'useYaeZakura',
      'usePinwheel',
      'useGoma',
      'useShokko',
      'usePlain'
    ),
    cellSize: 160,
    subdivide: 5,
    jigumiWidth: 7,
    infillWidth: 4.5,
    detailWidth: 3.5,
    levelThinning: 0.6,
    imageMode: 'halftone',
    varianceThreshold: 0.18,
    halftoneMinCell: 25,
    imageContrast: 1.3,
    halftoneDither: 0.06,
    webcam: true,
    colorTarget: 'openings',
    colorBy: 'image',
    palette: 'Kumiko Sumi',
    paletteExact: false,
    woodColor: '#2a221c',
    backlight: 1.6,
  },
  'Masu Grid': {
    ...SCENE_DEFAULTS,
    seed: 'masu',
    tiling: 'square',
    gridRotation: 0,
    cellSize: 80,
    ...only('useMasu', 'usePinwheel', 'useIzutsu', 'useUroko'),
    zoneMode: 'checker',
    zoneCount: 4,
    palette: 'Kumiko Aizome',
    colorBy: 'pattern',
  },
  'Ice Ray': {
    ...SCENE_DEFAULTS,
    seed: 'ice',
    tiling: 'square',
    gridRotation: 0,
    cellSize: 150,
    ...only('useIceRay'),
    iceCuts: 7,
    palette: 'Kumiko Aizome',
    colorBy: 'size',
    paletteExact: false,
  },
  'Nested Frames': {
    ...SCENE_DEFAULTS,
    seed: 'nest',
    ...only('useAsanoha', 'useSakura', 'useKikko', 'useTsunoAsanoha'),
    nestFrames: 2,
    nestStep: 0.14,
    zoneMode: 'columns',
    zoneCount: 1,
    colorBy: 'zone',
    palette: 'Kumiko Hinoki',
  },
  Multiscale: {
    ...SCENE_DEFAULTS,
    seed: 'multiscale',
    ...only('useAsanoha', 'useSakura', 'useUroko', 'usePlain'),
    cellSize: 150,
    subdivide: 3,
    splitChance: 0.6,
    splitFocus: 'center',
    childMix: 0.3,
    colorBy: 'level',
    palette: 'Kumiko Sumi',
  },
  Kagome: {
    ...SCENE_DEFAULTS,
    seed: 'kagome',
    tiling: 'kagome',
    cellSize: 48,
    ...only('useAsanoha', 'useSakura', 'useStar', 'useMasu'),
    zoneMode: 'radial',
    zoneCount: 6,
    symmetry: 'mirrorX',
    palette: 'Kumiko Sakura',
    colorBy: 'pattern',
  },
  'Snub Square': {
    ...SCENE_DEFAULTS,
    seed: 'snub',
    tiling: 'snubSquare',
    cellSize: 55,
    ...only('useAsanoha', 'useKikko', 'usePinwheel'),
    zoneMix: 0.4,
    colorBy: 'pattern',
    palette: 'Kumiko Aizome',
  },
  Everything: {
    ...SCENE_DEFAULTS,
    seed: 'everything',
    tiling: 'rhombitrihex',
    cellSize: 52,
    ...only(...POOL_KEYS),
    zoneMix: 1,
    colorBy: 'pattern',
    colorTarget: 'openings',
    palette: 'Kumiko Hinoki',
  },
  'Strip Build': {
    ...SCENE_DEFAULTS,
    seed: 'strips',
    ...only('useAsanoha', 'useSakura'),
    zoneMode: 'diagonal',
    zoneCount: 3,
    construction: 'strips',
    colorTarget: 'strips',
    colorBy: 'zone',
    palette: 'Kumiko Sakura',
    backlight: 0.6,
  },
};

export function getPresetControls({ currentControls, presetSnapshot }) {
  return Object.fromEntries(
    Object.entries(presetSnapshot).filter(([key]) => key in currentControls)
  );
}
