const DEFAULT_CLOTH = {
  width: 1.0,
  height: 0.7,
  segmentsX: 30,
  segmentsY: 21,
  pinMode: 'left',
  shapePreset: 'rectangle',
  wind: 1.0,
  windDirX: 1,
  windDirZ: 0,
  stiffness: 0.2,
  dampening: 0.99,
  gravity: 0.00005,
  stepsPerSecond: 360,
  maxVelocity: 0.01,
  alphaSeed: 42,
  alphaScale: 3,
  edgeFade: 0,
  holeAmount: 0,
  tatterEdge: 0,
  color: '#8866aa',
  roughness: 0.6,
  metalness: 0.0,
  opacity: 1,
  sphereX: 0.5,
  sphereY: -0.35,
  sphereZ: 0.1,
};

export default DEFAULT_CLOTH;
