const BASE_PRESET = {
  backgroundColor: '#140f24',
  ambientIntensity: 0.55,
  directionalIntensity: 1.35,
  rowSpacing: 2.8,
  columnSpacing: 2.4,
  glassColor: '#64b1ff',
  transmission: 1,
  thickness: 0.45,
  ior: 1.25,
  chromaticAberration: 0.045,
  explodeStrength: 0.3,
  pointerRadius: 0.45,
  falloff: 0.65,
  shakeAmount: 0.025,
  shakeSpeed: 18,
  returnSpeed: 10,
  motionBoost: 14,
  damping: 6,
  color: '#ffffff',
  roughness: 0.35,
  metalness: 0.15,
};

const EXPLOSION_PRESETS = {
  Default: {
    ...BASE_PRESET,
  },
  TightCore: {
    ...BASE_PRESET,
    glassColor: '#78beff',
    thickness: 0.5,
    chromaticAberration: 0.05,
    explodeStrength: 0.24,
    pointerRadius: 0.35,
    falloff: 0.9,
    shakeAmount: 0.018,
    shakeSpeed: 16,
    returnSpeed: 12,
    motionBoost: 10,
    damping: 8,
    roughness: 0.4,
    metalness: 0.08,
  },
  WideBurst: {
    ...BASE_PRESET,
    backgroundColor: '#101520',
    glassColor: '#88d1ff',
    thickness: 0.38,
    chromaticAberration: 0.035,
    explodeStrength: 0.42,
    pointerRadius: 0.58,
    falloff: 0.55,
    shakeAmount: 0.03,
    shakeSpeed: 20,
    returnSpeed: 9,
    motionBoost: 18,
    damping: 5.5,
    roughness: 0.3,
    metalness: 0.18,
  },
  LavaCore: {
    ...BASE_PRESET,
    backgroundColor: '#160a06',
    glassColor: '#ff7a3c',
    color: '#fff4df',
    transmission: 0.96,
    thickness: 0.56,
    chromaticAberration: 0.06,
    explodeStrength: 0.5,
    pointerRadius: 0.5,
    falloff: 0.6,
    shakeAmount: 0.045,
    shakeSpeed: 24,
    returnSpeed: 8,
    motionBoost: 20,
    damping: 5,
    roughness: 0.28,
    metalness: 0.1,
  },
  ArcticBloom: {
    ...BASE_PRESET,
    backgroundColor: '#dce9ff',
    glassColor: '#9de9ff',
    color: '#f8fbff',
    transmission: 1,
    thickness: 0.35,
    chromaticAberration: 0.02,
    explodeStrength: 0.22,
    pointerRadius: 0.38,
    falloff: 1.1,
    shakeAmount: 0.012,
    shakeSpeed: 12,
    returnSpeed: 14,
    motionBoost: 9,
    damping: 10,
    roughness: 0.55,
    metalness: 0.04,
  },
  NeonPunch: {
    ...BASE_PRESET,
    backgroundColor: '#050a24',
    glassColor: '#37ffd5',
    color: '#ff4fd1',
    thickness: 0.42,
    chromaticAberration: 0.09,
    explodeStrength: 0.55,
    pointerRadius: 0.62,
    falloff: 0.5,
    shakeAmount: 0.05,
    shakeSpeed: 30,
    returnSpeed: 7,
    motionBoost: 24,
    damping: 4.5,
    roughness: 0.22,
    metalness: 0.32,
  },
  ToxicMist: {
    ...BASE_PRESET,
    backgroundColor: '#0a1c11',
    glassColor: '#92ff7d',
    color: '#ecffe6',
    transmission: 0.98,
    thickness: 0.48,
    chromaticAberration: 0.04,
    explodeStrength: 0.36,
    pointerRadius: 0.52,
    falloff: 0.75,
    shakeAmount: 0.03,
    shakeSpeed: 22,
    returnSpeed: 9.5,
    motionBoost: 16,
    damping: 6.8,
    roughness: 0.34,
    metalness: 0.09,
  },
  RoyalPulse: {
    ...BASE_PRESET,
    backgroundColor: '#0f0b1f',
    glassColor: '#7d7bff',
    color: '#efe7ff',
    thickness: 0.46,
    chromaticAberration: 0.05,
    explodeStrength: 0.34,
    pointerRadius: 0.44,
    falloff: 0.7,
    shakeAmount: 0.026,
    shakeSpeed: 19,
    returnSpeed: 10.5,
    motionBoost: 13,
    damping: 6.2,
    roughness: 0.31,
    metalness: 0.2,
  },
  ShadowGlass: {
    ...BASE_PRESET,
    backgroundColor: '#020202',
    glassColor: '#8db3d9',
    color: '#d7d7d7',
    transmission: 0.93,
    thickness: 0.62,
    chromaticAberration: 0.03,
    explodeStrength: 0.18,
    pointerRadius: 0.32,
    falloff: 1.2,
    shakeAmount: 0.008,
    shakeSpeed: 10,
    returnSpeed: 16,
    motionBoost: 8,
    damping: 11,
    roughness: 0.65,
    metalness: 0.02,
  },
};
export default EXPLOSION_PRESETS;
