// Preset snapshots for the scene. Keys here must match the Leva schema built
// in useSceneControls 1:1 — no reshaping between a preset and the controls it
// applies (see docs/scene-conventions.md, "Controls & presets").
export const DEFAULT_PRESET = 'Default';

export const PRESETS = {
  Default: {
    // Background
    backgroundColor: '#202030',
    fogColor: '#202030',
    fogNear: 10,
    fogFar: 25,
    // Lighting
    ambientColor: '#ffffff',
    ambientIntensity: 0.35,
    keyColor: '#ffffff',
    keyIntensity: 1.1,
    keyPosition: { x: 2.5, y: 2, z: 4 },
    // Bloom
    bloomEnabled: true,
    bloomThreshold: 0.1,
    bloomStrength: 0.2,
    bloomRadius: 0.2,
    // Sparkles
    sparklesEnabled: true,
    sparkleCount: 100,
    sparkleSpeed: 0.71,
    sparkleOpactity: 0.7,
    sparkleColor: '#FFFFFF',
    sparkleSize: 0.7,
    sparkleScale: 3.6,
    // FractalPixelate
    fractalPixelateEnabled: false,
    fractalPixelateApplyToLogo: false,
    fractalPixelateCellSize: 12,
    fractalPixelateLevels: 3,
    fractalPixelateThreshold: 0.55,
    fractalPixelateNoiseScale: 1.5,
    fractalPixelateJitterAmount: 0.12,
    fractalPixelateOutlineWidth: 0.08,
    fractalPixelateOutlineStrength: 0.5,
    // Logo — Bret
    bretPosition: { x: 0, y: 0, z: 0 },
    bretRotation: { x: 0, y: 0, z: 0 },
    bretPressDepth: 0.012,
    bretInnerColor: '#FF0000',
    bretInnerColorEmissive: true,
    bretInnerColorEmissiveIntensity: 5,
    bretOuterColor: '#000000',
    bretOuterColorEmissive: false,
    bretOuterColorEmissiveIntensity: 0,
    // Logo — Reversal
    reversalPosition: { x: 0.9, y: -0.4, z: 0 },
    reversalRotation: { x: 0, y: 0, z: 0 },
    reversalPressDepth: 0.015,
    reversalInnerColor: '#FF0000',
    reversalInnerColorEmissive: true,
    reversalInnerColorEmissiveIntensity: 5,
    reversalOuterColor: '#000000',
    reversalOuterColorEmissive: false,
    reversalOuterColorEmissiveIntensity: 0,
    // Logo — Neon
    enableNeonFlicker: true,
    neonFlickerIntensity: 2,
    neonFlickerFrequency: 10,
    // Logo — Flip
    flip: true,
    flipDuration: 2,
    flipDelay: 4,
    // Logo — Float
    float: true,
    floatSpeed: 1,
    floatIntensity: 0.05,
    // Logo — Spin
    spin: true,
    spinRotation: 33,
    spinSpeed: 0.4,
    // Logo — Growth: differential-growth simulation on the inner meshes
    // (faithful port of ~/dev/examples/260308_DifferentialGrowth). Simulation
    // values mirror the reference defaults. The driver records growth into a
    // snapshot timeline then scrubs it, so the same sim can breathe subtly or
    // surge out of control and rewind. Off by default; see the Growth preset.
    growth: false,
    growthStep: 0.22,
    growthTargetEdge: 0.1,
    growthSplit: 1.35,
    growthRepulsion: 0.62,
    growthSmoothing: 1,
    growthRetention: 0.12,
    growthMaxVertices: 50000,
    growthSeed: 351107,
    growthSeedInfluence: 0.35,
    growthSpeed: 1,
    growthGradientBlur: 0.35,
    growthMode: 'breathe',
    growthReach: 40,
    growthTempo: 8,
    growthScrub: 0,
    growthPhase: 0,
    growthShadingMode: 'neon',
    growthGradientStart: '#9fd8ff',
    growthGradientEnd: '#ff0000',
    growthContrast: 1.4,
    growthBias: -0.4,
    growthFresnel: 0.05,
    growthSpecular: 0.6,
  },
  Growth: {
    // Identical to Default, with growth switched on in 'surge' mode so the
    // inner meshes grow out of control and rewind on a loop when selected.
    backgroundColor: '#202030',
    fogColor: '#202030',
    fogNear: 10,
    fogFar: 25,
    ambientColor: '#ffffff',
    ambientIntensity: 0.35,
    keyColor: '#ffffff',
    keyIntensity: 1.1,
    keyPosition: { x: 2.5, y: 2, z: 4 },
    bloomEnabled: true,
    bloomThreshold: 0.1,
    bloomStrength: 0.2,
    bloomRadius: 0.2,
    sparklesEnabled: true,
    sparkleCount: 100,
    sparkleSpeed: 0.71,
    sparkleOpactity: 0.7,
    sparkleColor: '#FFFFFF',
    sparkleSize: 0.7,
    sparkleScale: 3.6,
    fractalPixelateEnabled: false,
    fractalPixelateApplyToLogo: false,
    fractalPixelateCellSize: 12,
    fractalPixelateLevels: 3,
    fractalPixelateThreshold: 0.55,
    fractalPixelateNoiseScale: 1.5,
    fractalPixelateJitterAmount: 0.12,
    fractalPixelateOutlineWidth: 0.08,
    fractalPixelateOutlineStrength: 0.5,
    bretPosition: { x: 0, y: 0, z: 0 },
    bretRotation: { x: 0, y: 0, z: 0 },
    bretPressDepth: 0.012,
    bretInnerColor: '#FF0000',
    bretInnerColorEmissive: true,
    bretInnerColorEmissiveIntensity: 5,
    bretOuterColor: '#000000',
    bretOuterColorEmissive: false,
    bretOuterColorEmissiveIntensity: 0,
    reversalPosition: { x: 0.9, y: -0.4, z: 0 },
    reversalRotation: { x: 0, y: 0, z: 0 },
    reversalPressDepth: 0.015,
    reversalInnerColor: '#FF0000',
    reversalInnerColorEmissive: true,
    reversalInnerColorEmissiveIntensity: 5,
    reversalOuterColor: '#000000',
    reversalOuterColorEmissive: false,
    reversalOuterColorEmissiveIntensity: 0,
    enableNeonFlicker: true,
    neonFlickerIntensity: 2,
    neonFlickerFrequency: 10,
    flip: true,
    flipDuration: 2,
    flipDelay: 4,
    float: true,
    floatSpeed: 1,
    floatIntensity: 0.05,
    spin: true,
    spinRotation: 33,
    spinSpeed: 0.4,
    growth: true,
    growthStep: 0.22,
    growthTargetEdge: 0.1,
    growthSplit: 1.35,
    growthRepulsion: 0.62,
    growthSmoothing: 1,
    growthRetention: 0.12,
    growthMaxVertices: 50000,
    growthSeed: 351107,
    growthSeedInfluence: 0.35,
    growthSpeed: 1,
    growthGradientBlur: 0.35,
    growthMode: 'surge',
    growthReach: 90,
    growthTempo: 14,
    growthScrub: 0,
    growthPhase: 0,
    growthShadingMode: 'neon',
    growthGradientStart: '#9fd8ff',
    growthGradientEnd: '#ff0000',
    growthContrast: 1.4,
    growthBias: -0.4,
    growthFresnel: 0.05,
    growthSpecular: 0.6,
  },
  Mondrian: {
    cameraMode: 'orbit',
    cameraAutoFit: true,
    fixedBehavior: 'single',
    fixedShotMainDesktopPosition: {
      x: 0,
      y: 0,
      z: 5,
    },
    fixedShotMainDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    fixedShotMainDesktopFov: 50,
    fixedShotMainMobilePosition: {
      x: 0,
      y: 0,
      z: 6.5,
    },
    fixedShotMainMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    fixedShotMainMobileFov: 50,
    orbitAutoRotate: false,
    orbitAutoRotateSpeed: 2,
    orbitDesktopPosition: {
      x: 0,
      y: 0,
      z: 5,
    },
    orbitDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitDesktopPivot: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitDesktopFov: 50,
    orbitMobilePosition: {
      x: 0,
      y: 0,
      z: 5,
    },
    orbitMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitMobilePivot: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitMobileFov: 50,
    splineDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineDesktopFov: 50,
    splineMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineMobileFov: 50,
    splineOrientationMode: 'target',
    splineForwardDistance: 1,
    splinePosition: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineScale: {
      x: 1,
      y: 1,
      z: 1,
    },
    splineDuration: 30,
    splineTension: 0.5,
    splineClosed: true,
    splineShowPath: false,
    operatorMoveSpeed: 6,
    operatorLiftSpeed: 6,
    operatorBoostMultiplier: 2,
    operatorPointerLookSensitivity: 0.003,
    operatorStickLookSpeed: 2.5,
    operatorZoomSpeed: 24,
    operatorMinFov: 20,
    operatorMaxFov: 80,
    backgroundColor: '#b5b5b5',
    fogColor: '#202030',
    fogNear: 10,
    fogFar: 25,
    ambientColor: '#ffffff',
    ambientIntensity: 0.35,
    keyColor: '#ffffff',
    keyIntensity: 1.1,
    keyPosition: {
      x: 2.5,
      y: 2,
      z: 4,
    },
    bloomEnabled: false,
    bloomThreshold: 0.1,
    bloomStrength: 0.2,
    bloomRadius: 0.2,
    sparklesEnabled: false,
    sparkleCount: 100,
    sparkleSpeed: 0.71,
    sparkleOpactity: 0.7,
    sparkleColor: '#ffffff',
    sparkleSize: 0.7,
    sparkleScale: 3.6,
    fractalPixelateEnabled: true,
    fractalPixelateApplyToLogo: false,
    fractalPixelateCellSize: 64,
    fractalPixelateLevels: 4,
    fractalPixelateThreshold: 0.3400000000000001,
    fractalPixelateNoiseScale: 0.5,
    fractalPixelateJitterAmount: 0,
    fractalPixelateOutlineWidth: 0.03,
    fractalPixelateOutlineStrength: 1,
    bretPosition: {
      x: 0,
      y: 0,
      z: 0,
    },
    bretRotation: {
      x: 0,
      y: 0,
      z: 0,
    },
    bretPressDepth: 0.012,
    bretInnerColor: '#0023ff',
    bretInnerColorEmissive: false,
    bretInnerColorEmissiveIntensity: 0,
    bretOuterColor: '#000000',
    bretOuterColorEmissive: false,
    bretOuterColorEmissiveIntensity: 0,
    reversalPosition: {
      x: 0.9,
      y: -0.4,
      z: 0,
    },
    reversalRotation: {
      x: 0,
      y: 0,
      z: 0,
    },
    reversalPressDepth: 0.015,
    reversalInnerColor: '#0023ff',
    reversalInnerColorEmissive: false,
    reversalInnerColorEmissiveIntensity: 0,
    reversalOuterColor: '#000000',
    reversalOuterColorEmissive: false,
    reversalOuterColorEmissiveIntensity: 0,
    enableNeonFlicker: true,
    neonFlickerIntensity: 2,
    neonFlickerFrequency: 10,
    flip: true,
    flipDuration: 2,
    flipDelay: 4,
    float: true,
    floatSpeed: 1,
    floatIntensity: 0.05,
    spin: false,
    spinRotation: 33,
    spinSpeed: 0.4,
    growth: false,
    growthStep: 0.22,
    growthTargetEdge: 0.1,
    growthSplit: 1.35,
    growthRepulsion: 0.62,
    growthSmoothing: 1,
    growthRetention: 0.12,
    growthMaxVertices: 50000,
    growthSpeed: 1,
    growthSeed: 351107,
    growthSeedInfluence: 0.35,
    growthGradientBlur: 0.35,
    growthMode: 'breathe',
    growthReach: 40,
    growthTempo: 8,
    growthScrub: 0,
    growthPhase: 0,
    growthShadingMode: 'neon',
    growthGradientStart: '#9fd8ff',
    growthGradientEnd: '#ff0000',
    growthContrast: 1.4,
    growthBias: -0.4,
    growthFresnel: 0.05,
    growthSpecular: 0.6,
  },
};

// Companion fn to usePresetsFolder. Given the snapshot for the preset being
// applied, return the control values to set. Override this when a preset
// needs to derive values rather than apply the snapshot verbatim.
export function getPresetControls({ presetSnapshot }) {
  return { ...presetSnapshot };
}
