const PRESETS = {
  Default: {
    desktopCameraFov: 34,
    desktopCameraPosition: {
      x: 0,
      y: 2,
      z: 5.6,
    },
    desktopCameraTarget: {
      x: 0,
      y: 0.75,
      z: 0.4,
    },
    mobileCameraFov: 55,
    mobileCameraPosition: {
      x: 0,
      y: 2.1,
      z: 8.6,
    },
    mobileCameraTarget: {
      x: 0,
      y: 1.55,
      z: 0.35,
    },
    keyIntensity: 0.14,
    keyColor: '#efc29d',
    keyPosition: {
      x: -2.8,
      y: 3.4,
      z: 0.6,
    },
    keyTarget: {
      x: 0,
      y: 0.7,
      z: 0.35,
    },
    keyDebug: false,
    floorFillIntensity: 0.16,
    floorFillColor: '#a07755',
    floorFillPosition: {
      x: 1.7,
      y: 0.5,
      z: 4,
    },
    floorFillTarget: {
      x: 0,
      y: 0.1,
      z: 0.2,
    },
    floorFillDebug: false,
    rimEnabled: true,
    rimIntensity: 0.14,
    rimColor: '#cfdcff',
    rimPosition: {
      x: 2.6,
      y: 2,
      z: -2.2,
    },
    rimTarget: {
      x: 0,
      y: 0.85,
      z: 0.45,
    },
    rimDebug: false,
    spotIntensity: 0.12,
    spotColor: '#c99772',
    spotPosition: {
      x: 1.8,
      y: 2.2,
      z: 3.4,
    },
    spotTarget: {
      x: -0.1,
      y: 0.75,
      z: 0.55,
    },
    spotAngle: 18,
    spotPenumbra: 0.8,
    spotDecay: 2,
    spotDistance: 0,
    spotDebug: false,
    projectorColor: '#f7f3ec',
    projectorIntensity: 270,
    projectorPosition: {
      x: -3.1,
      y: 4,
      z: 3.6,
    },
    projectorTarget: {
      x: 0.15,
      y: 0.85,
      z: 0.35,
    },
    projectorAngle: 29,
    projectorPenumbra: 0.28,
    projectorDecay: 2,
    projectorDistance: 12,
    projectorFocus: 0.67,
    projectorRepeat: {
      x: 1.7,
      y: 1.7,
    },
    projectorTintColor: '#f4d5ad',
    projectorTintStrength: 0.22,
    projectorBlur: 1,
    projectorCausticAmount: 1,
    projectorCausticScale: 12.6,
    projectorCausticContrast: 0.16,
    projectorCausticSpeed: 0.2,
    projectorCastShadow: true,
    projectorDebug: false,
    bloomEnabled: true,
    bloomThreshold: 0.76,
    bloomStrength: 0.08,
    bloomRadius: 0.38,
    bloomDownSampleRatio: 2,
    projectorVolumeEnabled: true,
    projectorVolumeIntensity: 1.86,
    projectorVolumeDensity: 0.28,
    projectorVolumeNoiseSpeed: 1,
    projectorVolumeSteps: 14,
    projectorVolumeBlur: 0.88,
    projectorVolumeResolutionScale: 0.5,
    skullPosition: {
      x: 0,
      y: 0.7,
      z: 0.8,
    },
    skullRotation: {
      x: 0,
      y: 0,
      z: 0,
    },
    leftFemurPosition: {
      x: 0,
      y: 0.45,
      z: 0,
    },
    leftFemurRotation: {
      x: 98,
      y: 3,
      z: 35,
    },
    rightFemurPosition: {
      x: 0,
      y: 0.5,
      z: 0,
    },
    rightFemurRotation: {
      x: -98,
      y: -7,
      z: -142,
    },
  },
};

export default PRESETS;
