/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React from 'react';

import { useGLTF } from '@react-three/drei';

import { modelFile } from '@utils/appUtils';

export default function NewspaperStack(props) {
  const { nodes, materials } = useGLTF(modelFile('/newsPaperStack.glb'));
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_130.geometry}
        material={materials['sm36_010_Newspaper01A_A_Mat.001']}
        rotation={[Math.PI / 2, 0, -1.484]}
        scale={0.01}
      />
    </group>
  );
}

useGLTF.preload(modelFile('/newsPaperStack.glb'));
