export const DEFAULT_PRESET = 'Inspect';

const BASE = {
  cameraMode: 'orbit',
  asset: 'Stair Segment',
  kit: 'Staircase',
  corridorAsset: 'Corridor Segment',
  connection: 'Threshold to Corridor',
  showGrid: true,
  wallMode: 'Solid',
  variation: 'landing only + no flare',
  stoneColor: '#b9b6b0',
  textureScale: 0.12,
  textureBlend: 4,
  normalStrength: 0.85,
  backgroundColor: '#141619',
  voidRadius: 24,
  stairWidth: 6,
  landingOvershoot: 0,
  riser: 0.176,
  stepsPerTurn: 512,
  stepCount: 48,
  landingArc: 0.09,
  landingThickness: 1.2,
  wallArc: 0.55,
  wallHeight: 26,
  flights: 18,
  mouthWidth: 4.5,
  mouthHeight: 7,
  tunnelLength: 70,
  tunnelLengthEndRoom: 22,
  roomSide: 'End',
  roomAlong: 0.22,
  hallwayCapEnd: false,
  roomDepth: 9,
  roomWidth: 10,
  roomHeight: 8,
  // A shadow-casting point light is a cube map. More than a couple of them
  // exceeds WebGPU's bind group limits and invalidates the render pipeline,
  // which renders every node material black.
  flareShadows: false,
  flareShadowCount: 2,
  flareColor: '#ff3a1e',
  flareIntensity: 40,
  flareRange: 12,
  flareLength: 0.34,
  flareRadius: 0.035,
  flareGlow: 3,
  motionSpeed: 1,
  spinLock: 1,
  motionSlots: 34,
  variance: 0.35,
  fogEnabled: true,
  fogColor: '#141619',
  fogNear: 12,
  fogFar: 90,

  segmentLength: 24,
  corridorWidth: 5,
  corridorHeight: 8,
  archRatio: 0.3,
  corridorSegments: 20,
  corridorCount: 14,
  driftAmount: 0.35,
  driftWavelength: 140,
  stepAmount: 0,
  stepRunLength: 6,
  revealDepth: 0.4,
  bulkheadThickness: 0.4,
  branchChance: 0.45,
  branchWidthScale: 0.6,
  branchLength: 40,
  deadEndLength: 8,
  deadEndFlare: true,
  branchRoomDepth: 9,
  branchRoomWidth: 10,
  branchRoomHeight: 8,
  travelSpeed: 8,
  corridorLead: 0.75,
  mouthRoomSize: 70,
  mouthRoomHeight: 18,
  areaCorridorSegments: 8,
  areaDescentFlights: 6,
  areaFloorFlights: 4,
  showSensors: true,
  stairVariance: 0.35,
  stairFlareChance: 0.4,
  stationGlide: 1.6,
  showBounds: false,
  areaSensorFlights: 5,
  areaSensorSegments: 4,
  endlessCorridorSlots: 18,
  areaSpread: 0,
  tourFixedSegments: 2,
  tourMovingSegments: 6,
  tourFixedFlights: 2,
  tourMovingFlights: 10,
  floorExits: 6,
  floorExitVariance: 0.5,
  thresholdWallWidth: 14,
  thresholdWallHeight: 9,
};

// The column previews put the camera in the well, not outside looking in:
// the point is to stand where the scene's camera stands.
const INSIDE_SHAFT = {
  cameraMode: 'orbit',
  // Leva vector controls hold {x,y,z}; an array here silently fails to apply
  // and the camera stays wherever it was.
  orbitDesktopPosition: { x: 8, y: 0, z: 0 },
  orbitDesktopTarget: { x: 0, y: 0, z: 0 },
  orbitDesktopPivot: { x: 0, y: 0, z: 0 },
  orbitDesktopFov: 62,
  orbitMobilePosition: { x: 8, y: 0, z: 0 },
  orbitMobileTarget: { x: 0, y: 0, z: 0 },
  orbitMobilePivot: { x: 0, y: 0, z: 0 },
  orbitMobileFov: 74,
  orbitMinDistance: 0.5,
  orbitMaxDistance: 20,
  orbitMaxDistanceUnlimited: false,
  wallMode: 'Solid',
  showGrid: false,
};

// Standing in the corridor looking down it, the way the scene's camera will.
const INSIDE_CORRIDOR = {
  kit: 'Corridor',
  cameraMode: 'orbit',
  orbitDesktopPosition: { x: -6, y: 0, z: 0 },
  orbitDesktopTarget: { x: 30, y: 0, z: 0 },
  orbitDesktopPivot: { x: 30, y: 0, z: 0 },
  orbitDesktopFov: 62,
  orbitMobilePosition: { x: -6, y: 0, z: 0 },
  orbitMobileTarget: { x: 30, y: 0, z: 0 },
  orbitMobilePivot: { x: 30, y: 0, z: 0 },
  orbitMobileFov: 74,
  orbitMinDistance: 1,
  orbitMaxDistance: 200,
  orbitMaxDistanceUnlimited: false,
  showGrid: false,
  wallMode: 'Solid',
};

export const PRESETS = {
  Inspect: { ...BASE },
  Assembly: {
    ...BASE,
    ...INSIDE_SHAFT,
    asset: 'Assembled Preview',
    flights: 18,
  },
  'Landing Variations': { ...BASE, asset: 'Landing Variation' },
  'Motion Preview': {
    ...BASE,
    ...INSIDE_SHAFT,
    asset: 'Motion Preview',
    motionSlots: 34,
  },
  'Book Scale': { ...BASE, voidRadius: 30.5, stairWidth: 9, wallHeight: 60 },

  'Corridor: Inspect': { ...BASE, kit: 'Corridor', showGrid: true },
  'Corridor: Assembly': {
    ...BASE,
    ...INSIDE_CORRIDOR,
    corridorAsset: 'Corridor Assembly',
  },
  'Corridor: Motion': {
    ...BASE,
    ...INSIDE_CORRIDOR,
    corridorAsset: 'Corridor Motion',
  },
  'Corridor: Shape Drift': {
    ...BASE,
    ...INSIDE_CORRIDOR,
    corridorAsset: 'Corridor Motion',
    driftAmount: 0.85,
    stepAmount: 0,
    stepRunLength: 6,
    branchChance: 0.15,
  },
  'Corridor: Stepped Jumps': {
    ...BASE,
    ...INSIDE_CORRIDOR,
    corridorAsset: 'Corridor Motion',
    driftAmount: 0.15,
    stepAmount: 0.7,
    branchChance: 0.15,
  },
  'Corridor: Branches': {
    ...BASE,
    ...INSIDE_CORRIDOR,
    corridorAsset: 'Corridor Motion',
    branchChance: 0.9,
    driftAmount: 0.25,
  },
  'Join: Threshold to Corridor': {
    ...BASE,
    ...INSIDE_CORRIDOR,
    kit: 'Connections',
    connection: 'Threshold to Corridor',
    tourMovingSegments: 2,
    orbitDesktopPosition: { x: -230, y: 4, z: 12 },
    orbitDesktopTarget: { x: -210, y: 4, z: 0 },
    orbitDesktopPivot: { x: -210, y: 4, z: 0 },
  },
  'Join: Corridor to Great Room': {
    ...BASE,
    ...INSIDE_CORRIDOR,
    kit: 'Connections',
    connection: 'Corridor to Great Room',
    tourMovingSegments: 2,
    orbitDesktopPosition: { x: -70, y: 8, z: 26 },
    orbitDesktopTarget: { x: -30, y: 4, z: 0 },
    orbitDesktopPivot: { x: -30, y: 4, z: 0 },
    orbitMaxDistance: 300,
    wallMode: 'Cutaway',
  },
  'Join: Great Room to Shaft': {
    ...BASE,
    ...INSIDE_CORRIDOR,
    kit: 'Connections',
    connection: 'Great Room to Shaft',
    tourMovingFlights: 5,
    orbitDesktopPosition: { x: 20, y: 14, z: 20 },
    orbitDesktopTarget: { x: 0, y: -6, z: 0 },
    orbitDesktopPivot: { x: 0, y: -6, z: 0 },
    orbitMaxDistance: 300,
    wallMode: 'Cutaway',
  },
  'Join: Shaft to Floor': {
    ...BASE,
    ...INSIDE_CORRIDOR,
    kit: 'Connections',
    connection: 'Shaft to Floor',
    tourMovingFlights: 5,
    orbitDesktopPosition: { x: 34, y: -18, z: 34 },
    orbitDesktopTarget: { x: 0, y: -30, z: 0 },
    orbitDesktopPivot: { x: 0, y: -30, z: 0 },
    orbitMaxDistance: 300,
    wallMode: 'Cutaway',
  },
  'Join: Full Descent': {
    ...BASE,
    ...INSIDE_CORRIDOR,
    kit: 'Connections',
    connection: 'Full Descent',
    orbitDesktopPosition: { x: -120, y: 30, z: 90 },
    orbitDesktopTarget: { x: -30, y: -40, z: 0 },
    orbitDesktopPivot: { x: -30, y: -40, z: 0 },
    orbitMaxDistance: 600,
    wallMode: 'Cutaway',
  },
  'Tour: Continuous Descent': {
    ...BASE,
    ...INSIDE_CORRIDOR,
    kit: 'Connections',
    connection: 'Area Tour',
    cameraMode: 'operator',
    wallMode: 'Solid',
    travelSpeed: 6,
    motionSpeed: 6,
    showSensors: true,
    stairVariance: 0.35,
    stairFlareChance: 0.4,
    stationGlide: 1.6,
    showBounds: false,
    areaSensorFlights: 5,
    areaSensorSegments: 4,
    endlessCorridorSlots: 18,
    areaSpread: 0,
  },
  'Transition: Shaft Mouth': {
    ...BASE,
    ...INSIDE_CORRIDOR,
    corridorAsset: 'Shaft Mouth Room',
    orbitDesktopPosition: { x: -50, y: 12, z: 40 },
    orbitDesktopTarget: { x: 0, y: 0, z: 0 },
    orbitDesktopPivot: { x: 0, y: 0, z: 0 },
  },
  'Transition: Threshold': {
    ...BASE,
    ...INSIDE_CORRIDOR,
    corridorAsset: 'Threshold Archway',
    orbitDesktopPosition: { x: -14, y: 3, z: 8 },
    orbitDesktopTarget: { x: 2, y: 3, z: 0 },
    orbitDesktopPivot: { x: 2, y: 3, z: 0 },
  },
  'Transition: Shaft Floor': {
    ...BASE,
    ...INSIDE_CORRIDOR,
    corridorAsset: 'Shaft Floor',
    orbitDesktopPosition: { x: -40, y: 20, z: 34 },
    orbitDesktopTarget: { x: 0, y: 5, z: 0 },
    orbitDesktopPivot: { x: 0, y: 5, z: 0 },
  },
};

export function getPresetControls({ presetSnapshot }) {
  return { ...presetSnapshot };
}
