// Fluid config shared across both color variants.
// All debugXxx flags are false — the squares are rendered as scene geometry.
const SHARED_FLUID = {
  paused: false,
  pressureRelax: 0.84,
  pressureIterations: 14,
  vorticity: 54,
  velocityDissipation: 0.4,
  densityDissipation: 1.6,
  splatRadius: 0.0005,
  autoSplatRadius: 0.0005,
  stationarySplatRadius: 0.0005,
  randomSplatRadius: 0.0022,
  splatForce: 4200,
  dyeStrength: 0.25,
  inputMode: 'pointer',
  autoSplat: false,
  autoSplatStrength: 0.03,
  autoSplatDyeStrength: 2.5,
  autoSplatForce: 950,
  autoSplatRate: 100,
  autoSplatRange: 1,
  autoSplatBurst: 4,
  autoSplatCount: 2,
  autoSplatStarts: [
    { x: 0.5, y: 0.4 },
    { x: 0.5, y: 0.5 },
  ],
  randomSplatStrength: 1,
  randomSplatDyeStrength: 1.71,
  randomSplatForce: 4200,
  stationarySplatsEnabled: true,
  stationarySplatStrength: 0.51,
  stationarySplatDyeStrength: 0.51,
  stationarySplatForce: 4200,
  stationarySplatDirectionStrength: 0.0005,
  stationarySplatDirectionAngle: 270,
  stationarySplatCount: 10,
  stationarySplats: [
    { x: 0.5, y: 0.45 },
    { x: 0.5, y: 0.55 },
    { x: 0.5, y: 0.65 },
    { x: 0.5, y: 0.75 },
    { x: 0.4, y: 0.5 },
    { x: 0.4, y: 0.6 },
    { x: 0.4, y: 0.7 },
    { x: 0.6, y: 0.5 },
    { x: 0.6, y: 0.6 },
    { x: 0.6, y: 0.7 },
  ],
  stationaryDebugMarkersEnabled: true,
  stationaryDebugMarkerCount: 7,
  stationaryDebugMarkers: [
    { x: 0.5, y: 0.5 },
    { x: 0.5, y: 0.6 },
    { x: 0.5, y: 0.7 },
    { x: 0.4, y: 0.55 },
    { x: 0.4, y: 0.65 },
    { x: 0.6, y: 0.55 },
    { x: 0.6, y: 0.65 },
  ],
  shading: true,
  bgA: '#4b4b4b',
  bgB: '#797979',
  bloom: true,
  bloomResolution: 0.2,
  bloomIterations: 4,
  bloomIntensity: 0.5,
  bloomThreshold: 0.62,
  bloomSoftKnee: 0.7,
  sunrays: true,
  sunraysResolution: 0.16,
  sunraysWeight: 0.9,
  colorful: true,
  colorUpdateSpeed: 20,
  colorCycleSpeed: 0.55,
  dithering: false,
  ditherStrength: 2.85,
  ditherScale: 1,
  debugCursor: false,
  debugAutoSplat: false,
  debugStationarySplat: false,
  debugRandomBurst: false,
  // Geometry marker appearance — debugXxx fields drive the marker layer.
  // The shader debug flags stay false so the display shader does not render
  // its own marker pass.
  debugStationarySplatColor: '#000000',
  debugStationarySplatWidth: 0.05,
  debugStationarySplatHeight: 0.05,
  debugStationaryMarkerColor: '#000000',
  debugStationaryMarkerWidth: 0.05,
  debugStationaryMarkerHeight: 0.05,
  markerSplatColor: '#000000',
  markerFillColor: '#000000',
  markerSplatSize: 0.05,
  markerFillSize: 0.05,
};

export const WATERCOLOR_SQUARES_PRESETS = {
  'Warm Red': {
    ...SHARED_FLUID,
    colorA: '#ff0000',
    colorB: '#ff0000',
    colorC: '#7b0000',
    brightness: 1.76,
    contrast: 1.09,
    saturation: 1.64,
    blendMode: 0,
  },
  Blue: {
    ...SHARED_FLUID,
    colorA: '#0033ff',
    colorB: '#0033ff',
    colorC: '#001a7b',
    brightness: 1.76,
    contrast: 1.09,
    saturation: 1.64,
    blendMode: 0,
  },
};

export const PRESET_NAMES = Object.keys(WATERCOLOR_SQUARES_PRESETS);
export const DEFAULT_PRESET = 'Warm Red';
