import { SCENE_DEFAULTS } from './defaults';

export const DEFAULT_PRESET = 'Heart';

const SNAPSHOTS = {
  Heart: {
    seed: 'heart',
    stemHeight: 6,
    stemCurve: 0.08,
    leafBlades: 2,
    leafLength: 2.4,
    sideShoots: 0,
    crownShape: 'heart',
    crownRadius: 3.2,
    crownStretch: 0.85,
    crownLift: 0.55,
    crownOpen: 0.85,
    lobeCount: 2,
    lobeSpread: 0.62,
    accentAmount: 0,
    shellBias: 0.7,
    tips: 60000,
    sheaf: 0.9,
    splitRatio: 0.65,
    wispChance: 0.02,
    ornamentDensity: 0.14,
    dotAmount: 0.6,
    cubeAmount: 0.35,
    petalAmount: 0.4,
    ornamentSize: 0.06,
    stemColor: '#35c25a',
    budColor: '#f2e8ee',
    crownColor: '#e0407e',
    accentColor: '#f7a8c8',
    tipColor: '#ffffff',
    ornamentColor: '#f4a531',
    tipAmount: 0.45,
  },
  'Pink Tuft': {
    seed: 'tuft',
    stemHeight: 6.8,
    stemCurve: 0.2,
    leafBlades: 2,
    leafLength: 1.6,
    sideShoots: 1,
    sideShootLength: 5.5,
    crownShape: 'cluster',
    crownRadius: 3,
    crownStretch: 1.1,
    lobeCount: 6,
    lobeSpread: 0.85,
    lobeJitter: 0.5,
    accentAmount: 0.35,
    tips: 55000,
    ornamentDensity: 0.1,
    dotAmount: 0.3,
    cubeAmount: 1,
    ornamentSize: 0.07,
    stemColor: '#4c9a3c',
    budColor: '#e8ecd2',
    crownColor: '#f0a2d8',
    accentColor: '#b83a6e',
    tipColor: '#fbe7d6',
    ornamentColor: '#e8e2da',
    greenReach: 0.28,
  },
  'Blush Plume': {
    seed: 'plume',
    stemHeight: 6.5,
    stemCurve: 0.05,
    leafBlades: 0,
    sideShoots: 0,
    crownShape: 'fan',
    crownRadius: 3.3,
    crownStretch: 0.9,
    crownOpen: 0.9,
    lobeCount: 3,
    lobeSpread: 0.5,
    shellBias: 0.35,
    tips: 80000,
    umbelSize: 2,
    sheaf: 0.95,
    fiberBend: 0.1,
    wispChance: 0.05,
    wispReach: 1.4,
    ornamentDensity: 0.05,
    dotAmount: 1,
    cubeAmount: 0,
    ornamentSize: 0.03,
    stemColor: '#8a9a4a',
    budColor: '#f4ece6',
    crownColor: '#f0c4bc',
    accentColor: '#b06850',
    tipColor: '#ffffff',
    ornamentColor: '#d8a050',
    greenReach: 0.12,
  },
  Marigold: {
    seed: 'marigold',
    stemHeight: 5.6,
    stemCurve: 0.9,
    stemWaves: 1.1,
    leafBlades: 0,
    sideShoots: 0,
    crownShape: 'dome',
    crownRadius: 3.1,
    crownStretch: 0.8,
    lobeCount: 4,
    lobeSpread: 0.55,
    shellBias: 0.85,
    tips: 50000,
    ornamentDensity: 0.4,
    dotAmount: 0,
    cubeAmount: 0,
    heartAmount: 1,
    petalAmount: 0.6,
    ornamentSize: 0.07,
    stemColor: '#cfd6c8',
    budColor: '#8a6a7a',
    crownColor: '#7a4a6a',
    accentColor: '#9a5a4a',
    tipColor: '#c08a70',
    ornamentColor: '#ffa726',
    greenReach: 0.05,
  },
  'Lilac Tower': {
    seed: 'lilac',
    stemHeight: 6.4,
    stemCurve: 0.06,
    leafBlades: 2,
    leafLength: 2.2,
    sideShoots: 0,
    crownShape: 'cluster',
    crownRadius: 3,
    crownStretch: 1.25,
    crownLift: 0.9,
    lobeCount: 8,
    lobeSpread: 1,
    lobeJitter: 0.5,
    accentAmount: 0.35,
    tips: 65000,
    ornamentDensity: 0.1,
    dotAmount: 1,
    cubeAmount: 0.1,
    ornamentSize: 0.035,
    stemColor: '#6aa048',
    budColor: '#dfe8c8',
    crownColor: '#8f86f0',
    accentColor: '#c8e07a',
    tipColor: '#e4dcff',
    ornamentColor: '#f0d890',
    greenReach: 0.35,
  },
  'Ember Bloom': {
    seed: 'ember',
    stemHeight: 5,
    stemCurve: 0.1,
    leafBlades: 2,
    leafLength: 2.4,
    sideShoots: 0,
    crownShape: 'stack',
    crownBase: 0.5,
    crownRadius: 2.6,
    crownStretch: 0.95,
    crownLift: 0.2,
    lobeCount: 7,
    lobeSpread: 1.1,
    accentAmount: 0.7,
    tips: 60000,
    wispChance: 0.03,
    ornamentDensity: 0.25,
    dotAmount: 1,
    cubeAmount: 0,
    ornamentSize: 0.025,
    stemColor: '#3f9a4a',
    budColor: '#f0e4dc',
    crownColor: '#e0304a',
    accentColor: '#f08a30',
    tipColor: '#fff4f0',
    ornamentColor: '#c8d0ff',
    greenReach: 0.12,
  },
  'Petal Burst': {
    seed: 'petal',
    stemHeight: 6.6,
    stemCurve: 0.3,
    leafBlades: 1,
    leafLength: 2,
    sideShoots: 0,
    crownShape: 'dome',
    crownRadius: 2.6,
    crownStretch: 0.95,
    lobeCount: 5,
    lobeSpread: 0.7,
    shellBias: 0.3,
    tips: 30000,
    umbelSize: 4,
    ornamentDensity: 0.18,
    dotAmount: 1,
    cubeAmount: 0,
    petalAmount: 0.5,
    ornamentSize: 0.05,
    stemColor: '#3c9a48',
    budColor: '#e8f0e8',
    crownColor: '#c6c2ee',
    accentColor: '#9ad0c0',
    tipColor: '#ffffff',
    ornamentColor: '#f25060',
    greenReach: 0.25,
  },
  Mobile: {
    seed: 'heart',
    crownShape: 'heart',
    crownRadius: 3.2,
    crownStretch: 0.85,
    crownLift: 0.55,
    crownOpen: 0.85,
    lobeCount: 2,
    lobeSpread: 0.62,
    accentAmount: 0,
    shellBias: 0.7,
    tips: 14000,
    ornamentDensity: 0.12,
    dotAmount: 0.6,
    cubeAmount: 0.35,
    petalAmount: 0.4,
    stemColor: '#35c25a',
    crownColor: '#e0407e',
    ornamentColor: '#f4a531',
  },
};

export const PRESETS = Object.fromEntries(
  Object.entries(SNAPSHOTS).map(([name, snapshot]) => [
    name,
    { ...SCENE_DEFAULTS, ...snapshot },
  ])
);

export function getPresetControls({ presetSnapshot }) {
  return { ...presetSnapshot };
}
