import { sceneDefaults } from '@modules/flora';

const SCENE_DEFAULTS = sceneDefaults();

export const DEFAULT_PRESET = 'Heart';

const SNAPSHOTS = {
  Heart: {
    seed: 'heart',
    formCount: 2,
    warp: 0.3,
    asymmetry: 0.25,
    stemHeight: 6,
    stemCurve: 0.08,
    leafBlades: 2,
    leafLength: 2.4,
    sideShoots: 0,
    crownRadius: 3.2,
    crownStretch: 0.85,
    crownLift: 0.55,
    accentAmount: 0,
    shellBias: 0.7,
    tips: 60000,
    sheaf: 0.9,
    splitRatio: 0.65,
    wispChance: 0.02,
    ornamentDensity: 0.14,
    sphereAmount: 0.6,
    d6Amount: 0.35,
    petalAmount: 0.4,
    ornamentSize: 0.06,
    stemColor: '#35c25a',
    budColor: '#f2e8ee',
    crownColor: '#e0407e',
    accentColor: '#f7a8c8',
    tipColor: '#ffffff',
    ornamentColor: '#f4a531',
    tipAmount: 0.45,
  },
  'Pink Tuft': {
    seed: 'tuft',
    formCount: 4,
    formSpread: 1.1,
    warp: 0.55,
    asymmetry: 0.5,
    stemHeight: 6.8,
    stemCurve: 0.2,
    leafBlades: 2,
    leafLength: 1.6,
    sideShoots: 1,
    sideShootLength: 5.5,
    crownRadius: 3,
    crownStretch: 1.1,
    accentAmount: 0.35,
    tips: 55000,
    ornamentDensity: 0.1,
    sphereAmount: 0.3,
    d6Amount: 1,
    ornamentSize: 0.07,
    stemColor: '#4c9a3c',
    budColor: '#e8ecd2',
    crownColor: '#f0a2d8',
    accentColor: '#b83a6e',
    tipColor: '#fbe7d6',
    ornamentColor: '#e8e2da',
    greenReach: 0.28,
  },
  'Blush Plume': {
    seed: 'plume',
    formCount: 2,
    warp: 0.45,
    asymmetry: 0.35,
    stemHeight: 6.5,
    stemCurve: 0.05,
    leafBlades: 0,
    sideShoots: 0,
    crownRadius: 3.3,
    crownStretch: 0.9,
    shellBias: 0.35,
    tips: 80000,
    umbelSize: 2,
    sheaf: 0.95,
    fiberBend: 0.1,
    wispChance: 0.05,
    wispReach: 1.4,
    ornamentDensity: 0.05,
    sphereAmount: 1,
    d6Amount: 0,
    ornamentSize: 0.03,
    stemColor: '#8a9a4a',
    budColor: '#f4ece6',
    crownColor: '#f0c4bc',
    accentColor: '#b06850',
    tipColor: '#ffffff',
    ornamentColor: '#d8a050',
    greenReach: 0.12,
  },
  Marigold: {
    seed: 'marigold',
    formCount: 1,
    warp: 0.2,
    asymmetry: 0.15,
    stemHeight: 5.6,
    stemCurve: 0.9,
    stemWaves: 1.1,
    leafBlades: 0,
    sideShoots: 0,
    crownRadius: 3.1,
    crownStretch: 0.8,
    shellBias: 0.85,
    tips: 50000,
    ornamentDensity: 0.4,
    sphereAmount: 0,
    d6Amount: 0,
    heartAmount: 1,
    petalAmount: 0.6,
    ornamentSize: 0.07,
    stemColor: '#cfd6c8',
    budColor: '#8a6a7a',
    crownColor: '#7a4a6a',
    accentColor: '#9a5a4a',
    tipColor: '#c08a70',
    ornamentColor: '#ffa726',
    greenReach: 0.05,
  },
  'Lilac Tower': {
    seed: 'lilac',
    formCount: 4,
    formSpread: 0.9,
    warp: 0.5,
    asymmetry: 0.4,
    stemHeight: 6.4,
    stemCurve: 0.06,
    leafBlades: 2,
    leafLength: 2.2,
    sideShoots: 0,
    crownRadius: 3,
    crownStretch: 1.25,
    crownLift: 0.9,
    accentAmount: 0.35,
    tips: 65000,
    ornamentDensity: 0.1,
    sphereAmount: 1,
    d6Amount: 0.1,
    ornamentSize: 0.035,
    stemColor: '#6aa048',
    budColor: '#dfe8c8',
    crownColor: '#8f86f0',
    accentColor: '#c8e07a',
    tipColor: '#e4dcff',
    ornamentColor: '#f0d890',
    greenReach: 0.35,
  },
  'Ember Bloom': {
    seed: 'ember',
    formCount: 4,
    formSpread: 0.6,
    warp: 0.4,
    asymmetry: 0.3,
    stemHeight: 5,
    stemCurve: 0.1,
    leafBlades: 2,
    leafLength: 2.4,
    sideShoots: 0,
    crownBase: 0.45,
    crownRadius: 2.6,
    crownStretch: 0.95,
    crownLift: 0.2,
    accentAmount: 0.7,
    tips: 60000,
    wispChance: 0.03,
    ornamentDensity: 0.25,
    sphereAmount: 1,
    d6Amount: 0,
    ornamentSize: 0.025,
    stemColor: '#3f9a4a',
    budColor: '#f0e4dc',
    crownColor: '#e0304a',
    accentColor: '#f08a30',
    tipColor: '#fff4f0',
    ornamentColor: '#c8d0ff',
    greenReach: 0.12,
  },
  'Petal Burst': {
    seed: 'petal',
    formCount: 2,
    warp: 0.25,
    asymmetry: 0.2,
    stemHeight: 6.6,
    stemCurve: 0.3,
    leafBlades: 1,
    leafLength: 2,
    sideShoots: 0,
    crownRadius: 2.6,
    crownStretch: 0.95,
    shellBias: 0.3,
    tips: 30000,
    umbelSize: 4,
    ornamentDensity: 0.18,
    sphereAmount: 1,
    d6Amount: 0,
    petalAmount: 0.5,
    ornamentSize: 0.05,
    stemColor: '#3c9a48',
    budColor: '#e8f0e8',
    crownColor: '#c6c2ee',
    accentColor: '#9ad0c0',
    tipColor: '#ffffff',
    ornamentColor: '#f25060',
    greenReach: 0.25,
  },
  'Dice Bloom': {
    seed: 'dice',
    formCount: 3,
    formSpread: 1,
    warp: 0.5,
    asymmetry: 0.45,
    stemHeight: 6.2,
    stemCurve: 0.15,
    leafBlades: 2,
    leafLength: 2.2,
    sideShoots: 1,
    crownRadius: 2.9,
    crownStretch: 1.05,
    accentAmount: 0.4,
    tips: 40000,
    ornamentDensity: 0.3,
    ornamentSize: 0.055,
    sphereWire: 0.3,
    d4Wire: 0.45,
    d6Wire: 0.45,
    d8Wire: 0.45,
    d10Wire: 0.45,
    d12Wire: 0.45,
    d20Wire: 0.45,
    sphereAmount: 0.35,
    d4Amount: 0.6,
    d6Amount: 0.5,
    d8Amount: 0.6,
    d10Amount: 0.4,
    d12Amount: 0.5,
    d20Amount: 0.7,
    heartAmount: 0,
    petalAmount: 0,
    stemColor: '#3f9a4a',
    budColor: '#e8ecd8',
    crownColor: '#c86ad0',
    accentColor: '#f0b040',
    tipColor: '#fdf3ff',
    ornamentColor: '#ffd98a',
    greenReach: 0.22,
  },
  'Gradient Garden': {
    seed: 'garden',
    paletteShuffle: true,
    formCount: 3,
    formSpread: 0.9,
    warp: 0.45,
    asymmetry: 0.4,
    tips: 45000,
    ornamentDensity: 0.22,
    ornamentSize: 0.055,
    sphereAmount: 0.6,
    d8Amount: 0.4,
    d20Amount: 0.4,
    petalAmount: 0.5,
    d8Wire: 0.5,
    d20Wire: 0.3,
    stemColor: '#3c9a48',
    budColor: '#e8ecdc',
    greenReach: 0.2,
    tipAmount: 0.25,
    habitVariety: 0.8,
    styleVariety: 0.7,
  },
  Mobile: {
    seed: 'heart',
    crownRadius: 3.2,
    crownStretch: 0.85,
    crownLift: 0.55,
    accentAmount: 0,
    shellBias: 0.7,
    tips: 14000,
    ornamentDensity: 0.12,
    sphereAmount: 0.6,
    d6Amount: 0.35,
    petalAmount: 0.4,
    stemColor: '#35c25a',
    crownColor: '#e0407e',
    ornamentColor: '#f4a531',
  },
};

export const PRESETS = Object.fromEntries(
  Object.entries(SNAPSHOTS).map(([name, snapshot]) => [
    name,
    { ...SCENE_DEFAULTS, ...snapshot },
  ])
);

export function getPresetControls({ currentControls, presetSnapshot }) {
  return Object.fromEntries(
    Object.entries(presetSnapshot).filter(([key]) => key in currentControls)
  );
}
