import { folder, useControls } from 'leva';

const C = { collapsed: true };

export default function useSceneControls() {
  const [controls] = useControls(
    'Row It Alone',
    () => ({
      Scene: folder(
        {
          cameraPosition: {
            label: 'Camera Pos',
            value: { x: 4.4, y: 2.25, z: 8.8 },
            step: 0.05,
          },
          cameraTarget: {
            label: 'Camera Target',
            value: { x: 0, y: 0.25, z: 0 },
            step: 0.05,
          },
          cameraFov: {
            label: 'FOV',
            value: 50,
            min: 20,
            max: 80,
            step: 1,
          },
          exposure: {
            label: 'Exposure',
            value: 0.1,
            min: 0.05,
            max: 1.2,
            step: 0.01,
          },
          ambientIntensity: {
            label: 'Ambient',
            value: 0.26,
            min: 0,
            max: 2,
            step: 0.01,
          },
          ambientColor: { label: 'Ambient Color', value: '#e8edf5' },
          hemisphereIntensity: {
            label: 'Hemisphere',
            value: 0.7,
            min: 0,
            max: 2,
            step: 0.01,
          },
          hemisphereSkyColor: { label: 'Hemi Sky', value: '#e7f5ff' },
          hemisphereGroundColor: { label: 'Hemi Ground', value: '#102333' },
          sunIntensity: {
            label: 'Sun Intensity',
            value: 2.6,
            min: 0,
            max: 6,
            step: 0.05,
          },
          sunDistance: {
            label: 'Sun Distance',
            value: 42,
            min: 10,
            max: 120,
            step: 1,
          },
          sunColor: { label: 'Sun Color', value: '#fff2d6' },
        },
        C
      ),
      Sky: folder(
        {
          elevation: {
            label: 'Elevation',
            value: 2,
            min: 0,
            max: 90,
            step: 0.1,
          },
          azimuth: {
            label: 'Azimuth',
            value: 176,
            min: -180,
            max: 180,
            step: 0.1,
          },
          turbidity: {
            label: 'Turbidity',
            value: 10,
            min: 0,
            max: 20,
            step: 0.1,
          },
          rayleigh: {
            label: 'Rayleigh',
            value: 2,
            min: 0,
            max: 4,
            step: 0.01,
          },
          mieCoefficient: {
            label: 'Mie Coef',
            value: 0.005,
            min: 0,
            max: 0.1,
            step: 0.001,
          },
          mieDirectionalG: {
            label: 'Mie Dir',
            value: 0.8,
            min: 0,
            max: 1,
            step: 0.01,
          },
        },
        C
      ),
      Ocean: folder(
        {
          Appearance: folder(
            {
              deepColor: { label: 'Deep', value: '#001e0f' },
              shallowColor: { label: 'Shallow', value: '#2e7897' },
              horizonColor: { label: 'Horizon', value: '#a4d8f2' },
              foamColor: { label: 'Foam', value: '#f4fbff' },
              opacity: {
                label: 'Opacity',
                value: 0.98,
                min: 0.5,
                max: 1,
                step: 0.01,
              },
              distortionScale: {
                label: 'Distortion',
                value: 3.7,
                min: 0,
                max: 8,
                step: 0.1,
              },
              normalMapSize: {
                label: 'Normal Size',
                value: 1,
                min: 0.1,
                max: 10,
                step: 0.1,
              },
              fresnelPower: {
                label: 'Fresnel Power',
                value: 4.25,
                min: 0.5,
                max: 10,
                step: 0.05,
              },
              fresnelStrength: {
                label: 'Fresnel Strength',
                value: 0.82,
                min: 0,
                max: 2,
                step: 0.01,
              },
              foamStrength: {
                label: 'Foam Strength',
                value: 0.34,
                min: 0,
                max: 2,
                step: 0.01,
              },
              foamThreshold: {
                label: 'Foam Threshold',
                value: 0.18,
                min: 0,
                max: 1,
                step: 0.01,
              },
              foamSoftness: {
                label: 'Foam Softness',
                value: 0.18,
                min: 0.01,
                max: 1,
                step: 0.01,
              },
              foamWaveInfluence: {
                label: 'Foam Wave',
                value: 0.65,
                min: 0,
                max: 2,
                step: 0.01,
              },
              planeSize: {
                label: 'Size',
                value: 72,
                min: 24,
                max: 600,
                step: 4,
              },
              planeSegments: {
                label: 'Segments',
                value: 320,
                min: 32,
                max: 640,
                step: 8,
              },
            },
            C
          ),
          Waves: folder(
            {
              swellAmplitude: {
                label: 'Swell Amp',
                value: 0.045,
                min: 0,
                max: 2,
                step: 0.01,
              },
              swellFrequency: {
                label: 'Swell Freq',
                value: 1,
                min: 0.1,
                max: 3,
                step: 0.01,
              },
              swellSpeed: {
                label: 'Swell Speed',
                value: 0.95,
                min: 0,
                max: 4,
                step: 0.01,
              },
              chopAmplitude: {
                label: 'Chop Amp',
                value: 0.014,
                min: 0,
                max: 1,
                step: 0.005,
              },
              chopFrequency: {
                label: 'Chop Freq',
                value: 1.35,
                min: 0.2,
                max: 5,
                step: 0.01,
              },
              chopSpeed: {
                label: 'Chop Speed',
                value: 1.8,
                min: 0,
                max: 6,
                step: 0.01,
              },
              detailAmplitude: {
                label: 'Detail Amp',
                value: 0.004,
                min: 0,
                max: 0.4,
                step: 0.001,
              },
              detailFrequency: {
                label: 'Detail Freq',
                value: 2.3,
                min: 0.5,
                max: 8,
                step: 0.01,
              },
              detailSpeed: {
                label: 'Detail Speed',
                value: 2.6,
                min: 0,
                max: 8,
                step: 0.01,
              },
              normalEpsilon: {
                label: 'Normal Eps',
                value: 0.08,
                min: 0.01,
                max: 0.4,
                step: 0.005,
              },
            },
            C
          ),
        },
        C
      ),
      Interaction: folder(
        {
          interactionEnabled: { label: 'Enabled', value: true },
          interactionBounds: {
            label: 'Area Size',
            value: 12,
            min: 4,
            max: 32,
            step: 0.5,
          },
          interactionResolution: {
            label: 'Resolution',
            value: 128,
            min: 32,
            max: 256,
            step: 32,
          },
          interactionDepth: {
            label: 'Mouse Deep',
            value: 0.02,
            min: 0.001,
            max: 0.08,
            step: 0.001,
          },
          interactionRadius: {
            label: 'Mouse Size',
            value: 0.35,
            min: 0.05,
            max: 2,
            step: 0.01,
          },
          interactionViscosity: {
            label: 'Viscosity',
            value: 0.935,
            min: 0.9,
            max: 0.999,
            step: 0.001,
          },
          interactionInterval: {
            label: 'Emit Interval',
            value: 0.02,
            min: 0.01,
            max: 0.5,
            step: 0.01,
          },
          interactionMinDistance: {
            label: 'Emit Distance',
            value: 0.05,
            min: 0.01,
            max: 2,
            step: 0.01,
          },
          cursorColliderEnabled: { label: 'Cursor Collider', value: true },
          showCursorCollider: { label: 'Show Cursor', value: false },
          cursorColliderRadius: {
            label: 'Cursor Radius',
            value: 0.22,
            min: 0.05,
            max: 2,
            step: 0.01,
          },
          cursorHover: {
            label: 'Cursor Hover',
            value: 0.08,
            min: -1,
            max: 1,
            step: 0.01,
          },
          cursorParkY: {
            label: 'Cursor Park Y',
            value: -20,
            min: -100,
            max: -1,
            step: 1,
          },
        },
        C
      ),
      Boat: folder(
        {
          boatPosition: {
            label: 'Position',
            value: { x: 0, y: 0.12, z: 0 },
            step: 0.05,
          },
          boatRotationY: {
            label: 'Rot Y',
            value: -20,
            min: -180,
            max: 180,
            step: 1,
          },
          boatScale: {
            label: 'Scale',
            value: 0.4,
            min: 0.1,
            max: 2,
            step: 0.01,
          },
          boatDraft: {
            label: 'Draft',
            value: -0.02,
            min: -2,
            max: 2,
            step: 0.01,
          },
          boatMass: {
            label: 'Mass',
            value: 1.4,
            min: 0.05,
            max: 5,
            step: 0.01,
          },
          boatBuoyancy: {
            label: 'Buoyancy',
            value: 5.8,
            min: 0,
            max: 80,
            step: 0.1,
          },
          boatBuoyancyDamping: {
            label: 'Buoy Damp',
            value: 3,
            min: 0,
            max: 20,
            step: 0.05,
          },
          boatLinearDamping: {
            label: 'Linear Damp',
            value: 3.4,
            min: 0,
            max: 20,
            step: 0.05,
          },
          boatAngularDamping: {
            label: 'Angular Damp',
            value: 8.5,
            min: 0,
            max: 20,
            step: 0.05,
          },
          boatProbeLift: {
            label: 'Probe Lift',
            value: 0.02,
            min: -1,
            max: 2,
            step: 0.01,
          },
          boatProbeForward: {
            label: 'Probe Forward',
            value: 0.72,
            min: 0.05,
            max: 5,
            step: 0.01,
          },
          boatProbeSide: {
            label: 'Probe Side',
            value: 0.34,
            min: 0.05,
            max: 5,
            step: 0.01,
          },
        },
        C
      ),
      Oars: folder(
        {
          jointMinAngle: {
            label: 'Min Angle',
            value: -58,
            min: -180,
            max: 0,
            step: 1,
          },
          jointMaxAngle: {
            label: 'Max Angle',
            value: 36,
            min: 0,
            max: 180,
            step: 1,
          },
          linearDamping: {
            label: 'Linear Damp',
            value: 1.8,
            min: 0,
            max: 8,
            step: 0.05,
          },
          angularDamping: {
            label: 'Angular Damp',
            value: 5.5,
            min: 0,
            max: 20,
            step: 0.05,
          },
          buoyancy: {
            label: 'Buoyancy',
            value: 12,
            min: 0,
            max: 20,
            step: 0.1,
          },
          buoyancyDamping: {
            label: 'Buoy Damp',
            value: 2.2,
            min: 0,
            max: 10,
            step: 0.05,
          },
          probeLift: {
            label: 'Probe Lift',
            value: 0.1,
            min: -1,
            max: 2,
            step: 0.01,
          },
        },
        C
      ),
      Fog: folder(
        {
          fogColor: { label: 'Color', value: '#adc3cf' },
          fogDensity: {
            label: 'Density',
            value: 0.045,
            min: 0,
            max: 0.3,
            step: 0.001,
          },
          fogFloor: {
            label: 'Floor',
            value: -0.4,
            min: -20,
            max: 10,
            step: 0.05,
          },
          fogCeiling: {
            label: 'Ceiling',
            value: 4.4,
            min: -10,
            max: 20,
            step: 0.05,
          },
          fogNoiseScale: {
            label: 'Noise Scale',
            value: 0.018,
            min: 0.001,
            max: 0.1,
            step: 0.001,
          },
          fogNoiseStrength: {
            label: 'Noise Strength',
            value: 0.35,
            min: 0,
            max: 1,
            step: 0.01,
          },
          fogFlow: {
            label: 'Flow',
            value: { x: 0.2, y: 0.04, z: -0.08 },
            step: 0.01,
          },
          fogSpeed: {
            label: 'Flow Speed',
            value: 0.32,
            min: 0,
            max: 4,
            step: 0.01,
          },
        },
        C
      ),
      Physics: folder(
        {
          gravityY: {
            label: 'Gravity Y',
            value: -9.81,
            min: -20,
            max: 0,
            step: 0.01,
          },
          oarMass: {
            label: 'Oar Mass',
            value: 0.25,
            min: 0.05,
            max: 5,
            step: 0.01,
          },
        },
        C
      ),
    }),
    { collapsed: true }
  );

  return {
    scene: {
      ambientColor: controls.ambientColor,
      ambientIntensity: controls.ambientIntensity,
      cameraFar: 500,
      cameraFov: controls.cameraFov,
      cameraPosition: [
        controls.cameraPosition.x,
        controls.cameraPosition.y,
        controls.cameraPosition.z,
      ],
      cameraTarget: [
        controls.cameraTarget.x,
        controls.cameraTarget.y,
        controls.cameraTarget.z,
      ],
      exposure: controls.exposure,
      hemisphereGroundColor: controls.hemisphereGroundColor,
      hemisphereIntensity: controls.hemisphereIntensity,
      hemisphereSkyColor: controls.hemisphereSkyColor,
      sunColor: controls.sunColor,
      sunDistance: controls.sunDistance,
      sunIntensity: controls.sunIntensity,
    },
    sky: {
      azimuth: controls.azimuth,
      elevation: controls.elevation,
      mieCoefficient: controls.mieCoefficient,
      mieDirectionalG: controls.mieDirectionalG,
      rayleigh: controls.rayleigh,
      turbidity: controls.turbidity,
    },
    ocean: {
      chopAmplitude: controls.chopAmplitude,
      chopFrequency: controls.chopFrequency,
      chopSpeed: controls.chopSpeed,
      deepColor: controls.deepColor,
      detailAmplitude: controls.detailAmplitude,
      detailFrequency: controls.detailFrequency,
      detailSpeed: controls.detailSpeed,
      distortionScale: controls.distortionScale,
      foamColor: controls.foamColor,
      foamSoftness: controls.foamSoftness,
      foamStrength: controls.foamStrength,
      foamThreshold: controls.foamThreshold,
      foamWaveInfluence: controls.foamWaveInfluence,
      fresnelPower: controls.fresnelPower,
      fresnelStrength: controls.fresnelStrength,
      horizonColor: controls.horizonColor,
      normalEpsilon: controls.normalEpsilon,
      normalMapSize: controls.normalMapSize,
      opacity: controls.opacity,
      planeSegments: Math.round(controls.planeSegments),
      planeSize: controls.planeSize,
      shallowColor: controls.shallowColor,
      swellAmplitude: controls.swellAmplitude,
      swellFrequency: controls.swellFrequency,
      swellSpeed: controls.swellSpeed,
    },
    interaction: {
      bounds: controls.interactionBounds,
      cursorColliderEnabled: controls.cursorColliderEnabled,
      cursorColliderRadius: controls.cursorColliderRadius,
      cursorHover: controls.cursorHover,
      cursorParkY: controls.cursorParkY,
      depth: controls.interactionDepth,
      enabled: controls.interactionEnabled,
      interval: controls.interactionInterval,
      minDistance: controls.interactionMinDistance,
      radius: controls.interactionRadius,
      resolution: Math.round(controls.interactionResolution),
      showCursorCollider: controls.showCursorCollider,
      viscosity: controls.interactionViscosity,
    },
    boat: {
      angularDamping: controls.boatAngularDamping,
      buoyancy: controls.boatBuoyancy,
      buoyancyDamping: controls.boatBuoyancyDamping,
      draft: controls.boatDraft,
      linearDamping: controls.boatLinearDamping,
      mass: controls.boatMass,
      position: [
        controls.boatPosition.x,
        controls.boatPosition.y,
        controls.boatPosition.z,
      ],
      probeForward: controls.boatProbeForward,
      probeLift: controls.boatProbeLift,
      probeSide: controls.boatProbeSide,
      rotationY: controls.boatRotationY,
      scale: controls.boatScale,
    },
    oars: {
      angularDamping: controls.angularDamping,
      buoyancy: controls.buoyancy,
      buoyancyDamping: controls.buoyancyDamping,
      jointMaxAngle: controls.jointMaxAngle,
      jointMinAngle: controls.jointMinAngle,
      linearDamping: controls.linearDamping,
      probeLift: controls.probeLift,
    },
    fog: {
      ceiling: controls.fogCeiling,
      color: controls.fogColor,
      density: controls.fogDensity,
      floor: controls.fogFloor,
      flow: [controls.fogFlow.x, controls.fogFlow.y, controls.fogFlow.z],
      noiseScale: controls.fogNoiseScale,
      noiseStrength: controls.fogNoiseStrength,
      speed: controls.fogSpeed,
    },
    physics: {
      gravity: [0, controls.gravityY, 0],
      oarMass: controls.oarMass,
      timeStep: 1 / 60,
    },
  };
}
