import { imageFile } from '@utils/appUtils';

const PRESETS = {
  Surrender: {
    // Scene - Camera
    orbitControls: false,
    // Scene - Background
    bgColor: '#838383',
    fogNear: 5,
    fogFar: 14,
    // Scene - Lighting
    ambientIntensity: 0.5,
    ambientColor: '#ffffff',
    keyIntensity: 3,
    keyColor: '#ffffff',
    keyPosX: 3,
    keyPosY: 5,
    keyPosZ: 4,
    keyShadow: true,
    fillIntensity: 0.2,
    fillColor: '#ffffff',
    fillPosX: 2,
    fillPosY: 1,
    fillPosZ: -1,
    // Scene - Lighting - Environment
    envIntensity: 0.45,
    envSkyColor: '#b8c2cc',
    envHorizonColor: '#c9c9c9',
    envGroundColor: '#5a5a56',
    envSunIntensity: 1.5,
    // Flag - Orientation
    rotateX: -15,
    rotateY: 0,
    rotateZ: 15,
    posX: 0,
    posY: 0,
    // Flag - Cloth
    clothWidth: 1.0,
    clothHeight: 0.7,
    segmentsX: 30,
    segmentsY: 21,
    stiffness: 0.5,
    dampening: 0.98,
    // Flag - Cloth - Alpha
    alphaSeed: 42,
    alphaScale: 3,
    edgeFade: 0,
    holeAmount: 0,
    tatterEdge: 0,
    smoothEdges: false,
    // Flag - Material
    textureUrl: 'None',
    textureTile: true,
    textureScaleX: 1,
    textureScaleY: 1,
    textureRotation: 0,
    flagColor: '#f5f0e8',
    roughness: 0.65,
    metalness: 0.0,
    opacity: 1.0,
    // Flag - Material - Weave
    fabricAmount: 1,
    fabricThreads: 120,
    fabricDepth: 0.3,
    fabricShade: 0.32,
    fabricHem: 0.016,
    fabricWear: 0.3,
    sheen: 0.45,
    sheenRoughness: 0.35,
    sheenColor: '#fff6ea',
    clearcoat: 0.0,
    clearcoatRoughness: 0.0,
    transmission: 0.0,
    ior: 1.5,
    materialThickness: 0.0,
    // Flag - Pole
    poleColor: '#c4c4c4',
    poleMetalness: 0.6,
    poleRoughness: 0.4,
    // Flag - Finial
    finialColor: '#efcb5f',
    finialMetalness: 0.7,
    finialRoughness: 0.3,
    // Flag - Rings
    ringColor: '#c4c4c4',
    ringMetalness: 0.8,
    ringRoughness: 0.3,
    // Wind
    wind: 4.7,
    windDirX: 1,
    windDirZ: -0.2,
    // Leaves
    leavesEnabled: false,
    leafMode: 'Billboard',
    leafType: 'Leaves',
    leafCount: 300,
    leafSize: 0.08,
    leafSpeed: 0.08,
    leafSpeedJitter: 0.2,
    leafTravel: 5,
    leafTumble: 20,
    leafCurvature: 0.0,
    leafAspect: 1,
    leafWindInfluence: 0.15,
    leafFlutter: 0.35,
    leafRoughness: 0.6,
    leafTranslucency: 0.4,
    leafColor1: '#d70654',
    leafColor2: '#ffd95f',
    leafColor3: '#b8d576',
    // Thunder & Lightning
    thunderEnabled: false,
    thunderLightColor: '#c8c4ff',
    thunderPeakIntensity: 18,
    thunderMinGap: 12,
    thunderMaxGap: 28,
    ambienceTrack: '',
    // Moonlight
    moonColor: '#b8ccf0',
    moonPeakIntensity: 120,
    moonPosX: -3,
    moonPosY: 12,
    moonPosZ: 6,
    moonAngle: 24,
    cloudScale: 4.5,
    cloudDensity: -0.2,
    cloudContrast: 0.5,
    cloudSpeed: 1.0,
    cloudFloor: 0.0,
    // Postprocessing - Bloom
    bloomEnabled: false,
    bloomThreshold: 1.6,
    bloomStrength: 0.5,
    bloomRadius: 0.6,
    bloomDownSampleRatio: 2,
    // Postprocessing - Outline
    enabled: true,
    mode: 'glow',
    strength: 7,
    thickness: 12,
    color: '#3eb2ff',
    hiddenColor: '#000000',
    hiddenStrength: 0,
    glow: 0.35,
    inside: false,
    downSampleRatio: 1,
    patternScale: 8,
    patternOctaves: 3,
    patternLacunarity: 2,
    ringStride: 10,
    halftoneScale: 1,
    // Debug
    paused: false,
    wireframe: false,
    cursorCollider: true,
    debugColliders: false,
    debugColor: '#ff0000',
    cursorRadius: 0.12,
  },

  'Surrender Now': {
    // Scene - Camera
    orbitControls: false,
    // Scene - Background
    bgColor: '#000000',
    fogNear: 6,
    fogFar: 16,
    // Scene - Lighting
    // Ambient/key/fill are near-off — the MoonlightProjector carries the scene.
    ambientIntensity: 0.04,
    ambientColor: '#0a1525',
    keyIntensity: 0.08,
    keyColor: '#c8d8f0',
    keyPosX: -3,
    keyPosY: 5,
    keyPosZ: 4,
    keyShadow: true,
    fillIntensity: 0.03,
    fillColor: '#0d1a2e',
    fillPosX: 2,
    fillPosY: 1,
    fillPosZ: -1,
    // Scene - Lighting - Environment
    envIntensity: 0.25,
    envSkyColor: '#1a2030',
    envHorizonColor: '#101418',
    envGroundColor: '#050505',
    envSunIntensity: 0,
    // Flag - Orientation
    rotateX: -15,
    rotateY: 0,
    rotateZ: 15,
    posX: 0,
    posY: 0,
    // Flag - Cloth
    clothWidth: 1.0,
    clothHeight: 0.7,
    segmentsX: 30,
    segmentsY: 21,
    stiffness: 0.5,
    dampening: 0.98,
    // Flag - Cloth - Alpha
    alphaSeed: 57,
    alphaScale: 9.2,
    edgeFade: 0,
    holeAmount: 1,
    tatterEdge: 1,
    smoothEdges: true,
    // Flag - Material
    textureUrl: imageFile('turbo_flex.png'),
    textureTile: false,
    textureScaleX: 0.7,
    textureScaleY: 0.7,
    textureRotation: 0,
    flagColor: '#4b4b4b',
    roughness: 0.9,
    metalness: 0.0,
    opacity: 1.0,
    // Flag - Material - Weave
    fabricAmount: 1,
    fabricThreads: 120,
    fabricDepth: 0.3,
    fabricShade: 0.32,
    fabricHem: 0.016,
    fabricWear: 0.35,
    sheen: 0.35,
    sheenRoughness: 0.4,
    sheenColor: '#9aa4c0',
    clearcoat: 0.0,
    clearcoatRoughness: 0.0,
    transmission: 0.0,
    ior: 1.5,
    materialThickness: 0.0,
    // Flag - Pole
    poleColor: '#777676',
    poleMetalness: 0.97,
    poleRoughness: 0.7,
    // Flag - Finial
    finialColor: '#c8a84b',
    finialMetalness: 0.8,
    finialRoughness: 0.2,
    // Flag - Rings
    ringColor: '#b2b1b1',
    ringMetalness: 1,
    ringRoughness: 0.38,
    // Wind
    wind: 10,
    windDirX: 1,
    windDirZ: -0.2,
    // Leaves
    leavesEnabled: true,
    leafMode: 'Billboard',
    leafType: 'Rain',
    leafCount: 1500,
    leafSize: 0.01,
    leafSpeed: 0.25,
    leafSpeedJitter: 0.15,
    leafTravel: 8,
    leafTumble: 0,
    leafCurvature: 0,
    leafAspect: 8,
    leafWindInfluence: 0.7,
    leafFlutter: 0.35,
    leafRoughness: 0.6,
    leafTranslucency: 0.4,
    leafColor1: '#8aaec8',
    leafColor2: '#aac4d8',
    leafColor3: '#6888a0',
    // Thunder & Lightning
    thunderEnabled: true,
    thunderLightColor: '#c8c4ff',
    thunderPeakIntensity: 18,
    thunderMinGap: 12,
    thunderMaxGap: 28,
    ambienceTrack: '',
    // Moonlight
    moonColor: '#b8ccf0',
    moonPeakIntensity: 280,
    moonPosX: -3,
    moonPosY: 12,
    moonPosZ: 6,
    moonAngle: 24,
    cloudScale: 4.5,
    cloudDensity: -0.2,
    cloudContrast: 0.5,
    cloudSpeed: 1.0,
    cloudFloor: 0.15,
    // Postprocessing - Bloom
    bloomEnabled: true,
    bloomThreshold: 1.6,
    bloomStrength: 0.5,
    bloomRadius: 0.6,
    bloomDownSampleRatio: 2,
    // Postprocessing - Outline
    enabled: false,
    mode: 'worley',
    strength: 7,
    thickness: 12,
    color: '#ffffff',
    hiddenColor: '#000000',
    hiddenStrength: 0,
    glow: 0.5,
    inside: false,
    downSampleRatio: 1,
    patternScale: 8,
    patternOctaves: 3,
    patternLacunarity: 2,
    ringStride: 10,
    halftoneScale: 1,
    // Debug
    paused: false,
    wireframe: false,
    cursorCollider: true,
    debugColliders: false,
    debugColor: '#ff0000',
    cursorRadius: 0.12,
  },

  Autumn: {
    // Scene - Camera
    orbitControls: false,
    // Scene - Background
    bgColor: '#586848',
    fogNear: 3,
    fogFar: 9,
    // Scene - Lighting
    // The key carried the whole scene at 13:1 over ambient, which crushed every
    // shadowed fold on a cream flag to near black. The gradient environment now
    // does the filling, so the key only has to shape.
    ambientIntensity: 0.12,
    ambientColor: '#c8d0e0',
    keyIntensity: 2.1,
    keyColor: '#f7ecda',
    keyPosX: -6,
    keyPosY: 2.5,
    keyPosZ: 5.4,
    keyShadow: true,
    fillIntensity: 0.15,
    fillColor: '#304060',
    fillPosX: 3,
    fillPosY: 1,
    fillPosZ: -1,
    // Scene - Lighting - Environment
    envIntensity: 1.15,
    envSkyColor: '#8fa4b4',
    envHorizonColor: '#9aa284',
    envGroundColor: '#4a4230',
    envSunIntensity: 3,
    // Flag - Orientation
    rotateX: -15,
    rotateY: 0,
    rotateZ: 15,
    posX: 0,
    posY: 0,
    // Flag - Cloth
    clothWidth: 1.0,
    clothHeight: 0.7,
    segmentsX: 30,
    segmentsY: 21,
    stiffness: 0.5,
    dampening: 0.98,
    // Flag - Cloth - Alpha
    alphaSeed: 42,
    alphaScale: 3,
    edgeFade: 0,
    holeAmount: 0,
    tatterEdge: 0,
    smoothEdges: false,
    // Flag - Material
    textureUrl: 'None',
    textureTile: true,
    textureScaleX: 1,
    textureScaleY: 1,
    textureRotation: 0,
    flagColor: '#f5f0e8',
    roughness: 0.65,
    metalness: 0.0,
    opacity: 1.0,
    // Flag - Material - Weave
    fabricAmount: 1,
    fabricThreads: 150,
    fabricDepth: 0.25,
    fabricShade: 0.27,
    fabricHem: 0.03,
    fabricWear: 0.45,
    sheen: 0.55,
    sheenRoughness: 0.32,
    sheenColor: '#fff2df',
    clearcoat: 0.0,
    clearcoatRoughness: 0.0,
    transmission: 0.0,
    ior: 1.5,
    materialThickness: 0.0,
    // Flag - Pole
    poleColor: '#c4c4c4',
    poleMetalness: 0.6,
    poleRoughness: 0.4,
    // Flag - Finial
    finialColor: '#efcb5f',
    finialMetalness: 0.7,
    finialRoughness: 0.3,
    // Flag - Rings
    ringColor: '#c4c4c4',
    ringMetalness: 0.8,
    ringRoughness: 0.3,
    // Wind
    wind: 4.7,
    windDirX: 1,
    windDirZ: -0.2,
    // Leaves
    leavesEnabled: true,
    leafMode: 'Billboard',
    leafType: 'Leaves',
    leafCount: 400,
    leafSize: 0.06,
    leafSpeed: 0.02,
    leafSpeedJitter: 0.3,
    leafTravel: 8,
    leafTumble: 20,
    leafCurvature: 0.4,
    leafAspect: 1,
    leafWindInfluence: 0.15,
    leafFlutter: 0.55,
    leafRoughness: 0.55,
    leafTranslucency: 0.9,
    leafColor1: '#e03010',
    leafColor2: '#d06000',
    leafColor3: '#702010',
    // Thunder & Lightning
    thunderEnabled: false,
    thunderLightColor: '#c8c4ff',
    thunderPeakIntensity: 18,
    thunderMinGap: 12,
    thunderMaxGap: 28,
    ambienceTrack: 'wind-and-leaves.mp3',
    // Moonlight
    moonColor: '#b8ccf0',
    moonPeakIntensity: 120,
    moonPosX: -3,
    moonPosY: 12,
    moonPosZ: 6,
    moonAngle: 24,
    cloudScale: 4.5,
    cloudDensity: -0.2,
    cloudContrast: 0.5,
    cloudSpeed: 1.0,
    cloudFloor: 0.0,
    // Postprocessing - Bloom
    bloomEnabled: false,
    bloomThreshold: 1.6,
    bloomStrength: 0.5,
    bloomRadius: 0.6,
    bloomDownSampleRatio: 2,
    // Postprocessing - Outline
    enabled: true,
    mode: 'glow',
    strength: 7,
    thickness: 6,
    color: '#414d36',
    hiddenColor: '#000000',
    hiddenStrength: 0,
    glow: 0.35,
    inside: false,
    downSampleRatio: 1,
    patternScale: 8,
    patternOctaves: 3,
    patternLacunarity: 2,
    ringStride: 10,
    halftoneScale: 1,
    // Debug
    paused: false,
    wireframe: false,
    cursorCollider: true,
    debugColliders: false,
    debugColor: '#ff0000',
    cursorRadius: 0.12,
  },
  Spring: {
    // Scene - Camera
    orbitControls: false,
    // Scene - Background
    bgColor: '#f0c8dc',
    fogNear: 6,
    fogFar: 16,
    // Scene - Lighting
    ambientIntensity: 0.85,
    ambientColor: '#fff0f5',
    keyIntensity: 1.8,
    keyColor: '#fff8f2',
    keyPosX: 1,
    keyPosY: 7,
    keyPosZ: 5,
    keyShadow: true,
    fillIntensity: 0.55,
    fillColor: '#ffd8ee',
    fillPosX: -2,
    fillPosY: 1,
    fillPosZ: -1,
    // Scene - Lighting - Environment
    envIntensity: 0.5,
    envSkyColor: '#ffe4ef',
    envHorizonColor: '#f7d8e4',
    envGroundColor: '#c9a8b4',
    envSunIntensity: 1.2,
    // Flag - Orientation
    rotateX: -15,
    rotateY: 0,
    rotateZ: 15,
    posX: 0,
    posY: 0,
    // Flag - Cloth
    clothWidth: 1.0,
    clothHeight: 0.7,
    segmentsX: 30,
    segmentsY: 21,
    stiffness: 0.5,
    dampening: 0.98,
    // Flag - Cloth - Alpha
    alphaSeed: 42,
    alphaScale: 3,
    edgeFade: 0,
    holeAmount: 0,
    tatterEdge: 0,
    smoothEdges: false,
    // Flag - Material
    textureUrl: 'None',
    textureTile: true,
    textureScaleX: 1,
    textureScaleY: 1,
    textureRotation: 0,
    flagColor: '#cbebff',
    roughness: 0.65,
    metalness: 0.0,
    opacity: 1.0,
    // Flag - Material - Weave
    fabricAmount: 1,
    fabricThreads: 140,
    fabricDepth: 0.26,
    fabricShade: 0.28,
    fabricHem: 0.014,
    fabricWear: 0.2,
    sheen: 0.5,
    sheenRoughness: 0.35,
    sheenColor: '#fff0f5',
    clearcoat: 0.0,
    clearcoatRoughness: 0.0,
    transmission: 0.0,
    ior: 1.5,
    materialThickness: 0.0,
    // Flag - Pole
    poleColor: '#c4c4c4',
    poleMetalness: 0.6,
    poleRoughness: 0.4,
    // Flag - Finial
    finialColor: '#efcb5f',
    finialMetalness: 0.7,
    finialRoughness: 0.3,
    // Flag - Rings
    ringColor: '#c4c4c4',
    ringMetalness: 0.8,
    ringRoughness: 0.3,
    // Wind
    wind: 3.0,
    windDirX: 1,
    windDirZ: -0.2,
    // Leaves
    leavesEnabled: true,
    leafMode: 'Billboard',
    leafType: 'Blossoms',
    leafCount: 700,
    leafSize: 0.06,
    leafSpeed: 0.01,
    leafSpeedJitter: 0.25,
    leafTravel: 5,
    leafTumble: 35,
    leafCurvature: 1,
    leafAspect: 1,
    leafWindInfluence: 0.15,
    leafFlutter: 0.6,
    leafRoughness: 0.7,
    leafTranslucency: 1.1,
    leafColor1: '#c6c8d6',
    leafColor2: '#f7c3ea',
    leafColor3: '#d0baca',
    // Thunder & Lightning
    thunderEnabled: false,
    thunderLightColor: '#c8c4ff',
    thunderPeakIntensity: 18,
    thunderMinGap: 12,
    thunderMaxGap: 28,
    ambienceTrack: 'spring-birds-loop.mp3',
    // Moonlight
    moonColor: '#b8ccf0',
    moonPeakIntensity: 120,
    moonPosX: -3,
    moonPosY: 12,
    moonPosZ: 6,
    moonAngle: 24,
    cloudScale: 4.5,
    cloudDensity: -0.2,
    cloudContrast: 0.5,
    cloudSpeed: 1.0,
    cloudFloor: 0.0,
    // Postprocessing - Bloom
    bloomEnabled: false,
    bloomThreshold: 1.6,
    bloomStrength: 0.5,
    bloomRadius: 0.6,
    bloomDownSampleRatio: 2,
    // Postprocessing - Outline
    enabled: true,
    mode: 'outline',
    strength: 7,
    thickness: 1.2,
    color: '#ffffff',
    hiddenColor: '#000000',
    hiddenStrength: 0,
    glow: 0.35,
    inside: false,
    downSampleRatio: 1,
    patternScale: 8,
    patternOctaves: 3,
    patternLacunarity: 2,
    ringStride: 10,
    halftoneScale: 1,
    // Debug
    paused: false,
    wireframe: false,
    cursorCollider: true,
    debugColliders: false,
    debugColor: '#ff0000',
    cursorRadius: 0.12,
  },

  Winter: {
    // Scene - Camera
    orbitControls: false,
    // Scene - Background
    bgColor: '#0a1220',
    fogNear: 3,
    fogFar: 8,
    // Scene - Lighting
    ambientIntensity: 0.3,
    ambientColor: '#b0c8e8',
    keyIntensity: 1.8,
    keyColor: '#c0d8f8',
    keyPosX: -1,
    keyPosY: 9,
    keyPosZ: 3,
    keyShadow: true,
    fillIntensity: 0.1,
    fillColor: '#1a2840',
    fillPosX: 2,
    fillPosY: 1,
    fillPosZ: -1,
    // Scene - Lighting - Environment
    envIntensity: 0.45,
    envSkyColor: '#2a3d5c',
    envHorizonColor: '#18263c',
    envGroundColor: '#0c1424',
    envSunIntensity: 0.6,
    // Flag - Orientation
    rotateX: -15,
    rotateY: 0,
    rotateZ: 15,
    posX: 0,
    posY: 0,
    // Flag - Cloth
    clothWidth: 1.0,
    clothHeight: 0.7,
    segmentsX: 30,
    segmentsY: 21,
    stiffness: 0.5,
    dampening: 0.98,
    // Flag - Cloth - Alpha
    alphaSeed: 42,
    alphaScale: 3,
    edgeFade: 0,
    holeAmount: 0,
    tatterEdge: 0,
    smoothEdges: false,
    // Flag - Material
    textureUrl: 'None',
    textureTile: true,
    textureScaleX: 1,
    textureScaleY: 1,
    textureRotation: 0,
    flagColor: '#c8d4e0',
    roughness: 0.5,
    metalness: 0.0,
    opacity: 1.0,
    // Flag - Material - Weave
    fabricAmount: 1,
    fabricThreads: 110,
    fabricDepth: 0.3,
    fabricShade: 0.34,
    fabricHem: 0.018,
    fabricWear: 0.35,
    sheen: 0.4,
    sheenRoughness: 0.4,
    sheenColor: '#dce8ff',
    clearcoat: 0.0,
    clearcoatRoughness: 0.0,
    transmission: 0.0,
    ior: 1.5,
    materialThickness: 0.0,
    // Flag - Pole
    poleColor: '#c4c4c4',
    poleMetalness: 0.6,
    poleRoughness: 0.4,
    // Flag - Finial
    finialColor: '#efcb5f',
    finialMetalness: 0.7,
    finialRoughness: 0.3,
    // Flag - Rings
    ringColor: '#c4c4c4',
    ringMetalness: 0.8,
    ringRoughness: 0.3,
    // Wind
    wind: 2.0,
    windDirX: 0.3,
    windDirZ: 0,
    // Leaves
    leavesEnabled: true,
    leafMode: 'Billboard',
    leafType: 'Snowflakes',
    leafCount: 2000,
    leafSize: 0.02,
    leafSpeed: 0.015,
    leafSpeedJitter: 0.25,
    leafTravel: 5,
    leafTumble: 3,
    leafCurvature: 0.0,
    leafAspect: 1,
    leafWindInfluence: 0.15,
    leafFlutter: 0.3,
    leafRoughness: 0.35,
    leafTranslucency: 0.5,
    leafColor1: '#ffffff',
    leafColor2: '#ddeeff',
    leafColor3: '#ffffff',
    // Thunder & Lightning
    thunderEnabled: false,
    thunderLightColor: '#c8c4ff',
    thunderPeakIntensity: 18,
    thunderMinGap: 12,
    thunderMaxGap: 28,
    ambienceTrack: 'wind-draft-loop.mp3',
    // Moonlight
    moonColor: '#b8ccf0',
    moonPeakIntensity: 120,
    moonPosX: -3,
    moonPosY: 12,
    moonPosZ: 6,
    moonAngle: 24,
    cloudScale: 4.5,
    cloudDensity: -0.2,
    cloudContrast: 0.5,
    cloudSpeed: 1.0,
    cloudFloor: 0.0,
    // Postprocessing - Bloom
    bloomEnabled: false,
    bloomThreshold: 1.6,
    bloomStrength: 0.5,
    bloomRadius: 0.6,
    bloomDownSampleRatio: 2,
    // Postprocessing - Outline
    enabled: false,
    mode: 'glow',
    strength: 5,
    thickness: 10,
    color: '#aaccff',
    hiddenColor: '#000000',
    hiddenStrength: 0,
    glow: 0.3,
    inside: false,
    downSampleRatio: 1,
    patternScale: 8,
    patternOctaves: 3,
    patternLacunarity: 2,
    ringStride: 10,
    halftoneScale: 1,
    // Debug
    paused: false,
    wireframe: false,
    cursorCollider: true,
    debugColliders: false,
    debugColor: '#ff0000',
    cursorRadius: 0.12,
  },
  'Weather Any Storm': {
    // Scene - Camera
    orbitControls: false,
    // Scene - Background
    bgColor: '#000000',
    fogNear: 6,
    fogFar: 16,
    // Scene - Lighting
    ambientIntensity: 0.04,
    ambientColor: '#0a1525',
    keyIntensity: 0.08,
    keyColor: '#c8d8f0',
    keyPosX: -3,
    keyPosY: 5,
    keyPosZ: 4,
    keyShadow: true,
    fillIntensity: 0.03,
    fillColor: '#0d1a2e',
    fillPosX: 2,
    fillPosY: 1,
    fillPosZ: -1,
    // Scene - Lighting - Environment
    envIntensity: 0.25,
    envSkyColor: '#1a2030',
    envHorizonColor: '#101418',
    envGroundColor: '#050505',
    envSunIntensity: 0,
    // Moonlight
    moonColor: '#b8ccf0',
    moonPeakIntensity: 280,
    moonPosX: -3,
    moonPosY: 12,
    moonPosZ: 6,
    moonAngle: 24,
    cloudScale: 10.8,
    cloudDensity: -0.2,
    cloudContrast: 0.5,
    cloudSpeed: 2.2,
    cloudFloor: 0.15,
    // Flag - Orientation
    rotateX: -15,
    rotateY: 0,
    rotateZ: 15,
    posX: 0,
    posY: 0,
    // Flag - Cloth
    clothWidth: 1,
    clothHeight: 0.7,
    segmentsX: 30,
    segmentsY: 21,
    stiffness: 0.5,
    dampening: 0.98,
    // Flag - Cloth - Alpha
    alphaSeed: 57,
    alphaScale: 9.2,
    edgeFade: 0,
    holeAmount: 1,
    tatterEdge: 1,
    smoothEdges: true,
    // Flag - Material
    textureUrl: 'None',
    textureTile: false,
    textureScaleX: 0.7,
    textureScaleY: 0.7,
    textureRotation: 0,
    flagColor: '#ffffff',
    roughness: 0.9,
    metalness: 0,
    opacity: 1,
    // Flag - Material - Weave
    fabricAmount: 1,
    fabricThreads: 120,
    fabricDepth: 0.3,
    fabricShade: 0.32,
    fabricHem: 0.016,
    fabricWear: 0.35,
    sheen: 0.35,
    sheenRoughness: 0.4,
    sheenColor: '#9aa4c0',
    clearcoat: 1,
    clearcoatRoughness: 0.11,
    transmission: 0,
    ior: 1,
    materialThickness: 0,
    // Flag - Pole
    poleColor: '#a8a6a6',
    poleMetalness: 0.97,
    poleRoughness: 0.7,
    // Flag - Finial
    finialColor: '#e2ba42',
    finialMetalness: 0.8,
    finialRoughness: 0.2,
    // Flag - Rings
    ringColor: '#c9c7c7',
    ringMetalness: 1,
    ringRoughness: 0.14,
    // Wind
    wind: 10,
    windDirX: 1,
    windDirZ: -0.2,
    // Leaves
    leavesEnabled: true,
    leafMode: 'Billboard',
    leafType: 'Rain',
    leafCount: 1500,
    leafSize: 0.01,
    leafSpeed: 0.25,
    leafSpeedJitter: 0.15,
    leafTravel: 8,
    leafTumble: 0,
    leafCurvature: 0,
    leafAspect: 8,
    leafWindInfluence: 0.7,
    leafFlutter: 0.2,
    leafRoughness: 0.3,
    leafTranslucency: 0.2,
    leafColor1: '#8aaec8',
    leafColor2: '#aac4d8',
    leafColor3: '#6888a0',
    // Thunder & Lightning
    thunderEnabled: true,
    thunderLightColor: '#c8c4ff',
    thunderPeakIntensity: 58,
    thunderMinGap: 3,
    thunderMaxGap: 8,
    ambienceTrack: '',
    // Postprocessing - Bloom
    bloomEnabled: true,
    bloomThreshold: 1.6,
    bloomStrength: 0.5,
    bloomRadius: 0.6,
    bloomDownSampleRatio: 2,
    // Postprocessing - Outline
    enabled: false,
    mode: 'worley',
    strength: 7,
    thickness: 12,
    color: '#ffffff',
    hiddenColor: '#000000',
    hiddenStrength: 0,
    glow: 0.5,
    inside: false,
    downSampleRatio: 1,
    patternScale: 8,
    patternOctaves: 3,
    patternLacunarity: 2,
    ringStride: 10,
    halftoneScale: 1,
    // Debug
    paused: false,
    wireframe: false,
    cursorCollider: true,
    debugColliders: false,
    debugColor: '#ff0000',
    cursorRadius: 0.12,
  },
};

export default PRESETS;
