import {
  ASCII_BAKED,
  ASCII_BLEND_MODES,
  ASCII_COLOR_MODES,
  ASCII_DEFAULTS,
  ASCII_NOISE_MODES,
  ascii,
  updateAsciiUniforms,
} from '@modules/tsl';

import createPost from '../shared/createPost';
import { FITS } from '../shared/createSourcePlane';
import { choice, color, flag, num } from '../shared/specs';

const text = (label, value) => ({ default: value, label, type: 'string' });

const COLOR_MODE_LABELS = {
  ink: 'Ink on background',
  preserve: 'Preserve background',
  videoOnBackground: 'Picture on background',
  videoOnWhite: 'Picture on white',
};
const NOISE_MODE_LABELS = {
  additive: 'Additive',
  colorBurn: 'Color burn',
  colorDodge: 'Color dodge',
  linearBurn: 'Linear burn',
  multiply: 'Multiply',
  overlay: 'Overlay',
  screen: 'Screen',
  softLight: 'Soft light',
};

const d = ASCII_DEFAULTS;
const OPTIONS = {
  fit: choice('Fit', FITS, 'cover'),
  cellSize: num('Cell size (px)', d.cellSize, 5, 144, 1),
  charset: text('Glyphs (light → dark)', d.charset),
  variety: num('Glyph variety', d.variety, 0, 6, 0.1),
  glyphScale: num('Glyph size', d.glyphScale, 0.3, 4, 0.01),
  invert: flag('Invert', d.invert),
  colorMode: choice('Color mode', ASCII_COLOR_MODES, d.colorMode, {
    choiceLabels: COLOR_MODE_LABELS,
  }),
  ink: color('Ink', d.ink),
  background: color('Background', d.background),
  whiteCutoff: num('White cutoff', d.whiteCutoff, 0, 1, 0.01),
  asciiBlend: choice('ASCII ↔ picture', ASCII_BLEND_MODES, d.asciiBlend),
  asciiOpacity: num('ASCII opacity', d.asciiOpacity, 0, 1, 0.01),
  brightness: num('Brightness', d.brightness, -0.5, 0.5, 0.01),
  contrast: num('Contrast', d.contrast, 0, 3, 0.01),
  gamma: num('Gamma', d.gamma, 0.2, 3, 0.01),
  edges: flag('Edges', d.edges),
  edgeThreshold: num('Edge threshold', d.edgeThreshold, 0, 2, 0.01),
  edgeChars: text('Edge glyphs (- | / \\)', d.edgeChars),
  useMemory: flag('Memory', d.useMemory),
  morphRate: num('Change speed', d.morphRate, 0.075, 60, 0.05),
  glyphBlend: flag('Glyph cross-fade', d.glyphBlend),
  magnet: num('Magnetism', d.magnet, 0, 1.5, 0.01),
  sdfMorph: flag('Shape morph', d.sdfMorph),
  sdfThreshold: num('Stroke weight', d.sdfThreshold, 0.2, 0.8, 0.01),
  sdfAA: num('Edge softness', d.sdfAA, 0, 0.3, 0.005),
  colorVar: num('Mottling', d.colorVar, 0, 1, 0.01),
  noise: num('Grain', d.noise, 0, 1, 0.01),
  noiseScale: num('Grain size', d.noiseScale, 1, 24, 0.5),
  noiseMode: choice('Grain blend', ASCII_NOISE_MODES, d.noiseMode, {
    choiceLabels: NOISE_MODE_LABELS,
  }),
  bleed: num('Bleed', d.bleed, 0, 2, 0.01),
  bleedRadius: num('Bleed radius (px)', d.bleedRadius, 0, 80, 1),
  bleedBlur: num('Blur', d.bleedBlur, 0, 1, 0.01),
  bleedBlend: choice('Bleed ↔ ASCII', ASCII_BLEND_MODES, d.bleedBlend),
  bleedOpacity: num('Bleed opacity', d.bleedOpacity, 0, 1, 0.01),
};

const SHARED_LOOK = {
  asciiBlend: 'normal',
  asciiOpacity: 1,
  background: '#000000',
  bleed: 2,
  bleedBlend: 'multiply',
  bleedBlur: 1,
  bleedOpacity: 1,
  bleedRadius: 29,
  colorVar: 0,
  contrast: 1,
  edgeChars: '-|/\\',
  edgeThreshold: 0.3,
  edges: false,
  gamma: 1,
  glyphBlend: true,
  ink: '#b3ffb3',
  noise: 0.155,
  noiseMode: 'overlay',
  noiseScale: 5,
  sdfMorph: true,
  useMemory: true,
  whiteCutoff: 1,
};

// The reference demo's per-video looks; its grid is CSS px at DPR 2, which
// lands on the same row count here at 1080p output.
const PRESETS = {
  'Bad Apple': {
    ...SHARED_LOOK,
    brightness: 0,
    cellSize: 18,
    charset: ' ·•+✦★○◯●',
    colorMode: 'videoOnWhite',
    contrast: 2,
    glyphScale: 1.92,
    magnet: 1.5,
    morphRate: 17,
    sdfAA: 0.13,
    sdfThreshold: 0.43,
    variety: 6,
  },
  Flowers: {
    ...SHARED_LOOK,
    brightness: 0.08,
    cellSize: 20,
    charset: ' ·•+✦★○●',
    colorMode: 'videoOnWhite',
    glyphScale: 1.9,
    magnet: 0,
    morphRate: 2.5,
    noise: 0.505,
    noiseScale: 3,
    sdfAA: 0.05,
    sdfThreshold: 0.46,
    variety: 2.2,
  },
  Strawberries: {
    ...SHARED_LOOK,
    brightness: 0.08,
    cellSize: 18,
    charset: ' ·•+✦★○◯●',
    colorMode: 'preserve',
    glyphScale: 2.74,
    magnet: 1.5,
    morphRate: 17.4,
    sdfAA: 0.105,
    sdfThreshold: 0.5,
    variety: 0.4,
  },
  'Shade Blocks': {
    ...SHARED_LOOK,
    bleed: 0,
    bleedBlur: 0,
    brightness: 0,
    cellSize: 14,
    charset: ' ░▒▓█',
    colorMode: 'videoOnBackground',
    contrast: 1.3,
    glyphScale: 1.75,
    invert: true,
    magnet: 0.85,
    morphRate: 8,
    noise: 0.08,
    sdfMorph: false,
    variety: 0,
  },
  'Rising Bars': {
    ...SHARED_LOOK,
    brightness: 0.05,
    cellSize: 16,
    charset: ' ▁▂▃▄▅▆▇█',
    colorMode: 'videoOnWhite',
    glyphScale: 1.75,
    magnet: 0,
    morphRate: 6,
    noise: 0.1,
    sdfAA: 0.04,
    sdfThreshold: 0.5,
    variety: 0,
  },
  'Sideways Bars': {
    ...SHARED_LOOK,
    bleed: 0.8,
    brightness: 0,
    cellSize: 14,
    charset: ' ▏▎▍▌▋▊▉█',
    colorMode: 'videoOnBackground',
    glyphScale: 1.75,
    invert: true,
    magnet: 0.4,
    morphRate: 4,
    sdfAA: 0.04,
    sdfThreshold: 0.5,
    variety: 0,
  },
  'Classic ASCII': {
    ...SHARED_LOOK,
    bleed: 0.4,
    bleedBlend: 'screen',
    bleedBlur: 0.3,
    brightness: 0,
    cellSize: 12,
    charset: ' .:-=+*#%@',
    colorMode: 'ink',
    edges: true,
    edgeThreshold: 0.5,
    glyphScale: 1.3,
    invert: true,
    magnet: 1,
    morphRate: 10,
    noise: 0.08,
    noiseMode: 'additive',
    sdfAA: 0.08,
    sdfThreshold: 0.45,
    variety: 0.3,
  },
  Braille: {
    ...SHARED_LOOK,
    bleed: 0.5,
    bleedBlend: 'screen',
    brightness: 0,
    cellSize: 10,
    charset: ' ⠁⠃⠇⠏⠟⠿⡿⣿',
    colorMode: 'videoOnBackground',
    contrast: 1.4,
    glyphScale: 1.6,
    invert: true,
    magnet: 1,
    morphRate: 12,
    noise: 0.05,
    sdfAA: 0.06,
    sdfThreshold: 0.45,
    variety: 0.5,
  },
  'Katakana Rain': {
    ...SHARED_LOOK,
    background: '#000000',
    bleed: 1,
    bleedBlend: 'screen',
    bleedBlur: 0.5,
    bleedRadius: 18,
    brightness: 0,
    cellSize: 14,
    charset: ' ･ｰｼﾂｿﾝﾐﾊﾎﾑ',
    colorMode: 'ink',
    contrast: 1.5,
    glyphScale: 1.4,
    ink: '#5dff7a',
    invert: true,
    magnet: 0.3,
    morphRate: 3,
    noise: 0.1,
    noiseMode: 'additive',
    sdfAA: 0.07,
    sdfThreshold: 0.48,
    variety: 6,
  },
  Squares: {
    ...SHARED_LOOK,
    brightness: 0.05,
    cellSize: 18,
    charset: ' ·▫◽◻▪◼■',
    colorMode: 'videoOnWhite',
    glyphScale: 1.8,
    magnet: 0.6,
    morphRate: 5,
    sdfAA: 0.06,
    sdfThreshold: 0.47,
    variety: 1,
  },
};

export default {
  animated: (options) => options.useMemory,
  defaultPreset: 'Flowers',
  description:
    'Glyphs picked by brightness, each cell easing toward its target and morphing its shape into the next character, with Sobel edge glyphs, grain and an ink bleed.',
  engine: 'webgpu',
  id: 'ascii',
  inputs: ['still', 'video', 'live'],
  label: 'Morphing ASCII',
  options: OPTIONS,
  order: 45,
  presets: PRESETS,
  sections: [
    {
      keys: ['fit', 'cellSize', 'charset', 'variety', 'glyphScale', 'invert'],
      title: 'Grid & glyphs',
    },
    {
      keys: [
        'colorMode',
        'ink',
        'background',
        'whiteCutoff',
        'asciiBlend',
        'asciiOpacity',
      ],
      title: 'Color',
    },
    { keys: ['brightness', 'contrast', 'gamma'], title: 'Luminance' },
    { keys: ['edges', 'edgeThreshold', 'edgeChars'], title: 'Edges' },
    {
      keys: [
        'useMemory',
        'morphRate',
        'glyphBlend',
        'magnet',
        'sdfMorph',
        'sdfThreshold',
        'sdfAA',
      ],
      title: 'Memory & morph',
    },
    { keys: ['colorVar', 'noise', 'noiseScale', 'noiseMode'], title: 'Grain' },
    {
      keys: ['bleed', 'bleedRadius', 'bleedBlur', 'bleedBlend', 'bleedOpacity'],
      title: 'Ink bleed',
    },
  ],

  create(stage) {
    return createPost(stage, {
      baked: ASCII_BAKED,
      build({ options, plane }) {
        const effect = ascii(plane.scenePass.getTextureNode(), {
          ...options,
          initFromSource: true,
        });
        return {
          colorNode: effect.colorNode,
          dispose: () => effect.dispose(),
          prepare: (renderer, dt) => effect.setDelta(dt),
          update: (values) => updateAsciiUniforms(effect.uniforms, values),
        };
      },
    });
  },
};
