export const DEFAULT_PRESET = 'Corridor';

const BASE = {
  cameraMode: 'fixed',
  zone: 'Corridor',
  walkEnabled: true,
  journey: true,
  autopilot: false,
  walkSpeed: 1.5,
  sprintMultiplier: 2.4,
  turboMultiplier: 8,
  eyeHeight: 1.65,
  bobAmount: 0.045,
  bobSway: 0.03,
  bobRoll: 0.008,
  bobRate: 1.15,
  bobSettle: 6,
  walkerRadius: 0.4,
  lookSensitivity: 0.0022,

  hallLength: 900,
  descentLength: 1400,
  returnLength: 400,
  roomSize: 620,
  roomHeight: 155,
  floorExits: 6,
  floorExitVariance: 0.8,
  floorSkirt: 18,
  floorSpokeLength: 30,

  segmentLength: 24,
  corridorWidth: 5,
  corridorHeight: 8,
  archRatio: 0.3,
  revealDepth: 0.4,

  branchChance: 0.45,
  branchWidthScale: 0.7,
  branchLength: 26,
  deadEndLength: 9,
  branchRoomWidth: 14,
  branchRoomDepth: 12,
  branchRoomHeight: 9,
  bulkheadThickness: 0.5,
  driftAmount: 0.25,
  driftWavelength: 260,
  stepAmount: 0.2,
  stepRunLength: 5,

  mouthChanceNone: 0.55,
  mouthChanceOne: 0.33,
  mouthWidth: 4.5,
  mouthHeight: 7,
  mouthSpread: 0.9,
  mouthDepth: 12,

  flareChance: 0.35,
  flareLandingChance: 0.25,
  flareColor: '#ff3a1e',
  flareIntensity: 14,
  flareGlow: 3,
  flareRange: 16,
  flareRadius: 0.035,
  flareLength: 0.34,
  flareFlicker: 0.5,
  flareHeight: 0.2,
  flareScatter: 1,
  flareShadows: false,

  voidDiameterFt: 200,
  grownDiameterFt: 520,
  growthRun: 2400,
  risePerTurn: 90,
  stairWidth: 6,
  wallGap: 2,
  riser: 0.176,
  landingSpacing: 90,
  landingArc: 0.09,
  landingOvershoot: 0,
  slabThickness: 1.2,
  clockwise: true,

  radiusDriftAmount: 0,
  radiusDriftWavelength: 450,
  axisDriftAmount: 0,
  axisDriftWavelength: 600,
  overlapAmount: 0,
  overlapWavelength: 800,
  landingDriftAmount: 0,
  landingDriftPeriod: 6,

  beamEnabled: true,
  beamAngle: 26,
  beamPenumbra: 0.55,
  beamIntensity: 600,
  beamRange: 55,
  beamDecay: 2,
  beamColor: '#cdd3dd',
  beamForward: 0.35,
  beamDrop: -0.28,
  beamLag: 7,
  beamScatter: 1.4,
  beamFalloff: 0.004,
  beamShadows: true,
  beamShadowSize: 1024,
  beamLensGain: 1,
  beamLensLift: 0,

  fogEnabled: true,
  fogDensity: 0.045,
  fogNoiseAmount: 0.5,
  fogNoiseScale: 0.05,
  fogSteps: 24,
  fogMaxDistance: 160,
  fogResolutionScale: 0.5,
  bloomEnabled: false,
  bloomStrength: 0.35,
  bloomThreshold: 0.5,

  streamAhead: 220,
  streamBehind: 80,
  wallRebuildSlack: 40,

  baseColor: '#6b6a68',
  mottleAmount: 0.16,
  mottleScale: 0.28,
  inkAmount: 0.16,
  inkScale: 0.05,
  inkThreshold: 0.62,
  inkWarp: 4,
  inkFlow: 0.006,
  roughBase: 0.95,
  roughVary: 0.08,

  lightFillIntensity: 0,
};

// The baseline is a plausible spiral with every drift at zero. Each preset
// below turns on exactly one mechanism, so it can be judged on its own before
// they are combined — a stack of four simultaneous wrongnesses reads as noise
// and teaches nothing about which one is doing the work.
export const PRESETS = {
  Corridor: { ...BASE, journey: false },
  // The whole walk, end to end: hallway, great room, descent, the floor at the
  // bottom and its spokes.
  Journey: { ...BASE },
  'Great Room': { ...BASE, journey: false, zone: 'Great Room' },
  'Shaft Floor': { ...BASE, journey: false, zone: 'Shaft Floor' },
  Shaft: { ...BASE, journey: false, zone: 'Shaft' },
  'Shaft: Growth': { ...BASE, zone: 'Shaft', growthRun: 600 },
  'Shaft: Breathing': {
    ...BASE,
    journey: false,
    zone: 'Shaft',
    radiusDriftAmount: 0.35,
    radiusDriftWavelength: 380,
  },
  'Shaft: Off Axis': {
    ...BASE,
    journey: false,
    zone: 'Shaft',
    axisDriftAmount: 16,
    axisDriftWavelength: 520,
  },
  'Shaft: Escher': {
    ...BASE,
    journey: false,
    zone: 'Shaft',
    overlapAmount: 6,
    overlapWavelength: 640,
  },
  'Shaft: Uncountable': {
    ...BASE,
    journey: false,
    zone: 'Shaft',
    landingDriftAmount: 0.55,
    landingDriftPeriod: 5.4,
  },
  'Shaft: Everything': {
    ...BASE,
    journey: false,
    zone: 'Shaft',
    growthRun: 1200,
    radiusDriftAmount: 0.3,
    axisDriftAmount: 14,
    overlapAmount: 5,
    landingDriftAmount: 0.5,
  },
  // The shaft is where a lamp that reaches nowhere stops being atmosphere and
  // starts costing information: at 200ft across the far side is beyond the
  // beam entirely. Kept as a preset so the trade is visible rather than
  // discovered later.
  'Shaft: Lamp Only': {
    ...BASE,
    journey: false,
    zone: 'Shaft',
    fogDensity: 0.03,
    beamRange: 80,
    beamIntensity: 900,
  },
  // Blockout rig: flat light, no volumetric, free camera. For checking that
  // pieces meet, not for judging the look.
  Blockout: {
    ...BASE,
    cameraMode: 'orbit',
    walkEnabled: false,
    beamEnabled: false,
    fogEnabled: false,
    lightFillIntensity: 1.2,
  },
  // Every branch and every landing lit, for judging how a flare reads and how
  // far its spill carries. Not a look — a tuning rig.
  'Flare Rig': {
    ...BASE,
    journey: false,
    branchChance: 1,
    flareChance: 1,
    flareLandingChance: 1,
    mouthChanceNone: 0.2,
    mouthChanceOne: 0.4,
  },
  // Nothing to look at but the architecture: no branches, no mouths, no
  // flares. What the corridor and the shaft are before they are dressed.
  Bare: {
    ...BASE,
    branchChance: 0,
    driftAmount: 0,
    stepAmount: 0,
    mouthChanceNone: 1,
    mouthChanceOne: 0,
    flareChance: 0,
    flareLandingChance: 0,
  },
  'Seam Check': {
    ...BASE,
    journey: false,
    cameraMode: 'orbit',
    walkEnabled: false,
    beamEnabled: false,
    fogEnabled: false,
    lightFillIntensity: 1.2,
    autopilot: true,
    zone: 'Shaft',
    branchChance: 0,
    mouthChanceNone: 1,
    mouthChanceOne: 0,
    flareChance: 0,
    flareLandingChance: 0,
  },
};

export function getPresetControls({ presetSnapshot }) {
  return { ...presetSnapshot };
}
