export const DEFAULT_PRESET = 'Loop';

const BASE = {
  cameraMode: 'fixed',
  startZone: 'Living Room',
  directed: true,
  walkEnabled: true,
  walkSpeed: 1.4,
  runSpeed: 4.2,
  stairSpeed: 3,
  sprintMultiplier: 2.4,
  eyeHeight: 1.65,
  walkerRadius: 0.35,
  bobAmount: 0.04,
  bobSway: 0.025,
  bobRoll: 0.007,
  bobRate: 1.15,
  bobSettle: 6,
  handheld: 1,
  lookLag: 3.5,
  lookSensitivity: 0.0022,

  restSeconds: 3,
  sweepSeconds: 14,
  runAfter: 0.4,
  thresholdSlow: 24,
  thresholdSeconds: 6,
  edgeSeconds: 6,
  glanceEvery: 16,
  evaluateSeconds: 12,
  lightDistance: 110,
  floorChoice: -1,

  hallLength: 168,
  returnLength: 144,
  descentLength: 260,
  roomSize: 220,
  roomHeight: 155,
  floorExits: 6,
  floorExitVariance: 0.9,
  floorSkirt: 15,
  spokeLength: 3,
  mountMargin: 90,

  livingDepth: 6.4,
  livingWidth: 4.6,
  livingHeight: 2.6,
  wallThickness: 0.14,
  livingDoorZ: 0.9,
  lampColor: '#ffb877',
  lampIntensity: 9,
  tvColor: '#9fb8ff',
  tvIntensity: 2.5,
  tvScale: 1,
  beaconIntensity: 40,
  beaconGlow: 1.6,

  segmentLength: 24,
  startWidth: 1.0,
  startHeight: 2.3,
  corridorWidth: 4.2,
  corridorHeight: 7,
  hallGrowthRun: 90,
  revealDepth: 0.6,

  branchChance: 0.5,
  branchWidthScale: 0.62,
  branchLength: 28,
  deadEndLength: 8,
  branchRoomWidth: 12,
  branchRoomDepth: 10,
  branchRoomHeight: 8,
  driftAmount: 0.3,
  driftWavelength: 220,
  stepAmount: 0.25,
  stepRunLength: 4,

  voidDiameterFt: 200,
  grownDiameterFt: 520,
  shaftGrowthRun: 240,
  stairSlope: 32,
  stairWidth: 6,
  wallGap: -0.05,
  riser: 0.176,
  landingSpacing: 70,
  landingArc: 0.09,
  landingOvershoot: 0,
  slabThickness: 1.2,
  clockwise: true,
  shaftFill: 0.03,
  shaftFillColor: '#6d7d96',

  radiusDriftAmount: 0.22,
  radiusDriftWavelength: 300,
  axisDriftAmount: 10,
  axisDriftWavelength: 320,
  overlapAmount: 40,
  overlapWavelength: 520,
  landingDriftAmount: 0.45,
  landingDriftPeriod: 5.4,

  mouthChanceNone: 0.45,
  mouthChanceOne: 0.35,
  mouthWidth: 4.5,
  mouthHeight: 6.5,
  mouthSpread: 0.9,
  mouthDepth: 14,

  flareChance: 0.35,
  flareLandingChance: 0.25,
  flareColor: '#ff3a1e',
  flareIntensity: 14,
  flareGlow: 3,
  flareRange: 16,
  flareRadius: 0.035,
  flareLength: 0.34,
  flareFlicker: 0.5,
  flareHeight: 0.2,
  flareScatter: 1,
  flareShadows: false,

  beamEnabled: true,
  beamAngle: 26,
  beamPenumbra: 0.55,
  beamIntensity: 600,
  beamRange: 55,
  beamDecay: 2,
  beamColor: '#cdd3dd',
  beamForward: 0.35,
  beamDrop: -0.28,
  beamLag: 7,
  beamScatter: 1.4,
  beamFalloff: 0.004,
  beamShadows: true,
  beamShadowSize: 1024,
  beamLensGain: 1,
  beamLensLift: 0,

  fogEnabled: true,
  fogDensity: 0.045,
  fogNoiseAmount: 0.5,
  fogNoiseScale: 0.05,
  fogSteps: 24,
  fogMaxDistance: 160,
  fogResolutionScale: 0.5,
  airGlow: 0.006,
  airGlowColor: '#5b6b85',

  postEnabled: true,
  exposure: 1.25,
  bloomEnabled: true,
  bloomStrength: 0.28,
  bloomThreshold: 0.75,
  bloomRadius: 0.6,
  vignetteEnabled: true,
  vignetteAmount: 0.45,
  vignetteSoftness: 0.55,
  grainEnabled: true,
  grainAmount: 0.045,

  surfaceTint: '#6f6c68',
  floorTint: '#5a5754',
  surfaceScale: 0.45,
  surfaceDetile: 0.35,
  normalStrength: 0.8,
  roughnessScale: 1,
  livingTint: '#d8cfc1',
  livingFloorTint: '#a5825a',
  livingScale: 0.9,

  streamAhead: 200,
  streamBehind: 80,
  wallRebuildSlack: 40,

  lightFillIntensity: 0,
};

// The piece is the loop. The rest are ways of standing in one part of it.
export const PRESETS = {
  Loop: { ...BASE },
  // Lengths closer to the source: the hallway takes its five and a half
  // minutes and the descent takes the rest of the evening.
  'Five and a Half Minutes': {
    ...BASE,
    hallLength: 480,
    returnLength: 360,
    descentLength: 1400,
    shaftGrowthRun: 1300,
    runAfter: 0.55,
    glanceEvery: 24,
  },
  'Living Room': { ...BASE, startZone: 'Living Room' },
  Hallway: { ...BASE, startZone: 'Hallway' },
  'Great Room': { ...BASE, startZone: 'Great Room' },
  Staircase: { ...BASE, startZone: 'Staircase' },
  Floor: { ...BASE, startZone: 'Floor' },
  'Way Back': { ...BASE, startZone: 'Way Back' },
  // Every wrongness at once, hard, for judging the stair on its own.
  'Staircase: Escher': {
    ...BASE,
    startZone: 'Staircase',
    radiusDriftAmount: 0.35,
    axisDriftAmount: 18,
    overlapAmount: 90,
    landingDriftAmount: 0.6,
    stairSpeed: 3.2,
  },
  // Keys and drag-look drive the walker.
  'Debug Walk': { ...BASE, directed: false },
  // Blockout rig: flat light, no volumetric, free camera. For checking that
  // pieces meet, not for judging the look.
  Blockout: {
    ...BASE,
    startZone: 'Great Room',
    cameraMode: 'orbit',
    directed: false,
    walkEnabled: false,
    beamEnabled: false,
    fogEnabled: false,
    postEnabled: false,
    lightFillIntensity: 1.2,
    mountMargin: 300,
  },
  'Seam Check': {
    ...BASE,
    startZone: 'Staircase',
    cameraMode: 'orbit',
    directed: false,
    walkEnabled: false,
    beamEnabled: false,
    fogEnabled: false,
    postEnabled: false,
    lightFillIntensity: 1.2,
    branchChance: 0,
    mouthChanceNone: 1,
    mouthChanceOne: 0,
    flareChance: 0,
    flareLandingChance: 0,
    mountMargin: 300,
  },
};

export function getPresetControls({ presetSnapshot }) {
  return { ...presetSnapshot };
}
