const DEFAULT_PRESET = {
  frame: '1',
  backgroundColor: '#f2f2f2',
  colorRangeStart: '#FFFFFF',
  colorRangeEnd: '#D8D8D8',
  rotate: true,
  dataScale: 0.1,
  dataPosition: { x: 0, y: 1.1, z: 0.08 },
  frameVisible: true,
  framePosition: { x: 0, y: 1.1, z: 0 },
  frameScale: 1.1,
  frameColor: '#ffffff',
  frameRoughness: 0.5,
  frameWatercolor: false,
  squareRoughness: 0.8,
  squareMetalness: 0,
  squareFlatShading: false,
  squareWatercolor: false,
  animationMode: 'none',
  layerFadeLoopSeconds: 12,
  layerFadeStartA: '#ff0000',
  layerFadeStartB: '#ffffff',
  layerFadeStartC: '#000000',
  layerFadeEndA: '#000000',
  layerFadeEndB: '#2f2f2f',
  layerFadeEndC: '#ff0000',
  morseText: 'SOS',
  morseUnitSeconds: 0.2,
  morsePauseUnits: 9,
  morseColor: '#ff2020',
  morseEmissiveIntensity: 2,
  morseSeed: 7,
};

export default DEFAULT_PRESET;
