/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { useEffect, useMemo } from 'react';

import { createInstances, useGLTF } from '@react-three/drei';

import { modelFile } from '@utils/appUtils';
import bakeInstancedGeometry from '@utils/instancedGeometry';

const MC_CUP_MODEL_PATH = '/mcCup.glb';
const MC_CUP_MODEL_FILE = modelFile(MC_CUP_MODEL_PATH);
const MC_CUP_ROTATION = [-Math.PI / 2, 0, 0];
const MC_CUP_Y_OFFSET = 263.293 * 0.01;
const MC_CUP_TRANSFORM_CHAIN = [
  { position: [0, MC_CUP_Y_OFFSET, 0], rotation: MC_CUP_ROTATION },
];

const [McCupInstancesRoot, McCupInstanceRoot] = createInstances();

function useMcCupModel() {
  const { nodes, materials } = useGLTF(MC_CUP_MODEL_FILE);

  return {
    baseGeometry: nodes.Cup.geometry,
    sourceMaterial: materials.Material,
  };
}

function useMcCupGeometry(baseGeometry) {
  const geometry = useMemo(
    () => bakeInstancedGeometry(baseGeometry, MC_CUP_TRANSFORM_CHAIN),
    [baseGeometry]
  );

  useEffect(() => {
    return () => {
      geometry.dispose?.();
    };
  }, [geometry]);

  return geometry;
}

export function McCupInstances({ children, material, ...props }) {
  const { baseGeometry, sourceMaterial } = useMcCupModel();
  const geometry = useMcCupGeometry(baseGeometry);
  const instanceMaterial = useMemo(
    () => material ?? sourceMaterial.clone(),
    [material, sourceMaterial]
  );

  useEffect(() => {
    if (material) {
      return undefined;
    }

    return () => {
      instanceMaterial.dispose?.();
    };
  }, [instanceMaterial, material]);

  return (
    <McCupInstancesRoot
      geometry={geometry}
      material={instanceMaterial}
      {...props}
    >
      {children}
    </McCupInstancesRoot>
  );
}

export function McCupInstance(props) {
  return <McCupInstanceRoot {...props} />;
}

export function McCup(props) {
  const { baseGeometry, sourceMaterial } = useMcCupModel();
  const geometry = useMcCupGeometry(baseGeometry);

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={geometry}
        material={sourceMaterial}
      />
    </group>
  );
}

useGLTF.preload(MC_CUP_MODEL_FILE);
