/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { useEffect, useMemo } from 'react';

import { createInstances, useGLTF } from '@react-three/drei';

import { modelFile } from '../../../utils/appUtils';
import bakeInstancedGeometry from '../../../utils/instancedGeometry';

const MC_CUP_MODEL_PATH = '/mcCup.glb';
const MC_CUP_ROTATION = [-Math.PI / 2, 0, 0];
const MC_CUP_TRANSFORM_CHAIN = [
  { scale: 0.01 },
  { position: [0, 263.293, 0], rotation: MC_CUP_ROTATION, scale: 100 },
];

const [McCupInstancesRoot, McCupInstanceRoot] = createInstances();

export function McCupInstances({ children, material, ...props }) {
  const { nodes, materials } = useGLTF(modelFile(MC_CUP_MODEL_PATH));
  const baseGeometry = nodes.Cup.geometry;
  const sourceMaterial = materials.Material;
  const geometry = useMemo(
    () => bakeInstancedGeometry(baseGeometry, MC_CUP_TRANSFORM_CHAIN),
    [baseGeometry]
  );
  const instanceMaterial = useMemo(
    () => material ?? sourceMaterial.clone(),
    [material, sourceMaterial]
  );

  useEffect(() => {
    return () => {
      geometry.dispose?.();
    };
  }, [geometry]);

  useEffect(() => {
    if (material) {
      return undefined;
    }

    return () => {
      instanceMaterial.dispose?.();
    };
  }, [instanceMaterial, material]);

  return (
    <McCupInstancesRoot
      geometry={geometry}
      material={instanceMaterial}
      {...props}
    >
      {children}
    </McCupInstancesRoot>
  );
}

export function McCupInstance(props) {
  return <McCupInstanceRoot {...props} />;
}

export default function McCup(props) {
  const { nodes, materials } = useGLTF(modelFile(MC_CUP_MODEL_PATH));
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cup.geometry}
          material={materials.Material}
          position={[0, 263.293, 0]}
          rotation={MC_CUP_ROTATION}
          scale={100}
        />
      </group>
    </group>
  );
}

useGLTF.preload(modelFile(MC_CUP_MODEL_PATH));
