/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React from 'react';

import { useGLTF } from '@react-three/drei';

import { modelFile } from '../../../utils/appUtils';

export default function McCup(props) {
  const { nodes, materials } = useGLTF(modelFile('/mcCup.glb'));
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cup.geometry}
          material={materials.Material}
          position={[0, 263.293, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
      </group>
    </group>
  );
}

useGLTF.preload(modelFile('/mcCup.glb'));
