export const MODE = {
  renderMode: 'fibers',
  fiberMotion: 'noise',
  timeScale: 1,
};

export const QUALITY = {
  renderScale: 0.85,
  samples: 40,
  fiberBlend: 'blended',
};

export const FIELD = {
  seed: 7,
  threadCount: 320,
  segments: 28,
  fieldLength: 0.9,
  fieldWidth: 0.5,
  fieldDepth: 0.008,
  threadWeave: 0.0004,
  threadWeaveFrequency: 160,
};

export const WAVE = {
  waveMode: 'wave',
  waveAmplitude: 0.06,
  waveFrequency: 25,
  waveSpeed: 0.8,
  clump: 0.55,
  clumpSpacing: 0.012,
  phaseSpread: 0.3,
  crestThreshold: 0.15,
  frizz: 0.0006,
  frizzScale: 12,
  flyawayShare: 0.03,
  waveMeander: 1.2,
  waveMeanderScale: 6,
  waveLens: 0.5,
  lensX: 0,
  lensZ: 0,
  ringSpacing: 0.06,
  ringLobes: 5,
  ringDamp: 4,
  loopSpeed: 0.3,
  wavePull: 0.02,
  substeps: 1,
  constraintIterations: 3,
  gravity: 2,
  damping: 0.97,
  stiffness: 1,
  shapeRetention: 0.15,
  windStrength: 3,
  windScale: 0.6,
};

export const LOOK = {
  backgroundColor: '#050507',
  bandColorA: '#1c6f8c',
  bandColorB: '#2f3a9e',
  bandColorC: '#b072c8',
  bandColorD: '#f0e2c8',
  colorDrift: 9,
  fiberWidth: 0.0004,
  minPixels: 1,
  edgeSoftness: 0.6,
  wander: 0.0003,
  wanderFrequency: 7,
  iridescence: 0.6,
  iridescenceFrequency: 1.5,
  specular: 1.1,
  shininess: 90,
  secondarySpecular: 0.3,
  diffuse: 0.7,
  ambient: 0.05,
  backlight: 0.7,
  occlusion: 0.7,
  occlusionReach: 0.85,
  crestShadow: 0.4,
  shadowStrength: 60,
  shadowStep: 0.012,
  primaryShift: 0.08,
  secondaryShift: -0.12,
  transmission: 1.2,
  transmissionFocus: 14,
  glint: 0.45,
  glintScale: 9,
  plyFrequency: 5,
  plyDepth: 0.35,
  plyGloss: 0.7,
  depthFade: 0.15,
  lightColor: '#fff3e6',
  lightIntensity: 1.7,
  lightAzimuth: 35,
  lightElevation: 35,
};

export const PLATE = {
  plateTint: '#ffffff',
  plateBrightness: 1,
  plateThreadAmplitude: 0.2,
  plateThreadFrequency: 12,
  plateThreadEdge: 0.009,
  plateThreadSpacing: 250,
  plateThreadNoise: 2.5,
  plateRingRadius: 0.37,
  plateRingNoise: 0.12,
  plateRingGlow: 0.0008,
  plateRingLoopSpeed: 0.3,
  plateRingLobes: 5,
};

export const SCENE_DEFAULTS = {
  ...MODE,
  ...QUALITY,
  ...FIELD,
  ...WAVE,
  ...LOOK,
  ...PLATE,
};
