export const DEFAULT_PRESET = 'Convenience Store';
export const SOURCE_STARFIELD_PRESET = 'Source Starfield';

const SOURCE_STARFIELD_SCENE_PRESET = {
  presentationMode: 'backgroundField',
  blackHoleMass: 0.4,
  diskInnerRadius: 4.1,
  diskOuterRadius: 14.5,
  diskTemperature: 49.78,
  temperatureFalloff: 5.22,
  diskBrightness: 5,
  diskRotationSpeed: -8.7,
  turbulenceScale: 1.81,
  turbulenceStretch: 0.75,
  turbulenceSharpness: 7.4,
  turbulenceCycleTime: 5,
  turbulenceLacunarity: 3,
  turbulencePersistence: 0.8,
  diskEdgeSoftnessInner: 0.18,
  diskEdgeSoftnessOuter: 0.5,
  gravitationalLensing: 2.4,
  dopplerStrength: 1,
  stepSize: 1,
  blackHolePosition: { x: 0, y: 0, z: 0 },
  blackHoleRotation: { x: 0, y: 0, z: 0 },
  blackHoleScale: { x: 1, y: 1, z: 1 },
  starsEnabled: true,
  starBackgroundColor: '#000000',
  starDensity: 0.1,
  starSize: 1.2,
  starBrightness: 0.1,
  nebulaEnabled: true,
  nebula1Scale: 2,
  nebula1Density: 0.5,
  nebula1Brightness: 0.01,
  nebula1Color: '#071f44',
  nebula2Scale: 5.5,
  nebula2Density: 0.05,
  nebula2Brightness: 0.21,
  nebula2Color: '#010615',
  bloomEnabled: true,
  bloomStrength: 0.68,
  bloomRadius: 0.2,
  bloomThreshold: 0.4,
  bloomDownSampleRatio: 2,
  turbulenceBrightness: -0.05,
  diskDensity: 1,
  qualityPreset: 'medium',
  diskInnerThickness: 0.7,
  diskOuterThickness: 0.5,
  ringEnabled: true,
  ringScale: 0.83,
  ringContrast: 0.95,
  ringBrightness: 0.4,
  ringSharpness: 10,
  ringTwist: 10.3,
  noiseAnimFrequency: 4.2,
  noiseAnimAmplitude: 2,
  diskRadialFalloff: 2,
  diskOpacityFalloff: 0.5,
  adaptiveMinStep: 0.15,
  stepJitter: 0,
  diskInnerColor: '#ffffff',
  diskMidColor: '#ffffff',
  diskOuterColor: '#ffffff',
  diskTintStrength: 1,
  nebulaBrightness: 0.07,
  nebulaColor1: '#113844',
  nebulaColor2: '#1b214a',
  nebulaScale1: 3,
  nebulaScale2: 3.5,
  nebulaBlend: 0.55,
  nebulaSpeed: 0.065,
  nebulaDensity: 0.35,
  diskDifferentialRotation: 1,
  noiseEvolutionSpeed: 5,
  raySteps: 68,
  nebulaScale: 3,
  nebulaDetailScale: 2.4,
  nebulaOffsetX: 0,
  nebulaOffsetY: 0,
  nebulaOffsetZ: 0,
  diskTurbulence: 0.9,
  turbulencePrimaryScale: 0.65,
  turbulenceSecondaryScale: 1.3,
  turbulenceSecondaryStrength: 0.15,
  turbulenceOffset: 0.1,
  ringNoiseEnabled: true,
  ringNoiseScale: 4.5,
  ringNoiseAmplitude: 1.45,
  ringNoiseSharpness: 4,
  ringNoiseOffset: -0.2,
  ringNoiseOctaves: 2,
  ringNoiseLacunarity: 1.9,
  ringNoisePersistence: 0.45,
  maxRayDistance: 500,
  diskThickness: 1.3,
  heightDensityFalloff: 5,
  rayJitter: 1,
  temporalAA: false,
  temporalFrames: 16,
  cameraFov: 60,
  cameraNear: 0.1,
  cameraFar: 1000,
  cameraX: 0,
  cameraY: -5,
  cameraZ: 20,
  cameraTargetX: 0,
  cameraTargetY: 0,
  cameraTargetZ: 0,
  cameraMinDistance: 5,
  cameraMaxDistance: 50,
  cameraRotateSpeed: -0.5,
  cameraDampingFactor: 0.05,
  storeScale: 320,
  storePosition: { x: 0, y: 0, z: 0 },
  storeRotation: { x: 0, y: 0, z: 0 },
};

const CONVENIENCE_STORE_SCENE_PRESET = {
  ...SOURCE_STARFIELD_SCENE_PRESET,
  presentationMode: 'storeWarp',
  starsEnabled: false,
  starBackgroundColor: '#05070b',
  nebulaEnabled: false,
  bloomStrength: 0.42,
  bloomRadius: 0.14,
  bloomThreshold: 0.5,
  cameraFar: 5000,
  cameraX: 0,
  cameraY: -5,
  cameraZ: 20,
  cameraTargetX: 0,
  cameraTargetY: 0,
  cameraTargetZ: 0,
  cameraMinDistance: 5,
  cameraMaxDistance: 160,
};

export const PRESETS = {
  [DEFAULT_PRESET]: CONVENIENCE_STORE_SCENE_PRESET,
  [SOURCE_STARFIELD_PRESET]: SOURCE_STARFIELD_SCENE_PRESET,
};
