import { DEFAULT_AISLE9_CAMERA_SPLINE } from '../../../../../../presets/spline/aisle9CameraSplines';
import CENTER_STORE_REF_POSITION from '../../../../../elements/sevenEleven/sevenElevenAnchors';

export const DEFAULT_PRESET = 'Store';
export const GUIDED_TOUR_PRESET = 'Guided Tour';
export const SURVEILLANCE_PRESET = 'Surveillance';
export const SURVEILLANCE_2_PRESET = 'Surveillance 2';
export const SURVEILLANCE_3_PRESET = 'Surveillance 3';
export const SPACE_PRESET = 'Space';
export const SPACE_2_PRESET = 'Space 2';

function cloneCenterStoreRef() {
  return {
    x: CENTER_STORE_REF_POSITION.x,
    y: CENTER_STORE_REF_POSITION.y,
    z: CENTER_STORE_REF_POSITION.z,
  };
}

// Up to three bodies orbiting the hole (sim-space units, same scale as the
// disk radii). They are intersected inside the bent ray loop, so they get
// gravitationally lensed as they pass behind the singularity.
const BLACK_HOLE_BODIES_OFF = {
  body1Enabled: false,
  body1Color: '#9ec5ff',
  body1Size: 2.3,
  body1OrbitRadius: 19,
  body1OrbitSpeed: 0.6,
  body1OrbitPhase: 0,
  body1Height: 0,
  body2Enabled: false,
  body2Color: '#ffd27f',
  body2Size: 1.8,
  body2OrbitRadius: 23.5,
  body2OrbitSpeed: -0.42,
  body2OrbitPhase: 120,
  body2Height: 1.5,
  body3Enabled: false,
  body3Color: '#ff8fa3',
  body3Size: 4,
  body3OrbitRadius: 21,
  body3OrbitSpeed: 0.28,
  body3OrbitPhase: 240,
  body3Height: -2,
};

const DEFAULT_CAMERA_SPLINE_SETTINGS = {
  cameraMode: 'orbit',
  cameraAutoRotate: false,
  cameraMobileFov: 85,
  cameraMobilePosition: { x: 0, y: -5, z: 20 },
  cameraMobileTarget: { x: 0, y: 0, z: 0 },
  fixedCameraPosition: { x: 3, y: 2.5, z: -4 },
  fixedCameraMobilePosition: { x: 3, y: 2.5, z: -4 },
  fixedCameraTarget: cloneCenterStoreRef(),
  fixedCameraMobileTarget: cloneCenterStoreRef(),
  cameraSplinePreset: DEFAULT_AISLE9_CAMERA_SPLINE,
  cameraSplinePosition: { x: 0, y: 0, z: 0 },
  cameraSplineScale: { x: 1, y: 1, z: 1 },
  cameraSplineDuration: 38,
  cameraSplineTension: 0.45,
  cameraSplineLookAt: cloneCenterStoreRef(),
};

const SECURITY_CAM_DEFAULTS = {
  surveillanceFxEnabled: false,
  surveillanceOverlayEnabled: false,
  surveillanceCameraLabel: 'CAM 01',
  surveillanceDesaturation: 0.42,
  surveillanceNoiseAmount: 0.028,
  surveillanceScanlineStrength: 0.22,
  surveillanceScanlineDensity: 940,
  surveillanceVignette: 0.36,
  surveillanceRollingBandStrength: 0.18,
  surveillanceHudOpacity: 0.42,
};

const SECURITY_CAM_SURVEILLANCE = {
  ...SECURITY_CAM_DEFAULTS,
  surveillanceFxEnabled: true,
  surveillanceOverlayEnabled: true,
  surveillanceDesaturation: 0.5,
  surveillanceNoiseAmount: 0.042,
  surveillanceScanlineStrength: 0.34,
  surveillanceScanlineDensity: 980,
  surveillanceVignette: 0.44,
  surveillanceRollingBandStrength: 0.26,
  surveillanceHudOpacity: 0.56,
};

const SPACE_SCENE_PRESET = {
  ...DEFAULT_CAMERA_SPLINE_SETTINGS,
  ...BLACK_HOLE_BODIES_OFF,
  ...SECURITY_CAM_DEFAULTS,
  presentationMode: 'backgroundField',
  blackHoleMass: 0.4,
  diskInnerRadius: 4.1,
  diskOuterRadius: 14.5,
  diskTemperature: 49.78,
  temperatureFalloff: 5.22,
  diskBrightness: 5,
  diskOpacity: 1,
  diskOpacityFloor: 0,
  diskRotationSpeed: -8.7,
  turbulenceScale: 1.81,
  turbulenceStretch: 0.75,
  turbulenceSharpness: 7.4,
  turbulenceCycleTime: 5,
  turbulenceLacunarity: 3,
  turbulencePersistence: 0.8,
  diskEdgeSoftnessInner: 0.18,
  diskEdgeSoftnessOuter: 0.5,
  gravitationalLensing: 2.4,
  dopplerStrength: 1,
  stepSize: 1,
  blackHolePosition: { x: 0, y: 0, z: 0 },
  blackHoleRotation: { x: 0, y: 0, z: 0 },
  blackHoleScale: { x: 1, y: 1, z: 1 },
  starsEnabled: true,
  starBackgroundColor: '#000000',
  starDensity: 0.1,
  starSize: 1.2,
  starBrightness: 0.1,
  nebulaEnabled: true,
  nebula1Scale: 2,
  nebula1Density: 0.5,
  nebula1Brightness: 0.01,
  nebula1Color: '#071f44',
  nebula2Scale: 5.5,
  nebula2Density: 0.05,
  nebula2Brightness: 0.21,
  nebula2Color: '#010615',
  bloomEnabled: true,
  bloomStrength: 0.68,
  bloomRadius: 0.2,
  bloomThreshold: 0.4,
  bloomDownSampleRatio: 2,
  turbulenceBrightness: -0.05,
  diskDensity: 1,
  qualityPreset: 'medium',
  diskInnerThickness: 0.7,
  diskOuterThickness: 0.5,
  ringEnabled: true,
  ringScale: 0.83,
  ringContrast: 0.95,
  ringBrightness: 0.4,
  ringSharpness: 10,
  ringTwist: 10.3,
  noiseAnimFrequency: 4.2,
  noiseAnimAmplitude: 2,
  diskRadialFalloff: 2,
  diskOpacityFalloff: 0.5,
  adaptiveMinStep: 0.15,
  stepJitter: 0,
  diskInnerColor: '#ffffff',
  diskMidColor: '#ffffff',
  diskOuterColor: '#ffffff',
  diskTintStrength: 0,
  nebulaBrightness: 0.07,
  nebulaColor1: '#113844',
  nebulaColor2: '#1b214a',
  nebulaScale1: 3,
  nebulaScale2: 3.5,
  nebulaBlend: 0.55,
  nebulaSpeed: 0.065,
  nebulaDensity: 0.35,
  diskDifferentialRotation: 1,
  noiseEvolutionSpeed: 5,
  raySteps: 68,
  nebulaScale: 3,
  nebulaDetailScale: 2.4,
  nebulaOffsetX: 0,
  nebulaOffsetY: 0,
  nebulaOffsetZ: 0,
  diskTurbulence: 0.9,
  turbulencePrimaryScale: 0.65,
  turbulenceSecondaryScale: 1.3,
  turbulenceSecondaryStrength: 0.15,
  turbulenceOffset: 0.1,
  ringNoiseEnabled: true,
  ringNoiseScale: 4.5,
  ringNoiseAmplitude: 1.45,
  ringNoiseSharpness: 4,
  ringNoiseOffset: -0.2,
  ringNoiseOctaves: 2,
  ringNoiseLacunarity: 1.9,
  ringNoisePersistence: 0.45,
  maxRayDistance: 500,
  diskThickness: 1.3,
  heightDensityFalloff: 5,
  rayJitter: 1,
  temporalAA: false,
  temporalFrames: 16,
  cameraFov: 60,
  cameraNear: 0.1,
  cameraFar: 1000,
  cameraPosition: { x: 0, y: -5, z: 20 },
  cameraTarget: { x: 0, y: 0, z: 0 },
  cameraMinDistance: 5,
  cameraMaxDistance: 50,
  cameraRotateSpeed: -0.5,
  cameraDampingFactor: 0.05,
  storeScale: 320,
  storePosition: { x: 0, y: 0, z: 0 },
  storeRotation: { x: 0, y: 0, z: 0 },
};

const STORE_SCENE_PRESET = {
  ...DEFAULT_CAMERA_SPLINE_SETTINGS,
  ...BLACK_HOLE_BODIES_OFF,
  ...SECURITY_CAM_DEFAULTS,
  body1Enabled: true,
  body1OrbitRadius: 18,
  body2Enabled: true,
  body2OrbitRadius: 21,
  body3Enabled: true,
  body3OrbitRadius: 24,
  cameraFov: 60,
  cameraMobileFov: 85,
  cameraNear: 0.1,
  cameraFar: 5000,
  cameraAutoRotate: true,
  cameraPosition: { x: 0, y: -5, z: 20 },
  cameraMobilePosition: { x: 0, y: -5, z: 28 },
  cameraTarget: cloneCenterStoreRef(),
  cameraMobileTarget: cloneCenterStoreRef(),
  cameraMinDistance: 5,
  cameraMaxDistance: 160,
  cameraRotateSpeed: -0.5,
  cameraDampingFactor: 0.05,
  presentationMode: 'storeWarp',
  blackHoleMass: 0.4,
  gravitationalLensing: 2.4,
  dopplerStrength: 1,
  stepSize: 1,
  blackHolePosition: {
    ...cloneCenterStoreRef(),
  },
  blackHoleRotation: {
    x: 0,
    y: 0,
    z: 0,
  },
  blackHoleScale: {
    x: 1,
    y: 1,
    z: 1,
  },
  diskInnerRadius: 4.1,
  diskOuterRadius: 14.5,
  diskBrightness: 5,
  diskOpacity: 1.75,
  diskOpacityFloor: 0,
  diskTemperature: 49.78,
  temperatureFalloff: 5.22,
  diskEdgeSoftnessInner: 0.18,
  diskEdgeSoftnessOuter: 0.5,
  diskInnerColor: '#ffffff',
  diskMidColor: '#ffffff',
  diskOuterColor: '#ffffff',
  diskTintStrength: 0,
  diskRotationSpeed: -8.7,
  turbulenceScale: 1.81,
  turbulenceStretch: 0.75,
  turbulenceSharpness: 10,
  turbulenceCycleTime: 15,
  turbulenceLacunarity: 3.2,
  turbulencePersistence: 0.75,
  starsEnabled: false,
  starBackgroundColor: '#05070b',
  starDensity: 0.1,
  starSize: 1.2,
  starBrightness: 0.1,
  nebulaEnabled: false,
  nebula1Scale: 2,
  nebula1Density: 0.5,
  nebula1Brightness: 0.01,
  nebula1Color: '#071f44',
  nebula2Scale: 5.5,
  nebula2Density: 0.05,
  nebula2Brightness: 0.21,
  nebula2Color: '#010615',
  storeScale: 320,
  storePosition: {
    x: 0,
    y: 0,
    z: 0,
  },
  storeRotation: {
    x: 0,
    y: 0,
    z: 0,
  },
  bloomEnabled: true,
  bloomStrength: 0.42,
  bloomRadius: 0.14,
  bloomThreshold: 0.5,
  bloomDownSampleRatio: 2,
  turbulenceBrightness: -0.05,
  diskDensity: 1,
  qualityPreset: 'medium',
  diskInnerThickness: 0.7,
  diskOuterThickness: 0.5,
  ringEnabled: true,
  ringScale: 0.83,
  ringContrast: 0.95,
  ringBrightness: 0.4,
  ringSharpness: 10,
  ringTwist: 10.3,
  noiseAnimFrequency: 4.2,
  noiseAnimAmplitude: 2,
  diskRadialFalloff: 2,
  diskOpacityFalloff: 0.5,
  adaptiveMinStep: 0.15,
  stepJitter: 0,
  nebulaBrightness: 0.07,
  nebulaColor1: '#113844',
  nebulaColor2: '#1b214a',
  nebulaScale1: 3,
  nebulaScale2: 3.5,
  nebulaBlend: 0.55,
  nebulaSpeed: 0.065,
  nebulaDensity: 0.35,
  diskDifferentialRotation: 1,
  noiseEvolutionSpeed: 5,
  raySteps: 68,
  nebulaScale: 3,
  nebulaDetailScale: 2.4,
  nebulaOffsetX: 0,
  nebulaOffsetY: 0,
  nebulaOffsetZ: 0,
  diskTurbulence: 0.9,
  turbulencePrimaryScale: 0.65,
  turbulenceSecondaryScale: 1.3,
  turbulenceSecondaryStrength: 0.15,
  turbulenceOffset: 0.1,
  ringNoiseEnabled: true,
  ringNoiseScale: 4.5,
  ringNoiseAmplitude: 1.45,
  ringNoiseSharpness: 4,
  ringNoiseOffset: -0.2,
  ringNoiseOctaves: 2,
  ringNoiseLacunarity: 1.9,
  ringNoisePersistence: 0.45,
  maxRayDistance: 500,
  diskThickness: 1.3,
  heightDensityFalloff: 5,
  rayJitter: 1,
  temporalAA: false,
  temporalFrames: 16,
};

const SPACE_2_SCENE_PRESET = {
  ...SPACE_SCENE_PRESET,
  body1Enabled: true,
  body1Color: '#d7dcff',
  body1Size: 2.6,
  body1OrbitRadius: 17.5,
  body1OrbitSpeed: 0.52,
  body1OrbitPhase: 0,
  body1Height: -0.75,
  body2Enabled: true,
  body2Color: '#ffd9b5',
  body2Size: 1.7,
  body2OrbitRadius: 22.5,
  body2OrbitSpeed: -0.34,
  body2OrbitPhase: 115,
  body2Height: 1.6,
  body3Enabled: true,
  body3Color: '#d7b8ff',
  body3Size: 3.4,
  body3OrbitRadius: 26,
  body3OrbitSpeed: 0.22,
  body3OrbitPhase: 245,
  body3Height: 2.8,
};

const GUIDED_TOUR_SCENE_PRESET = {
  ...STORE_SCENE_PRESET,
  cameraMode: 'spline',
  cameraSplinePreset: DEFAULT_AISLE9_CAMERA_SPLINE,
  cameraSplineDuration: 42,
  cameraSplineTension: 0.45,
  cameraSplineLookAt: cloneCenterStoreRef(),
};

const SURVEILLANCE_SCENE_PRESET = {
  ...STORE_SCENE_PRESET,
  ...SECURITY_CAM_SURVEILLANCE,
  cameraMode: 'fixed',
  cameraFov: 80,
  // Uniform scale only: the raymarch views the disk in local units, so the
  // camera's distance in disk-radii = worldDistance / scale. ~8 sits the camera
  // a couple disk-radii out (full ring visible); larger engulfs the camera.
  blackHoleScale: { x: 8, y: 8, z: 8 },
  fixedCameraPosition: { x: 3, y: 2.5, z: -4 },
  fixedCameraTarget: cloneCenterStoreRef(),
};

const SURVEILLANCE_2_SCENE_PRESET = {
  ...SURVEILLANCE_SCENE_PRESET,
  surveillanceCameraLabel: 'CAM 02',
  fixedCameraPosition: { x: 5, y: 2.5, z: 1.5 },
  fixedCameraMobilePosition: { x: 5, y: 2.5, z: 1.5 },
  fixedCameraTarget: cloneCenterStoreRef(),
  fixedCameraMobileTarget: cloneCenterStoreRef(),
};

const SURVEILLANCE_3_SCENE_PRESET = {
  ...SURVEILLANCE_SCENE_PRESET,
  surveillanceCameraLabel: 'CAM 03',
  fixedCameraPosition: { x: -5.5, y: 2.5, z: -2 },
  fixedCameraMobilePosition: { x: -5.5, y: 2.5, z: -2 },
  fixedCameraTarget: cloneCenterStoreRef(),
  fixedCameraMobileTarget: cloneCenterStoreRef(),
};

export const PRESETS = {
  [DEFAULT_PRESET]: STORE_SCENE_PRESET,
  [GUIDED_TOUR_PRESET]: GUIDED_TOUR_SCENE_PRESET,
  [SURVEILLANCE_PRESET]: SURVEILLANCE_SCENE_PRESET,
  [SURVEILLANCE_2_PRESET]: SURVEILLANCE_2_SCENE_PRESET,
  [SURVEILLANCE_3_PRESET]: SURVEILLANCE_3_SCENE_PRESET,
  [SPACE_PRESET]: SPACE_SCENE_PRESET,
  [SPACE_2_PRESET]: SPACE_2_SCENE_PRESET,
};
