const SHARED_LIGHTING = {
  bgColor: '#120d14',
  keyColor: '#ffd3b8',
  rimColor: '#7db7ff',
  ambientIntensity: 0.3,
  keyIntensity: 7.0,
  rimIntensity: 2.6,
};

const PRESETS = {
  'Used Engine Oil': {
    ...SHARED_LIGHTING,
    mcResolution: 32,
    trailLength: 5,
    envIntensity: 0.45,
    bgColor: '#0d0b08',
    keyColor: '#ffc890',
    // Liquid material — near-black brown, glossy clearcoat, faint gas sheen
    liquidColor: '#241505',
    emissiveColor: '#000000',
    emissiveIntensity: 0,
    roughness: 0.16,
    metalness: 0.0,
    transmission: 0,
    ior: 1.47,
    thickness: 0.3,
    clearcoat: 1.0,
    clearcoatRoughness: 0.12,
    iridescence: 0.3,
    // Coat
    coverage: 0.85,
    coatSoftness: 0.18,
    coatThickness: 0.014,
    streakScale: 3.2,
    streakStretch: 4.5,
    topBias: 0.35,
    flowSpeed: 0.035,
    rippleStrength: 0.3,
    // Drips — slow, heavy, long-stretching
    dripCount: 8,
    dripRate: 0.4,
    viscosity: 0.85,
    dropSize: 0.085,
    fallSpeed: 0.7,
    // Bone
    showBone: true,
    boneWetness: 0.85,
  },
  'Clean Water': {
    ...SHARED_LIGHTING,
    mcResolution: 32,
    trailLength: 9,
    envIntensity: 0.75,
    bgColor: '#0b1016',
    liquidColor: '#dceef2',
    emissiveColor: '#000000',
    emissiveIntensity: 0,
    roughness: 0.04,
    metalness: 0.0,
    transmission: 1.0,
    ior: 1.33,
    thickness: 0.35,
    clearcoat: 0.25,
    clearcoatRoughness: 0.05,
    iridescence: 0,
    coverage: 0.55,
    coatSoftness: 0.12,
    coatThickness: 0.007,
    streakScale: 4.5,
    streakStretch: 6.0,
    topBias: 0.3,
    flowSpeed: 0.12,
    rippleStrength: 0.2,
    dripCount: 8,
    dripRate: 1.4,
    viscosity: 0.12,
    dropSize: 0.05,
    fallSpeed: 1.0,
    showBone: true,
    boneWetness: 0.9,
  },
  'Fresh Blood': {
    ...SHARED_LIGHTING,
    mcResolution: 32,
    trailLength: 7,
    envIntensity: 0.5,
    bgColor: '#0e0a0c',
    rimColor: '#ff9a9a',
    liquidColor: '#3f040a',
    emissiveColor: '#000000',
    emissiveIntensity: 0,
    roughness: 0.22,
    metalness: 0.0,
    transmission: 0.2,
    ior: 1.35,
    thickness: 0.25,
    clearcoat: 0.9,
    clearcoatRoughness: 0.18,
    iridescence: 0,
    coverage: 0.7,
    coatSoftness: 0.15,
    coatThickness: 0.011,
    streakScale: 3.8,
    streakStretch: 5.0,
    topBias: 0.4,
    flowSpeed: 0.06,
    rippleStrength: 0.25,
    dripCount: 8,
    dripRate: 0.7,
    viscosity: 0.5,
    dropSize: 0.07,
    fallSpeed: 0.85,
    showBone: true,
    boneWetness: 0.7,
  },
  'Toxic Slime': {
    ...SHARED_LIGHTING,
    mcResolution: 32,
    trailLength: 4,
    envIntensity: 0.35,
    bgColor: '#070d08',
    keyColor: '#d8ffd0',
    rimColor: '#52ff9d',
    liquidColor: '#1f9148',
    emissiveColor: '#2bff70',
    emissiveIntensity: 0.55,
    roughness: 0.3,
    metalness: 0.0,
    transmission: 0.35,
    ior: 1.4,
    thickness: 0.4,
    clearcoat: 0.6,
    clearcoatRoughness: 0.3,
    iridescence: 0,
    coverage: 0.95,
    coatSoftness: 0.22,
    coatThickness: 0.018,
    streakScale: 2.6,
    streakStretch: 3.5,
    topBias: 0.3,
    flowSpeed: 0.025,
    rippleStrength: 0.4,
    dripCount: 8,
    dripRate: 0.3,
    viscosity: 0.95,
    dropSize: 0.11,
    fallSpeed: 0.55,
    showBone: true,
    boneWetness: 0.6,
  },
};

export const DEFAULT_PRESET = 'Used Engine Oil';

export default PRESETS;
