const PRESETS = {
  'Default Sphere': {
    shapeMode: 'sphere',
    interactionMode: 'press',
    bgColor: '#120d14',
    keyColor: '#ffd3b8',
    rimColor: '#7db7ff',
    ambientIntensity: 0.18,
    keyIntensity: 5.5,
    rimIntensity: 2.6,
    dripSpeed: 1.0,
    dripCount: 8,
    dripDropletFall: 3.0,
    viscosity: 0.62,
    noiseScale: 4.0,
    noiseStrength: 0.2,
    tintA: '#2c2442',
    tintB: '#d35f5f',
    paletteBrightness: 3.0,
    paletteSpeed: 0.2,
    pointerRadius: 0.65,
    pointerStrength: 0.3,
    skullScale: 0.1,
  },
  'Default Skull': {
    shapeMode: 'skull',
    interactionMode: 'press',
    bgColor: '#120d14',
    keyColor: '#ffd3b8',
    rimColor: '#7db7ff',
    ambientIntensity: 0.18,
    keyIntensity: 5.5,
    rimIntensity: 2.6,
    dripSpeed: 1.0,
    dripCount: 8,
    dripDropletFall: 3.0,
    viscosity: 0.62,
    noiseScale: 4.0,
    noiseStrength: 0.2,
    tintA: '#2c2442',
    tintB: '#d35f5f',
    paletteBrightness: 3.0,
    paletteSpeed: 0.2,
    pointerRadius: 0.65,
    pointerStrength: 0.3,
    skullScale: 0.1,
  },
  'Warm Metal Melt': {
    shapeMode: 'sphere',
    interactionMode: 'hover',
    bgColor: '#120c08',
    keyColor: '#ffca8a',
    rimColor: '#ffd8b8',
    ambientIntensity: 0.22,
    keyIntensity: 6.2,
    rimIntensity: 2.0,
    dripSpeed: 0.9,
    dripCount: 8,
    dripDropletFall: 3.5,
    viscosity: 0.78,
    noiseScale: 3.4,
    noiseStrength: 0.24,
    tintA: '#3b1f0d',
    tintB: '#e67e3f',
    paletteBrightness: 3.5,
    paletteSpeed: 0.15,
    pointerRadius: 0.8,
    pointerStrength: 0.28,
    skullScale: 0.1,
  },
  'Cold Chrome Melt': {
    shapeMode: 'sphere',
    interactionMode: 'press',
    bgColor: '#090c11',
    keyColor: '#c6ddff',
    rimColor: '#7dd6ff',
    ambientIntensity: 0.13,
    keyIntensity: 4.4,
    rimIntensity: 3.5,
    dripSpeed: 1.2,
    dripCount: 10,
    dripDropletFall: 2.5,
    viscosity: 0.48,
    noiseScale: 5.2,
    noiseStrength: 0.18,
    tintA: '#1b2b44',
    tintB: '#7f95aa',
    paletteBrightness: 2.5,
    paletteSpeed: 0.3,
    pointerRadius: 0.55,
    pointerStrength: 0.34,
    skullScale: 0.1,
  },
  'High Viscosity Drips': {
    shapeMode: 'sphere',
    interactionMode: 'hover',
    bgColor: '#17111e',
    keyColor: '#ffe2c8',
    rimColor: '#8bbdff',
    ambientIntensity: 0.2,
    keyIntensity: 5.1,
    rimIntensity: 2.5,
    dripSpeed: 0.6,
    dripCount: 6,
    dripDropletFall: 4.0,
    viscosity: 0.92,
    noiseScale: 3.0,
    noiseStrength: 0.22,
    tintA: '#281838',
    tintB: '#ad4f66',
    paletteBrightness: 3.2,
    paletteSpeed: 0.1,
    pointerRadius: 1.0,
    pointerStrength: 0.2,
    skullScale: 0.1,
  },
  'Fast Drip': {
    shapeMode: 'sphere',
    interactionMode: 'press',
    bgColor: '#120f18',
    keyColor: '#ffd4c5',
    rimColor: '#77b0ff',
    ambientIntensity: 0.16,
    keyIntensity: 5.8,
    rimIntensity: 2.7,
    dripSpeed: 1.8,
    dripCount: 12,
    dripDropletFall: 2.0,
    viscosity: 0.36,
    noiseScale: 6.2,
    noiseStrength: 0.16,
    tintA: '#241c35',
    tintB: '#ff6b5c',
    paletteBrightness: 3.8,
    paletteSpeed: 0.4,
    pointerRadius: 0.5,
    pointerStrength: 0.46,
    skullScale: 0.1,
  },
};

export const DEFAULT_PRESET = 'Default Sphere';

export default PRESETS;
