export {
  default,
  AREAS,
  AREA_ICONS,
  AREA_ROUTE_SEGMENTS,
  CHANNELS,
  DEFAULT_SCENE_PATH,
  EYE_CANDIES,
  getAreaDefaultPath,
  getScenesFor,
  normalizeScenePath,
  resolveLegacyScenePath,
  resolveSceneRoute,
  resolveScenePath,
} from './sceneRegistry.jsx';
