const QUINNS_DICE_PRESETS = {
  Default: {
    physicsEnabled: true,
    debug: false,
    debugLights: false,
    orbitControlsEnabled: false,
    backgroundTopColor: '#f5b7f8',
    backgroundBottomColor: '#220031',
    bloomEnabled: true,
    bloomIntensity: 2,
    bloomLuminanceThreshold: 0.2,
    bloomLuminanceSmoothing: 0.15,
    bloomRadius: 0.8,
    d4Scale: 1,
    d4ColliderMode: 'hull',
    d6Scale: 1,
    d6ColliderMode: 'hull',
    d8Scale: 1,
    d8ColliderMode: 'hull',
    d10Scale: 1,
    d10ColliderMode: 'hull',
    d12Scale: 1,
    d12ColliderMode: 'hull',
    d20Scale: 1,
    d20ColliderMode: 'hull',
    d20EmissiveColor: '#fec1ff',
    d20EmissiveIntensity: 0.25,
    rollTarget: 'random',
    rollPower: 1,
    rollRejoinDelaySeconds: 1.5,
    returnStrength: 1,
    maxImpulse: 0.5,
    linearDamping: 2,
    angularDamping: 1,
    friction: 0.1,
    boxWidth: 10,
    boxHeight: 10,
    boxDepth: 10,
    targetX: 0,
    targetY: 0,
    targetZ: 0,
    pointerRadius: 0.6,
  },
};

export default QUINNS_DICE_PRESETS;
