import { MOUNTAIN_TARGET, OCEAN_TARGET } from '../utils/targetGeometry';

export const DEFAULT_PRESET = 'An Ocean Implied';

const BASE = {
  targetMode: OCEAN_TARGET,
  targetReveal: false,
  targetProbeArea: 60,
  targetScale: 1,
  targetHeight: 0,
  targetTilt: -1.2,
  targetSpinSpeed: 0.16,
  timeScale: 1,
  rainEnabled: true,
  rainDropCount: 800000,
  rainBounds: 70,
  rainCeiling: 10,
  rainSpawnRange: 40,
  rainFallSpeed: 26,
  rainSpeedJitter: 0.4,
  rainWindX: 0.8,
  rainWindZ: 0,
  rainStreakLength: 0.21,
  rainStreakWidth: 0.07,
  rainOpacity: 1.11,
  rainTint: '#d5e7f0',
  rainEdgeFade: 0.55,
  catchDepth: 3,
  slideGravity: 18,
  slideDrag: 2,
  slopeRelease: 1.1,
  surfaceLifeMin: 6,
  surfaceLifeMax: 12,
  stretchSpeed: 5.8,
  gravity: 20,
  airDrag: 1.1,
  sinkDepth: 26,
  lightX: 0,
  lightZ: -6,
  lightHeight: 62,
  lightRadius: 9,
  lightSpread: 0.42,
  lightSoftness: 1.8,
  lightReach: 95,
  lightIntensity: 1.6,
  lightAmbient: 0.08,
  lightDriftSpeed: 0.12,
  lightDriftRadius: 7,
  lightPulse: 0.22,
  oceanDisplayMode: 'Hidden',
  oceanPatchSize: 200,
  oceanPatchResolution: 192,
  oceanLodScale: 3.7,
  oceanPaletteMode: 'Monochrome',
  oceanSeaColor: '#000000',
  oceanHorizonColor: '#050505',
  oceanSkyColor: '#000000',
  oceanSunColor: '#ffffff',
  enhanceSurfaceDetails: false,
  oceanFoamStrength: 1.1,
  oceanFoamThreshold: 2.8,
  impactAreaSize: 140,
  impactDotSize: 0.55,
  impactDotStrength: 1,
  impactFoamStrength: 0.8,
  impactFoamDecay: 0.06,
  mountainDisplayMode: 'Hidden',
  mountainShape: 'Range',
  mountainPalette: 'Monochrome',
  mountainMeshResolution: 512,
  mountainFieldResolution: 1024,
  mountainExtent: 140,
  mountainRelief: 140,
  mountainBaseHeight: 0.4,
  mountainFrequency: 2.2,
  mountainAmplitude: 0.125,
  mountainTreeline: 0.465,
  peakRadius: 0.35,
  peakAmplitude: 0.1,
  erosionScale: 0.15,
  erosionStrength: 0.22,
  erosionGullyWeight: 0.5,
  erosionDetail: 1.5,
  erosionOctaves: 5,
  quality: 'Medium',
  pauseWater: false,
  waveUpdateHz: 30,
};

// The mirror of the implied ocean. The range is ~25 units of relief across 140,
// so the rain volume has to sit above the peaks rather than above sea level, and
// the drops live long enough on the surface to trace a gully end to end.
const MOUNTAIN = {
  ...BASE,
  targetMode: MOUNTAIN_TARGET,
  rainDropCount: 700000,
  rainBounds: 120,
  rainCeiling: 42,
  rainSpawnRange: 26,
  rainFallSpeed: 24,
  rainWindX: 0.4,
  rainStreakLength: 0.18,
  rainStreakWidth: 0.06,
  rainEdgeFade: 0.7,
  catchDepth: 2,
  slideGravity: 26,
  slideDrag: 3.2,
  // Measured slope magnitudes over the baked range run 0.5 mean, 1.85 peak, so
  // the release sits between: cliff faces and ridges shed their drops, gullies
  // and shoulders hold onto them.
  slopeRelease: 1.2,
  surfaceLifeMin: 4,
  surfaceLifeMax: 11,
  stretchSpeed: 5,
  sinkDepth: 30,
  lightHeight: 74,
  lightRadius: 18,
  lightSpread: 0.36,
  lightReach: 130,
  lightIntensity: 1.7,
  lightAmbient: 0.07,
  lightDriftRadius: 12,
};

// Geometry targets are small and close, so the whole rain volume, the light
// cone and the fall-off depth shrink to match the probe area.
const GEOMETRY = {
  ...BASE,
  targetProbeArea: 26,
  rainDropCount: 600000,
  rainBounds: 62,
  rainCeiling: 34,
  rainSpawnRange: 22,
  rainFallSpeed: 22,
  rainWindX: 0,
  rainStreakLength: 0.14,
  rainStreakWidth: 0.045,
  rainOpacity: 1.07,
  rainEdgeFade: 0.72,
  catchDepth: 1.6,
  slideGravity: 12,
  slideDrag: 5,
  slopeRelease: 3,
  surfaceLifeMin: 1.5,
  surfaceLifeMax: 5.5,
  stretchSpeed: 3.7,
  sinkDepth: 34,
  lightHeight: 40,
  lightRadius: 16,
  lightSpread: 0.3,
  lightSoftness: 1.4,
  lightReach: 78,
  lightIntensity: 1.5,
  lightAmbient: 0.1,
  lightDriftSpeed: 0.07,
  lightDriftRadius: 4,
};

// The logos are flat plates, so the reveal comes from the letterform edges and
// counters rather than from curvature: drops sheet across the face, pour off the
// downhill edge, and fall straight through the holes. A shallow tilt gives them
// somewhere to run and turns the plate toward the camera.
const LOGO = {
  ...GEOMETRY,
  targetProbeArea: 26,
  targetTilt: -0.5,
  targetSpinSpeed: 0,
  rainBounds: 54,
  rainEdgeFade: 0.8,
  rainDropCount: 700000,
  slideGravity: 30,
  slideDrag: 4,
  catchDepth: 1,
  rainOpacity: 0.73,
  stretchSpeed: 7,
  lightRadius: 20,
  lightHeight: 44,
  // A flat plate only reads from above, so these keep the raised orbit
  // framing rather than inheriting the scene's spline default.
  cameraMode: 'orbit',
  orbitDesktopPosition: { x: 0, y: 26, z: 26 },
  orbitDesktopTarget: { x: 0, y: 0, z: 0 },
  orbitDesktopPivot: { x: 0, y: 0, z: 0 },
  orbitDesktopFov: 40,
  orbitMobilePosition: { x: 0, y: 32, z: 32 },
  orbitMobileTarget: { x: 0, y: 0, z: 0 },
  orbitMobilePivot: { x: 0, y: 0, z: 0 },
  orbitMobileFov: 52,
};

export const PRESETS = {
  'An Ocean Implied': { ...BASE },
  'Rain on Ocean Reverse': {
    ...BASE,
    timeScale: -1.6,
    rainDropCount: 500000,
    rainOpacity: 1.23,
    surfaceLifeMin: 0.4,
    surfaceLifeMax: 1.6,
    lightDriftSpeed: 0.08,
    lightPulse: 0.1,
  },
  Downpour: {
    ...BASE,
    rainDropCount: 700000,
    rainFallSpeed: 34,
    rainStreakLength: 0.24,
    rainStreakWidth: 0.08,
    rainOpacity: 0.8,
    surfaceLifeMax: 1.5,
    slideGravity: 30,
    slopeRelease: 0.85,
    stretchSpeed: 9.7,
    lightRadius: 14,
    lightIntensity: 1.85,
    lightDriftSpeed: 0.2,
  },
  Drizzle: {
    ...BASE,
    rainDropCount: 180000,
    rainFallSpeed: 17,
    rainStreakLength: 0.17,
    rainStreakWidth: 0.055,
    rainOpacity: 0.86,
    surfaceLifeMin: 1.2,
    surfaceLifeMax: 4,
    slideGravity: 12,
    slideDrag: 3,
    slopeRelease: 1.4,
    stretchSpeed: 2.6,
    lightIntensity: 1.35,
    lightDriftSpeed: 0.06,
  },
  'Rain on Torus': {
    ...GEOMETRY,
    targetMode: 'Torus',
  },
  'Rain on Torus Knot': {
    ...GEOMETRY,
    targetMode: 'Torus Knot',
    targetSpinSpeed: 0.24,
  },
  'Rain on Sphere': {
    ...GEOMETRY,
    targetMode: 'Sphere',
    targetTilt: 0,
  },
  'Rain on Bret': {
    ...LOGO,
    targetMode: 'Bret',
  },
  'Rain on Bret Inner': {
    ...LOGO,
    targetMode: 'Bret Inner',
  },
  'Rain on Reversal': {
    ...LOGO,
    targetMode: 'Reversal',
  },
  'Rain on Reversal Inner': {
    ...LOGO,
    targetMode: 'Reversal Inner',
  },
  'Foam + Rain': {
    ...BASE,
    oceanDisplayMode: 'Foam Only',
    oceanFoamStrength: 1.35,
    oceanFoamThreshold: 2.9,
    impactDotSize: 0.7,
    impactDotStrength: 1.5,
    impactFoamStrength: 1.2,
    impactFoamDecay: 0.05,
    lightAmbient: 0.12,
  },
  'Visible Ocean': {
    ...BASE,
    rainDropCount: 260000,
    rainOpacity: 0.78,
    lightAmbient: 0.22,
    lightIntensity: 1.2,
    oceanDisplayMode: 'Full',
    oceanPaletteMode: 'Row It Alone',
    oceanSeaColor: '#01040c',
    oceanHorizonColor: '#6b9ed1',
    oceanSkyColor: '#143663',
    oceanSunColor: '#ffe6b8',
    enhanceSurfaceDetails: true,
    impactDotSize: 0.75,
    impactDotStrength: 1.4,
    impactFoamStrength: 1.1,
    impactFoamDecay: 0.05,
  },
  'A Mountain Implied': { ...MOUNTAIN },
  // The same single eroded dome Endless Erosion's paint preset starts from, so
  // the rain has one peak to run off rather than a whole range. The surrounding
  // plain sits at the brush's own base height, which puts it at world zero.
  'A Single Peak Implied': {
    ...MOUNTAIN,
    mountainShape: 'Single Peak',
    mountainBaseHeight: 0.45,
    rainBounds: 110,
    rainCeiling: 38,
    lightHeight: 66,
    lightReach: 120,
  },
  'Visible Single Peak': {
    ...MOUNTAIN,
    mountainShape: 'Single Peak',
    mountainBaseHeight: 0.45,
    mountainDisplayMode: 'Full',
    rainBounds: 110,
    rainCeiling: 38,
    rainDropCount: 320000,
    rainOpacity: 0.82,
    lightAmbient: 0.2,
    lightIntensity: 1.25,
    lightHeight: 66,
    lightReach: 120,
  },
  'Visible Mountain': {
    ...MOUNTAIN,
    mountainDisplayMode: 'Full',
    mountainPalette: 'Monochrome',
    rainDropCount: 320000,
    rainOpacity: 0.82,
    lightAmbient: 0.2,
    lightIntensity: 1.25,
  },
  'Still Light': {
    ...BASE,
    lightDriftSpeed: 0,
    lightPulse: 0,
    rainWindX: 0,
  },
};

export function getPresetControls({ presetSnapshot }) {
  return { ...presetSnapshot };
}
