import { imageFile } from '../../../../../../utils/appUtils';

const PRESETS = {
  Surrender: {
    // Scene - Camera
    orbitControls: false,
    // Scene - Background
    bgColor: '#838383',
    fogNear: 5,
    fogFar: 14,
    // Scene - Lighting
    ambientIntensity: 0.5,
    ambientColor: '#ffffff',
    keyIntensity: 3,
    keyColor: '#ffffff',
    keyPosX: 3,
    keyPosY: 5,
    keyPosZ: 4,
    keyShadow: true,
    fillIntensity: 0.2,
    fillColor: '#ffffff',
    fillPosX: 2,
    fillPosY: 1,
    fillPosZ: -1,
    // Flag - Orientation
    rotateX: -15,
    rotateY: 0,
    rotateZ: 15,
    posX: 0,
    posY: 0,
    // Flag - Cloth
    clothWidth: 1.0,
    clothHeight: 0.7,
    segmentsX: 30,
    segmentsY: 21,
    stiffness: 0.5,
    dampening: 0.98,
    // Flag - Cloth - Alpha
    alphaSeed: 42,
    alphaScale: 3,
    edgeFade: 0,
    holeAmount: 0,
    tatterEdge: 0,
    smoothEdges: false,
    // Flag - Material
    textureUrl: 'None',
    textureTile: true,
    textureScaleX: 1,
    textureScaleY: 1,
    textureRotation: 0,
    flagColor: '#f5f0e8',
    roughness: 0.65,
    metalness: 0.0,
    opacity: 1.0,
    sheen: 0,
    sheenRoughness: 0.5,
    sheenColor: '#ffffff',
    clearcoat: 0.0,
    clearcoatRoughness: 0.0,
    transmission: 0.0,
    ior: 1.5,
    materialThickness: 0.0,
    // Flag - Pole
    poleColor: '#c4c4c4',
    poleMetalness: 0.6,
    poleRoughness: 0.4,
    // Flag - Finial
    finialColor: '#efcb5f',
    finialMetalness: 0.7,
    finialRoughness: 0.3,
    // Flag - Rings
    ringColor: '#c4c4c4',
    ringMetalness: 0.8,
    ringRoughness: 0.3,
    // Wind
    wind: 4.7,
    windDirX: 1,
    windDirZ: -0.2,
    // Leaves
    leavesEnabled: false,
    leafType: 'Leaves',
    leafCount: 300,
    leafSize: 0.08,
    leafSpeed: 0.08,
    leafTravel: 5,
    leafTumble: 20,
    leafCurvature: 0.0,
    leafColor1: '#d70654',
    leafColor2: '#ffd95f',
    leafColor3: '#b8d576',
    // Postprocessing - Outline
    enabled: true,
    mode: 'glow',
    strength: 7,
    thickness: 12,
    color: '#3eb2ff',
    hiddenColor: '#000000',
    hiddenStrength: 0,
    glow: 0.35,
    inside: false,
    downSampleRatio: 1,
    patternScale: 8,
    patternOctaves: 3,
    patternLacunarity: 2,
    ringStride: 10,
    halftoneScale: 1,
    // Debug
    paused: false,
    wireframe: false,
    cursorCollider: true,
    debugColliders: false,
    debugColor: '#ff0000',
    cursorRadius: 0.12,
  },

  'Surrender Now': {
    // Scene - Camera
    orbitControls: false,
    // Scene - Background
    bgColor: '#3c3c3c',
    fogNear: 6,
    fogFar: 16,
    // Scene - Lighting
    ambientIntensity: 0.3,
    ambientColor: '#ffffff',
    keyIntensity: 1.2,
    keyColor: '#fff4cc',
    keyPosX: -3,
    keyPosY: 5,
    keyPosZ: 4,
    keyShadow: true,
    fillIntensity: 0.1,
    fillColor: '#ffffff',
    fillPosX: 2,
    fillPosY: 1,
    fillPosZ: -1,
    // Flag - Orientation
    rotateX: -15,
    rotateY: 0,
    rotateZ: 15,
    posX: 0,
    posY: 0,
    // Flag - Cloth
    clothWidth: 1.0,
    clothHeight: 0.7,
    segmentsX: 30,
    segmentsY: 21,
    stiffness: 0.5,
    dampening: 0.98,
    // Flag - Cloth - Alpha
    alphaSeed: 57,
    alphaScale: 9.2,
    edgeFade: 0,
    holeAmount: 1,
    tatterEdge: 1,
    smoothEdges: true,
    // Flag - Material
    textureUrl: imageFile('turbo_flex.png'),
    textureTile: false,
    textureScaleX: 0.7,
    textureScaleY: 0.7,
    textureRotation: 0,
    flagColor: '#000000',
    roughness: 0.9,
    metalness: 0.0,
    opacity: 1.0,
    sheen: 0,
    sheenRoughness: 0.5,
    sheenColor: '#ffffff',
    clearcoat: 0.0,
    clearcoatRoughness: 0.0,
    transmission: 0.0,
    ior: 1.5,
    materialThickness: 0.0,
    // Flag - Pole
    poleColor: '#1a1a1a',
    poleMetalness: 0.4,
    poleRoughness: 0.7,
    // Flag - Finial
    finialColor: '#c8a84b',
    finialMetalness: 0.8,
    finialRoughness: 0.2,
    // Flag - Rings
    ringColor: '#1a1a1a',
    ringMetalness: 0.4,
    ringRoughness: 0.7,
    // Wind
    wind: 10,
    windDirX: 1,
    windDirZ: -0.2,
    // Leaves
    leavesEnabled: false,
    leafType: 'Leaves',
    leafCount: 300,
    leafSize: 0.08,
    leafSpeed: 0.08,
    leafTravel: 5,
    leafTumble: 20,
    leafCurvature: 0.0,
    leafColor1: '#d70654',
    leafColor2: '#ffd95f',
    leafColor3: '#b8d576',
    // Postprocessing - Outline
    enabled: false,
    mode: 'worley',
    strength: 7,
    thickness: 12,
    color: '#ffffff',
    hiddenColor: '#000000',
    hiddenStrength: 0,
    glow: 0.5,
    inside: false,
    downSampleRatio: 1,
    patternScale: 8,
    patternOctaves: 3,
    patternLacunarity: 2,
    ringStride: 10,
    halftoneScale: 1,
    // Debug
    paused: false,
    wireframe: false,
    cursorCollider: true,
    debugColliders: false,
    debugColor: '#ff0000',
    cursorRadius: 0.12,
  },

  Autumn: {
    // Scene - Camera
    orbitControls: false,
    // Scene - Background
    bgColor: '#8b7355',
    fogNear: 4,
    fogFar: 12,
    // Scene - Lighting
    ambientIntensity: 0.5,
    ambientColor: '#ffffff',
    keyIntensity: 3,
    keyColor: '#ffffff',
    keyPosX: 3,
    keyPosY: 5,
    keyPosZ: 4,
    keyShadow: true,
    fillIntensity: 0.2,
    fillColor: '#ffffff',
    fillPosX: 2,
    fillPosY: 1,
    fillPosZ: -1,
    // Flag - Orientation
    rotateX: -15,
    rotateY: 0,
    rotateZ: 15,
    posX: 0,
    posY: 0,
    // Flag - Cloth
    clothWidth: 1.0,
    clothHeight: 0.7,
    segmentsX: 30,
    segmentsY: 21,
    stiffness: 0.5,
    dampening: 0.98,
    // Flag - Cloth - Alpha
    alphaSeed: 42,
    alphaScale: 3,
    edgeFade: 0,
    holeAmount: 0,
    tatterEdge: 0,
    smoothEdges: false,
    // Flag - Material
    textureUrl: 'None',
    textureTile: true,
    textureScaleX: 1,
    textureScaleY: 1,
    textureRotation: 0,
    flagColor: '#f5f0e8',
    roughness: 0.65,
    metalness: 0.0,
    opacity: 1.0,
    sheen: 0,
    sheenRoughness: 0.5,
    sheenColor: '#ffffff',
    clearcoat: 0.0,
    clearcoatRoughness: 0.0,
    transmission: 0.0,
    ior: 1.5,
    materialThickness: 0.0,
    // Flag - Pole
    poleColor: '#c4c4c4',
    poleMetalness: 0.6,
    poleRoughness: 0.4,
    // Flag - Finial
    finialColor: '#efcb5f',
    finialMetalness: 0.7,
    finialRoughness: 0.3,
    // Flag - Rings
    ringColor: '#c4c4c4',
    ringMetalness: 0.8,
    ringRoughness: 0.3,
    // Wind
    wind: 4.7,
    windDirX: 1,
    windDirZ: -0.2,
    // Leaves
    leavesEnabled: true,
    leafType: 'Leaves',
    leafCount: 400,
    leafSize: 0.06,
    leafSpeed: 0.02,
    leafTravel: 8,
    leafTumble: 20,
    leafCurvature: 0.4,
    leafColor1: '#c8521a',
    leafColor2: '#e8a020',
    leafColor3: '#8b6914',
    // Postprocessing - Outline
    enabled: true,
    mode: 'glow',
    strength: 7,
    thickness: 12,
    color: '#3eb2ff',
    hiddenColor: '#000000',
    hiddenStrength: 0,
    glow: 0.35,
    inside: false,
    downSampleRatio: 1,
    patternScale: 8,
    patternOctaves: 3,
    patternLacunarity: 2,
    ringStride: 10,
    halftoneScale: 1,
    // Debug
    paused: false,
    wireframe: false,
    cursorCollider: true,
    debugColliders: false,
    debugColor: '#ff0000',
    cursorRadius: 0.12,
  },
  Spring: {
    // Scene - Camera
    orbitControls: false,
    // Scene - Background
    bgColor: '#ff9ec3',
    fogNear: 5,
    fogFar: 14,
    // Scene - Lighting
    ambientIntensity: 0.7,
    ambientColor: '#ffffff',
    keyIntensity: 2.5,
    keyColor: '#fff8f0',
    keyPosX: 3,
    keyPosY: 5,
    keyPosZ: 4,
    keyShadow: true,
    fillIntensity: 0.3,
    fillColor: '#e8f0ff',
    fillPosX: 2,
    fillPosY: 1,
    fillPosZ: -1,
    // Flag - Orientation
    rotateX: -15,
    rotateY: 0,
    rotateZ: 15,
    posX: 0,
    posY: 0,
    // Flag - Cloth
    clothWidth: 1.0,
    clothHeight: 0.7,
    segmentsX: 30,
    segmentsY: 21,
    stiffness: 0.5,
    dampening: 0.98,
    // Flag - Cloth - Alpha
    alphaSeed: 42,
    alphaScale: 3,
    edgeFade: 0,
    holeAmount: 0,
    tatterEdge: 0,
    smoothEdges: false,
    // Flag - Material
    textureUrl: 'None',
    textureTile: true,
    textureScaleX: 1,
    textureScaleY: 1,
    textureRotation: 0,
    flagColor: '#f5f0e8',
    roughness: 0.65,
    metalness: 0.0,
    opacity: 1.0,
    sheen: 0,
    sheenRoughness: 0.5,
    sheenColor: '#ffffff',
    clearcoat: 0.0,
    clearcoatRoughness: 0.0,
    transmission: 0.0,
    ior: 1.5,
    materialThickness: 0.0,
    // Flag - Pole
    poleColor: '#c4c4c4',
    poleMetalness: 0.6,
    poleRoughness: 0.4,
    // Flag - Finial
    finialColor: '#efcb5f',
    finialMetalness: 0.7,
    finialRoughness: 0.3,
    // Flag - Rings
    ringColor: '#c4c4c4',
    ringMetalness: 0.8,
    ringRoughness: 0.3,
    // Wind
    wind: 3.0,
    windDirX: 1,
    windDirZ: -0.2,
    // Leaves
    leavesEnabled: true,
    leafType: 'Blossoms',
    leafCount: 700,
    leafSize: 0.06,
    leafSpeed: 0.05,
    leafTravel: 5,
    leafTumble: 18,
    leafCurvature: 0.55,
    leafColor1: '#ffffff',
    leafColor2: '#ffffff',
    leafColor3: '#ffffff',
    // Postprocessing - Outline
    enabled: true,
    mode: 'glow',
    strength: 7,
    thickness: 12,
    color: '#3eb2ff',
    hiddenColor: '#000000',
    hiddenStrength: 0,
    glow: 0.35,
    inside: false,
    downSampleRatio: 1,
    patternScale: 8,
    patternOctaves: 3,
    patternLacunarity: 2,
    ringStride: 10,
    halftoneScale: 1,
    // Debug
    paused: false,
    wireframe: false,
    cursorCollider: true,
    debugColliders: false,
    debugColor: '#ff0000',
    cursorRadius: 0.12,
  },

  Winter: {
    // Scene - Camera
    orbitControls: false,
    // Scene - Background
    bgColor: '#222222',
    fogNear: 5,
    fogFar: 14,
    // Scene - Lighting
    ambientIntensity: 0.8,
    ambientColor: '#ddeeff',
    keyIntensity: 1.5,
    keyColor: '#eef4ff',
    keyPosX: 3,
    keyPosY: 5,
    keyPosZ: 4,
    keyShadow: true,
    fillIntensity: 0.4,
    fillColor: '#c8ddf0',
    fillPosX: 2,
    fillPosY: 1,
    fillPosZ: -1,
    // Flag - Orientation
    rotateX: -15,
    rotateY: 0,
    rotateZ: 15,
    posX: 0,
    posY: 0,
    // Flag - Cloth
    clothWidth: 1.0,
    clothHeight: 0.7,
    segmentsX: 30,
    segmentsY: 21,
    stiffness: 0.5,
    dampening: 0.98,
    // Flag - Cloth - Alpha
    alphaSeed: 42,
    alphaScale: 3,
    edgeFade: 0,
    holeAmount: 0,
    tatterEdge: 0,
    smoothEdges: false,
    // Flag - Material
    textureUrl: 'None',
    textureTile: true,
    textureScaleX: 1,
    textureScaleY: 1,
    textureRotation: 0,
    flagColor: '#ddeeff',
    roughness: 0.5,
    metalness: 0.0,
    opacity: 1.0,
    sheen: 0,
    sheenRoughness: 0.5,
    sheenColor: '#ffffff',
    clearcoat: 0.0,
    clearcoatRoughness: 0.0,
    transmission: 0.0,
    ior: 1.5,
    materialThickness: 0.0,
    // Flag - Pole
    poleColor: '#c4c4c4',
    poleMetalness: 0.6,
    poleRoughness: 0.4,
    // Flag - Finial
    finialColor: '#efcb5f',
    finialMetalness: 0.7,
    finialRoughness: 0.3,
    // Flag - Rings
    ringColor: '#c4c4c4',
    ringMetalness: 0.8,
    ringRoughness: 0.3,
    // Wind
    wind: 2.0,
    windDirX: 0.3,
    windDirZ: 0,
    // Leaves
    leavesEnabled: true,
    leafType: 'Snowflakes',
    leafCount: 1000,
    leafSize: 0.02,
    leafSpeed: 0.015,
    leafTravel: 5,
    leafTumble: 3,
    leafCurvature: 0.0,
    leafColor1: '#ffffff',
    leafColor2: '#ddeeff',
    leafColor3: '#ffffff',
    // Postprocessing - Outline
    enabled: true,
    mode: 'glow',
    strength: 5,
    thickness: 10,
    color: '#aaccff',
    hiddenColor: '#000000',
    hiddenStrength: 0,
    glow: 0.3,
    inside: false,
    downSampleRatio: 1,
    patternScale: 8,
    patternOctaves: 3,
    patternLacunarity: 2,
    ringStride: 10,
    halftoneScale: 1,
    // Debug
    paused: false,
    wireframe: false,
    cursorCollider: true,
    debugColliders: false,
    debugColor: '#ff0000',
    cursorRadius: 0.12,
  },
};

export default PRESETS;
