export const HALO_PRESET_ORDER = [
  'Default Rings',
  'Gradient Rings',
  'Atomic',
  'Network',
  'Record',
  'Plate',
];

export const PRESETS = {
  'Default Rings': {
    haloType: 'rings',
    ringsPosition: { x: 0, y: 1.5, z: -1 },
    ringsRotation: { x: 45, y: 0, z: 0 },
    ringsVisible: true,
    ringsScale: 0.9,
    ringsStyle: 'default',
    ringsInnerRadius: 0.5,
    ringsOuterRadius: 2,
    ringsSm: 0.1,
    ringsMed: 1,
    ringsLg: 2,
    ringsXl: 3,
    ringsSilver: '#c1c1c1',
    ringsWhite: '#ffffff',
    ringsBlack: '#000000',
    ringsBlue: '#0023ff',
    ringsLightblue: '#69d8ff',
  },
  'Gradient Rings': {
    haloType: 'rings',
    ringsPosition: { x: 0, y: 1.5, z: -1 },
    ringsRotation: { x: 45, y: 0, z: 0 },
    ringsVisible: true,
    ringsScale: 0.9,
    ringsStyle: 'gradient',
    ringsInnerRadius: 0.5,
    ringsOuterRadius: 2,
    ringsStart: '#FFFFFF',
    ringsEnd: '#000000',
    ringsSteps: 8,
  },
  Atomic: {
    haloType: 'atomic',
    atomPosition: { x: 0, y: 1.5, z: -1 },
    atomRotation: { x: -45, y: 0, z: 0 },
    atomVisible: true,
    animate: false,
    atomScale: 1.05,
    atomicNumber: 8,
    atomAnimateElectrons: true,
    atomShellSpacing: 0.65,
  },
  Network: {
    haloType: 'network',
    networkPosition: { x: 0, y: 1.5, z: -1 },
    networkRotation: { x: -45, y: 0, z: 0 },
    networkVisible: true,
    animate: false,
    networkScale: 0.53,
    networkPointColor: '#ff0000',
    networkLineColor: '#000000',
    networkPointSize: 5,
    networkParticleCount: 500,
    networkMaxDistance: 0.8,
    networkAngularSpeed: 0.53,
    networkTimeScale: 0.4,
  },
  Record: {
    haloType: 'record',
    recordPosition: { x: 0, y: 1.5, z: -1 },
    recordRotation: { x: 45, y: 0, z: 0 },
    recordVisible: true,
    recordScale: 12,
    recordSideA: true,
    animate: true,
    speed: 33,
  },
  Plate: {
    haloType: 'plate',
    platePosition: { x: 0, y: 1.5, z: -1 },
    plateRotation: { x: 45, y: 0, z: 0 },
    plateVisible: true,
    plateScale: 0.18,
    animate: false,
  },
};
