export const HALO_PRESET_ORDER = [
  'Default Rings',
  'Gradient Rings',
  'Atomic',
  'Network',
  'Record',
  'Plate',
];

export const PRESETS = {
  'Default Rings': {
    haloType: 'rings',
    haloScale: 0.9,
    haloRotation: { x: 45, y: 0, z: 0 },
    ringsStyle: 'default',
    ringsInnerRadius: 0.5,
    ringsOuterRadius: 2,
    ringsSm: 0.1,
    ringsMed: 1,
    ringsLg: 2,
    ringsXl: 3,
    ringsSilver: '#c1c1c1',
    ringsWhite: '#ffffff',
    ringsBlack: '#000000',
    ringsBlue: '#0023ff',
    ringsLightblue: '#69d8ff',
  },
  'Gradient Rings': {
    haloType: 'rings',
    haloScale: 0.9,
    haloRotation: { x: 45, y: 0, z: 0 },
    ringsStyle: 'gradient',
    ringsInnerRadius: 0.5,
    ringsOuterRadius: 2,
    ringsStart: '#FFFFFF',
    ringsEnd: '#000000',
    ringsSteps: 8,
  },
  Atomic: {
    haloType: 'atomic',
    haloScale: 1.05,
    haloRotation: { x: -45, y: 0, z: 0 },
    animate: false,
    atomicNumber: 8,
    atomAnimateElectrons: true,
    atomShellSpacing: 0.65,
  },
  Network: {
    haloType: 'network',
    haloScale: 0.53,
    haloRotation: { x: -45, y: 0, z: 0 },
    animate: false,
    networkPointColor: '#ff0000',
    networkLineColor: '#000000',
    networkPointSize: 2.5,
    networkParticleCount: 500,
    networkMaxDistance: 0.8,
    networkAngularSpeed: 0.53,
    networkTimeScale: 0.4,
  },
  Record: {
    haloType: 'record',
    haloScale: 12,
    haloRotation: { x: 45, y: 0, z: 0 },
    recordSideA: true,
  },
  Plate: {
    haloType: 'plate',
    haloScale: 0.18,
    haloRotation: { x: 45, y: 0, z: 0 },
  },
};
