import React from "react";
import { useGLTF } from "@react-three/drei";
import skull from "../models/Skull.gltf";

export function Skull(props) {
  const { nodes, materials } = useGLTF(skull);
  return (
    <group {...props} dispose={null}>
      <group
        position={[-0.249, 5.881, 0.961]}
        rotation={[-2.352, 0.002, -0.08]}
      >
        <group
          position={[-0.418, -1.66, 0.931]}
          rotation={[-0.154, 0.022, 0.045]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Lower_teeth_1.geometry}
            material={materials.phong3}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mandible_2.geometry}
            material={materials.lambert5}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Left_zygomatic_1.geometry}
          material={materials.lambert5}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Occipital_1.geometry}
          material={materials.lambert5}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Right_lacrimal_1.geometry}
          material={materials.lambert5}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Right_max_1.geometry}
          material={materials.lambert5}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Right_nasal_1.geometry}
          material={materials.lambert5}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Right_palatine_1.geometry}
          material={materials.lambert5}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Right_Parietal_1.geometry}
          material={materials.lambert5}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Right_temporal_1.geometry}
          material={materials.lambert5}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Right_zygomatic_1.geometry}
          material={materials.lambert5}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sphenoid_1.geometry}
          material={materials.lambert5}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Teeth_1.geometry}
          material={materials.phong3}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Vomer_1.geometry}
          material={materials.lambert5}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Ethmoid_1.geometry}
          material={materials.lambert5}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Ethmoid_2.geometry}
          material={materials.lambert5}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Frontal_1.geometry}
          material={materials.lambert5}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Inferior_conchae_1.geometry}
          material={materials.lambert5}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Left_lacrimal_1.geometry}
          material={materials.lambert5}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Left_maxilla_1.geometry}
          material={materials.lambert5}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Left_maxilla_2.geometry}
          material={materials.lambert5}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Left_nasal_1.geometry}
          material={materials.lambert5}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Left_palatine_1.geometry}
          material={materials.lambert5}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Left_parietal_1.geometry}
          material={materials.lambert5}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Left_temporal_1.geometry}
          material={materials.lambert5}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/Skull.gltf");
