// Every knob the reference exposes on the filter, at its documented defaults.
// Scale and gully weight pull against each other: raising one while lowering the
// other sharpens peaks and valleys without changing how deep the gullies cut.
export default function getErosionControls(snapshot = {}) {
  return {
    scale: {
      label: 'Scale',
      max: 0.6,
      min: 0.02,
      step: 0.005,
      value: snapshot.scale ?? 0.15,
    },
    strength: {
      label: 'Strength',
      max: 0.6,
      min: 0,
      step: 0.005,
      value: snapshot.strength ?? 0.22,
    },
    gullyWeight: {
      label: 'Gully Weight',
      max: 1,
      min: 0,
      step: 0.01,
      value: snapshot.gullyWeight ?? 0.5,
    },
    detail: {
      label: 'Detail',
      max: 4,
      min: 0.2,
      step: 0.05,
      value: snapshot.detail ?? 1.5,
    },
    octaves: {
      label: 'Octaves',
      max: 8,
      min: 1,
      step: 1,
      value: snapshot.octaves ?? 5,
    },
    lacunarity: {
      label: 'Lacunarity',
      max: 3,
      min: 1.2,
      step: 0.05,
      value: snapshot.lacunarity ?? 2,
    },
    gain: {
      label: 'Gain',
      max: 0.9,
      min: 0.1,
      step: 0.01,
      value: snapshot.gain ?? 0.5,
    },
    ridgeRounding: {
      label: 'Ridge Rounding',
      max: 1,
      min: 0,
      step: 0.01,
      value: snapshot.ridgeRounding ?? 0.1,
    },
    creaseRounding: {
      label: 'Crease Rounding',
      max: 1,
      min: 0,
      step: 0.01,
      value: snapshot.creaseRounding ?? 0,
    },
    roundingInput: {
      label: 'Rounding / Base',
      max: 1,
      min: 0,
      step: 0.01,
      value: snapshot.roundingInput ?? 0.1,
    },
    roundingOctave: {
      label: 'Rounding / Octave',
      max: 3,
      min: 0.5,
      step: 0.05,
      value: snapshot.roundingOctave ?? 2,
    },
    onsetInput: {
      label: 'Onset / Base',
      max: 4,
      min: 0.1,
      step: 0.05,
      value: snapshot.onsetInput ?? 1.25,
    },
    onsetOctave: {
      label: 'Onset / Octave',
      max: 4,
      min: 0.1,
      step: 0.05,
      value: snapshot.onsetOctave ?? 1.25,
    },
    onsetRidgeInput: {
      label: 'Ridge Onset / Base',
      max: 6,
      min: 0.1,
      step: 0.05,
      value: snapshot.onsetRidgeInput ?? 2.8,
    },
    onsetRidgeOctave: {
      label: 'Ridge Onset / Octave',
      max: 6,
      min: 0.1,
      step: 0.05,
      value: snapshot.onsetRidgeOctave ?? 1.5,
    },
    assumedSlope: {
      label: 'Assumed Slope',
      max: 2,
      min: 0,
      step: 0.01,
      value: snapshot.assumedSlope ?? 0.7,
    },
    assumedSlopeAmount: {
      label: 'Assumed Slope Mix',
      max: 1,
      min: 0,
      step: 0.01,
      value: snapshot.assumedSlopeAmount ?? 1,
    },
    cellScale: {
      label: 'Cell Scale',
      max: 1.6,
      min: 0.2,
      step: 0.01,
      value: snapshot.cellScale ?? 0.7,
    },
    normalization: {
      label: 'Normalization',
      max: 1,
      min: 0,
      step: 0.01,
      value: snapshot.normalization ?? 0.5,
    },
    heightOffset: {
      label: 'Raise / Lower',
      max: 1,
      min: -1,
      step: 0.01,
      value: snapshot.heightOffset ?? -0.65,
    },
    heightOffsetFade: {
      label: 'Preserve Extremes',
      max: 1,
      min: 0,
      step: 0.01,
      value: snapshot.heightOffsetFade ?? 0,
    },
  };
}
