import {
  DEFAULT_WOOD_FINISH,
  DEFAULT_WOOD_GENUS,
  getWoodMaterialPresetValues,
} from '@materials/WebGPU/WoodMaterial';

const DEFAULT_TABLE_WOOD = getWoodMaterialPresetValues(
  DEFAULT_WOOD_GENUS,
  DEFAULT_WOOD_FINISH
);

const BASE_PRESET = {
  ambientIntensity: 0.95,
  backgroundColor: '#0f172a',
  cameraDesktopFov: 34,
  cameraDesktopPosition: { x: 5.8, y: 3.4, z: 8.2 },
  cameraDesktopTarget: { x: 0, y: 1.15, z: 0 },
  cameraMobileFov: 46,
  cameraMobilePosition: { x: 0, y: 3.2, z: 9.4 },
  cameraMobileTarget: { x: 0, y: 1.1, z: 0 },
  cameraMode: 'Fixed',
  directionalIntensity: 1.25,
  directionalPosition: { x: 6, y: 9, z: 4 },
  drainRate: 0.16,
  fishEscapeDistance: 1.2,
  fishBaseYOffset: 0.05,
  fishBobAmplitude: 0.08,
  fishCount: 2,
  fishFlopAmplitude: 0.95,
  fishMarkerColor: '#f472b6',
  fishMarkerSize: 0.045,
  fishRadiusX: 0.78,
  fishRadiusZ: 0.42,
  fishScale: 0.018,
  fishSpeed: 0.45,
  fishStrandLevel: 0.2,
  fishVisible: true,
  floorColor: '#bca88c',
  fogColor: '#0f172a',
  fogFar: 24,
  fogNear: 10,
  glassColor: '#dbeafe',
  glassOpacity: 0.16,
  gridColor: '#8aa1b1',
  operatorBoostMultiplier: 2,
  operatorLiftSpeed: 3,
  operatorMaxFov: 72,
  operatorMinFov: 22,
  operatorMoveSpeed: 4,
  operatorPointerLookSensitivity: 0.0025,
  operatorStickLookSpeed: 2.2,
  operatorZoomSpeed: 28,
  rockGravity: 8.5,
  rockScale: 0.7,
  rockSpeed: 40,
  rockSpin: 10,
  sandColor: '#c9a46b',
  showFishMarkers: false,
  showRapierDebug: false,
  splashBreakImpulseDuration: 0.42,
  splashBreakImpulseRadius: 4.5,
  splashBreakImpulseStrength: 2.75,
  splashColorDensity: 1.3,
  splashGravity: 0.4,
  splashMaxDelta: 0.4,
  splashParticleBudget: 'Medium',
  splashRestDensity: 3,
  splashRunning: true,
  splashShowParticles: false,
  splashSimSpeed: 12,
  splashStiffness: 50,
  splashViscosity: 0.1,
  splashWallStiffness: 1,
  spillExtent: 3.8,
  spillOpacity: 0.28,
  spillThickness: 0.045,
  showTankBounds: false,
  showWaterBounds: false,
  tableDepth: 5.98,
  tableLegDepth: 0.22,
  tableLegInset: 0.32,
  tableLegWidth: 0.22,
  tableMetalness: 0,
  tablePosition: { x: 0, y: 1.1, z: 0 },
  tableRoughness: 0.78,
  tableThickness: 0.18,
  tableWidth: 7.95,
  tableWoodBarkThickness: DEFAULT_TABLE_WOOD.barkThickness,
  tableWoodCellScale: DEFAULT_TABLE_WOOD.cellScale,
  tableWoodCellSize: DEFAULT_TABLE_WOOD.cellSize,
  tableWoodCenterSize: DEFAULT_TABLE_WOOD.centerSize,
  tableWoodClearcoat: DEFAULT_TABLE_WOOD.clearcoat,
  tableWoodClearcoatRoughness: DEFAULT_TABLE_WOOD.clearcoatRoughness,
  tableWoodDarkGrainColor: DEFAULT_TABLE_WOOD.darkGrainColor,
  tableWoodFineWarpScale: DEFAULT_TABLE_WOOD.fineWarpScale,
  tableWoodFineWarpStrength: DEFAULT_TABLE_WOOD.fineWarpStrength,
  tableWoodFinish: DEFAULT_WOOD_FINISH,
  tableWoodGrainOffset: { x: 0, y: 0, z: 0 },
  tableWoodGrainRotation: { x: 0, y: 0, z: 0 },
  tableWoodGrainScale: { x: 1, y: 1, z: 1 },
  tableWoodGenus: DEFAULT_WOOD_GENUS,
  tableWoodLargeGrainStretch: DEFAULT_TABLE_WOOD.largeGrainStretch,
  tableWoodLargeWarpScale: DEFAULT_TABLE_WOOD.largeWarpScale,
  tableWoodLightGrainColor: DEFAULT_TABLE_WOOD.lightGrainColor,
  tableWoodRingBias: DEFAULT_TABLE_WOOD.ringBias,
  tableWoodRingSizeVariance: DEFAULT_TABLE_WOOD.ringSizeVariance,
  tableWoodRingThickness: DEFAULT_TABLE_WOOD.ringThickness,
  tableWoodRingVarianceScale: DEFAULT_TABLE_WOOD.ringVarianceScale,
  tableWoodSmallWarpScale: DEFAULT_TABLE_WOOD.smallWarpScale,
  tableWoodSmallWarpStrength: DEFAULT_TABLE_WOOD.smallWarpStrength,
  tableWoodSplotchIntensity: DEFAULT_TABLE_WOOD.splotchIntensity,
  tableWoodSplotchScale: DEFAULT_TABLE_WOOD.splotchScale,
  tankDepth: 1.8,
  tankHeight: 2.2,
  tankPosition: { x: 0, y: 1.2, z: 0 },
  tankRotation: { x: 0, y: 0, z: 0 },
  tankScale: 1,
  tankVisible: true,
  tankWidth: 3.2,
  waterColor: '#4cc9f0',
  waterDisturbance: 0.09,
  waterInset: 0.12,
  waterLevel: 0.78,
  glassThickness: 0.06,
};

const SCENE_PRESETS = {
  Default: {
    ...BASE_PRESET,
  },
  Orbit: {
    ...BASE_PRESET,
    backgroundColor: '#111827',
    cameraMode: 'Orbit',
    fogFar: 26,
    waterLevel: 0.72,
  },
  Operator: {
    ...BASE_PRESET,
    cameraMode: 'Operator',
    fishSpeed: 0.55,
    waterLevel: 0.68,
  },
  Debug: {
    ...BASE_PRESET,
    backgroundColor: '#020617',
    cameraMode: 'Orbit',
    showFishMarkers: true,
    showRapierDebug: true,
    showTankBounds: true,
    showWaterBounds: true,
    waterLevel: 0.58,
  },
};

export default SCENE_PRESETS;
