// Selectable ghost skins: character-only prop sets for the shared
// BaseGhostCharacter element. Values are lifted from GhostBuster's preset
// bible (kept as data here — scenes never import another scene's presets).
// Start with Hero; more skins get added as flat entries when wanted.
const GHOST_SKINS = {
  Hero: {
    alphaScale: 4,
    alphaSeed: 42,
    baseWind: 0.3,
    bobAmplitude: 0.03,
    bobSpeed: 0.5,
    clothHeight: 1.0,
    clothWidth: 1.0,
    color: '#ffffff',
    cutoutRimColor: '#000000',
    cutoutRimOffset: 0,
    cutoutRimWidth: 0.003,
    dampening: 0.99,
    edgeFade: 0.15,
    emissiveCenterU: 0.5,
    emissiveCenterV: 0.4,
    emissiveFalloff: 2.5,
    envMapIntensity: 1,
    eyeColor: '#000000',
    eyeIntensity: 0.2,
    gravity: 0.00012,
    handHeight: 0.3,
    handSize: 0.05,
    handSpacing: 0.3,
    handSpring: 8,
    handTrail: 0.08,
    holeAmount: 0,
    innerColor: '#cc2222',
    innerEmissiveColor: '#88ccff',
    innerEmissiveIntensity: 0,
    innerMetalness: 0,
    innerRoughness: 0.8,
    maxVelocity: 0.01,
    metalness: 0,
    outerEmissiveColor: '#88ccff',
    outerEmissiveIntensity: 0,
    roughness: 0.8,
    smoothEdges: false,
    squashIntensity: 0.3,
    stiffness: 0.16,
    swayAmplitude: 0.02,
    tatterEdge: 0,
    tiltIntensity: 0.3,
    windAmplitude: 0.0004,
    windBoostMul: 2,
  },
};

export default GHOST_SKINS;
