import React from 'react';

import { useGLTF } from '@react-three/drei';

import { modelFile } from '../../../utils/appUtils';

export default function FishTank(props) {
  const { nodes, materials } = useGLTF(modelFile('/fishTank.glb'));
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.rubber.geometry}
        material={materials.rubber}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.plastic_1.geometry}
        material={materials.plastic_1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.glass_left.geometry}
        material={materials.glass}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.rock_1.geometry}
        material={materials.rock_1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.sand.geometry}
        material={materials.sand}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.rock_3.geometry}
        material={materials.rock_3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.rock_4.geometry}
        material={materials.rock_4}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.rock_5.geometry}
        material={materials.rock_5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.rock_6.geometry}
        material={materials.rock_6}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.rock_7.geometry}
        material={materials.rock_7}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.rock_2.geometry}
        material={materials.rock_2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.stone.geometry}
        material={materials.stone}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.glass_2.geometry}
        material={materials.glass_2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.glass_5.geometry}
        material={materials.glass_5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.glass_back.geometry}
        material={materials.glass}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.glass_right.geometry}
        material={materials.glass}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.glass_front.geometry}
        material={materials.glass}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.plastic_2.geometry}
        material={materials.plastic_1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.lid_1.geometry}
        material={materials.plastic_1}
      />
    </group>
  );
}

useGLTF.preload(modelFile('/fishTank.glb'));
