import { MAX_PARTICLES } from '../utils/domain';

export const DEFAULT_PRESET = 'Data Structure';

const BASE = {
  cameraMode: 'orbit',
  orbitAutoRotate: true,
  orbitAutoRotateSpeed: 0.35,

  runSimulation: true,
  particles: 65536,
  speed: 1,
  gravity: 78,
  fluidity: 0.96,
  turbulence: 0.09,
  pressureIterations: 20,
  targetDensity: 3,
  densityCorrection: 1,

  sourceRadius: 3.2,
  sourceSpeed: 0,
  sourceHeight: 50,
  sourceOrbitRadius: 6,
  sourceOrbitSpeed: 0.07,
  sourceOrbitBob: 2,
  sourceOffsetX: 0,
  sourceOffsetZ: 0,
  pourRate: 16000,
  drainHeight: 16,
  maxAge: 30,

  showFluid: true,
  fluidRenderMode: 'Solid',
  particleScale: 1,
  particleSoftness: 0.06,
  fluidOpacity: 1,
  particleMaxPixels: 96,
  sortPasses: 0,
  fluidShading: 1,
  fluidSpecular: 0.8,
  fluidGloss: 32,
  fluidRim: 0.25,
  fluidLightGain: 1.1,
  fluidAmbient: 0.1,
  shadowDensity: 0.32,
  shadowSolid: 1.4,
  shadowReach: 28,
  shadowBias: 1.5,
  fluidColorCold: '#2b0b3a',
  fluidColorWarm: '#ff4a10',
  fluidColorHot: '#fff1c4',
  fluidEmissive: 2.2,
  heatGain: 1.1,
  heatBias: -0.05,
  heatGamma: 1.5,
  speedHeat: 0.25,

  showPins: true,
  showPlate: true,
  solidColor: '#e9e9ef',
  pinCount: 7,
  pinRadius: 2.2,
  pinLength: 15,
  pinSpread: 6.5,
  pinTilt: 0.35,
  pinSeed: 7,
  plateY: 30,
  plateSize: 17,
  plateThickness: 1.6,
  solidFriction: 0.12,
  solidRestitution: 0,

  showGrid: true,
  gridColor: '#c8dcff',
  gridFluidLevel: 0,
  gridSolidLevel: 2,
  gridFineOpacity: 0.26,
  gridCoarseOpacity: 0.24,
  gridFalloff: 1.1,
  gridMargin: 1,
  gridInset: 0.98,

  backgroundColor: '#000000',
  showBounds: false,
  boundsColor: '#2a3550',
};

export const PRESETS = {
  'Data Structure': { ...BASE },
  'Raw Pour': {
    ...BASE,
    showGrid: false,
    fluidEmissive: 1.2,
    heatGain: 0.8,
    backgroundColor: '#05060a',
  },
  Scaffold: {
    ...BASE,
    showFluid: false,
    gridColor: '#ffffff',
    gridFineOpacity: 0.75,
    gridCoarseOpacity: 0.1,
    solidColor: '#1c1e26',
    showBounds: true,
  },
  'Cold Sludge': {
    ...BASE,
    fluidity: 0.55,
    turbulence: 0.02,
    gravity: 40,
    sourceSpeed: 0,
    fluidRenderMode: 'Alpha',
    fluidOpacity: 0.55,
    particleSoftness: 0.45,
    particleScale: 1.4,
    sortPasses: 12,
    fluidShading: 0.6,
    fluidSpecular: 0.3,
    fluidColorWarm: '#2f6bff',
    fluidColorHot: '#dff0ff',
    fluidColorCold: '#06091c',
    fluidEmissive: 1.1,
    gridColor: '#5f7dff',
  },
  'Glossy Liquid': {
    ...BASE,
    particles: MAX_PARTICLES,
    fluidity: 0.88,
    turbulence: 0.04,
    pressureIterations: 28,
    fluidRenderMode: 'Solid',
    particleScale: 0.9,
    particleSoftness: 0.04,
    fluidShading: 1,
    fluidSpecular: 1.1,
    fluidGloss: 64,
    fluidRim: 0.45,
    fluidLightGain: 1,
    fluidAmbient: 0.06,
    shadowDensity: 0.5,
    shadowSolid: 2,
    shadowReach: 34,
    fluidColorCold: '#1b0a2e',
    fluidColorWarm: '#ff4a10',
    fluidColorHot: '#ffd9a0',
    fluidEmissive: 0.35,
    heatGain: 1.2,
    heatGamma: 1.8,
    gridFineOpacity: 0.18,
    gridCoarseOpacity: 0.1,
  },
  'Particulate Smoke': {
    ...BASE,
    particles: MAX_PARTICLES,
    gravity: 18,
    fluidity: 0.99,
    turbulence: 0.3,
    fluidRenderMode: 'Additive',
    particleScale: 2.2,
    particleSoftness: 1,
    fluidOpacity: 0.05,
    particleMaxPixels: 128,
    sortPasses: 0,
    fluidShading: 0.15,
    fluidSpecular: 0,
    fluidRim: 0,
    fluidLightGain: 1.4,
    fluidAmbient: 0.05,
    shadowDensity: 0.55,
    shadowSolid: 1.8,
    shadowReach: 40,
    fluidColorCold: '#140a24',
    fluidColorWarm: '#ff6a22',
    fluidColorHot: '#ffeccc',
    fluidEmissive: 1.6,
    showGrid: false,
  },
};

export function getPresetControls({ presetSnapshot }) {
  return { ...presetSnapshot };
}
