// Preset snapshots for the scene. Keys here must match the Leva schema built
// in useSceneControls 1:1 — no reshaping between a preset and the controls it
// applies (see docs/scene-conventions.md, "Controls & presets").
export const DEFAULT_PRESET = 'Default';

export const PRESETS = {
  Default: {
    cameraMode: 'orbit',
    cameraAutoFit: true,
    fixedBehavior: 'single',
    fixedShotDefaultDesktopPosition: {
      x: 0,
      y: 0,
      z: 9,
    },
    fixedShotDefaultDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    fixedShotDefaultDesktopFov: 40,
    fixedShotDefaultMobilePosition: {
      x: 0,
      y: 0,
      z: 9,
    },
    fixedShotDefaultMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    fixedShotDefaultMobileFov: 40,
    orbitAutoRotate: false,
    orbitAutoRotateSpeed: 2,
    orbitEnablePan: true,
    orbitMinPolarAngle: 0,
    orbitMaxPolarAngle: 180,
    orbitAzimuthUnlimited: true,
    orbitMinAzimuthAngle: -180,
    orbitMaxAzimuthAngle: 180,
    orbitMinDistance: 0,
    orbitMaxDistanceUnlimited: true,
    orbitMaxDistance: 100,
    orbitDesktopPosition: {
      x: 0,
      y: 0,
      z: 9,
    },
    orbitDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitDesktopPivot: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitDesktopFov: 40,
    orbitMobilePosition: {
      x: 0,
      y: 0,
      z: 12,
    },
    orbitMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitMobilePivot: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitMobileFov: 45,
    splineDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineDesktopFov: 40,
    splineMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineMobileFov: 40,
    splineOrientationMode: 'target',
    splineForwardDistance: 1,
    splinePosition: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineScale: {
      x: 1,
      y: 1,
      z: 1,
    },
    splineDuration: 30,
    splineTension: 0.5,
    splineClosed: true,
    splineShowPath: false,
    operatorMoveSpeed: 6,
    operatorLiftSpeed: 6,
    operatorBoostMultiplier: 2,
    operatorPointerLookSensitivity: 0.003,
    operatorStickLookSpeed: 2.5,
    operatorZoomSpeed: 24,
    operatorMinFov: 20,
    operatorMaxFov: 80,
    gridMode: 'square',
    gridCols: 10,
    gridRows: 10,
    hexRadius: 6,
    cellSize: 0.5,
    straightTileChance: 0.28,
    layerBiasAmount: 0,
    weaveEnabled: true,
    weaveGapWidth: 0,
    strokePitch: 0.096,
    strokeWidth: 0.066,
    fillMode: 'line',
    fillWidth: 0.16,
    bgColor: '#ff0000',
    strokeColor: '#141414',
    sceneBgColor: '#919191',
    clipShape: 'circle',
    clipCornerRadius: 0.3,
    clipRotation: 0,
    borderInset: 0,
    borderVisible: true,
    borderThickness: 0.05,
    borderColor: '#141414',
    planeRotation: 45,
    showGridLines: false,
    gridLineColor: '#999999',
    gridLineWidth: 0.01,
    seed: 1,
    animMode: 'ySpin',
    animSpeed: 0.9,
    retileRate: 4,
    animStagger: 0.6,
  },
};

// Companion fn to usePresetsFolder. Given the snapshot for the preset being
// applied, return the control values to set.
export function getPresetControls({ presetSnapshot }) {
  return { ...presetSnapshot };
}
