// Preset snapshots for the scene. Keys here must match the Leva schema built
// in useSceneControls 1:1 — no reshaping between a preset and the controls it
// applies (see docs/scene-conventions.md, "Controls & presets").
export const DEFAULT_PRESET = '001';

export const PRESETS = {
  '001': {
    cameraMode: 'orbit',
    cameraAutoFit: true,
    fixedBehavior: 'single',
    fixedShotDefaultDesktopPosition: {
      x: 0,
      y: 0,
      z: 9,
    },
    fixedShotDefaultDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    fixedShotDefaultDesktopFov: 40,
    fixedShotDefaultMobilePosition: {
      x: 0,
      y: 0,
      z: 9,
    },
    fixedShotDefaultMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    fixedShotDefaultMobileFov: 40,
    orbitAutoRotate: false,
    orbitAutoRotateSpeed: 2,
    orbitEnablePan: true,
    orbitMinPolarAngle: 0,
    orbitMaxPolarAngle: 180,
    orbitAzimuthUnlimited: true,
    orbitMinAzimuthAngle: -180,
    orbitMaxAzimuthAngle: 180,
    orbitMinDistance: 0,
    orbitMaxDistanceUnlimited: true,
    orbitMaxDistance: 100,
    orbitDesktopPosition: {
      x: 0,
      y: 0,
      z: 9,
    },
    orbitDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitDesktopPivot: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitDesktopFov: 40,
    orbitMobilePosition: {
      x: 0,
      y: 0,
      z: 12,
    },
    orbitMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitMobilePivot: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitMobileFov: 45,
    splineDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineDesktopFov: 40,
    splineMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineMobileFov: 40,
    splineOrientationMode: 'target',
    splineForwardDistance: 1,
    splinePosition: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineScale: {
      x: 1,
      y: 1,
      z: 1,
    },
    splineDuration: 30,
    splineTension: 0.5,
    splineClosed: true,
    splineShowPath: false,
    operatorMoveSpeed: 6,
    operatorLiftSpeed: 6,
    operatorBoostMultiplier: 2,
    operatorPointerLookSensitivity: 0.003,
    operatorStickLookSpeed: 2.5,
    operatorZoomSpeed: 24,
    operatorMinFov: 20,
    operatorMaxFov: 80,
    gridMode: 'square',
    gridCols: 10,
    gridRows: 10,
    hexRadius: 6,
    cellSize: 0.5,
    straightTileChance: 0.28,
    layerBiasAmount: 0,
    weaveEnabled: true,
    multiscaleEnabled: false,
    splitProbability: 0.7,
    minGeneration: 1,
    maxGeneration: 4,
    lanesEnabled: false,
    resubdivideEnabled: false,
    resubdivideInterval: 6,
    weaveGapWidth: 0,
    strokePitch: 0.096,
    strokeWidth: 0.066,
    fillMode: 'line',
    fillWidth: 0.16,
    bgColor: '#ff0000',
    strokeColor: '#141414',
    sceneBgColor: '#919191',
    clipShape: 'circle',
    clipCornerRadius: 0.3,
    clipRotation: 0,
    borderInset: 0,
    borderVisible: true,
    borderThickness: 0.05,
    borderColor: '#141414',
    planeRotation: 45,
    showGridLines: false,
    gridLineColor: '#999999',
    gridLineWidth: 0.01,
    seed: 1,
    blobSeed: 'Change me, empty seed means random',
    blobGridSize: 25,
    blobCanvasSize: 8,
    blobPathsPerUnit: 6,
    blobSizeFunction: '1+(gridSize/9)*Math.random()',
    blobDistribution: 0.1,
    blobConnectivity: 0.95,
    blobOneFill: 0.25,
    blobHoles: 0,
    blobMeatballs: 2,
    blobPalette: 'None',
    blobLaneMode: 'Cycle',
    blobPaletteExact: true,
    blobPaletteShuffle: 0,
    blobShowStrokes: true,
    blobDebug: 0,
    animMode: 'ySpin',
    animSpeed: 0.9,
    retileRate: 4,
    animStagger: 0.6,
  },
  '002': {
    cameraMode: 'orbit',
    cameraAutoFit: true,
    fixedBehavior: 'single',
    fixedShotDefaultDesktopPosition: {
      x: 0,
      y: 0,
      z: 9,
    },
    fixedShotDefaultDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    fixedShotDefaultDesktopFov: 40,
    fixedShotDefaultMobilePosition: {
      x: 0,
      y: 0,
      z: 9,
    },
    fixedShotDefaultMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    fixedShotDefaultMobileFov: 40,
    orbitAutoRotate: false,
    orbitAutoRotateSpeed: 2,
    orbitEnablePan: true,
    orbitMinPolarAngle: 0,
    orbitMaxPolarAngle: 180,
    orbitAzimuthUnlimited: true,
    orbitMinAzimuthAngle: -180,
    orbitMaxAzimuthAngle: 180,
    orbitMinDistance: 0,
    orbitMaxDistanceUnlimited: true,
    orbitMaxDistance: 100,
    orbitDesktopPosition: {
      x: 0,
      y: 0,
      z: 9,
    },
    orbitDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitDesktopPivot: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitDesktopFov: 40,
    orbitMobilePosition: {
      x: 0,
      y: 0,
      z: 12,
    },
    orbitMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitMobilePivot: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitMobileFov: 45,
    splineDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineDesktopFov: 40,
    splineMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineMobileFov: 40,
    splineOrientationMode: 'target',
    splineForwardDistance: 1,
    splinePosition: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineScale: {
      x: 1,
      y: 1,
      z: 1,
    },
    splineDuration: 30,
    splineTension: 0.5,
    splineClosed: true,
    splineShowPath: false,
    operatorMoveSpeed: 6,
    operatorLiftSpeed: 6,
    operatorBoostMultiplier: 2,
    operatorPointerLookSensitivity: 0.003,
    operatorStickLookSpeed: 2.5,
    operatorZoomSpeed: 24,
    operatorMinFov: 20,
    operatorMaxFov: 80,
    gridMode: 'square',
    gridCols: 10,
    gridRows: 10,
    hexRadius: 6,
    cellSize: 0.5,
    straightTileChance: 0.28,
    layerBiasAmount: 0,
    weaveEnabled: false,
    multiscaleEnabled: true,
    splitProbability: 0.7,
    minGeneration: 0,
    maxGeneration: 2,
    lanesEnabled: false,
    resubdivideEnabled: false,
    resubdivideInterval: 6,
    weaveGapWidth: 0,
    strokePitch: 0.063,
    strokeWidth: 0.045,
    fillMode: 'line',
    fillWidth: 0.16,
    bgColor: '#ff0000',
    strokeColor: '#141414',
    sceneBgColor: '#919191',
    clipShape: 'circle',
    clipCornerRadius: 0.3,
    clipRotation: 0,
    borderInset: 0,
    borderVisible: true,
    borderThickness: 0.05,
    borderColor: '#141414',
    planeRotation: 45,
    showGridLines: false,
    gridLineColor: '#999999',
    gridLineWidth: 0.01,
    seed: 1,
    blobSeed: 'Change me, empty seed means random',
    blobGridSize: 25,
    blobCanvasSize: 8,
    blobPathsPerUnit: 6,
    blobSizeFunction: '1+(gridSize/9)*Math.random()',
    blobDistribution: 0.1,
    blobConnectivity: 0.95,
    blobOneFill: 0.25,
    blobHoles: 0,
    blobMeatballs: 2,
    blobPalette: 'None',
    blobLaneMode: 'Cycle',
    blobPaletteExact: true,
    blobPaletteShuffle: 0,
    blobShowStrokes: true,
    blobDebug: 0,
    retileEnabled: true,
    animMode: 'ySpin',
    animSpeed: 0.9,
    retileRate: 4,
    animStagger: 0.6,
  },
  '003': {
    cameraMode: 'orbit',
    cameraAutoFit: true,
    fixedBehavior: 'single',
    fixedShotDefaultDesktopPosition: {
      x: 0,
      y: 0,
      z: 9,
    },
    fixedShotDefaultDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    fixedShotDefaultDesktopFov: 40,
    fixedShotDefaultMobilePosition: {
      x: 0,
      y: 0,
      z: 9,
    },
    fixedShotDefaultMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    fixedShotDefaultMobileFov: 40,
    orbitAutoRotate: false,
    orbitAutoRotateSpeed: 2,
    orbitEnablePan: true,
    orbitMinPolarAngle: 0,
    orbitMaxPolarAngle: 180,
    orbitAzimuthUnlimited: true,
    orbitMinAzimuthAngle: -180,
    orbitMaxAzimuthAngle: 180,
    orbitMinDistance: 0,
    orbitMaxDistanceUnlimited: true,
    orbitMaxDistance: 100,
    orbitDesktopPosition: {
      x: 0,
      y: 0,
      z: 9,
    },
    orbitDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitDesktopPivot: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitDesktopFov: 40,
    orbitMobilePosition: {
      x: 0,
      y: 0,
      z: 12,
    },
    orbitMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitMobilePivot: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitMobileFov: 45,
    splineDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineDesktopFov: 40,
    splineMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineMobileFov: 40,
    splineOrientationMode: 'target',
    splineForwardDistance: 1,
    splinePosition: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineScale: {
      x: 1,
      y: 1,
      z: 1,
    },
    splineDuration: 30,
    splineTension: 0.5,
    splineClosed: true,
    splineShowPath: false,
    operatorMoveSpeed: 6,
    operatorLiftSpeed: 6,
    operatorBoostMultiplier: 2,
    operatorPointerLookSensitivity: 0.003,
    operatorStickLookSpeed: 2.5,
    operatorZoomSpeed: 24,
    operatorMinFov: 20,
    operatorMaxFov: 80,
    gridMode: 'field',
    gridCols: 10,
    gridRows: 10,
    hexRadius: 6,
    cellSize: 0.5,
    straightTileChance: 0.28,
    layerBiasAmount: 0,
    weaveEnabled: true,
    multiscaleEnabled: false,
    splitProbability: 0.7,
    minGeneration: 1,
    maxGeneration: 4,
    lanesEnabled: false,
    resubdivideEnabled: false,
    resubdivideInterval: 6,
    weaveGapWidth: 0,
    strokePitch: 0.096,
    strokeWidth: 0.016,
    fillMode: 'line',
    fillWidth: 0.16,
    bgColor: '#ff0000',
    strokeColor: '#141414',
    sceneBgColor: '#ffffff',
    clipShape: 'none',
    clipCornerRadius: 0.3,
    clipRotation: 0,
    borderInset: 0,
    borderVisible: false,
    borderThickness: 0.05,
    borderColor: '#141414',
    planeRotation: 0,
    showGridLines: false,
    gridLineColor: '#999999',
    gridLineWidth: 0.01,
    seed: 1,
    blobSeed: 'Change me, empty seed means random',
    blobGridSize: 25,
    blobCanvasSize: 8,
    blobPathsPerUnit: 6,
    blobSizeFunction: '1+(gridSize/9)*Math.random()',
    blobDistribution: 0.1,
    blobConnectivity: 0.95,
    blobOneFill: 0.25,
    blobHoles: 0,
    blobMeatballs: 2,
    blobPalette: 'None',
    blobLaneMode: 'Cycle',
    blobPaletteExact: true,
    blobPaletteShuffle: 0,
    blobShowStrokes: true,
    blobDebug: 0,
    retileEnabled: false,
    animMode: 'ySpin',
    animSpeed: 0.9,
    retileRate: 4,
    animStagger: 0.6,
  },
  '004': {
    cameraMode: 'orbit',
    cameraAutoFit: true,
    fixedBehavior: 'single',
    fixedShotDefaultDesktopPosition: {
      x: 0,
      y: 0,
      z: 9,
    },
    fixedShotDefaultDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    fixedShotDefaultDesktopFov: 40,
    fixedShotDefaultMobilePosition: {
      x: 0,
      y: 0,
      z: 9,
    },
    fixedShotDefaultMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    fixedShotDefaultMobileFov: 40,
    orbitAutoRotate: false,
    orbitAutoRotateSpeed: 2,
    orbitEnablePan: true,
    orbitMinPolarAngle: 0,
    orbitMaxPolarAngle: 180,
    orbitAzimuthUnlimited: true,
    orbitMinAzimuthAngle: -180,
    orbitMaxAzimuthAngle: 180,
    orbitMinDistance: 0,
    orbitMaxDistanceUnlimited: true,
    orbitMaxDistance: 100,
    orbitDesktopPosition: {
      x: 0,
      y: 0,
      z: 9,
    },
    orbitDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitDesktopPivot: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitDesktopFov: 40,
    orbitMobilePosition: {
      x: 0,
      y: 0,
      z: 12,
    },
    orbitMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitMobilePivot: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitMobileFov: 45,
    splinePreset: 'Loop de Loop',
    splineDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineDesktopFov: 40,
    splineMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineMobileFov: 40,
    splineOrientationMode: 'target',
    splineForwardDistance: 1,
    splinePosition: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineScale: {
      x: 1,
      y: 1,
      z: 1,
    },
    splineDuration: 30,
    splineTension: 0.5,
    splineClosed: true,
    splineShowPath: false,
    operatorMoveSpeed: 6,
    operatorLiftSpeed: 6,
    operatorBoostMultiplier: 2,
    operatorPointerLookSensitivity: 0.003,
    operatorStickLookSpeed: 2.5,
    operatorZoomSpeed: 24,
    operatorMinFov: 20,
    operatorMaxFov: 80,
    gridMode: 'field',
    gridCols: 10,
    gridRows: 10,
    hexRadius: 6,
    cellSize: 0.5,
    seed: 1,
    blobSeed: 'Change me, empty seed means random',
    blobGridSize: 44,
    blobCanvasSize: 8,
    blobPathsPerUnit: 5,
    blobSizeFunction: '2+(gridSize/2)*Math.random()',
    blobDistribution: 0.75,
    blobConnectivity: 0.95,
    blobOneFill: 0.48,
    blobHoles: 0,
    blobMeatballs: 2,
    blobPalette: 'Cobalt Desert 7 (lospec)',
    blobLaneMode: 'Depth',
    blobPaletteExact: false,
    blobPaletteShuffle: 256975,
    blobShowStrokes: true,
    blobDebug: 0,
    straightTileChance: 0.28,
    layerBiasAmount: 0,
    weaveEnabled: true,
    weaveGapWidth: 0,
    lanesEnabled: false,
    multiscaleEnabled: false,
    splitProbability: 0.7,
    minGeneration: 1,
    maxGeneration: 4,
    resubdivideEnabled: false,
    resubdivideInterval: 6,
    strokePitch: 0.096,
    strokeWidth: 0.016,
    fillMode: 'line',
    fillWidth: 0.16,
    bgColor: '#ff0000',
    strokeColor: '#141414',
    sceneBgColor: '#ffffff',
    clipShape: 'none',
    clipCornerRadius: 0.3,
    clipRotation: 0,
    borderInset: 0,
    borderVisible: false,
    borderThickness: 0.05,
    borderColor: '#141414',
    planeRotation: -45,
    showGridLines: false,
    gridLineColor: '#999999',
    gridLineWidth: 0.01,
    retileEnabled: false,
    animMode: 'ySpin',
    animSpeed: 0.9,
    retileRate: 4,
    animStagger: 0.6,
  },
  '005': {
    cameraMode: 'orbit',
    cameraAutoFit: true,
    fixedBehavior: 'single',
    fixedShotDefaultDesktopPosition: {
      x: 0,
      y: 0,
      z: 9,
    },
    fixedShotDefaultDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    fixedShotDefaultDesktopFov: 40,
    fixedShotDefaultMobilePosition: {
      x: 0,
      y: 0,
      z: 9,
    },
    fixedShotDefaultMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    fixedShotDefaultMobileFov: 40,
    orbitAutoRotate: false,
    orbitAutoRotateSpeed: 2,
    orbitEnablePan: true,
    orbitMinPolarAngle: 0,
    orbitMaxPolarAngle: 180,
    orbitAzimuthUnlimited: true,
    orbitMinAzimuthAngle: -180,
    orbitMaxAzimuthAngle: 180,
    orbitMinDistance: 0,
    orbitMaxDistanceUnlimited: true,
    orbitMaxDistance: 100,
    orbitDesktopPosition: {
      x: 0,
      y: 0,
      z: 9,
    },
    orbitDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitDesktopPivot: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitDesktopFov: 40,
    orbitMobilePosition: {
      x: 0,
      y: 0,
      z: 12,
    },
    orbitMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitMobilePivot: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitMobileFov: 45,
    splinePreset: 'Loop de Loop',
    splineDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineDesktopFov: 40,
    splineMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineMobileFov: 40,
    splineOrientationMode: 'target',
    splineForwardDistance: 1,
    splinePosition: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineScale: {
      x: 1,
      y: 1,
      z: 1,
    },
    splineDuration: 30,
    splineTension: 0.5,
    splineClosed: true,
    splineShowPath: false,
    operatorMoveSpeed: 6,
    operatorLiftSpeed: 6,
    operatorBoostMultiplier: 2,
    operatorPointerLookSensitivity: 0.003,
    operatorStickLookSpeed: 2.5,
    operatorZoomSpeed: 24,
    operatorMinFov: 20,
    operatorMaxFov: 80,
    gridMode: 'field',
    gridCols: 10,
    gridRows: 10,
    hexRadius: 6,
    cellSize: 0.5,
    seed: 1,
    blobSeed: 'Change me, empty seed means random',
    blobGridSize: 44,
    blobCanvasSize: 8,
    blobPathsPerUnit: 5,
    blobSizeFunction: '2+(gridSize)*Math.random()',
    blobDistribution: 0.75,
    blobConnectivity: 0.95,
    blobOneFill: 0.48,
    blobHoles: 0,
    blobMeatballs: 2,
    blobPalette: 'Exophobia (lospec)',
    blobLaneMode: 'Depth',
    blobPaletteExact: false,
    blobPaletteShuffle: 532319,
    blobShowStrokes: true,
    blobDebug: 0,
    straightTileChance: 0.28,
    layerBiasAmount: 0,
    weaveEnabled: true,
    weaveGapWidth: 0,
    lanesEnabled: false,
    multiscaleEnabled: false,
    splitProbability: 0.7,
    minGeneration: 1,
    maxGeneration: 4,
    resubdivideEnabled: false,
    resubdivideInterval: 6,
    strokePitch: 0.096,
    strokeWidth: 0.016,
    fillMode: 'line',
    fillWidth: 0.16,
    bgColor: '#ff0000',
    strokeColor: '#646464',
    sceneBgColor: '#000000',
    clipShape: 'none',
    clipCornerRadius: 0.3,
    clipRotation: 0,
    borderInset: 0,
    borderVisible: false,
    borderThickness: 0.05,
    borderColor: '#141414',
    planeRotation: -45,
    showGridLines: false,
    gridLineColor: '#999999',
    gridLineWidth: 0.01,
    retileEnabled: false,
    animMode: 'ySpin',
    animSpeed: 0.9,
    retileRate: 4,
    animStagger: 0.6,
  },
  '006': {
    cameraMode: 'orbit',
    cameraAutoFit: true,
    fixedBehavior: 'single',
    fixedShotDefaultDesktopPosition: {
      x: 0,
      y: 0,
      z: 9,
    },
    fixedShotDefaultDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    fixedShotDefaultDesktopFov: 40,
    fixedShotDefaultMobilePosition: {
      x: 0,
      y: 0,
      z: 9,
    },
    fixedShotDefaultMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    fixedShotDefaultMobileFov: 40,
    orbitAutoRotate: false,
    orbitAutoRotateSpeed: 2,
    orbitEnablePan: true,
    orbitMinPolarAngle: 0,
    orbitMaxPolarAngle: 180,
    orbitAzimuthUnlimited: true,
    orbitMinAzimuthAngle: -180,
    orbitMaxAzimuthAngle: 180,
    orbitMinDistance: 0,
    orbitMaxDistanceUnlimited: true,
    orbitMaxDistance: 100,
    orbitDesktopPosition: {
      x: 0,
      y: 0,
      z: 9,
    },
    orbitDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitDesktopPivot: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitDesktopFov: 40,
    orbitMobilePosition: {
      x: 0,
      y: 0,
      z: 12,
    },
    orbitMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitMobilePivot: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitMobileFov: 45,
    splinePreset: 'Loop de Loop',
    splineDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineDesktopFov: 40,
    splineMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineMobileFov: 40,
    splineOrientationMode: 'target',
    splineForwardDistance: 1,
    splinePosition: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineScale: {
      x: 1,
      y: 1,
      z: 1,
    },
    splineDuration: 30,
    splineTension: 0.5,
    splineClosed: true,
    splineShowPath: false,
    operatorMoveSpeed: 6,
    operatorLiftSpeed: 6,
    operatorBoostMultiplier: 2,
    operatorPointerLookSensitivity: 0.003,
    operatorStickLookSpeed: 2.5,
    operatorZoomSpeed: 24,
    operatorMinFov: 20,
    operatorMaxFov: 80,
    gridMode: 'field',
    gridCols: 10,
    gridRows: 10,
    hexRadius: 6,
    cellSize: 0.5,
    seed: 1,
    blobSeed: '666',
    blobGridSize: 44,
    blobCanvasSize: 8,
    blobPathsPerUnit: 5,
    blobSizeFunction: '2+(gridSize)*Math.random()',
    blobDistribution: 0.75,
    blobConnectivity: 0.95,
    blobOneFill: 0.48,
    blobHoles: 0,
    blobMeatballs: 2,
    blobPalette: 'Rettiepunk (lospec)',
    blobLaneMode: 'Depth',
    blobPaletteExact: false,
    blobPaletteShuffle: 957916,
    blobShowStrokes: true,
    blobDebug: 0,
    straightTileChance: 0.28,
    layerBiasAmount: 0,
    weaveEnabled: true,
    weaveGapWidth: 0,
    lanesEnabled: false,
    multiscaleEnabled: false,
    splitProbability: 0.7,
    minGeneration: 1,
    maxGeneration: 4,
    resubdivideEnabled: false,
    resubdivideInterval: 6,
    strokePitch: 0.096,
    strokeWidth: 0.016,
    fillMode: 'line',
    fillWidth: 0.16,
    bgColor: '#ff0000',
    strokeColor: '#646464',
    sceneBgColor: '#000000',
    clipShape: 'none',
    clipCornerRadius: 0.3,
    clipRotation: 0,
    borderInset: 0,
    borderVisible: false,
    borderThickness: 0.05,
    borderColor: '#141414',
    planeRotation: -45,
    showGridLines: false,
    gridLineColor: '#999999',
    gridLineWidth: 0.01,
    retileEnabled: false,
    animMode: 'ySpin',
    animSpeed: 0.9,
    retileRate: 4,
    animStagger: 0.6,
  },
  '007': {
    cameraMode: 'orbit',
    cameraAutoFit: true,
    fixedBehavior: 'single',
    fixedShotDefaultDesktopPosition: {
      x: 0,
      y: 0,
      z: 9,
    },
    fixedShotDefaultDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    fixedShotDefaultDesktopFov: 40,
    fixedShotDefaultMobilePosition: {
      x: 0,
      y: 0,
      z: 9,
    },
    fixedShotDefaultMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    fixedShotDefaultMobileFov: 40,
    orbitAutoRotate: false,
    orbitAutoRotateSpeed: 2,
    orbitEnablePan: true,
    orbitMinPolarAngle: 0,
    orbitMaxPolarAngle: 180,
    orbitAzimuthUnlimited: true,
    orbitMinAzimuthAngle: -180,
    orbitMaxAzimuthAngle: 180,
    orbitMinDistance: 0,
    orbitMaxDistanceUnlimited: true,
    orbitMaxDistance: 100,
    orbitDesktopPosition: {
      x: 0,
      y: 0,
      z: 9,
    },
    orbitDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitDesktopPivot: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitDesktopFov: 40,
    orbitMobilePosition: {
      x: 0,
      y: 0,
      z: 12,
    },
    orbitMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitMobilePivot: {
      x: 0,
      y: 0,
      z: 0,
    },
    orbitMobileFov: 45,
    splinePreset: 'Loop de Loop',
    splineDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineDesktopFov: 40,
    splineMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineMobileFov: 40,
    splineOrientationMode: 'target',
    splineForwardDistance: 1,
    splinePosition: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineScale: {
      x: 1,
      y: 1,
      z: 1,
    },
    splineDuration: 30,
    splineTension: 0.5,
    splineClosed: true,
    splineShowPath: false,
    operatorMoveSpeed: 6,
    operatorLiftSpeed: 6,
    operatorBoostMultiplier: 2,
    operatorPointerLookSensitivity: 0.003,
    operatorStickLookSpeed: 2.5,
    operatorZoomSpeed: 24,
    operatorMinFov: 20,
    operatorMaxFov: 80,
    gridMode: 'field',
    gridCols: 10,
    gridRows: 10,
    hexRadius: 6,
    cellSize: 0.5,
    seed: 1,
    blobSeed: 'Change me, empty seed means random',
    blobGridSize: 44,
    blobCanvasSize: 8,
    blobPathsPerUnit: 5,
    blobSizeFunction: '2+(gridSize/2)*Math.random()',
    blobDistribution: 0.75,
    blobConnectivity: 1,
    blobOneFill: 1,
    blobHoles: 0,
    blobMeatballs: 2,
    blobPalette: 'VividMemory8 (lospec)',
    blobLaneMode: 'Depth',
    blobPaletteExact: false,
    blobPaletteShuffle: 357568,
    blobShowStrokes: true,
    blobDebug: 0,
    straightTileChance: 0.28,
    layerBiasAmount: 0,
    weaveEnabled: true,
    weaveGapWidth: 0,
    lanesEnabled: false,
    multiscaleEnabled: false,
    splitProbability: 0.7,
    minGeneration: 1,
    maxGeneration: 4,
    resubdivideEnabled: false,
    resubdivideInterval: 6,
    strokePitch: 0.096,
    strokeWidth: 0.016,
    fillMode: 'line',
    fillWidth: 0.16,
    bgColor: '#ff0000',
    strokeColor: '#141414',
    sceneBgColor: '#ffffff',
    clipShape: 'none',
    clipCornerRadius: 0.3,
    clipRotation: 0,
    borderInset: 0,
    borderVisible: false,
    borderThickness: 0.05,
    borderColor: '#141414',
    planeRotation: -45,
    showGridLines: false,
    gridLineColor: '#999999',
    gridLineWidth: 0.01,
    retileEnabled: false,
    animMode: 'ySpin',
    animSpeed: 0.9,
    retileRate: 4,
    animStagger: 0.6,
  },
};

// Companion fn to usePresetsFolder. Given the snapshot for the preset being
// applied, return the control values to set.
export function getPresetControls({ presetSnapshot }) {
  return { ...presetSnapshot };
}
