export const DEFAULT_PRESET = 'Default';

// The channel keys are fair game for a preset. A rebake re-solves the bed
// under the running water rather than reflooding it, so switching to a preset
// that moves the reach costs one CPU bake and a grain relay -- a hitch, not a
// restart, and the water that was running is still running afterwards. Only
// grain count and solver resolution tear the pipeline down, so those stay
// identical everywhere.
const BASE = {
  cameraMode: 'spline',
  splinePreset: 'Lateral Arc Sweep',
  orbitAutoRotate: false,
  orbitDesktopPosition: [6, 15, 20],
  orbitDesktopTarget: [0, 0, -4],
  orbitDesktopPivot: [0, 0, -4],
  orbitDesktopFov: 34,

  // The reach itself.
  streamSeed: 7,
  gradient: 0.045,
  channelWidth: 15,
  thalweg: 0.5,
  meander: 4,
  meanderRate: 1.1,
  riffleRelief: 0.38,
  riffleRate: 3.5,
  restDepth: 0.45,
  bankHeight: 1.6,
  bankSlope: 5,
  bankRelief: 0.8,
  bedRelief: 0.12,
  boulderCount: 14,
  boulderSize: 1,
  cobbleCount: 420,
  cobbleSize: 1,
  waterline: 0.06,
  roleFeather: 0.35,
  grainCount: 500000,
  grainJitter: 1,
  solverResolution: 384,

  bedShape: 'Square',
  bedSize: 1,
  bedRotation: 0,

  containerEnabled: false,
  containerWall: 1.6,
  containerRim: 1,
  containerFloor: 1.2,
  containerDrop: 0.4,
  containerColor: '#2b2621',
  containerRoughness: 0.85,
  containerMetalness: 0,

  inflowDepth: 0.5,
  inflowDrive: 0.85,
  outfallDepth: 0.34,
  outfallDrive: 0.55,
  surgeAmount: 0.18,
  surgePeriod: 22,

  breakLow: 0.55,
  breakHigh: 1.1,
  breakWeight: 1.5,
  steepWeight: 0.3,
  shallowDepth: 0.9,
  aerationBirth: 2.2,
  aerationDecay: 1.1,
  churnStrength: 1.4,
  churnScale: 0.9,
  churnEvolve: 0.6,
  wetDepth: 0.04,
  pipeArea: 1,
  friction: 0.4,
  bedDrag: 0.02,

  foamBirth: 6,
  foamDecay: 5,
  foamAdvect: 1,
  foamReaction: 26,
  foamSmooth: 24,
  foamJitter: 1,
  foamSpread: 2,
  foamGrain: 0.5,
  foamGrainScale: 2.2,
  foamAging: 0.5,
  foamSink: 0.35,
  foamSinkDepth: 0.9,

  waterGrainSize: 0.1,
  rockGrainSize: 0.16,
  grainSizeMin: 0.6,
  grainSizeMax: 1.5,
  flowGain: 1,
  grainResponse: 9,
  grainLife: 3.5,
  grainFade: 0.09,
  grainSettle: 16,
  churnLift: 0.045,
  churnRate: 3.5,
  foamLift: 0.04,
  shoreDrying: 0.5,
  foamMemory: 1.4,
  foamPickup: 14,
  flowTip: 0.14,
  rockTip: 0.7,
  tipLimit: 1,
  rockJag: 0.3,
  rockDepth: 0.22,

  deepColor: '#06202f',
  shallowColor: '#2b7fa8',
  aeratedColor: '#b4dcf2',
  absorption: 0.95,
  aerationTint: 0.9,
  reefColor: '#3b3227',
  reefDepth: 0.9,
  reefStrength: 0.85,
  foamColor: '#f4f9fd',
  foamOldColor: '#c3d5e3',
  foamThreshold: 0.16,
  foamSoftness: 0.24,
  foamBreakup: 0.55,
  foamSwell: 1.3,
  waterRoughness: 0.12,
  foamRoughness: 0.92,
  rockDryColor: '#3a3830',
  rockWetColor: '#16150f',
  rockMottle: 0.45,
  rockRoughness: 0.88,
  grainVariance: 0.24,

  brushEnabled: false,
  brushMode: 'Push Ground',
  brushRadius: 2.4,
  brushStrength: 1.2,

  morphologyEnabled: false,
  bedCarry: 0.35,
  bedErode: 0.12,
  bedDeposit: 1.6,
  bedResist: 0.4,
  carryDepth: 0.3,
  bedLimit: 0.03,

  driftEnabled: false,
  driftAmount: 0.45,
  driftRate: 1,

  runSimulation: true,
  timeScale: 1,
  substeps: 4,
  renderScale: 1,
  backgroundColor: '#050e19',
  fogNear: 26,
  fogFar: 105,
};

export const PRESETS = {
  // The signature look, and the one every pair below is read against: one
  // pool-riffle couplet in frame at moderate flow.
  'Riffle Run': { ...BASE },

  // Each pair that follows moves ONE axis and holds everything else at BASE,
  // so the two halves can be flipped between to see what that axis does and
  // nothing else. Drift is off in all of them for the same reason -- a preset
  // that is wandering is not a preset you can compare against anything.

  // --- Discharge ------------------------------------------------------------
  'Flow: High': {
    ...BASE,
    inflowDepth: 1.05,
    outfallDepth: 0.8,
    surgeAmount: 0.28,
    surgePeriod: 14,
    breakLow: 0.45,
    breakWeight: 2,
    friction: 0.32,
    aerationBirth: 3.4,
    aerationDecay: 0.8,
    churnStrength: 2.4,
    foamBirth: 8,
    foamDecay: 4,
    foamSink: 0.25,
    foamThreshold: 0.1,
    flowGain: 1.3,
    grainLife: 2.6,
    absorption: 1.4,
    shallowColor: '#2e6d8f',
    deepColor: '#081b28',
  },
  'Flow: Low': {
    ...BASE,
    inflowDepth: 0.24,
    outfallDepth: 0.16,
    surgeAmount: 0.08,
    breakLow: 0.7,
    breakWeight: 1.1,
    steepWeight: 0.2,
    friction: 0.5,
    aerationBirth: 1.8,
    aerationDecay: 1.5,
    churnStrength: 0.8,
    foamBirth: 4.5,
    foamDecay: 6,
    foamReaction: 18,
    flowGain: 0.8,
    grainLife: 5,
    absorption: 0.45,
    reefStrength: 1,
    reefDepth: 0.6,
    waterRoughness: 0.07,
    foamThreshold: 0.13,
    shallowColor: '#4a9ac2',
  },

  // --- Rock in the channel --------------------------------------------------
  // Count only. Size is a separate axis, and raising both at once was what
  // put four-metre boulders abreast across a fifteen-metre channel and dammed
  // the reach instead of splitting it.
  'Rocks: Many': { ...BASE, boulderCount: 40, cobbleCount: 820 },
  'Rocks: None': { ...BASE, boulderCount: 0, cobbleCount: 0 },

  // --- Planform -------------------------------------------------------------
  'Bends: Tight': { ...BASE, meander: 8.5, meanderRate: 2.6 },
  'Bends: Straight': { ...BASE, meander: 0, meanderRate: 0.2 },

  // --- Gradient -------------------------------------------------------------
  // The strongest control in the scene: it is what the water runs down, so it
  // sets the speed, the Froude number and therefore where the reach goes white.
  // Both halves move the datum, so switching either way refloods rather than
  // rebasing -- the reach refills on the new slope instead of being left dry
  // at the top and ponded at the bottom.
  // Real tilt, not faster ripples. The riffle controls stay at the default on
  // purpose: an earlier version of this preset raised the riffle rate instead
  // of the gradient, which made a high-frequency wave train rather than a
  // reach running down a mountain. Everything else moved here follows from the
  // slope -- a steeper reach breaks harder and holds its whitewater longer.
  'Gradient: Steep': {
    ...BASE,
    // A 9.4m fall across the frame, near six times the default's 1.6m. Pushed
    // further the reach starts to surge: at 0.38 a cell's surface moved 1.6m
    // up and down in steady state, which is the field heaving rather than a
    // stream running. The control goes to 0.6 for anyone who wants that.
    gradient: 0.26,
    // Discharge held steadier than the default. A steep reach amplifies the
    // inflow surge into a pumping motion the geometry alone does not have.
    surgeAmount: 0.06,
    inflowDepth: 0.8,
    outfallDepth: 0.5,
    friction: 0.55,
    breakLow: 0.5,
    breakWeight: 2.2,
    aerationBirth: 3.8,
    churnStrength: 2.6,
    foamBirth: 9,
    foamDecay: 4.5,
    foamThreshold: 0.1,
    grainLife: 2.2,
  },
  'Gradient: Flat': {
    ...BASE,
    gradient: 0.004,
    inflowDepth: 0.6,
    outfallDepth: 0.5,
    friction: 0.55,
    breakWeight: 0.8,
    aerationBirth: 0.9,
    aerationDecay: 1.6,
    churnStrength: 0.5,
    foamBirth: 2.5,
    foamDecay: 6,
    absorption: 0.5,
    waterRoughness: 0.07,
  },

  // --- Foam behaviour -------------------------------------------------------
  // The reaction term driven past what the water alone would sustain, so the
  // foam stops behaving like spray and starts behaving like a pattern: cells,
  // fronts and holes that hold shape all the way down the reach.
  'Foam: Art Directed': {
    ...BASE,
    foamBirth: 1.5,
    foamDecay: 1.2,
    foamAdvect: 0.6,
    foamReaction: 54,
    foamSmooth: 24,
    foamSpread: 4,
    foamGrain: 0.72,
    foamGrainScale: 2.8,
    foamSink: 0.18,
    foamAging: 0.2,
    aerationDecay: 0.5,
    churnStrength: 2.8,
    churnScale: 1.2,
    foamThreshold: 0.09,
    foamSoftness: 0.15,
    foamBreakup: 0.3,
    aeratedColor: '#c6e6f7',
  },
  // The opposite balance: high birth against high decay with the reaction
  // subordinate, which is what makes foam follow the hydraulics instead of
  // sustaining itself.
  'Foam: Natural': {
    ...BASE,
    foamBirth: 9,
    foamDecay: 8,
    foamAdvect: 1,
    foamReaction: 8,
    foamSpread: 2,
    foamGrain: 0.3,
    foamAging: 0.8,
    foamThreshold: 0.2,
    foamSoftness: 0.32,
    foamBreakup: 0.7,
  },

  // --- The bed as an object -------------------------------------------------
  // Rotation 30 turns a vertex of the hexagon into the flow, so the reach
  // enters and leaves at a point and the two faces either side of it carry the
  // inflow between them. The channel is narrowed and straightened to suit: a
  // meander tuned to a 36m square runs into the wall of a bed that no longer
  // fills it.
  'Sandbox: Hex Flume': {
    ...BASE,
    bedShape: 'Hexagon',
    bedRotation: 30,
    bedSize: 0.88,
    containerEnabled: true,
    containerWall: 1.2,
    containerRim: 1.1,
    containerFloor: 1,
    containerDrop: 0.4,
    containerColor: '#262a2b',
    containerRoughness: 0.55,
    containerMetalness: 0.3,
    cameraMode: 'orbit',
    orbitDesktopPosition: [0, 22, 24],
    orbitDesktopTarget: [0, 0, 0],
    orbitDesktopPivot: [0, 0, 0],
    orbitDesktopFov: 32,
    channelWidth: 10,
    meander: 1.6,
    meanderRate: 1,
    bankSlope: 3.2,
    bankHeight: 1.1,
    riffleRate: 4,
    boulderCount: 9,
    cobbleCount: 300,
  },
  // The same reach in a round basin, where the inflow arrives across the whole
  // upstream arc rather than through a face.
  'Sandbox: Round Basin': {
    ...BASE,
    bedShape: 'Circle',
    bedSize: 0.82,
    containerEnabled: true,
    containerWall: 1.6,
    containerRim: 0.9,
    containerFloor: 1.3,
    containerDrop: 0.5,
    containerColor: '#332d26',
    cameraMode: 'orbit',
    orbitAutoRotate: true,
    orbitDesktopPosition: [0, 24, 22],
    orbitDesktopTarget: [0, 0, 0],
    orbitDesktopPivot: [0, 0, 0],
    orbitDesktopFov: 33,
    channelWidth: 11,
    meander: 2.2,
    bankSlope: 3.5,
    bankHeight: 1.2,
    boulderCount: 11,
    cobbleCount: 340,
  },

  // --- The two running modes ------------------------------------------------
  // Not a contrast pair: these are the two things the scene does on its own,
  // each turned up far enough to be seen inside a minute rather than tuned for
  // how it should actually be left running.
  'Mode: Drifting': {
    ...BASE,
    driftEnabled: true,
    driftAmount: 0.85,
    driftRate: 2.5,
  },
  'Mode: Reshaping': {
    ...BASE,
    morphologyEnabled: true,
    bedErode: 0.5,
    bedDeposit: 1.6,
    bedLimit: 0.08,
    bedCarry: 0.5,
    boulderCount: 22,
    cobbleCount: 600,
  },
  Default: {
    cameraMode: 'spline',
    cameraProjection: 'perspective',
    cameraFrustumHeight: 10,
    cameraMobileFrustumHeight: 10,
    cameraAutoFit: true,
    fixedBehavior: 'single',
    fixedShotDefaultDesktopPosition: {
      x: 0,
      y: 0,
      z: 5,
    },
    fixedShotDefaultDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    fixedShotDefaultDesktopFov: 50,
    fixedShotDefaultMobilePosition: {
      x: 0,
      y: 0,
      z: 5,
    },
    fixedShotDefaultMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    fixedShotDefaultMobileFov: 50,
    orbitAutoRotate: false,
    orbitAutoRotateSpeed: 2,
    orbitEnablePan: true,
    orbitMinPolarAngle: 0,
    orbitMaxPolarAngle: 180,
    orbitAzimuthUnlimited: true,
    orbitMinAzimuthAngle: -180,
    orbitMaxAzimuthAngle: 180,
    orbitMinDistance: 0,
    orbitMaxDistanceUnlimited: true,
    orbitMaxDistance: 100,
    orbitDesktopPosition: [6, 15, 20],
    orbitDesktopTarget: [0, 0, -4],
    orbitDesktopPivot: [0, 0, -4],
    orbitDesktopFov: 34,
    orbitMobilePosition: {
      x: 4,
      y: 17,
      z: 22,
    },
    orbitMobileTarget: {
      x: 0,
      y: 0,
      z: -4,
    },
    orbitMobilePivot: {
      x: 0,
      y: 0,
      z: -4,
    },
    orbitMobileFov: 52,
    splinePreset: 'Wide Crossing Loop',
    splineDesktopTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineDesktopFov: 34,
    splineMobileTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineMobileFov: 33,
    splineOrientationMode: 'target',
    splineForwardDistance: 1,
    splinePosition: {
      x: 0,
      y: 0,
      z: 0,
    },
    splineScale: {
      x: 2.5,
      y: 2.5,
      z: 2.5,
    },
    splineDuration: 30,
    splineTension: 0.35,
    splineClosed: true,
    splineShowPath: false,
    operatorMoveSpeed: 6,
    operatorLiftSpeed: 6,
    operatorBoostMultiplier: 2,
    operatorPointerLookSensitivity: 0.003,
    operatorStickLookSpeed: 2.5,
    operatorZoomSpeed: 24,
    operatorMinFov: 20,
    operatorMaxFov: 80,
    lightEnabled: true,
    lightSkyEnabled: true,
    lightSkySkyColor: '#b9d2d8',
    lightSkyGroundColor: '#0d1410',
    lightSkyIntensity: 1.5,
    lightSunEnabled: true,
    lightSunColor: '#fff4dd',
    lightSunIntensity: 2.5,
    lightSunAzimuth: 52,
    lightSunElevation: 44,
    lightSunRadius: 120,
    lightSunTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    lightSunDebug: false,
    lightFillEnabled: true,
    lightFillColor: '#3a6a8f',
    lightFillIntensity: 0.5,
    lightFillAzimuth: -128,
    lightFillElevation: 18,
    lightFillRadius: 120,
    lightFillTarget: {
      x: 0,
      y: 0,
      z: 0,
    },
    lightFillDebug: false,
    inflowDepth: 0.5,
    inflowDrive: 0.85,
    outfallDepth: 0.34,
    outfallDrive: 0.55,
    surgeAmount: 0.18,
    surgePeriod: 22,
    breakLow: 0.55,
    breakHigh: 1.1,
    breakWeight: 1.5,
    steepWeight: 0.3,
    shallowDepth: 0.9,
    aerationBirth: 2.2,
    aerationDecay: 1.1,
    churnStrength: 1.4,
    churnScale: 0.9,
    churnEvolve: 0.6,
    wetDepth: 0.04,
    pipeArea: 1,
    friction: 0.4,
    bedDrag: 0.02,
    foamBirth: 6,
    foamDecay: 5,
    foamAdvect: 1,
    foamReaction: 26,
    foamSmooth: 24,
    foamJitter: 1,
    foamSpread: 2,
    foamGrain: 0.5,
    foamGrainScale: 2.2,
    foamAging: 0.5,
    foamSink: 0.35,
    foamSinkDepth: 0.9,
    grainCount: 500000,
    waterGrainSize: 0.1,
    rockGrainSize: 0.16,
    grainSizeMin: 0.6,
    grainSizeMax: 1.5,
    grainJitter: 1,
    flowGain: 1,
    grainResponse: 9,
    grainLife: 3.5,
    grainFade: 0.09,
    grainSettle: 16,
    churnLift: 0.045,
    churnRate: 3.5,
    foamLift: 0.04,
    shoreDrying: 0.5,
    foamMemory: 1.4,
    foamPickup: 14,
    flowTip: 0.14,
    rockTip: 0.7,
    tipLimit: 1,
    rockJag: 0.3,
    rockDepth: 0.22,
    deepColor: '#06202f',
    shallowColor: '#2b7fa8',
    aeratedColor: '#b4dcf2',
    absorption: 0.95,
    aerationTint: 0.9,
    reefColor: '#3b3227',
    reefDepth: 0.9,
    reefStrength: 0.85,
    foamColor: '#f4f9fd',
    foamOldColor: '#c3d5e3',
    foamThreshold: 0.16,
    foamSoftness: 0.24,
    foamBreakup: 0.55,
    foamSwell: 1.3,
    waterRoughness: 0.12,
    foamRoughness: 0.92,
    rockDryColor: '#3a3830',
    rockWetColor: '#16150f',
    rockMottle: 0.45,
    rockRoughness: 0.88,
    grainVariance: 0.24,
    streamSeed: 144,
    gradient: 0.045,
    channelWidth: 15,
    thalweg: 0.9199999999999999,
    meander: 4,
    meanderRate: 1.1,
    riffleRelief: 0.38,
    riffleRate: 3.5,
    restDepth: 0.45,
    bankHeight: 1.6,
    bankSlope: 5,
    bankRelief: 0.8,
    bedRelief: 0.12,
    boulderCount: 14,
    boulderSize: 1,
    cobbleCount: 420,
    cobbleSize: 1,
    waterline: 0.06,
    roleFeather: 0.35,
    bedShape: 'Square',
    bedSize: 1,
    bedRotation: 0,
    containerEnabled: false,
    containerWall: 1.6,
    containerRim: 1,
    containerFloor: 1.2,
    containerDrop: 0.4,
    containerColor: '#2b2621',
    containerRoughness: 0.85,
    containerMetalness: 0,
    driftEnabled: false,
    driftAmount: 0.45,
    driftRate: 1,
    brushEnabled: false,
    brushMode: 'Push Ground',
    brushRadius: 2.4,
    brushStrength: 1.2,
    morphologyEnabled: false,
    bedCarry: 0.35,
    bedErode: 0.12,
    bedDeposit: 1.6,
    bedResist: 0.4,
    carryDepth: 0.3,
    bedLimit: 0.03,
    runSimulation: true,
    timeScale: 1,
    substeps: 4,
    solverResolution: 384,
    renderScale: 1,
    backgroundColor: '#0a192c',
    fogNear: 26,
    fogFar: 105,
  },
};

export function getPresetControls({ presetSnapshot }) {
  return { ...presetSnapshot };
}
