const DEBUG_CONTACT_CAP = 12;
const DEBUG_CONTACT_TTL_DEFAULT = 0.28;
const RANDOM_BURST_COUNT = DEBUG_CONTACT_CAP;

// Blend mode constants
const BLEND_MODE_ADDITIVE = 0;
const BLEND_MODE_MULTIPLY = 1;
const BLEND_MODE_SUBTRACTIVE = 2;

const FLUID_PRESETS = {
  test: {
    paused: false,
    simResolution: 1,
    pressureRelax: 1,
    pressureIterations: 40,
    vorticity: 90,
    velocityDissipation: 2,
    densityDissipation: 2,
    splatRadius: 0.003,
    autoSplatRadius: 0.003,
    stationarySplatRadius: 0.003,
    randomSplatRadius: 0.003,
    splatForce: 2200,
    autoSplatForce: 2200,
    stationarySplatForce: 2200,
    dyeStrength: 0.92,
    inputMode: 'pointer',
    testMode: 'plane',
    autoSplat: true,
    autoSplatStrength: 0.6,
    autoSplatDyeStrength: 0.6,
    autoSplatRate: 100,
    autoSplatRange: 1,
    autoSplatBurst: 2,
    autoSplatCount: 2,
    autoSplatStarts: [
      {
        x: 0.35,
        y: 0.35,
      },
      {
        x: 0.65,
        y: 0.65,
      },
    ],
    randomSplatStrength: 1,
    randomSplatDyeStrength: 0.92,
    randomSplatForce: 2200,
    stationarySplatsEnabled: true,
    stationarySplatStrength: 0.35,
    stationarySplatDyeStrength: 0.35,
    stationarySplatCount: 8,
    handsMaxHands: 1,
    handsShowVideo: false,
    handsShowDebugSkeleton: false,
    handsLandmarkColor: '#ff3366',
    handsConnectorColor: '#00ffaa',
    handsLandmarkRadius: 4,
    handsConnectorLineWidth: 3,
    handsModelComplexity: 1,
    handsMinDetectionConfidence: 0.6,
    handsMinTrackingConfidence: 0.6,
    handsXScale: 4,
    handsYScale: 3,
    handsZScale: 5,
    handsInvertX: false,
    handsInvertY: false,
    gesturesEnabled: true,
    shading: true,
    bloom: true,
    bloomResolution: 0.25,
    bloomIterations: 8,
    bloomIntensity: 0.65,
    bloomThreshold: 0.6,
    bloomSoftKnee: 0.7,
    sunrays: true,
    sunraysResolution: 0.18,
    sunraysWeight: 0.85,
    colorA: '#ff6d6d',
    colorB: '#ff0000',
    colorC: '#7b0000',
    colorful: true,
    colorUpdateSpeed: 20,
    colorCycleSpeed: 0.55,
    bgA: '#4b4b4b',
    bgB: '#797979',
    dithering: true,
    ditherStrength: 1,
    ditherScale: 1,
    brightness: 1.37,
    contrast: 1.2,
    saturation: 1.33,
    blendMode: 0,
    debugCursor: true,
    debugAutoSplat: true,
    debugStationarySplat: true,
    debugRandomBurst: true,
    debugPointerColor: '#ffffff',
    debugAutoColor: '#000000',
    debugAutoWidth: 0.03,
    debugAutoHeight: 0.03,
    debugPointerWidth: 0.03,
    debugPointerHeight: 0.03,
    debugPointerLineWeight: 2,
    debugPointerFill: false,
    debugPointerRotation: 0,
    debugAutoLineWeight: 2,
    debugAutoFill: false,
    debugAutoRotation: 0,
    debugStationaryColor: '#ffd166',
    debugStationaryWidth: 0.03,
    debugStationaryHeight: 0.03,
    debugStationaryLineWeight: 2,
    debugStationaryFill: false,
    debugStationaryRotation: 0,
    debugRandomColor: '#7c3aed',
    debugRandomWidth: 0.03,
    debugRandomHeight: 0.03,
    debugRandomLineWeight: 2,
    debugRandomFill: false,
    debugRandomRotation: 0,
    debugContactFadeDuration: 0.28,
    stationarySplats: [
      {
        x: 0.1,
        y: 0.1,
      },
      {
        x: 0.2,
        y: 0.2,
      },
      {
        x: 0.3,
        y: 0.3,
      },
      {
        x: 0.4,
        y: 0.4,
      },
      {
        x: 0.5,
        y: 0.5,
      },
      {
        x: 0.6,
        y: 0.6,
      },
      {
        x: 0.7,
        y: 0.7,
      },
      {
        x: 0.8,
        y: 0.8,
      },
    ],
  },
  cardinalsMobile: {
    paused: false,
    simResolution: 0.98,
    pressureRelax: 0.84,
    pressureIterations: 14,
    vorticity: 2,
    velocityDissipation: 0.4,
    densityDissipation: 1.6,
    splatRadius: 0.0022,
    autoSplatRadius: 0.0022,
    stationarySplatRadius: 0.0022,
    randomSplatRadius: 0.0022,
    splatForce: 4200,
    autoSplatForce: 4200,
    stationarySplatForce: 4200,
    dyeStrength: 2.5,
    inputMode: 'pointer',
    testMode: 'plane',
    autoSplat: true,
    autoSplatStrength: 0.24,
    autoSplatDyeStrength: 0.24,
    autoSplatRate: 25,
    autoSplatRange: 1,
    autoSplatBurst: 1,
    autoSplatCount: 4,
    autoSplatStarts: [
      {
        x: 0.2,
        y: 0.2,
      },
      {
        x: 0.8,
        y: 0.2,
      },
      {
        x: 0.2,
        y: 0.8,
      },
      {
        x: 0.8,
        y: 0.8,
      },
    ],
    randomSplatStrength: 1,
    randomSplatDyeStrength: 2.5,
    randomSplatForce: 4200,
    stationarySplatsEnabled: false,
    stationarySplatStrength: 0.35,
    stationarySplatDyeStrength: 0.35,
    stationarySplatCount: 0,
    handsMaxHands: 1,
    handsShowVideo: false,
    handsShowDebugSkeleton: false,
    handsLandmarkColor: '#FF3366',
    handsConnectorColor: '#00FFAA',
    handsLandmarkRadius: 4,
    handsConnectorLineWidth: 3,
    handsModelComplexity: 1,
    handsMinDetectionConfidence: 0.6,
    handsMinTrackingConfidence: 0.6,
    handsXScale: 4,
    handsYScale: 3,
    handsZScale: 5,
    handsInvertX: false,
    handsInvertY: false,
    gesturesEnabled: true,
    shading: true,
    bloom: true,
    bloomResolution: 0.2,
    bloomIterations: 4,
    bloomIntensity: 0.5,
    bloomThreshold: 0.62,
    bloomSoftKnee: 0.7,
    sunrays: true,
    sunraysResolution: 0.16,
    sunraysWeight: 0.9,
    colorA: '#ff6d6d',
    colorB: '#ff0000',
    colorC: '#7b0000',
    colorful: true,
    colorUpdateSpeed: 20,
    colorCycleSpeed: 0.55,
    bgA: '#4b4b4b',
    bgB: '#797979',
    dithering: true,
    ditherStrength: 2.85,
    ditherScale: 1,
    brightness: 1.05,
    contrast: 1.16,
    saturation: 1.2,
    blendMode: 0,
    debugCursor: true,
    debugAutoSplat: true,
    debugStationarySplat: true,
    debugRandomBurst: true,
    debugPointerColor: '#ffffff',
    debugAutoColor: '#000000',
    debugAutoWidth: 0.0375,
    debugAutoHeight: 0.0375,
    debugPointerWidth: 0.024,
    debugPointerHeight: 0.024,
    debugPointerLineWeight: 1,
    debugPointerFill: false,
    debugPointerRotation: 0,
    debugAutoLineWeight: 1,
    debugAutoFill: false,
    debugAutoRotation: 0,
    debugStationaryColor: '#ffd166',
    debugStationaryWidth: 0.03,
    debugStationaryHeight: 0.03,
    debugStationaryLineWeight: 1,
    debugStationaryFill: false,
    debugStationaryRotation: 0,
    debugRandomColor: '#7c3aed',
    debugRandomWidth: 0.03,
    debugRandomHeight: 0.03,
    debugRandomLineWeight: 1,
    debugRandomFill: false,
    debugRandomRotation: 0,
    debugContactFadeDuration: 0.28,
    stationarySplats: [],
  },
  fastFlow: {
    paused: false,
    simResolution: 0.7,
    pressureRelax: 0.78,
    pressureIterations: 24,
    vorticity: 46,
    velocityDissipation: 0.16,
    densityDissipation: 0.9,
    splatRadius: 0.0024,
    autoSplatRadius: 0.0024,
    stationarySplatRadius: 0.0024,
    randomSplatRadius: 0.0024,
    splatForce: 7200,
    autoSplatForce: 7200,
    stationarySplatForce: 7200,
    dyeStrength: 1.1,
    inputMode: 'pointer',
    testMode: 'plane',
    autoSplat: true,
    autoSplatStrength: 0.11,
    autoSplatDyeStrength: 0.11,
    autoSplatRate: 41,
    autoSplatRange: 1,
    autoSplatBurst: 3,
    autoSplatCount: 3,
    autoSplatStarts: [
      {
        x: 0.25,
        y: 0.5,
      },
      {
        x: 0.5,
        y: 0.25,
      },
      {
        x: 0.75,
        y: 0.5,
      },
    ],
    randomSplatStrength: 1,
    randomSplatDyeStrength: 1.1,
    randomSplatForce: 7200,
    stationarySplatsEnabled: false,
    stationarySplatStrength: 0.35,
    stationarySplatDyeStrength: 0.35,
    stationarySplatCount: 0,
    handsMaxHands: 1,
    handsShowVideo: false,
    handsShowDebugSkeleton: false,
    handsLandmarkColor: '#FF3366',
    handsConnectorColor: '#00FFAA',
    handsLandmarkRadius: 4,
    handsConnectorLineWidth: 3,
    handsModelComplexity: 1,
    handsMinDetectionConfidence: 0.6,
    handsMinTrackingConfidence: 0.6,
    handsXScale: 4,
    handsYScale: 3,
    handsZScale: 5,
    handsInvertX: false,
    handsInvertY: false,
    gesturesEnabled: true,
    shading: true,
    bloom: true,
    bloomResolution: 0.24,
    bloomIterations: 9,
    bloomIntensity: 0.72,
    bloomThreshold: 0.58,
    bloomSoftKnee: 0.7,
    sunrays: true,
    sunraysResolution: 0.19,
    sunraysWeight: 0.9,
    colorA: '#3b82f6',
    colorB: '#22c55e',
    colorC: '#a855f7',
    colorful: true,
    colorUpdateSpeed: 14,
    colorCycleSpeed: 1.6,
    bgA: '#020617',
    bgB: '#000000',
    dithering: true,
    ditherStrength: 1,
    ditherScale: 1,
    brightness: 1.15,
    contrast: 1.3,
    saturation: 1.35,
    blendMode: 0,
    debugCursor: false,
    debugAutoSplat: false,
    debugStationarySplat: false,
    debugRandomBurst: false,
    debugPointerColor: '#ffffff',
    debugAutoColor: '#22c55e',
    debugAutoWidth: 0.03,
    debugAutoHeight: 0.03,
    debugPointerWidth: 0.03,
    debugPointerHeight: 0.03,
    debugPointerLineWeight: 1,
    debugPointerFill: false,
    debugPointerRotation: 0,
    debugAutoLineWeight: 1,
    debugAutoFill: false,
    debugAutoRotation: 0,
    debugStationaryColor: '#ffd166',
    debugStationaryWidth: 0.03,
    debugStationaryHeight: 0.03,
    debugStationaryLineWeight: 1,
    debugStationaryFill: false,
    debugStationaryRotation: 0,
    debugRandomColor: '#7c3aed',
    debugRandomWidth: 0.03,
    debugRandomHeight: 0.03,
    debugRandomLineWeight: 1,
    debugRandomFill: false,
    debugRandomRotation: 0,
    debugContactFadeDuration: 0.28,
    stationarySplats: [],
  },
  viscousFlow: {
    paused: false,
    simResolution: 0.7,
    pressureRelax: 0.86,
    pressureIterations: 32,
    vorticity: 18,
    velocityDissipation: 0.46,
    densityDissipation: 0.72,
    splatRadius: 0.0042,
    autoSplatRadius: 0.0042,
    stationarySplatRadius: 0.0042,
    randomSplatRadius: 0.0042,
    splatForce: 3800,
    autoSplatForce: 3800,
    stationarySplatForce: 3800,
    dyeStrength: 0.85,
    inputMode: 'pointer',
    testMode: 'plane',
    autoSplat: true,
    autoSplatStrength: 0.06,
    autoSplatDyeStrength: 0.06,
    autoSplatRate: 10,
    autoSplatRange: 1,
    autoSplatBurst: 1,
    autoSplatCount: 1,
    autoSplatStarts: [
      {
        x: 0.5,
        y: 0.5,
      },
    ],
    randomSplatStrength: 1,
    randomSplatDyeStrength: 0.85,
    randomSplatForce: 3800,
    stationarySplatsEnabled: false,
    stationarySplatStrength: 0.35,
    stationarySplatDyeStrength: 0.35,
    stationarySplatCount: 0,
    handsMaxHands: 1,
    handsShowVideo: false,
    handsShowDebugSkeleton: false,
    handsLandmarkColor: '#FF3366',
    handsConnectorColor: '#00FFAA',
    handsLandmarkRadius: 4,
    handsConnectorLineWidth: 3,
    handsModelComplexity: 1,
    handsMinDetectionConfidence: 0.6,
    handsMinTrackingConfidence: 0.6,
    handsXScale: 4,
    handsYScale: 3,
    handsZScale: 5,
    handsInvertX: false,
    handsInvertY: false,
    gesturesEnabled: true,
    shading: true,
    bloom: true,
    bloomResolution: 0.22,
    bloomIterations: 7,
    bloomIntensity: 0.58,
    bloomThreshold: 0.6,
    bloomSoftKnee: 0.72,
    sunrays: false,
    sunraysResolution: 0.18,
    sunraysWeight: 0.8,
    colorA: '#22c55e',
    colorB: '#0f766e',
    colorC: '#155e75',
    colorful: true,
    colorUpdateSpeed: 6,
    colorCycleSpeed: 0.4,
    bgA: '#020617',
    bgB: '#040314',
    dithering: true,
    ditherStrength: 1,
    ditherScale: 1,
    brightness: 1.02,
    contrast: 1.12,
    saturation: 1.1,
    blendMode: 0,
    debugCursor: false,
    debugAutoSplat: false,
    debugStationarySplat: false,
    debugRandomBurst: false,
    debugPointerColor: '#7dd3fc',
    debugAutoColor: '#22c55e',
    debugAutoWidth: 0.03,
    debugAutoHeight: 0.03,
    debugPointerWidth: 0.03,
    debugPointerHeight: 0.03,
    debugPointerLineWeight: 1,
    debugPointerFill: false,
    debugPointerRotation: 0,
    debugAutoLineWeight: 1,
    debugAutoFill: false,
    debugAutoRotation: 0,
    debugStationaryColor: '#ffd166',
    debugStationaryWidth: 0.03,
    debugStationaryHeight: 0.03,
    debugStationaryLineWeight: 1,
    debugStationaryFill: false,
    debugStationaryRotation: 0,
    debugRandomColor: '#7c3aed',
    debugRandomWidth: 0.03,
    debugRandomHeight: 0.03,
    debugRandomLineWeight: 1,
    debugRandomFill: false,
    debugRandomRotation: 0,
    debugContactFadeDuration: 0.28,
    stationarySplats: [],
  },
  pastel: {
    paused: false,
    simResolution: 0.75,
    pressureRelax: 0.8,
    pressureIterations: 28,
    vorticity: 42,
    velocityDissipation: 0.18,
    densityDissipation: 1,
    splatRadius: 0.0028,
    autoSplatRadius: 0.0028,
    stationarySplatRadius: 0.0028,
    randomSplatRadius: 0.0028,
    splatForce: 7000,
    autoSplatForce: 7000,
    stationarySplatForce: 7000,
    dyeStrength: 1,
    inputMode: 'pointer',
    testMode: 'plane',
    autoSplat: false,
    autoSplatStrength: 0.25,
    autoSplatDyeStrength: 0.25,
    autoSplatRate: 10,
    autoSplatRange: 1,
    autoSplatBurst: 2,
    autoSplatCount: 2,
    autoSplatStarts: [
      {
        x: 0.32,
        y: 0.68,
      },
      {
        x: 0.68,
        y: 0.32,
      },
    ],
    randomSplatStrength: 1,
    randomSplatDyeStrength: 1,
    randomSplatForce: 7000,
    stationarySplatsEnabled: false,
    stationarySplatStrength: 0.35,
    stationarySplatDyeStrength: 0.35,
    stationarySplatCount: 0,
    handsMaxHands: 1,
    handsShowVideo: false,
    handsShowDebugSkeleton: false,
    handsLandmarkColor: '#FF3366',
    handsConnectorColor: '#00FFAA',
    handsLandmarkRadius: 4,
    handsConnectorLineWidth: 3,
    handsModelComplexity: 1,
    handsMinDetectionConfidence: 0.6,
    handsMinTrackingConfidence: 0.6,
    handsXScale: 4,
    handsYScale: 3,
    handsZScale: 5,
    handsInvertX: false,
    handsInvertY: false,
    gesturesEnabled: true,
    shading: true,
    bloom: true,
    bloomResolution: 0.25,
    bloomIterations: 10,
    bloomIntensity: 0.72,
    bloomThreshold: 0.58,
    bloomSoftKnee: 0.7,
    sunrays: true,
    sunraysResolution: 0.2,
    sunraysWeight: 0.85,
    colorA: '#1de9ff',
    colorB: '#ff4ccf',
    colorC: '#ffd35e',
    colorful: true,
    colorUpdateSpeed: 12,
    colorCycleSpeed: 1.2,
    bgA: '#000000',
    bgB: '#0a0017',
    dithering: true,
    ditherStrength: 1,
    ditherScale: 1,
    brightness: 1.12,
    contrast: 1.3,
    saturation: 1.4,
    blendMode: 0,
    debugCursor: false,
    debugAutoSplat: false,
    debugStationarySplat: false,
    debugRandomBurst: false,
    debugPointerColor: '#8df4ff',
    debugAutoColor: '#ffd35e',
    debugAutoWidth: 0.03,
    debugAutoHeight: 0.03,
    debugPointerWidth: 0.03,
    debugPointerHeight: 0.03,
    debugPointerLineWeight: 1,
    debugPointerFill: false,
    debugPointerRotation: 0,
    debugAutoLineWeight: 1,
    debugAutoFill: false,
    debugAutoRotation: 0,
    debugStationaryColor: '#ffd166',
    debugStationaryWidth: 0.03,
    debugStationaryHeight: 0.03,
    debugStationaryLineWeight: 1,
    debugStationaryFill: false,
    debugStationaryRotation: 0,
    debugRandomColor: '#7c3aed',
    debugRandomWidth: 0.03,
    debugRandomHeight: 0.03,
    debugRandomLineWeight: 1,
    debugRandomFill: false,
    debugRandomRotation: 0,
    debugContactFadeDuration: 0.28,
    stationarySplats: [],
  },
  mobile: {
    paused: false,
    simResolution: 0.42,
    pressureRelax: 0.84,
    pressureIterations: 14,
    vorticity: 24,
    velocityDissipation: 0.24,
    densityDissipation: 1,
    splatRadius: 0.0022,
    autoSplatRadius: 0.0022,
    stationarySplatRadius: 0.0022,
    randomSplatRadius: 0.0022,
    splatForce: 4200,
    autoSplatForce: 4200,
    stationarySplatForce: 4200,
    dyeStrength: 0.9,
    inputMode: 'pointer',
    testMode: 'plane',
    autoSplat: false,
    autoSplatStrength: 0.1,
    autoSplatDyeStrength: 0.1,
    autoSplatRate: 6,
    autoSplatRange: 1,
    autoSplatBurst: 1,
    autoSplatCount: 1,
    autoSplatStarts: [
      {
        x: 0.5,
        y: 0.5,
      },
    ],
    randomSplatStrength: 1,
    randomSplatDyeStrength: 0.9,
    randomSplatForce: 4200,
    stationarySplatsEnabled: false,
    stationarySplatStrength: 0.35,
    stationarySplatDyeStrength: 0.35,
    stationarySplatCount: 0,
    handsMaxHands: 1,
    handsShowVideo: false,
    handsShowDebugSkeleton: false,
    handsLandmarkColor: '#FF3366',
    handsConnectorColor: '#00FFAA',
    handsLandmarkRadius: 4,
    handsConnectorLineWidth: 3,
    handsModelComplexity: 1,
    handsMinDetectionConfidence: 0.6,
    handsMinTrackingConfidence: 0.6,
    handsXScale: 4,
    handsYScale: 3,
    handsZScale: 5,
    handsInvertX: false,
    handsInvertY: false,
    gesturesEnabled: true,
    shading: false,
    bloom: false,
    bloomResolution: 0.2,
    bloomIterations: 4,
    bloomIntensity: 0.5,
    bloomThreshold: 0.62,
    bloomSoftKnee: 0.7,
    sunrays: false,
    sunraysResolution: 0.16,
    sunraysWeight: 0.9,
    colorA: '#4bd5ff',
    colorB: '#ff7cd8',
    colorC: '#7cf08b',
    colorful: true,
    colorUpdateSpeed: 8,
    colorCycleSpeed: 0.7,
    bgA: '#030611',
    bgB: '#0b0414',
    dithering: false,
    ditherStrength: 0.5,
    ditherScale: 1,
    brightness: 1.05,
    contrast: 1.16,
    saturation: 1.2,
    blendMode: 0,
    debugCursor: false,
    debugAutoSplat: false,
    debugStationarySplat: false,
    debugRandomBurst: false,
    debugPointerColor: '#7fdfff',
    debugAutoColor: '#8ff0b0',
    debugAutoWidth: 0.03,
    debugAutoHeight: 0.03,
    debugPointerWidth: 0.03,
    debugPointerHeight: 0.03,
    debugPointerLineWeight: 1,
    debugPointerFill: false,
    debugPointerRotation: 0,
    debugAutoLineWeight: 1,
    debugAutoFill: false,
    debugAutoRotation: 0,
    debugStationaryColor: '#ffd166',
    debugStationaryWidth: 0.03,
    debugStationaryHeight: 0.03,
    debugStationaryLineWeight: 1,
    debugStationaryFill: false,
    debugStationaryRotation: 0,
    debugRandomColor: '#7c3aed',
    debugRandomWidth: 0.03,
    debugRandomHeight: 0.03,
    debugRandomLineWeight: 1,
    debugRandomFill: false,
    debugRandomRotation: 0,
    debugContactFadeDuration: 0.28,
    stationarySplats: [],
  },
  inkOnPaper: {
    paused: false,
    simResolution: 0.75,
    pressureRelax: 0.88,
    pressureIterations: 26,
    vorticity: 18,
    velocityDissipation: 0.42,
    densityDissipation: 0.85,
    splatRadius: 0.0013,
    autoSplatRadius: 0.0013,
    stationarySplatRadius: 0.0013,
    randomSplatRadius: 0.0013,
    splatForce: 9000,
    autoSplatForce: 9000,
    stationarySplatForce: 9000,
    dyeStrength: 2.2,
    inputMode: 'pointer',
    testMode: 'plane',
    autoSplat: true,
    autoSplatStrength: 0.6,
    autoSplatDyeStrength: 0.6,
    autoSplatRate: 100,
    autoSplatRange: 1,
    autoSplatBurst: 2,
    autoSplatCount: 2,
    autoSplatStarts: [
      {
        x: 0.4,
        y: 0.45,
      },
      {
        x: 0.6,
        y: 0.55,
      },
    ],
    randomSplatStrength: 1,
    randomSplatDyeStrength: 2.2,
    randomSplatForce: 9000,
    stationarySplatsEnabled: false,
    stationarySplatStrength: 0.35,
    stationarySplatDyeStrength: 0.35,
    stationarySplatCount: 0,
    handsMaxHands: 1,
    handsShowVideo: false,
    handsShowDebugSkeleton: false,
    handsLandmarkColor: '#FF3366',
    handsConnectorColor: '#00FFAA',
    handsLandmarkRadius: 4,
    handsConnectorLineWidth: 3,
    handsModelComplexity: 1,
    handsMinDetectionConfidence: 0.6,
    handsMinTrackingConfidence: 0.6,
    handsXScale: 4,
    handsYScale: 3,
    handsZScale: 5,
    handsInvertX: false,
    handsInvertY: false,
    gesturesEnabled: true,
    shading: false,
    bloom: false,
    bloomResolution: 0.22,
    bloomIterations: 4,
    bloomIntensity: 0.4,
    bloomThreshold: 0.7,
    bloomSoftKnee: 0.7,
    sunrays: false,
    sunraysResolution: 0.16,
    sunraysWeight: 0.8,
    colorA: '#000000',
    colorB: '#585858',
    colorC: '#8d8d8d',
    colorful: true,
    colorUpdateSpeed: 12.2,
    colorCycleSpeed: 0,
    bgA: '#fafaf9',
    bgB: '#f5f5f4',
    dithering: false,
    ditherStrength: 0.3,
    ditherScale: 1,
    brightness: 1,
    contrast: 1.15,
    saturation: 0.8,
    blendMode: 1,
    debugCursor: true,
    debugAutoSplat: true,
    debugStationarySplat: true,
    debugRandomBurst: true,
    debugPointerColor: '#111827',
    debugAutoColor: '#4b5563',
    debugAutoWidth: 0.025,
    debugAutoHeight: 0.025,
    debugPointerWidth: 0.025,
    debugPointerHeight: 0.025,
    debugPointerLineWeight: 1,
    debugPointerFill: false,
    debugPointerRotation: 0,
    debugAutoLineWeight: 1,
    debugAutoFill: false,
    debugAutoRotation: 0,
    debugStationaryColor: '#ffd166',
    debugStationaryWidth: 0.03,
    debugStationaryHeight: 0.03,
    debugStationaryLineWeight: 1,
    debugStationaryFill: false,
    debugStationaryRotation: 0,
    debugRandomColor: '#7c3aed',
    debugRandomWidth: 0.03,
    debugRandomHeight: 0.03,
    debugRandomLineWeight: 1,
    debugRandomFill: false,
    debugRandomRotation: 0,
    debugContactFadeDuration: 0.28,
    stationarySplats: [],
  },
  freon: {
    paused: false,
    simResolution: 0.75,
    pressureRelax: 0.88,
    pressureIterations: 26,
    vorticity: 18,
    velocityDissipation: 0.42,
    densityDissipation: 0.85,
    splatRadius: 0.0013,
    autoSplatRadius: 0.0013,
    stationarySplatRadius: 0.0013,
    randomSplatRadius: 0.0013,
    splatForce: 9000,
    autoSplatForce: 9000,
    stationarySplatForce: 9000,
    dyeStrength: 2.2,
    inputMode: 'pointer',
    testMode: 'plane',
    autoSplat: true,
    autoSplatStrength: 0.6,
    autoSplatDyeStrength: 0.6,
    autoSplatRate: 100,
    autoSplatRange: 1,
    autoSplatBurst: 2,
    autoSplatCount: 8,
    autoSplatStarts: [
      {
        x: 0.2,
        y: 0.2,
      },
      {
        x: 0.8,
        y: 0.2,
      },
      {
        x: 0.2,
        y: 0.8,
      },
      {
        x: 0.8,
        y: 0.8,
      },
      {
        x: 0.5,
        y: 0.2,
      },
      {
        x: 0.2,
        y: 0.5,
      },
      {
        x: 0.8,
        y: 0.5,
      },
      {
        x: 0.5,
        y: 0.8,
      },
    ],
    randomSplatStrength: 1,
    randomSplatDyeStrength: 2.2,
    randomSplatForce: 9000,
    stationarySplatsEnabled: false,
    stationarySplatStrength: 0.35,
    stationarySplatDyeStrength: 0.35,
    stationarySplatCount: 0,
    handsMaxHands: 1,
    handsShowVideo: false,
    handsShowDebugSkeleton: false,
    handsLandmarkColor: '#FF3366',
    handsConnectorColor: '#00FFAA',
    handsLandmarkRadius: 4,
    handsConnectorLineWidth: 3,
    handsModelComplexity: 1,
    handsMinDetectionConfidence: 0.6,
    handsMinTrackingConfidence: 0.6,
    handsXScale: 4,
    handsYScale: 3,
    handsZScale: 5,
    handsInvertX: false,
    handsInvertY: false,
    gesturesEnabled: true,
    shading: true,
    bloom: true,
    bloomResolution: 0.22,
    bloomIterations: 4,
    bloomIntensity: 0.4,
    bloomThreshold: 0.7,
    bloomSoftKnee: 0.7,
    sunrays: true,
    sunraysResolution: 0.16,
    sunraysWeight: 0.8,
    colorA: '#000000',
    colorB: '#585858',
    colorC: '#8d8d8d',
    colorful: true,
    colorUpdateSpeed: 12.2,
    colorCycleSpeed: 0,
    bgA: '#000000',
    bgB: '#939392',
    dithering: true,
    ditherStrength: 4,
    ditherScale: 1.85,
    brightness: 1.09,
    contrast: 1.15,
    saturation: 1.31,
    blendMode: 0,
    debugCursor: true,
    debugAutoSplat: true,
    debugStationarySplat: true,
    debugRandomBurst: true,
    debugPointerColor: '#111827',
    debugAutoColor: '#4b5563',
    debugAutoWidth: 0.025,
    debugAutoHeight: 0.025,
    debugPointerWidth: 0.025,
    debugPointerHeight: 0.025,
    debugPointerLineWeight: 1,
    debugPointerFill: false,
    debugPointerRotation: 0,
    debugAutoLineWeight: 1,
    debugAutoFill: false,
    debugAutoRotation: 0,
    debugStationaryColor: '#ffd166',
    debugStationaryWidth: 0.03,
    debugStationaryHeight: 0.03,
    debugStationaryLineWeight: 1,
    debugStationaryFill: false,
    debugStationaryRotation: 0,
    debugRandomColor: '#7c3aed',
    debugRandomWidth: 0.03,
    debugRandomHeight: 0.03,
    debugRandomLineWeight: 1,
    debugRandomFill: false,
    debugRandomRotation: 0,
    debugContactFadeDuration: 0.28,
    stationarySplats: [],
  },
  watercolorSquares: {
    paused: false,
    simResolution: 0.98,
    pressureRelax: 0.84,
    pressureIterations: 14,
    vorticity: 54,
    velocityDissipation: 0.4,
    densityDissipation: 1.6,
    splatRadius: 0.0005,
    autoSplatRadius: 0.0005,
    stationarySplatRadius: 0.0005,
    randomSplatRadius: 0.0022,
    splatForce: 4200,
    dyeStrength: 0.25,
    inputMode: 'pointer',
    testMode: 'plane',
    autoSplat: false,
    autoSplatStrength: 0.029999999999999916,
    autoSplatDyeStrength: 2.5,
    autoSplatForce: 950,
    autoSplatRate: 100,
    autoSplatRange: 1,
    autoSplatBurst: 4,
    autoSplatCount: 2,
    autoSplatStarts: [
      {
        x: 0.5,
        y: 0.4,
      },
      {
        x: 0.5,
        y: 0.5,
      },
    ],
    randomSplatStrength: 1,
    randomSplatDyeStrength: 1.71,
    randomSplatForce: 4200,
    stationarySplatsEnabled: true,
    stationarySplatStrength: 0.51,
    stationarySplatDyeStrength: 0.51,
    stationarySplatForce: 4200,
    stationarySplatDirectionStrength: 0.0005,
    stationarySplatDirectionAngle: 270,
    stationarySplatCount: 10,
    stationarySplats: [
      {
        x: 0.5,
        y: 0.45,
      },
      {
        x: 0.5,
        y: 0.55,
      },
      {
        x: 0.5,
        y: 0.65,
      },
      {
        x: 0.5,
        y: 0.75,
      },
      {
        x: 0.4,
        y: 0.5,
      },
      {
        x: 0.4,
        y: 0.6,
      },
      {
        x: 0.4,
        y: 0.7,
      },
      {
        x: 0.6,
        y: 0.5,
      },
      {
        x: 0.6,
        y: 0.6,
      },
      {
        x: 0.6,
        y: 0.7,
      },
    ],
    stationaryDebugMarkersEnabled: true,
    stationaryDebugMarkerCount: 7,
    stationaryDebugMarkers: [
      {
        x: 0.5,
        y: 0.5,
      },
      {
        x: 0.5,
        y: 0.6,
      },
      {
        x: 0.5,
        y: 0.7,
      },
      {
        x: 0.4,
        y: 0.55,
      },
      {
        x: 0.4,
        y: 0.65,
      },
      {
        x: 0.6,
        y: 0.55,
      },
      {
        x: 0.6,
        y: 0.65,
      },
    ],
    handsMaxHands: 1,
    handsShowVideo: false,
    handsShowDebugSkeleton: false,
    handsLandmarkColor: '#ff3366',
    handsConnectorColor: '#00ffaa',
    handsLandmarkRadius: 4,
    handsConnectorLineWidth: 3,
    handsModelComplexity: 1,
    handsMinDetectionConfidence: 0.6,
    handsMinTrackingConfidence: 0.6,
    handsXScale: 4,
    handsYScale: 3,
    handsZScale: 5,
    handsInvertX: false,
    handsInvertY: false,
    gesturesEnabled: true,
    shading: true,
    bloom: true,
    bloomResolution: 0.2,
    bloomIterations: 4,
    bloomIntensity: 0.5,
    bloomThreshold: 0.62,
    bloomSoftKnee: 0.7,
    sunrays: true,
    sunraysResolution: 0.16,
    sunraysWeight: 0.9,
    colorA: '#ff0000',
    colorB: '#ff0000',
    colorC: '#7b0000',
    colorful: true,
    colorUpdateSpeed: 20,
    colorCycleSpeed: 0.55,
    bgA: '#4b4b4b',
    bgB: '#797979',
    dithering: false,
    ditherStrength: 2.85,
    ditherScale: 1,
    brightness: 1.7600000000000002,
    contrast: 1.0899999999999999,
    saturation: 1.6400000000000001,
    blendMode: 0,
    debugCursor: true,
    debugAutoSplat: true,
    debugStationarySplat: true,
    debugRandomBurst: true,
    debugPointerColor: '#ffffff',
    debugAutoColor: '#000000',
    debugAutoWidth: 0.01,
    debugAutoHeight: 0.01,
    debugPointerWidth: 0.024,
    debugPointerHeight: 0.024,
    debugPointerLineWeight: 1,
    debugPointerFill: false,
    debugPointerRotation: 45,
    debugAutoLineWeight: 1,
    debugAutoFill: true,
    debugAutoRotation: 45,
    debugStationarySplatColor: '#000000',
    debugStationarySplatWidth: 0.05,
    debugStationarySplatHeight: 0.05,
    debugStationarySplatLineWeight: 1,
    debugStationarySplatFill: false,
    debugStationarySplatRotation: 45,
    debugStationaryMarkerColor: '#000000',
    debugStationaryMarkerWidth: 0.05,
    debugStationaryMarkerHeight: 0.05,
    debugStationaryMarkerLineWeight: 1,
    debugStationaryMarkerFill: true,
    debugStationaryMarkerRotation: 45,
    debugRandomColor: '#7c3aed',
    debugRandomWidth: 0.03,
    debugRandomHeight: 0.03,
    debugRandomLineWeight: 1,
    debugRandomFill: true,
    debugRandomRotation: 45,
    debugContactFadeDuration: 0.28,
  },
  watercolorSquares_blue: {
    paused: false,
    simResolution: 0.98,
    pressureRelax: 0.84,
    pressureIterations: 14,
    vorticity: 54,
    velocityDissipation: 0.4,
    densityDissipation: 1.6,
    splatRadius: 0.0005,
    autoSplatRadius: 0.0005,
    stationarySplatRadius: 0.0005,
    randomSplatRadius: 0.0022,
    splatForce: 4200,
    dyeStrength: 0.25,
    inputMode: 'pointer',
    testMode: 'plane',
    autoSplat: false,
    autoSplatStrength: 0.029999999999999916,
    autoSplatDyeStrength: 2.5,
    autoSplatForce: 950,
    autoSplatRate: 100,
    autoSplatRange: 1,
    autoSplatBurst: 4,
    autoSplatCount: 2,
    autoSplatStarts: [
      {
        x: 0.5,
        y: 0.4,
      },
      {
        x: 0.5,
        y: 0.5,
      },
    ],
    randomSplatStrength: 1,
    randomSplatDyeStrength: 1.71,
    randomSplatForce: 4200,
    stationarySplatsEnabled: true,
    stationarySplatStrength: 0.51,
    stationarySplatDyeStrength: 0.51,
    stationarySplatForce: 4200,
    stationarySplatDirectionStrength: 0.0005,
    stationarySplatDirectionAngle: 270,
    stationarySplatCount: 10,
    stationarySplats: [
      {
        x: 0.5,
        y: 0.45,
      },
      {
        x: 0.5,
        y: 0.55,
      },
      {
        x: 0.5,
        y: 0.65,
      },
      {
        x: 0.5,
        y: 0.75,
      },
      {
        x: 0.4,
        y: 0.5,
      },
      {
        x: 0.4,
        y: 0.6,
      },
      {
        x: 0.4,
        y: 0.7,
      },
      {
        x: 0.6,
        y: 0.5,
      },
      {
        x: 0.6,
        y: 0.6,
      },
      {
        x: 0.6,
        y: 0.7,
      },
    ],
    stationaryDebugMarkersEnabled: true,
    stationaryDebugMarkerCount: 7,
    stationaryDebugMarkers: [
      {
        x: 0.5,
        y: 0.5,
      },
      {
        x: 0.5,
        y: 0.6,
      },
      {
        x: 0.5,
        y: 0.7,
      },
      {
        x: 0.4,
        y: 0.55,
      },
      {
        x: 0.4,
        y: 0.65,
      },
      {
        x: 0.6,
        y: 0.55,
      },
      {
        x: 0.6,
        y: 0.65,
      },
    ],
    handsMaxHands: 1,
    handsShowVideo: false,
    handsShowDebugSkeleton: false,
    handsLandmarkColor: '#ff3366',
    handsConnectorColor: '#00ffaa',
    handsLandmarkRadius: 4,
    handsConnectorLineWidth: 3,
    handsModelComplexity: 1,
    handsMinDetectionConfidence: 0.6,
    handsMinTrackingConfidence: 0.6,
    handsXScale: 4,
    handsYScale: 3,
    handsZScale: 5,
    handsInvertX: false,
    handsInvertY: false,
    gesturesEnabled: true,
    shading: true,
    bloom: true,
    bloomResolution: 0.2,
    bloomIterations: 4,
    bloomIntensity: 0.5,
    bloomThreshold: 0.62,
    bloomSoftKnee: 0.7,
    sunrays: true,
    sunraysResolution: 0.16,
    sunraysWeight: 0.9,
    colorA: '#0000ff',
    colorB: '#8c00ff',
    colorC: '#ffffff',
    colorful: true,
    colorUpdateSpeed: 20,
    colorCycleSpeed: 0.55,
    bgA: '#4b4b4b',
    bgB: '#797979',
    dithering: false,
    ditherStrength: 2.85,
    ditherScale: 1,
    brightness: 1.7600000000000002,
    contrast: 1.0899999999999999,
    saturation: 1.6400000000000001,
    blendMode: 0,
    debugCursor: true,
    debugAutoSplat: true,
    debugStationarySplat: true,
    debugRandomBurst: true,
    debugPointerColor: '#ffffff',
    debugAutoColor: '#000000',
    debugAutoWidth: 0.01,
    debugAutoHeight: 0.01,
    debugPointerWidth: 0.024,
    debugPointerHeight: 0.024,
    debugPointerLineWeight: 1,
    debugPointerFill: false,
    debugPointerRotation: 45,
    debugAutoLineWeight: 1,
    debugAutoFill: true,
    debugAutoRotation: 45,
    debugStationarySplatColor: '#000000',
    debugStationarySplatWidth: 0.05,
    debugStationarySplatHeight: 0.05,
    debugStationarySplatLineWeight: 1,
    debugStationarySplatFill: false,
    debugStationarySplatRotation: 45,
    debugStationaryMarkerColor: '#000000',
    debugStationaryMarkerWidth: 0.05,
    debugStationaryMarkerHeight: 0.05,
    debugStationaryMarkerLineWeight: 1,
    debugStationaryMarkerFill: true,
    debugStationaryMarkerRotation: 45,
    debugRandomColor: '#7c3aed',
    debugRandomWidth: 0.03,
    debugRandomHeight: 0.03,
    debugRandomLineWeight: 1,
    debugRandomFill: true,
    debugRandomRotation: 45,
    debugContactFadeDuration: 0.28,
  },
};

export {
  DEBUG_CONTACT_CAP,
  DEBUG_CONTACT_TTL_DEFAULT,
  RANDOM_BURST_COUNT,
  BLEND_MODE_ADDITIVE,
  BLEND_MODE_MULTIPLY,
  BLEND_MODE_SUBTRACTIVE,
  FLUID_PRESETS,
};
