export const HALO_PRESET_ORDER = [
  'Default Rings',
  'Gradient Rings',
  'Atomic',
  'Network',
  'Record',
  'Plate',
  'Static',
];

export const PRESETS = {
  'Default Rings': {
    backgroundColor: '#ffffff',
    haloType: 'rings',
    bloomEnabled: false,
    wobble: false,
    floatSpeed: 0,
    ringsPosition: { x: 0, y: 1.5, z: -1 },
    ringsRotation: { x: 45, y: 0, z: 0 },
    ringsVisible: true,
    ringsScale: 0.9,
    ringsStyle: 'default',
    ringsInnerRadius: 0.5,
    ringsOuterRadius: 2,
    ringsSm: 0.1,
    ringsMed: 1,
    ringsLg: 2,
    ringsXl: 3,
    ringsSilver: '#c1c1c1',
    ringsWhite: '#ffffff',
    ringsBlack: '#000000',
    ringsBlue: '#0023ff',
    ringsLightblue: '#69d8ff',
  },
  'Gradient Rings': {
    backgroundColor: '#ffffff',
    haloType: 'rings',
    bloomEnabled: false,
    wobble: false,
    floatSpeed: 0,
    ringsPosition: { x: 0, y: 1.5, z: -1 },
    ringsRotation: { x: 45, y: 0, z: 0 },
    ringsVisible: true,
    ringsScale: 0.9,
    ringsStyle: 'gradient',
    ringsInnerRadius: 0.5,
    ringsOuterRadius: 2,
    ringsStart: '#FFFFFF',
    ringsEnd: '#000000',
    ringsSteps: 8,
  },
  Atomic: {
    backgroundColor: '#ffffff',
    haloType: 'atomic',
    bloomEnabled: false,
    censorPanelVisible: false,
    wobble: false,
    floatSpeed: 0,
    atomPosition: { x: 0, y: 1.5, z: -1 },
    atomRotation: { x: 45, y: 0, z: 0 },
    atomVisible: true,
    animate: false,
    atomScale: 1.05,
    atomicNumber: 8,
    atomAnimateElectrons: true,
    atomShellSpacing: 0.65,
  },
  Network: {
    backgroundColor: '#ffffff',
    haloType: 'network',
    bloomEnabled: false,
    censorPanelVisible: false,
    wobble: false,
    floatSpeed: 0,
    networkPosition: { x: 0, y: 1.5, z: -1 },
    networkRotation: { x: 45, y: 0, z: 0 },
    networkVisible: true,
    animate: false,
    networkScale: 0.53,
    networkPointColor: '#ff0000',
    networkLineColor: '#000000',
    networkPointSize: 5,
    networkParticleCount: 500,
    networkMaxDistance: 0.8,
    networkAngularSpeed: 0.53,
    networkTimeScale: 0.4,
  },
  Record: {
    backgroundColor: '#ffffff',
    haloType: 'record',
    bloomEnabled: false,
    censorPanelVisible: false,
    floatSpeed: 0,
    recordPosition: { x: 0, y: 1.5, z: -1 },
    recordRotation: { x: 45, y: 0, z: 0 },
    recordVisible: true,
    recordScale: 12,
    recordSideA: true,
    animate: true,
    wobble: true,
    speed: 33,
  },
  Plate: {
    backgroundColor: '#ffffff',
    haloType: 'plate',
    bloomEnabled: false,
    censorPanelVisible: false,
    floatSpeed: 0,
    platePosition: { x: 0, y: 1.5, z: -1 },
    plateRotation: { x: 45, y: 0, z: 1 },
    plateVisible: true,
    plateScale: 0.18,
    animate: false,
    wobble: false,
  },
  Static: {
    backgroundColor: '#000000',
    haloType: 'crtStaticRing',
    censorPanelVisible: true,
    floatSpeed: 0,
    plPosition: { x: 2.8, y: 2.4, z: 4.4 },
    plIntensity: 0,
    ambientIntensity: 0,
    plCastShadow: true,
    spotlightEnabled: true,
    spotlightPosition: { x: -4.5, y: 2.4, z: -5 },
    spotlightAngle: 0.4,
    spotlightPenumbra: 1,
    spotlightIntensity: 10,
    spotlightColor: '#005eff',
    spotlightCastShadow: false,
    environmentIntensity: 0.04,
    bloomEnabled: true,
    bloomIntensity: 1.1,
    bloomLuminanceThreshold: 0.3,
    bloomLuminanceSmoothing: 0.28,
    bloomRadius: 0.68,
    crtStaticRingVignette: 0.92,
    crtStaticRingPosition: { x: 0, y: 1.5, z: -1 },
    crtStaticRingRotation: { x: 45, y: 0, z: 0 },
    crtStaticRingVisible: true,
    crtStaticRingScale: 0.9,
    crtStaticRingInnerRadius: 0.5,
    crtStaticRingOuterRadius: 2,
    crtStaticRingSnowScale: 90,
    crtStaticRingSnowSpeed: 5,
    crtStaticRingSnowSize: 100,
    animate: false,
    wobble: false,
  },
};
