import { folder, useControls } from 'leva';

import { imageFile } from '../../../../../../utils/appUtils';
import { PATTERN_TYPES } from '../components/WebGPUOutline';

export const TEXTURE_OPTIONS = {
  None: 'None',
  'Turbo Flex': imageFile('turbo_flex.png'),
  Squares: imageFile('squares.png'),
  FYC: imageFile('fyc.png'),
  'FYC 2': imageFile('fyc2.png'),
  Bret: imageFile('bret.png'),
  'Bret (circled)': imageFile('bret-circled.png'),
  Reversal: imageFile('reversal.png'),
  'Reversal Inner': imageFile('reversal-inner.png'),
  'Reversal Outer': imageFile('reversal-outer-empty.png'),
};

export const TEXTURE_URLS = Object.values(TEXTURE_OPTIONS);

export default function useSceneControls() {
  return useControls({
    Orientation: folder({
      rotateX: {
        value: -15,
        min: -180,
        max: 180,
        step: 1,
        label: 'Rotate X (deg)',
      },
      rotateY: {
        value: 0,
        min: -180,
        max: 180,
        step: 1,
        label: 'Rotate Y (deg)',
      },
      rotateZ: {
        value: 15,
        min: -90,
        max: 90,
        step: 1,
        label: 'Rotate Z (deg)',
      },
      posX: {
        value: 0,
        min: -2,
        max: 2,
        step: 0.01,
        label: 'Position X',
      },
      posY: {
        value: 0,
        min: -2,
        max: 2,
        step: 0.01,
        label: 'Position Y',
      },
    }),
    Wind: folder({
      wind: { value: 4.7, min: 0, max: 5, step: 0.1, label: 'Strength' },
      windDirX: {
        value: 1,
        min: -1,
        max: 1,
        step: 0.01,
        label: 'Direction X',
      },
      windDirZ: {
        value: -0.2,
        min: -1,
        max: 1,
        step: 0.01,
        label: 'Direction Z',
      },
    }),
    Cloth: folder({
      clothWidth: {
        value: 1.0,
        min: 0.2,
        max: 3.0,
        step: 0.05,
        label: 'Width',
      },
      clothHeight: {
        value: 0.7,
        min: 0.2,
        max: 3.0,
        step: 0.05,
        label: 'Height',
      },
      segmentsX: {
        value: 30,
        min: 5,
        max: 80,
        step: 1,
        label: 'Segments X',
      },
      segmentsY: {
        value: 21,
        min: 5,
        max: 80,
        step: 1,
        label: 'Segments Y',
      },
      stiffness: {
        value: 0.5,
        min: 0.1,
        max: 0.5,
        step: 0.01,
        label: 'Stiffness',
      },
      dampening: {
        value: 0.98,
        min: 0.9,
        max: 1.0,
        step: 0.001,
        label: 'Dampening',
      },
    }),
    Tatter: folder({
      tatterSeed: {
        value: 42,
        min: 0,
        max: 200,
        step: 1,
        label: 'Seed',
      },
      tatterScale: {
        value: 3,
        min: 0.5,
        max: 10,
        step: 0.1,
        label: 'Scale',
      },
      tatterEdge: {
        value: 0,
        min: 0,
        max: 1,
        step: 0.01,
        label: 'Edge Amount',
      },
      tatterHoles: {
        value: 0,
        min: 0,
        max: 1,
        step: 0.01,
        label: 'Holes Amount',
      },
    }),
    Debug: folder({
      paused: { value: false, label: 'Pause Sim' },
      wireframe: { value: false, label: 'Wireframe' },
      sphere: { value: true, label: 'Cursor Sphere' },
      sphereWireframe: { value: false, label: 'Show Sphere' },
      sphereColor: { value: '#ff0000', label: 'Sphere Color' },
      sphereRadius: {
        value: 0.12,
        min: 0.02,
        max: 0.4,
        step: 0.01,
        label: 'Sphere Radius',
      },
    }),
    'Flag Material': folder({
      textureUrl: {
        value: 'None',
        options: TEXTURE_OPTIONS,
        label: 'Texture',
      },
      textureScaleX: {
        value: 1,
        min: 0.1,
        max: 5,
        step: 0.05,
        label: 'Texture Scale X',
      },
      textureScaleY: {
        value: 1,
        min: 0.1,
        max: 5,
        step: 0.05,
        label: 'Texture Scale Y',
      },
      textureRotation: {
        value: 0,
        min: -180,
        max: 180,
        step: 1,
        label: 'Texture Rotation',
      },
      color: { value: '#f5f0e8', label: 'Color' },
      roughness: {
        value: 0.65,
        min: 0,
        max: 1,
        step: 0.01,
        label: 'Roughness',
      },
      metalness: {
        value: 0.0,
        min: 0,
        max: 1,
        step: 0.01,
        label: 'Metalness',
      },
      opacity: {
        value: 1.0,
        min: 0,
        max: 1,
        step: 0.01,
        label: 'Opacity',
      },
      sheen: { value: 0, min: 0, max: 1, step: 0.01, label: 'Sheen' },
      sheenRoughness: {
        value: 0.5,
        min: 0,
        max: 1,
        step: 0.01,
        label: 'Sheen Roughness',
      },
      sheenColor: { value: '#ffffff', label: 'Sheen Color' },
      clearcoat: {
        value: 0.0,
        min: 0,
        max: 1,
        step: 0.01,
        label: 'Clearcoat',
      },
      clearcoatRoughness: {
        value: 0.0,
        min: 0,
        max: 1,
        step: 0.01,
        label: 'Clearcoat Roughness',
      },
      transmission: {
        value: 0.0,
        min: 0,
        max: 1,
        step: 0.01,
        label: 'Transmission',
      },
      ior: {
        value: 1.5,
        min: 1.0,
        max: 2.5,
        step: 0.01,
        label: 'IOR',
      },
      thickness: {
        value: 0.0,
        min: 0,
        max: 2,
        step: 0.01,
        label: 'Thickness',
      },
    }),
    Pole: folder({
      poleColor: { value: '#c4c4c4', label: 'Color' },
      poleMetalness: {
        value: 0.6,
        min: 0,
        max: 1,
        step: 0.01,
        label: 'Metalness',
      },
      poleRoughness: {
        value: 0.4,
        min: 0,
        max: 1,
        step: 0.01,
        label: 'Roughness',
      },
    }),
    Finial: folder({
      finialColor: { value: '#efcb5f', label: 'Color' },
      finialMetalness: {
        value: 0.7,
        min: 0,
        max: 1,
        step: 0.01,
        label: 'Metalness',
      },
      finialRoughness: {
        value: 0.3,
        min: 0,
        max: 1,
        step: 0.01,
        label: 'Roughness',
      },
    }),
    Rings: folder({
      ringColor: { value: '#c4c4c4', label: 'Color' },
      ringMetalness: {
        value: 0.8,
        min: 0,
        max: 1,
        step: 0.01,
        label: 'Metalness',
      },
      ringRoughness: {
        value: 0.3,
        min: 0,
        max: 1,
        step: 0.01,
        label: 'Roughness',
      },
    }),
    Scene: folder({
      orbitControls: { value: false, label: 'Orbit Controls' },
      bgColor: { value: '#838383', label: 'Background' },
      fogNear: { value: 5, min: 0, max: 20, step: 0.5, label: 'Fog Near' },
      fogFar: { value: 14, min: 1, max: 30, step: 0.5, label: 'Fog Far' },
      ambientIntensity: {
        value: 0.5,
        min: 0,
        max: 2,
        step: 0.01,
        label: 'Ambient',
      },
      ambientColor: { value: '#ffffff', label: 'Ambient Color' },
      keyIntensity: {
        value: 0.8,
        min: 0,
        max: 3,
        step: 0.01,
        label: 'Key Light',
      },
      keyColor: { value: '#ffffff', label: 'Key Color' },
      keyPosX: {
        value: -3,
        min: -10,
        max: 10,
        step: 0.1,
        label: 'Key Pos X',
      },
      keyPosY: {
        value: 5,
        min: 0,
        max: 10,
        step: 0.1,
        label: 'Key Pos Y',
      },
      keyPosZ: {
        value: 4,
        min: -10,
        max: 10,
        step: 0.1,
        label: 'Key Pos Z',
      },
      keyShadow: { value: true, label: 'Key Shadows' },
      fillIntensity: {
        value: 0.2,
        min: 0,
        max: 2,
        step: 0.01,
        label: 'Fill Light',
      },
      fillColor: { value: '#ffffff', label: 'Fill Color' },
      fillPosX: {
        value: 2,
        min: -10,
        max: 10,
        step: 0.1,
        label: 'Fill Pos X',
      },
      fillPosY: {
        value: 1,
        min: 0,
        max: 10,
        step: 0.1,
        label: 'Fill Pos Y',
      },
      fillPosZ: {
        value: -1,
        min: -10,
        max: 10,
        step: 0.1,
        label: 'Fill Pos Z',
      },
    }),
    Outline: folder({
      outlineEnabled: { value: true, label: 'Enabled' },
      edgeStrength: {
        value: 7,
        min: 0,
        max: 10,
        step: 0.1,
        label: 'Strength',
      },
      edgeThickness: {
        value: 2.5,
        min: 0.5,
        max: 8,
        step: 0.1,
        label: 'Thickness',
      },
      visibleEdgeColor: { value: '#3eb2ff', label: 'Color' },
      downSampleRatio: {
        value: 1,
        min: 1,
        max: 4,
        step: 1,
        label: 'Downsample',
      },
      patternType: {
        value: 'None',
        options: PATTERN_TYPES,
        label: 'Pattern',
      },
      patternScale: {
        value: 5,
        min: 0.1,
        max: 40,
        step: 0.1,
        label: 'Pattern Scale',
      },
      patternOctaves: {
        value: 3,
        min: 1,
        max: 8,
        step: 1,
        label: 'Octaves',
      },
      patternLacunarity: {
        value: 2,
        min: 1,
        max: 4,
        step: 0.1,
        label: 'Lacunarity',
      },
    }),
  });
}
