import React from 'react';

import { useGLTF } from '@react-three/drei';

import { modelFile } from '../../../utils/appUtils';
import CENTER_STORE_REF_POSITION from './sevenElevenAnchors';

export default function SevenEleven(props) {
  const { nodes, materials } = useGLTF(modelFile('/711.glb'));
  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <group
          name="Sketchfab_model"
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.029}
        >
          <group name="03objcleanermaterialmergergles">
            <mesh
              name="Object_10"
              castShadow
              receiveShadow
              geometry={nodes.Object_10.geometry}
              material={materials.B_Stack06_VB_5}
            />
            <mesh
              name="Object_100"
              castShadow
              receiveShadow
              geometry={nodes.Object_100.geometry}
              material={materials.Material__19546_10}
            />
            <mesh
              name="Object_101"
              castShadow
              receiveShadow
              geometry={nodes.Object_101.geometry}
              material={materials.Material__19546_11}
            />
            <mesh
              name="Object_102"
              castShadow
              receiveShadow
              geometry={nodes.Object_102.geometry}
              material={materials.Material__19546_12}
            />
            <mesh
              name="Object_103"
              castShadow
              receiveShadow
              geometry={nodes.Object_103.geometry}
              material={materials.B_Stack06_VB_65}
            />
            <mesh
              name="Object_104"
              castShadow
              receiveShadow
              geometry={nodes.Object_104.geometry}
              material={materials.B_Stack06_VB_66}
            />
            <mesh
              name="Object_105"
              castShadow
              receiveShadow
              geometry={nodes.Object_105.geometry}
              material={materials.B_Stack06_VB_67}
            />
            <mesh
              name="Object_106"
              castShadow
              receiveShadow
              geometry={nodes.Object_106.geometry}
              material={materials.B_Stack06_VB_68}
            />
            <mesh
              name="Object_107"
              castShadow
              receiveShadow
              geometry={nodes.Object_107.geometry}
              material={materials.B_Stack06_VB_69}
            />
            <mesh
              name="Object_111"
              castShadow
              receiveShadow
              geometry={nodes.Object_111.geometry}
              material={materials.B_Stack06_VB_71}
            />
            <mesh
              name="Object_12"
              castShadow
              receiveShadow
              geometry={nodes.Object_12.geometry}
              material={materials.B_Stack06_VB_7}
            />
            <mesh
              name="Object_17"
              castShadow
              receiveShadow
              geometry={nodes.Object_17.geometry}
              material={materials.B_Stack06_VB_12}
            />
            <mesh
              name="Object_18"
              castShadow
              receiveShadow
              geometry={nodes.Object_18.geometry}
              material={materials.B_Stack06_VB_13}
            />
            <mesh
              name="Object_19"
              castShadow
              receiveShadow
              geometry={nodes.Object_19.geometry}
              material={materials.Material__272}
            />
            <mesh
              name="Object_2"
              castShadow
              receiveShadow
              geometry={nodes.Object_2.geometry}
              material={materials.B_Stack06_VB}
            />
            <mesh
              name="Object_21"
              castShadow
              receiveShadow
              geometry={nodes.Object_21.geometry}
              material={materials.Material__19546_1}
            />
            <mesh
              name="Object_22"
              castShadow
              receiveShadow
              geometry={nodes.Object_22.geometry}
              material={materials.B_Stack06_VB_15}
            />
            <mesh
              name="Object_23"
              castShadow
              receiveShadow
              geometry={nodes.Object_23.geometry}
              material={materials.B_Stack06_VB_16}
            />
            <mesh
              name="Object_24"
              castShadow
              receiveShadow
              geometry={nodes.Object_24.geometry}
              material={materials.B_Stack06_VB_17}
            />
            <mesh
              name="Object_25"
              castShadow
              receiveShadow
              geometry={nodes.Object_25.geometry}
              material={materials.B_Stack06_VB_18}
            />
            <mesh
              name="Object_26"
              castShadow
              receiveShadow
              geometry={nodes.Object_26.geometry}
              material={materials.B_Stack06_VB_18}
            />
            <mesh
              name="Object_27"
              castShadow
              receiveShadow
              geometry={nodes.Object_27.geometry}
              material={materials.B_Stack06_VB_18}
            />
            <mesh
              name="Object_28"
              castShadow
              receiveShadow
              geometry={nodes.Object_28.geometry}
              material={materials.B_Stack06_VB_19}
            />
            <mesh
              name="Object_29"
              castShadow
              receiveShadow
              geometry={nodes.Object_29.geometry}
              material={materials.B_Stack06_VB_20}
            />
            <mesh
              name="Object_3"
              castShadow
              receiveShadow
              geometry={nodes.Object_3.geometry}
              material={materials.B_Stack06_VB_0}
            />
            <mesh
              name="Object_30"
              castShadow
              receiveShadow
              geometry={nodes.Object_30.geometry}
              material={materials.B_Stack06_VB_20}
            />
            <mesh
              name="Object_31"
              castShadow
              receiveShadow
              geometry={nodes.Object_31.geometry}
              material={materials.B_Stack06_VB_20}
            />
            <mesh
              name="Object_32"
              castShadow
              receiveShadow
              geometry={nodes.Object_32.geometry}
              material={materials.B_Stack06_VB_21}
            />
            <mesh
              name="Object_33"
              castShadow
              receiveShadow
              geometry={nodes.Object_33.geometry}
              material={materials.B_Stack06_VB_22}
            />
            <mesh
              name="Object_34"
              castShadow
              receiveShadow
              geometry={nodes.Object_34.geometry}
              material={materials.B_Stack06_VB_23}
            />
            <mesh
              name="Object_35"
              castShadow
              receiveShadow
              geometry={nodes.Object_35.geometry}
              material={materials.B_Stack06_VB_24}
            />
            <mesh
              name="Object_36"
              castShadow
              receiveShadow
              geometry={nodes.Object_36.geometry}
              material={materials.B_Stack06_VB_25}
            />
            <mesh
              name="Object_37"
              castShadow
              receiveShadow
              geometry={nodes.Object_37.geometry}
              material={materials.B_Stack06_VB_26}
            />
            <mesh
              name="Object_38"
              castShadow
              receiveShadow
              geometry={nodes.Object_38.geometry}
              material={materials.B_Stack06_VB_27}
            />
            <mesh
              name="Object_39"
              castShadow
              receiveShadow
              geometry={nodes.Object_39.geometry}
              material={materials.B_Stack06_VB_28}
            />
            <mesh
              name="Object_4"
              castShadow
              receiveShadow
              geometry={nodes.Object_4.geometry}
              material={materials.B_Stack06_VB_1}
            />
            <mesh
              name="Object_40"
              castShadow
              receiveShadow
              geometry={nodes.Object_40.geometry}
              material={materials.B_Stack06_VB_29}
            />
            <mesh
              name="Object_41"
              castShadow
              receiveShadow
              geometry={nodes.Object_41.geometry}
              material={materials.B_Stack06_VB_30}
            />
            <mesh
              name="Object_42"
              castShadow
              receiveShadow
              geometry={nodes.Object_42.geometry}
              material={materials['711_wps_007456']}
            />
            <mesh
              name="Object_43"
              castShadow
              receiveShadow
              geometry={nodes.Object_43.geometry}
              material={materials['711_wps_007456ccv']}
            />
            <mesh
              name="Object_44"
              castShadow
              receiveShadow
              geometry={nodes.Object_44.geometry}
              material={materials.B_Stack06_VB_31}
            />
            <mesh
              name="Object_45"
              castShadow
              receiveShadow
              geometry={nodes.Object_45.geometry}
              material={materials.B_Stack06_VB_32}
            />
            <mesh
              name="Object_46"
              castShadow
              receiveShadow
              geometry={nodes.Object_46.geometry}
              material={materials.B_Stack06_VB_33}
            />
            <mesh
              name="Object_48"
              castShadow
              receiveShadow
              geometry={nodes.Object_48.geometry}
              material={materials.Material__19546_2}
            />
            <mesh
              name="Object_49"
              castShadow
              receiveShadow
              geometry={nodes.Object_49.geometry}
              material={materials.B_Stack06_VB_35}
            />
            <mesh
              name="Object_5"
              castShadow
              receiveShadow
              geometry={nodes.Object_5.geometry}
              material={materials.B_Stack06_VB_2}
            />
            <mesh
              name="Object_50"
              castShadow
              receiveShadow
              geometry={nodes.Object_50.geometry}
              material={materials.B_Stack06_VB_36}
            />
            <mesh
              name="Object_51"
              castShadow
              receiveShadow
              geometry={nodes.Object_51.geometry}
              material={materials.B_Stack06_VB_37}
            />
            <mesh
              name="Object_52"
              castShadow
              receiveShadow
              geometry={nodes.Object_52.geometry}
              material={materials.B_Stack06_VB_38}
            />
            <mesh
              name="Object_53"
              castShadow
              receiveShadow
              geometry={nodes.Object_53.geometry}
              material={materials.B_Stack06_VB_39}
            />
            <mesh
              name="Object_54"
              castShadow
              receiveShadow
              geometry={nodes.Object_54.geometry}
              material={materials.B_Stack06_VB_40}
            />
            <mesh
              name="Object_55"
              castShadow
              receiveShadow
              geometry={nodes.Object_55.geometry}
              material={materials.B_Stack06_VB_41}
            />
            <mesh
              name="Object_56"
              castShadow
              receiveShadow
              geometry={nodes.Object_56.geometry}
              material={materials.COcola}
            />
            <mesh
              name="Object_57"
              castShadow
              receiveShadow
              geometry={nodes.Object_57.geometry}
              material={materials.COcolasc}
            />
            <mesh
              name="Object_58"
              castShadow
              receiveShadow
              geometry={nodes.Object_58.geometry}
              material={materials.Cashier_glass}
            />
            <mesh
              name="Object_59"
              castShadow
              receiveShadow
              geometry={nodes.Object_59.geometry}
              material={materials.Cashier_glasssss}
            />
            <mesh
              name="Object_6"
              castShadow
              receiveShadow
              geometry={nodes.Object_6.geometry}
              material={materials.Material__19546}
            />
            <mesh
              name="Object_60"
              castShadow
              receiveShadow
              geometry={nodes.Object_60.geometry}
              material={materials.Material__19546_3}
            />
            <mesh
              name="Object_61"
              castShadow
              receiveShadow
              geometry={nodes.Object_61.geometry}
              material={materials.Material__19546_4}
            />
            <mesh
              name="Object_62"
              castShadow
              receiveShadow
              geometry={nodes.Object_62.geometry}
              material={materials.Material__19546_5}
            />
            <mesh
              name="Object_63"
              castShadow
              receiveShadow
              geometry={nodes.Object_63.geometry}
              material={materials.Material__19546_6}
            />
            <mesh
              name="Object_64"
              castShadow
              receiveShadow
              geometry={nodes.Object_64.geometry}
              material={materials.Material__19546_7}
            />
            <mesh
              name="Object_65"
              castShadow
              receiveShadow
              geometry={nodes.Object_65.geometry}
              material={materials.B_Stack06_VB_42}
            />
            <mesh
              name="Object_66"
              castShadow
              receiveShadow
              geometry={nodes.Object_66.geometry}
              material={materials.B_Stack06_VB_42}
            />
            <mesh
              name="Object_67"
              castShadow
              receiveShadow
              geometry={nodes.Object_67.geometry}
              material={materials.B_Stack06_VB_42}
            />
            <mesh
              name="Object_68"
              castShadow
              receiveShadow
              geometry={nodes.Object_68.geometry}
              material={materials.FZ_t_04sglass}
            />
            <mesh
              name="Object_69"
              castShadow
              receiveShadow
              geometry={nodes.Object_69.geometry}
              material={materials.Material__368}
            />
            <mesh
              name="Object_7"
              castShadow
              receiveShadow
              geometry={nodes.Object_7.geometry}
              material={materials.Material__19546_0}
            />
            <mesh
              name="Object_70"
              castShadow
              receiveShadow
              geometry={nodes.Object_70.geometry}
              material={materials.B_Stack06_VB_43}
            />
            <mesh
              name="Object_71"
              castShadow
              receiveShadow
              geometry={nodes.Object_71.geometry}
              material={materials.B_Stack06_VB_44}
            />
            <mesh
              name="Object_72"
              castShadow
              receiveShadow
              geometry={nodes.Object_72.geometry}
              material={materials.B_Stack06_VB_45}
            />
            <mesh
              name="Object_78"
              castShadow
              receiveShadow
              geometry={nodes.Object_78.geometry}
              material={materials.Material__19546_8}
            />
            <mesh
              name="Object_79"
              castShadow
              receiveShadow
              geometry={nodes.Object_79.geometry}
              material={materials.B_Stack06_VB_51}
            />
            <mesh
              name="Object_8"
              castShadow
              receiveShadow
              geometry={nodes.Object_8.geometry}
              material={materials.B_Stack06_VB_3}
            />
            <mesh
              name="Object_80"
              castShadow
              receiveShadow
              geometry={nodes.Object_80.geometry}
              material={materials.B_Stack06_VB_52}
            />
            <mesh
              name="Object_81"
              castShadow
              receiveShadow
              geometry={nodes.Object_81.geometry}
              material={materials.B_Stack06_VB_53}
            />
            <mesh
              name="Object_82"
              castShadow
              receiveShadow
              geometry={nodes.Object_82.geometry}
              material={materials.Material__24470}
            />
            <mesh
              name="Object_86"
              castShadow
              receiveShadow
              geometry={nodes.Object_86.geometry}
              material={materials.B_Stack06_VB_57}
            />
            <mesh
              name="Object_87"
              castShadow
              receiveShadow
              geometry={nodes.Object_87.geometry}
              material={materials.B_Stack06_VB_57}
            />
            <mesh
              name="Object_88"
              castShadow
              receiveShadow
              geometry={nodes.Object_88.geometry}
              material={materials.B_Stack06_VB_57}
            />
            <mesh
              name="Object_89"
              castShadow
              receiveShadow
              geometry={nodes.Object_89.geometry}
              material={materials.B_Stack06_VB_58}
            />
            <mesh
              name="Object_9"
              castShadow
              receiveShadow
              geometry={nodes.Object_9.geometry}
              material={materials.B_Stack06_VB_4}
            />
            <mesh
              name="Object_90"
              castShadow
              receiveShadow
              geometry={nodes.Object_90.geometry}
              material={materials.B_Stack06_VB_59}
            />
            <mesh
              name="Object_91"
              castShadow
              receiveShadow
              geometry={nodes.Object_91.geometry}
              material={materials.B_Stack06_VB_60}
            />
            <mesh
              name="Object_92"
              castShadow
              receiveShadow
              geometry={nodes.Object_92.geometry}
              material={materials.B_Stack06_VB_61}
            />
            <mesh
              name="Object_93"
              castShadow
              receiveShadow
              geometry={nodes.Object_93.geometry}
              material={materials.B_Stack06_VB_62}
            />
            <mesh
              name="Object_94"
              castShadow
              receiveShadow
              geometry={nodes.Object_94.geometry}
              material={materials.B_Stack06_VB_63}
            />
            <mesh
              name="Object_95"
              castShadow
              receiveShadow
              geometry={nodes.Object_95.geometry}
              material={materials.Material__404}
            />
            <mesh
              name="Object_97"
              castShadow
              receiveShadow
              geometry={nodes.Object_97.geometry}
              material={materials.Material__19546_9}
            />
            <mesh
              name="Object_98"
              castShadow
              receiveShadow
              geometry={nodes.Object_98.geometry}
              material={materials.Stacks_A5_003vv}
            />
            <mesh
              name="Object_99"
              castShadow
              receiveShadow
              geometry={nodes.Object_99.geometry}
              material={materials.Stacks_Chshier_06_001}
            />
          </group>
        </group>
        <group
          name="CenterStoreRef"
          position={[
            CENTER_STORE_REF_POSITION.x,
            CENTER_STORE_REF_POSITION.y,
            CENTER_STORE_REF_POSITION.z,
          ]}
        />
      </group>
    </group>
  );
}

useGLTF.preload(modelFile('/711.glb'));
