const BASE = {
  cameraMode: 'orbit',
  orbitAutoRotate: true,
  orbitAutoRotateSpeed: 2,

  lightEnabled: true,
  lightAmbientEnabled: true,
  lightAmbientColor: '#8fa8c4',
  lightAmbientIntensity: 0.12,
  lightHemiEnabled: true,
  lightHemiSkyColor: '#b7cbe4',
  lightHemiGroundColor: '#12161c',
  lightHemiIntensity: 0.35,
  lightSpotEnabled: true,
  lightSpotColor: '#e9f2ff',
  lightSpotIntensity: 180,
  lightSpotPosition: { x: 0, y: 9.5, z: 0 },
  lightSpotTarget: { x: 0, y: 0, z: 0 },
  lightSpotAngle: 34,
  lightSpotPenumbra: 0.85,
  lightSpotDistance: 26,
  lightSpotDecay: 1.1,
  lightFillEnabled: false,
  lightFillColor: '#6d8cb5',
  lightFillIntensity: 0.6,

  playbackSpeed: 1,
  frontSpeed: 2.2,
  holdDuration: 0.9,
  restDuration: 3.4,
  seed: 629090,
  strikeVariance: 0.6,
  boltHeight: 5,
  branchCount: 84,
  leaderSpread: 1.4,
  stepLength: 0.016,
  channelDensity: 12,
  channelRadius: 0.04,
  followBoltTip: false,
  followBoltDamping: 2.5,
  contactDepth: 1,
  emergeArc: 0.09,

  bedCount: 200000,
  boltCapacity: 48000,
  pileMemory: 3,
  grainSize: 0.014,
  bedRadius: 3.4,
  bedDuneHeight: 0.05,
  bedThickness: 0.09,
  bedBaseY: 0,
  bedNoiseScale: 1,
  bedNoiseDrift: 0.35,
  bedSettle: 0.35,
  grainRoughness: 0.92,
  grainMetalness: 0.05,
  grainColor: '#8fa6bd',
  leaderColor: '#5f86b8',
  returnColor: '#dfeeff',

  ejectSpeed: 0.9,
  ejectLift: 1.9,
  ejectSwirl: 0.55,
  ejectFalloff: 1.4,
  grainGravity: 3.2,
  grainDrag: 0.6,
  bounceRestitution: 0.2,
  bounceFriction: 0.55,
  bounceThreshold: 0.3,
  curlStrength: 0.55,
  curlFrequency: 1.6,
  curlEvolve: 0.25,

  emissiveStrength: 3.2,
  tipFalloff: 0.35,
  channelGlow: 0.05,
  returnPeak: 1.6,
  returnSpeedScale: 4,
  returnStrokes: 3,
  returnGap: 0.18,
  returnDecay: 0.55,
  returnHold: 0.9,
  returnHoldDecay: 3.5,
  returnBranchGlow: 0,
  returnWidth: 0.5,
  ejectaGlow: 0.04,

  postEnabled: true,
  postGodraysEnabled: true,
  postGodraysDensity: 0.7,
  postGodraysMaxDensity: 0.4,
  postGodraysDistanceAttenuation: 1.2,
  postGodraysRaymarchSteps: 48,
  postGodraysBlendColor: '#e9f2ff',
  postDofEnabled: true,
  postDofFocusMode: 'target',
  postDofFocusDistance: 8,
  postDofFocalLength: 2,
  postDofBokehScale: 5,
  postDofFocusSmoothing: 4,
  postBloomEnabled: true,
  postBloomThreshold: 0.9,
  postBloomStrength: 0.35,
  postBloomRadius: 0.4,

  backgroundColor: '#05070a',
  floorColor: '#0a0d12',
  floorCenterColor: '#2a3542',
  wallLowColor: '#505152',
  wallHighColor: '#05070a',
  wallGradientStart: 0.02,
  wallGradientEnd: 0.55,
  floorGapRatio: 1,
  roomRadius: 14,
  roomHeight: 22,
  fogNear: 12,
  fogFar: 45,
};

export const DEFAULT_PRESET = 'Default';

export const PRESETS = {
  Default: { ...BASE },
  'Deep Field': {
    ...BASE,
    bedRadius: 4.6,
    bedCount: 240000,
    boltHeight: 6,
    branchCount: 96,
    frontSpeed: 1.6,
    grainSize: 0.012,
    boltCapacity: 68000,
    grainColor: '#6f8399',
    leaderColor: '#3f6fa8',
    returnColor: '#cfe6ff',
    wallLowColor: '#8fa6bd',
    wallGradientEnd: 0.35,
    floorCenterColor: '#1b232c',
    backgroundColor: '#04060b',
    restDuration: 4.2,
  },
  'Hard Light': {
    ...BASE,
    lightSpotAngle: 22,
    lightSpotIntensity: 320,
    lightSpotPenumbra: 0.45,
    lightHemiIntensity: 0.12,
    lightAmbientIntensity: 0.05,
    channelGlow: 0.02,
    emissiveStrength: 4.6,
    returnPeak: 2.4,
    grainColor: '#9fb3c6',
    leaderColor: '#7aa6d8',
    returnColor: '#ffffff',
    wallLowColor: '#e8f0fa',
    wallGradientEnd: 0.28,
    floorCenterColor: '#3b4854',
  },

  // Requested palette: pure-black grains with graphite emission, staged against
  // a high-key room so the sand and bolt read as silhouette. Note that a #000
  // albedo takes no diffuse light at all — these grains are shape and emission
  // only, with no shading or self-shadow detail.
  // Requested palette: pure-black grains with graphite emission, staged against
  // a high-key room so the sand and bolt read as silhouette. Roughness is
  // dropped well below the default because a #000 albedo takes no diffuse
  // light — without a specular response the grains are flat voids, not glossy.
  Graphite: {
    ...BASE,
    lightAmbientIntensity: 0.55,
    lightHemiIntensity: 0.8,
    lightSpotIntensity: 120,
    strikeVariance: 1,
    followBoltTip: true,
    followBoltDamping: 0.3,
    pileMemory: 8,
    grainRoughness: 0.3,
    grainMetalness: 0.25,
    grainColor: '#000000',
    leaderColor: '#2e2e2e',
    returnColor: '#525252',
    ejectSpeed: 1.5,
    ejectLift: 2.55,
    ejectSwirl: 1.2,
    bounceRestitution: 0.31,
    emissiveStrength: 6.4,
    channelGlow: 0.12,
    returnPeak: 2.4,
    returnSpeedScale: 6,
    returnHold: 1.4,
    ejectaGlow: 0,
    backgroundColor: '#656565',
    floorColor: '#656565',
    floorCenterColor: '#656565',
    wallLowColor: '#656565',
    wallHighColor: '#656565',
    wallGradientStart: 0,
    wallGradientEnd: 0.8,
    fogNear: 16,
    fogFar: 60,
  },
  Ionised: {
    ...BASE,
    grainColor: '#b6d4f2',
    leaderColor: '#3d93ea',
    returnColor: '#ffffff',
    floorCenterColor: '#22384f',
    wallLowColor: '#6f93b8',
    emissiveStrength: 4.4,
    returnPeak: 2.2,
    returnStrokes: 4,
    returnSpeedScale: 6,
    returnGap: 0.12,
    returnHoldDecay: 5,
    strikeVariance: 0.85,
    branchCount: 104,
    boltCapacity: 60000,
    frontSpeed: 2.8,
    ejectSwirl: 0.9,
  },
  'Dust Storm': {
    ...BASE,
    bedRadius: 4.4,
    bedCount: 240000,
    bedDuneHeight: 0.085,
    bedNoiseScale: 0.7,
    bedNoiseDrift: 0.9,
    ejectSpeed: 1.5,
    ejectLift: 2.8,
    ejectSwirl: 1.3,
    curlStrength: 1.1,
    curlFrequency: 2.2,
    grainDrag: 0.9,
    bounceRestitution: 0.28,
    grainColor: '#727f8c',
    leaderColor: '#5b7386',
    returnColor: '#c2d2e0',
    floorCenterColor: '#2c343b',
    wallLowColor: '#8d959c',
    backgroundColor: '#070809',
    emissiveStrength: 2.4,
    fogNear: 7,
    fogFar: 32,
  },
  'Single Stroke': {
    ...BASE,
    strikeVariance: 0.15,
    branchCount: 34,
    leaderSpread: 0.85,
    frontSpeed: 1.3,
    returnStrokes: 1,
    returnSpeedScale: 2.5,
    returnPeak: 2.8,
    returnHold: 1.8,
    returnHoldDecay: 1.6,
    holdDuration: 1.8,
    restDuration: 5.5,
    pileMemory: 5,
    channelGlow: 0.02,
    ejectSpeed: 0.65,
    ejectLift: 1.4,
    grainColor: '#98a3ab',
    leaderColor: '#6b8296',
    returnColor: '#e8f0f6',
    floorCenterColor: '#242c33',
    wallLowColor: '#aeb9c2',
  },
  // A deep bed raised clear of the floor, thrown hard: ejection speed and lift
  // are 4x and 3x the default with most of the distance falloff removed, so the
  // shock front carries sand right to the rim. Note the ejecta reach roughly
  // bolt height at the contact point by design, and the pool is ~638k grains —
  // nearly double the default, and the heaviest preset here.
  'Big Impact': {
    ...BASE,
    bedCount: 350000,
    bedThickness: 0.4,
    bedBaseY: 0.5,
    pileMemory: 6,
    ejectSpeed: 4,
    ejectLift: 6,
    ejectFalloff: 0.4,
    bounceRestitution: 0.62,
    bounceFriction: 0.35,
    grainColor: '#869cb5',
    leaderColor: '#4a7ec4',
    returnColor: '#eaf6ff',
    floorCenterColor: '#33414f',
    wallLowColor: '#5c6c7c',
  },
};

export function getPresetControls({ presetSnapshot }) {
  return { ...presetSnapshot };
}
