const BASE = {
  cameraMode: 'spline',
  orbitAutoRotate: true,
  orbitAutoRotateSpeed: 2,
  lightEnabled: true,
  lightAmbientEnabled: false,
  lightAmbientColor: '#8fa8c4',
  lightAmbientIntensity: 0.55,
  lightHemiEnabled: false,
  lightHemiSkyColor: '#b7cbe4',
  lightHemiGroundColor: '#12161c',
  lightHemiIntensity: 0.8,
  lightSpotEnabled: true,
  lightSpotColor: '#ffffff',
  lightSpotIntensity: 60,
  lightSpotPosition: { x: 0, y: 9.5, z: 0 },
  lightSpotTarget: { x: 0, y: 0, z: 0 },
  lightSpotAngle: 34,
  lightSpotPenumbra: 0.85,
  lightSpotDistance: 26,
  lightSpotDecay: 1.1,
  lightFillEnabled: false,
  lightFillColor: '#6d8cb5',
  lightFillIntensity: 0.6,
  playbackSpeed: 1,
  frontSpeed: 2.2,
  holdDuration: 0.9,
  restDuration: 3.4,
  seed: 629090,
  strikeVariance: 1,
  boltHeight: 5,
  branchCount: 84,
  leaderSpread: 1.4,
  stepLength: 0.016,
  channelDensity: 12,
  channelRadius: 0.04,
  followBoltTip: true,
  followBoltDamping: 0.3,
  followBoltLateral: 0,
  contactDepth: 1,
  emergeArc: 0.09,
  bedCount: 200000,
  boltCapacity: 48000,
  pileMemory: 8,
  grainSize: 0.014,
  bedRadius: 3.4,
  bedDuneHeight: 0.05,
  bedThickness: 0.09,
  bedBaseY: 0,
  bedNoiseScale: 1,
  bedNoiseDrift: 0.35,
  bedSettle: 0.35,
  grainRoughness: 0.3,
  grainMetalness: 0.25,
  grainColor: '#000000',
  grainColorB: '#6f8399',
  grainColorC: '#c7d4e2',
  grainPaletteMix: 0,
  grainPaletteSplitB: 0.55,
  grainPaletteSplitC: 0.85,
  leaderColor: '#2e2e2e',
  returnColor: '#525252',
  ejectSpeed: 1.5,
  ejectLift: 2.55,
  ejectSwirl: 1.8,
  ejectFalloff: 1.4,
  grainGravity: 3.2,
  grainDrag: 0.6,
  bounceRestitution: 0.31,
  bounceFriction: 0.55,
  bounceThreshold: 0.3,
  curlStrength: 1.35,
  curlFrequency: 1.6,
  curlEvolve: 0.25,
  emissiveStrength: 6.4,
  tipFalloff: 0.35,
  channelGlow: 0.12,
  returnPeak: 2.4,
  returnSpeedScale: 6,
  returnStrokes: 3,
  returnGap: 0.18,
  returnDecay: 0.55,
  returnHold: 1.4,
  returnHoldDecay: 3.5,
  returnBranchGlow: 0,
  returnWidth: 0.5,
  ejectaGlow: 0,
  postEnabled: true,
  postGodraysEnabled: true,
  postGodraysDensity: 0.7,
  postGodraysMaxDensity: 0.4,
  postGodraysDistanceAttenuation: 1.2,
  postGodraysRaymarchSteps: 48,
  postGodraysBlendColor: '#e9f2ff',
  postDofEnabled: true,
  postDofFocusMode: 'target',
  postDofFocusDistance: 8,
  postDofFocalLength: 2,
  postDofBokehScale: 2,
  postDofFocusSmoothing: 4,
  postBloomEnabled: true,
  postBloomThreshold: 0.9,
  postBloomStrength: 0.35,
  postBloomRadius: 0.4,
  backgroundColor: '#656565',
  floorColor: '#656565',
  floorCenterColor: '#656565',
  wallLowColor: '#656565',
  wallHighColor: '#656565',
  wallGradientStart: 0,
  wallGradientEnd: 0.8,
  floorGapRatio: 1,
  roomRadius: 14,
  roomHeight: 22,
  fogNear: 16,
  fogFar: 60,
  splinePreset: 'Spiral Up',
  splineClosed: true,
  splineDesktopFov: 50,
  splineDesktopTarget: { x: 0, y: 0, z: 0 },
  splineDuration: 60,
  splineForwardDistance: 1,
  splineMobileFov: 50,
  splineMobileTarget: { x: 0, y: 0, z: 0 },
  splineOrientationMode: 'target',
  splinePosition: { x: 0, y: 0, z: 0 },
  splineScale: { x: 1, y: 1, z: 1 },
  splineShowPath: false,
  splineTension: 0.5,
};

export const DEFAULT_PRESET = 'Dark';

export const PRESETS = {
  Dark: { ...BASE },
  // Graphite inverted: pale glossy sand in a near-black void. The room is
  // flat like Graphite's, only at the other end of the value range, so the two
  // read as a deliberate pair rather than as different scenes.
  Light: {
    ...BASE,
    grainColor: '#e8e4dc',
    grainRoughness: 0.35,
    grainMetalness: 0.15,
    leaderColor: '#8a8a86',
    returnColor: '#ffffff',
    backgroundColor: '#0d0d0f',
    floorColor: '#0d0d0f',
    floorCenterColor: '#0d0d0f',
    wallLowColor: '#0d0d0f',
    wallHighColor: '#0d0d0f',
    lightSpotIntensity: 40,
    emissiveStrength: 4.2,
    channelGlow: 0.08,
  },
  // Same flat void and black sand as BASE, but the soft even fill is swapped
  // for a hard low key. Varies light rather than colour — the axis Graphite
  // leaves untouched — so the bed gains long shadows and hard specular glints.
  'Raking Light': {
    ...BASE,
    // cameraMode: 'orbit',
    grainRoughness: 0.22,
    grainMetalness: 0.35,
    lightAmbientIntensity: 0.08,
    lightHemiIntensity: 0.12,
    lightSpotIntensity: 40,
    lightSpotAngle: 20,
    lightSpotPenumbra: 0.25,
    lightSpotPosition: { x: 6, y: 3.2, z: 4 },
    postGodraysDensity: 1.1,
    postGodraysMaxDensity: 0.55,
  },
  // Minimum contrast: mid-grey sand in the mid-grey void, separated almost
  // entirely by specular. Where Graphite is maximum value contrast this is
  // nearly tonal, and the bolt reads as light rather than as shape.
  Pewter: {
    ...BASE,
    grainColor: '#6e6e6e',
    grainRoughness: 0.66,
    grainMetalness: 0.76,
    leaderColor: '#7d7d7d',
    returnColor: '#b8b8b8',
    lightSpotIntensity: 45,
    lightAmbientIntensity: 0.4,
    emissiveStrength: 3.4,
    channelGlow: 0.06,
    returnPeak: 1.9,
  },
  // Achromatic scene, one accent. Sand and room stay grey and only the
  // discharge carries colour — in an otherwise monochrome frame a single
  // restrained hue reads as intentional.
  Ember: {
    ...BASE,
    leaderColor: '#5a2e12',
    returnColor: '#ffb066',
    emissiveStrength: 7,
    returnPeak: 3,
    returnHold: 1.8,
    channelGlow: 0.1,
    ejectaGlow: 0.09,
    // The bolt cannot light the bed, so the sand is tied to it two other ways:
    // a warm key (the cyclorama is unlit, so the void stays neutral) and grains
    // lifted off pure black into warm minerals that have some albedo to tint.
    grainColor: '#1c1410',
    grainColorB: '#2e2015',
    grainColorC: '#0d0a08',
    grainPaletteMix: 1,
    grainPaletteSplitB: 0.52,
    grainPaletteSplitC: 0.84,
    lightSpotColor: '#ffd9b0',
    lightAmbientColor: '#c49a72',
    lightHemiSkyColor: '#e8c9a8',
    lightHemiGroundColor: '#1a120c',
    postBloomStrength: 0.5,
    postBloomThreshold: 0.8,
    postGodraysBlendColor: '#ffcf9a',
  },
  // The cold counterpart to Ember: everything shifts blue, sand included, and
  // the return stroke is the brightest thing in the frame.
  Voltaic: {
    ...BASE,
    // Same reasoning as Ember: lifted off near-black so the blue actually reads,
    // with a cool key so the bed shares the discharge's temperature.
    grainColor: '#141d28',
    grainColorB: '#0d1520',
    grainColorC: '#28394d',
    grainPaletteMix: 1,
    grainPaletteSplitB: 0.5,
    grainPaletteSplitC: 0.82,
    grainRoughness: 0.28,
    grainMetalness: 0.42,
    lightHemiSkyColor: '#a8ccf0',
    lightHemiGroundColor: '#0b131c',
    ejectaGlow: 0.06,
    leaderColor: '#1e4f8a',
    returnColor: '#9fdcff',
    backgroundColor: '#16202b',
    floorColor: '#16202b',
    floorCenterColor: '#16202b',
    wallLowColor: '#16202b',
    wallHighColor: '#16202b',
    lightSpotColor: '#cfe6ff',
    lightAmbientColor: '#8fb4d8',
    emissiveStrength: 7.5,
    returnPeak: 2.8,
    channelGlow: 0.15,
    postGodraysBlendColor: '#bfe4ff',
    postBloomStrength: 0.45,
  },
  // Tempo, not colour: one slow powerful return with a long hold, few
  // branches and almost no variance, so every strike reads the same way.
  'Single Stroke': {
    ...BASE,
    strikeVariance: 0.15,
    branchCount: 34,
    leaderSpread: 0.85,
    frontSpeed: 1.3,
    returnStrokes: 1,
    returnSpeedScale: 2.5,
    returnPeak: 2.8,
    returnHold: 1.8,
    returnHoldDecay: 1.6,
    holdDuration: 1.8,
    restDuration: 5.5,
    channelGlow: 0.02,
    ejectSpeed: 0.65,
    ejectLift: 1.4,
  },
  // A deep bed raised clear of the floor, thrown hard. Ejection speed and lift
  // are well above default with most of the distance falloff removed, so the
  // shock front carries sand to the rim — the ejecta reach roughly bolt height
  // at the contact point by design.
  'Big Impact': {
    ...BASE,
    bedCount: 350000,
    bedThickness: 0.4,
    bedBaseY: 0.5,
    pileMemory: 6,
    ejectSpeed: 4,
    ejectLift: 6,
    ejectFalloff: 0.4,
    bounceRestitution: 0.62,
    bounceFriction: 0.35,
  },
};

export function getPresetControls({ presetSnapshot }) {
  return { ...presetSnapshot };
}
