import { OCEAN_TARGET } from '../utils/targetGeometry';

export const DEFAULT_PRESET = 'Rain Ocean';

const BASE = {
  targetMode: OCEAN_TARGET,
  targetReveal: false,
  targetProbeArea: 60,
  targetScale: 1,
  targetHeight: 0,
  targetTilt: -1.2,
  targetSpinSpeed: 0.16,
  rainEnabled: true,
  rainDropCount: 400000,
  rainBounds: 140,
  rainCeiling: 60,
  rainSpawnRange: 40,
  rainFallSpeed: 26,
  rainSpeedJitter: 0.4,
  rainWindX: 0.8,
  rainWindZ: 0,
  rainStreakLength: 0.9,
  rainStreakWidth: 0.045,
  rainOpacity: 0.5,
  rainTint: '#d5e7f0',
  rainEdgeFade: 0.55,
  catchDepth: 3,
  slideGravity: 18,
  slideDrag: 2,
  slopeRelease: 1.1,
  surfaceLifeMin: 0.6,
  surfaceLifeMax: 2.5,
  stretchSpeed: 6,
  gravity: 20,
  airDrag: 1.1,
  sinkDepth: 26,
  lightX: 0,
  lightZ: -6,
  lightHeight: 62,
  lightRadius: 9,
  lightSpread: 0.42,
  lightSoftness: 1.8,
  lightReach: 95,
  lightIntensity: 1.6,
  lightAmbient: 0.08,
  lightDriftSpeed: 0.12,
  lightDriftRadius: 7,
  lightPulse: 0.22,
  oceanDisplayMode: 'Hidden',
  oceanPatchSize: 200,
  oceanPatchResolution: 192,
  oceanLodScale: 3.7,
  oceanPaletteMode: 'Monochrome',
  oceanSeaColor: '#000000',
  oceanHorizonColor: '#050505',
  oceanSkyColor: '#000000',
  oceanSunColor: '#ffffff',
  enhanceSurfaceDetails: false,
  oceanFoamStrength: 1.1,
  oceanFoamThreshold: 2.8,
  impactAreaSize: 140,
  impactDotSize: 0.55,
  impactDotStrength: 1,
  impactFoamStrength: 0.8,
  impactFoamDecay: 0.06,
  quality: 'Medium',
  pauseWater: false,
  waveUpdateHz: 30,
};

// Geometry targets are small and close, so the whole rain volume, the light
// cone and the fall-off depth shrink to match the probe area.
const GEOMETRY = {
  ...BASE,
  rainDropCount: 600000,
  rainBounds: 62,
  rainCeiling: 34,
  rainSpawnRange: 22,
  rainFallSpeed: 22,
  rainWindX: 0,
  rainStreakLength: 0.5,
  rainStreakWidth: 0.03,
  rainOpacity: 0.45,
  rainEdgeFade: 0.72,
  catchDepth: 1.6,
  slideGravity: 12,
  slideDrag: 5,
  slopeRelease: 3,
  surfaceLifeMin: 1.5,
  surfaceLifeMax: 5.5,
  stretchSpeed: 5,
  sinkDepth: 34,
  lightHeight: 40,
  lightRadius: 16,
  lightSpread: 0.3,
  lightSoftness: 1.4,
  lightReach: 78,
  lightIntensity: 1.5,
  lightAmbient: 0.1,
  lightDriftSpeed: 0.07,
  lightDriftRadius: 4,
};

// The logos are flat plates, so the reveal comes from the letterform edges and
// counters rather than from curvature: drops sheet across the face, pour off the
// downhill edge, and fall straight through the holes. A shallow tilt gives them
// somewhere to run and turns the plate toward the camera.
const LOGO = {
  ...GEOMETRY,
  targetProbeArea: 28,
  targetTilt: -0.5,
  targetSpinSpeed: 0,
  rainBounds: 54,
  rainEdgeFade: 0.8,
  rainDropCount: 700000,
  slideGravity: 30,
  slideDrag: 4,
  catchDepth: 1,
  lightRadius: 20,
  lightHeight: 44,
  orbitDesktopPosition: { x: 0, y: 26, z: 26 },
  orbitDesktopTarget: { x: 0, y: 0, z: 0 },
  orbitDesktopPivot: { x: 0, y: 0, z: 0 },
  orbitDesktopFov: 40,
  orbitMobilePosition: { x: 0, y: 32, z: 32 },
  orbitMobileTarget: { x: 0, y: 0, z: 0 },
  orbitMobilePivot: { x: 0, y: 0, z: 0 },
  orbitMobileFov: 52,
};

export const PRESETS = {
  'Rain Ocean': { ...BASE },
  Downpour: {
    ...BASE,
    rainDropCount: 700000,
    rainFallSpeed: 34,
    rainStreakLength: 1.3,
    rainOpacity: 0.6,
    surfaceLifeMax: 1.5,
    slideGravity: 30,
    slopeRelease: 0.85,
    lightRadius: 14,
    lightIntensity: 1.85,
    lightDriftSpeed: 0.2,
  },
  Drizzle: {
    ...BASE,
    rainDropCount: 180000,
    rainFallSpeed: 17,
    rainStreakLength: 0.55,
    rainStreakWidth: 0.035,
    rainOpacity: 0.42,
    surfaceLifeMin: 1.2,
    surfaceLifeMax: 4,
    slideGravity: 12,
    slideDrag: 3,
    slopeRelease: 1.4,
    lightIntensity: 1.35,
    lightDriftSpeed: 0.06,
  },
  'Rain Torus': {
    ...GEOMETRY,
    targetMode: 'Torus',
  },
  'Rain Torus Knot': {
    ...GEOMETRY,
    targetMode: 'Torus Knot',
    targetProbeArea: 52,
    targetSpinSpeed: 0.24,
  },
  'Rain Sphere': {
    ...GEOMETRY,
    targetMode: 'Sphere',
    targetProbeArea: 48,
    targetTilt: 0,
  },
  'Rain Bret': {
    ...LOGO,
    targetMode: 'Bret',
  },
  'Rain Bret Inner': {
    ...LOGO,
    targetMode: 'Bret Inner',
  },
  'Rain Reversal': {
    ...LOGO,
    targetMode: 'Reversal',
  },
  'Rain Reversal Inner': {
    ...LOGO,
    targetMode: 'Reversal Inner',
  },
  'Foam + Rain': {
    ...BASE,
    oceanDisplayMode: 'Foam Only',
    oceanFoamStrength: 1.35,
    oceanFoamThreshold: 2.9,
    impactDotSize: 0.7,
    impactDotStrength: 1.5,
    impactFoamStrength: 1.2,
    impactFoamDecay: 0.05,
    lightAmbient: 0.12,
  },
  'Visible Ocean': {
    ...BASE,
    rainDropCount: 260000,
    rainOpacity: 0.35,
    lightAmbient: 0.22,
    lightIntensity: 1.2,
    oceanDisplayMode: 'Full',
    oceanPaletteMode: 'Row It Alone',
    oceanSeaColor: '#01040c',
    oceanHorizonColor: '#6b9ed1',
    oceanSkyColor: '#143663',
    oceanSunColor: '#ffe6b8',
    enhanceSurfaceDetails: true,
    impactDotSize: 0.75,
    impactDotStrength: 1.4,
    impactFoamStrength: 1.1,
    impactFoamDecay: 0.05,
  },
  'Still Light': {
    ...BASE,
    lightDriftSpeed: 0,
    lightPulse: 0,
    rainWindX: 0,
  },
};

export function getPresetControls({ presetSnapshot }) {
  return { ...presetSnapshot };
}
