export const DEFAULT_PLOTTER_TEST_PRESET = 'low';

export function normalizePlotterTestConfig(config = {}) {
  const hatchRotX = Number(config.rotX) || 0;
  const hatchRotY = Number(config.rotY) || 0;
  const hatchRotZ = Number(config.rotZ) || 0;
  const legacyAngleOffset = Number(config.secondHatchPassAngle);
  const crossHatchAngleOffset = Number.isFinite(legacyAngleOffset)
    ? legacyAngleOffset
    : 45;
  const hatchMaxSegments =
    Number(config.hatchMaxSegments) || Number(config.maxSegments) || 700;

  return {
    ...config,
    showCrossHatches:
      config.showCrossHatches ?? config.secondHatchPass ?? false,
    hatchStrokeWidthScale: config.hatchStrokeWidthScale ?? 1,
    hatchMaxSegments,
    crossHatchRotX: config.crossHatchRotX ?? hatchRotX + crossHatchAngleOffset,
    crossHatchRotY: config.crossHatchRotY ?? hatchRotY + crossHatchAngleOffset,
    crossHatchRotZ: config.crossHatchRotZ ?? hatchRotZ + crossHatchAngleOffset,
    crossHatchSpaceX: config.crossHatchSpaceX ?? config.spaceX ?? 8,
    crossHatchSpaceY: config.crossHatchSpaceY ?? config.spaceY ?? 8,
    crossHatchSpaceZ: config.crossHatchSpaceZ ?? config.spaceZ ?? 8,
    crossHatchInsetPixels:
      config.crossHatchInsetPixels ?? config.insetPixels ?? 2,
    crossHatchConnectHatches:
      config.crossHatchConnectHatches ?? config.connectHatches ?? false,
    crossHatchMaxSegments:
      Number(config.crossHatchMaxSegments) || hatchMaxSegments,
    crossHatchStrokeWidthScale: config.crossHatchStrokeWidthScale ?? 1,
  };
}

const RAW_PLOTTER_TEST_PRESETS = {
  low: {
    theme: 'dark',
    autoRefresh: false,
    showSilhouettes: false,
    showEdges: true,
    showHatches: false,
    showCrossHatches: false,
    rotX: 0,
    rotY: 0,
    rotZ: 0,
    spaceX: 8,
    spaceY: 8,
    spaceZ: 8,
    insetPixels: 1,
    connectHatches: false,
    hatchStrokeWidthScale: 1,
    crossHatchRotX: 45,
    crossHatchRotY: 45,
    crossHatchRotZ: 45,
    crossHatchSpaceX: 8,
    crossHatchSpaceY: 8,
    crossHatchSpaceZ: 8,
    crossHatchInsetPixels: 1,
    crossHatchConnectHatches: false,
    crossHatchMaxSegments: 700,
    crossHatchStrokeWidthScale: 1,
    brightnessShading: false,
    minSpacing: 8,
    maxSpacing: 24,
    lightX: 5,
    lightY: 5,
    lightZ: 5,
    lightIntensity: 1,
    hatchMaxSegments: 700,
    interactiveDebounceMs: 260,
    fullFrameBudgetMs: 6,
    smoothThreshold: 0.985,
    silhouetteSimplifyTolerance: 1.2,
    silhouetteMinArea: 24,
    silhouetteNormalBuckets: 12,
    strokeWidth: 0.85,
    precision: 1,
    exportName: 'plotter-test-low',
  },
  medium: {
    theme: 'dark',
    autoRefresh: false,
    showSilhouettes: true,
    showEdges: true,
    showHatches: true,
    showCrossHatches: false,
    rotX: 0,
    rotY: 0,
    rotZ: 0,
    spaceX: 4,
    spaceY: 4,
    spaceZ: 5,
    insetPixels: 1.5,
    connectHatches: false,
    hatchStrokeWidthScale: 1,
    crossHatchRotX: 45,
    crossHatchRotY: 45,
    crossHatchRotZ: 45,
    crossHatchSpaceX: 4,
    crossHatchSpaceY: 4,
    crossHatchSpaceZ: 5,
    crossHatchInsetPixels: 1.5,
    crossHatchConnectHatches: false,
    crossHatchMaxSegments: 2200,
    crossHatchStrokeWidthScale: 1,
    brightnessShading: true,
    minSpacing: 3,
    maxSpacing: 10,
    lightX: 5,
    lightY: 5,
    lightZ: 5,
    lightIntensity: 1,
    hatchMaxSegments: 2200,
    interactiveDebounceMs: 320,
    fullFrameBudgetMs: 9,
    smoothThreshold: 0.995,
    silhouetteSimplifyTolerance: 0.4,
    silhouetteMinArea: 8,
    silhouetteNormalBuckets: 20,
    strokeWidth: 0.8,
    precision: 2,
    exportName: 'plotter-test-medium',
  },
  high: {
    theme: 'dark',
    autoRefresh: false,
    showSilhouettes: true,
    showEdges: true,
    showHatches: true,
    showCrossHatches: true,
    rotX: 0,
    rotY: 0,
    rotZ: 0,
    spaceX: 1,
    spaceY: 1,
    spaceZ: 1,
    insetPixels: 2,
    connectHatches: false,
    hatchStrokeWidthScale: 1,
    crossHatchRotX: 45,
    crossHatchRotY: 45,
    crossHatchRotZ: 45,
    crossHatchSpaceX: 1,
    crossHatchSpaceY: 1,
    crossHatchSpaceZ: 1,
    crossHatchInsetPixels: 2,
    crossHatchConnectHatches: false,
    crossHatchMaxSegments: 4000,
    crossHatchStrokeWidthScale: 1,
    brightnessShading: true,
    minSpacing: 1,
    maxSpacing: 4,
    lightX: 5,
    lightY: 5,
    lightZ: 5,
    lightIntensity: 1,
    hatchMaxSegments: 4000,
    interactiveDebounceMs: 360,
    fullFrameBudgetMs: 10,
    smoothThreshold: 0.999,
    silhouetteSimplifyTolerance: 0,
    silhouetteMinArea: 0,
    silhouetteNormalBuckets: 32,
    strokeWidth: 0.8,
    precision: 2,
    exportName: 'plotter-test-high',
  },
};

export const PLOTTER_TEST_PRESETS = Object.fromEntries(
  Object.entries(RAW_PLOTTER_TEST_PRESETS).map(([name, preset]) => [
    name,
    normalizePlotterTestConfig(preset),
  ])
);
