export const DEFAULT_PRESET = 'Moonlit Swarm';

export const PRESETS = {
  'Moonlit Swarm': {
    backgroundColor: '#02050d',
    toneMappingExposure: 3,
    fireflyCount: 220,
    fireflySize: 5,
    fireflyGlow: 2.5,
    fireflySpeed: 0.9,
    fireCycle: 3,
    separationRadius: 38,
    neighborRadius: 150,
    cursorMode: 'flee',
    cursorRadius: 230,
    hunterSpeed: 90,
    hunterRadius: 22,
    hunterCount: 1,
    volumeDensity: 2,
    volumeSteps: 12,
    volumeResolution: 1,
    volumeBlur: 0.6,
    volumeDenoise: true,
    volumeIntensity: 1,
    lightIntensity: 3,
  },
  'Synchronous Choir': {
    backgroundColor: '#02040a',
    toneMappingExposure: 3,
    fireflyCount: 320,
    fireflySize: 5.5,
    fireflyGlow: 3.5,
    fireflySpeed: 0.75,
    fireCycle: 2.2,
    separationRadius: 42,
    neighborRadius: 180,
    cursorMode: 'attract',
    cursorRadius: 270,
    hunterSpeed: 65,
    hunterRadius: 19,
    hunterCount: 1,
    volumeDensity: 2,
    volumeSteps: 12,
    volumeResolution: 1,
    volumeBlur: 0.6,
    volumeDenoise: true,
    volumeIntensity: 1,
    lightIntensity: 3,
  },
  'Hunters Awake': {
    backgroundColor: '#030207',
    toneMappingExposure: 3,
    fireflyCount: 260,
    fireflySize: 5,
    fireflyGlow: 3,
    fireflySpeed: 1.15,
    fireCycle: 2.6,
    separationRadius: 35,
    neighborRadius: 135,
    cursorMode: 'flee',
    cursorRadius: 250,
    hunterSpeed: 150,
    hunterRadius: 28,
    hunterCount: 3,
    volumeDensity: 2,
    volumeSteps: 12,
    volumeResolution: 1,
    volumeBlur: 0.6,
    volumeDenoise: true,
    volumeIntensity: 1,
    lightIntensity: 3,
  },
};

export function getPresetControls({ presetSnapshot }) {
  return { ...presetSnapshot };
}
