const LAYER_FADE_PRESET = {
  frame: '1',
  backgroundColor: '#050505',
  colorRangeStart: '#ff0000',
  colorRangeEnd: '#050505',
  rotate: true,
  dataScale: 0.1,
  dataPosition: { x: 0, y: 1.1, z: 0.08 },
  frameVisible: true,
  framePosition: { x: 0, y: 1.1, z: 0 },
  frameScale: 1.1,
  frameColor: '#111111',
  frameRoughness: 0.9,
  frameWatercolor: true,
  squareRoughness: 1,
  squareMetalness: 0,
  squareFlatShading: true,
  squareWatercolor: true,
  animationMode: 'layerFade',
  layerFadeLoopSeconds: 10,
  layerFadeStartA: '#ff0000',
  layerFadeStartB: '#ffffff',
  layerFadeStartC: '#000000',
  layerFadeEndA: '#000000',
  layerFadeEndB: '#2f2f2f',
  layerFadeEndC: '#ff0000',
  morseText: 'SOS',
  morseUnitSeconds: 0.2,
  morsePauseUnits: 9,
  morseColor: '#ff2020',
  morseEmissiveIntensity: 2,
  morseSeed: 7,
};

export default LAYER_FADE_PRESET;
