const MORSE_CODE_PRESET = {
  frame: '1',
  backgroundColor: '#050505',
  colorRangeStart: '#535353',
  colorRangeEnd: '#282828',
  rotate: true,
  dataScale: 0.1,
  dataPosition: { x: 0, y: 1.1, z: 0.08 },
  frameVisible: true,
  framePosition: { x: 0, y: 1.1, z: 0 },
  frameScale: 1.1,
  frameColor: '#111111',
  frameRoughness: 0.9,
  frameWatercolor: true,
  squareRoughness: 1,
  squareMetalness: 0,
  squareFlatShading: true,
  squareWatercolor: true,
  animationMode: 'morseCode',
  layerFadeLoopSeconds: 10,
  layerFadeStartA: '#ff0000',
  layerFadeStartB: '#ffffff',
  layerFadeStartC: '#000000',
  layerFadeEndA: '#000000',
  layerFadeEndB: '#2f2f2f',
  layerFadeEndC: '#ff0000',
  morseText: 'SOS',
  morseUnitSeconds: 0.22,
  morsePauseUnits: 12,
  morseColor: '#ff0000',
  morseEmissiveIntensity: 0.8,
  morseSeed: 13,
};

export default MORSE_CODE_PRESET;
