import { folder } from 'leva';

// Leva schema for AngularFlowField, keys 1:1 with its prop API
// (docs/scene-conventions.md §9) — scenes that embed it (e.g. FractalAutomata's
// Cloud + Flow Field preset, Phase 2) spread this folder's values straight
// into <AngularFlowField {...} />.
export default function getAngularFlowFieldControls(p = {}) {
  return folder({
    animationEnabled: { label: 'Animate', value: p.animationEnabled ?? true },
    length: {
      label: 'Trail Length',
      value: p.length ?? 48,
      min: 8,
      max: 256,
      step: 1,
    },
    loopEnabled: { label: 'Loop (respawn)', value: p.loopEnabled ?? true },
    renderMode: {
      label: 'Render Mode',
      value: p.renderMode ?? 'tube',
      options: ['tube', 'points'],
    },
    emitterCountX: {
      label: 'Emitters X',
      value: p.emitterCountX ?? 5,
      min: 1,
      max: 12,
      step: 1,
    },
    emitterCountY: {
      label: 'Emitters Y',
      value: p.emitterCountY ?? 3,
      min: 1,
      max: 12,
      step: 1,
    },
    emitterCountZ: {
      label: 'Emitters Z',
      value: p.emitterCountZ ?? 5,
      min: 1,
      max: 12,
      step: 1,
    },
    spacingX: {
      label: 'Spacing X',
      value: p.spacingX ?? 1.2,
      min: 0.1,
      max: 5,
      step: 0.05,
    },
    spacingY: {
      label: 'Spacing Y',
      value: p.spacingY ?? 1.2,
      min: 0.1,
      max: 5,
      step: 0.05,
    },
    spacingZ: {
      label: 'Spacing Z',
      value: p.spacingZ ?? 1.2,
      min: 0.1,
      max: 5,
      step: 0.05,
    },
    generationDistance: {
      label: 'Generation Distance',
      value: p.generationDistance ?? 0.35,
      min: 0.02,
      max: 2,
      step: 0.01,
    },
    discreteResolution: {
      label: 'Discrete Resolution',
      value: p.discreteResolution ?? 4,
      min: 1,
      max: 12,
      step: 1,
    },
    noiseScale: {
      label: 'Noise Scale',
      value: p.noiseScale ?? 0.35,
      min: 0.01,
      max: 2,
      step: 0.01,
    },
    noiseSpeed: {
      label: 'Noise Speed',
      value: p.noiseSpeed ?? 0.6,
      min: 0,
      max: 3,
      step: 0.01,
    },
    noiseStrength: {
      label: 'Noise Strength',
      value: p.noiseStrength ?? 1.2,
      min: 0,
      max: 5,
      step: 0.01,
    },
    octaves: {
      label: 'Octaves',
      value: p.octaves ?? 3,
      min: 1,
      max: 8,
      step: 1,
    },
    lacunarity: {
      label: 'Lacunarity',
      value: p.lacunarity ?? 2,
      min: 1,
      max: 4,
      step: 0.01,
    },
    gain: { label: 'Gain', value: p.gain ?? 0.5, min: 0, max: 1, step: 0.01 },
    warpStrength: {
      label: 'Warp Strength',
      value: p.warpStrength ?? 0,
      min: 0,
      max: 3,
      step: 0.01,
    },
    warpScale: {
      label: 'Warp Scale',
      value: p.warpScale ?? 1.2,
      min: 0.01,
      max: 4,
      step: 0.01,
    },
    vorticity: {
      label: 'Vorticity',
      value: p.vorticity ?? 1,
      min: 0,
      max: 4,
      step: 0.01,
    },
    attraction: {
      label: 'Attraction',
      value: p.attraction ?? 0.25,
      min: 0,
      max: 2,
      step: 0.01,
    },
    repulsion: {
      label: 'Repulsion',
      value: p.repulsion ?? 0.1,
      min: 0,
      max: 2,
      step: 0.01,
    },
    alignmentStrength: {
      label: 'Alignment Strength',
      value: p.alignmentStrength ?? 0.4,
      min: 0,
      max: 2,
      step: 0.01,
    },
    alignmentRadius: {
      label: 'Alignment Radius',
      value: p.alignmentRadius ?? 1.5,
      min: 0.05,
      max: 6,
      step: 0.05,
    },
    divergenceStrength: {
      label: 'Divergence Strength',
      value: p.divergenceStrength ?? 0,
      min: 0,
      max: 2,
      step: 0.01,
    },
    divergenceRadius: {
      label: 'Divergence Radius',
      value: p.divergenceRadius ?? 1.5,
      min: 0.05,
      max: 6,
      step: 0.05,
    },
    damping: {
      label: 'Damping',
      value: p.damping ?? 0.985,
      min: 0,
      max: 0.999,
      step: 0.001,
    },
    seed: { label: 'Seed', value: p.seed ?? 1, min: 0, max: 9999, step: 1 },
    colorMode: {
      label: 'Color Mode',
      value: p.colorMode ?? 'age',
      options: ['age', 'curvature', 'solid'],
    },
    colorStart: { label: 'Color Start', value: p.colorStart ?? '#3fd0ff' },
    colorEnd: { label: 'Color End', value: p.colorEnd ?? '#a742ff' },
    curvatureContrast: {
      label: 'Gradient Contrast',
      value: p.curvatureContrast ?? 1,
      min: 0,
      max: 4,
      step: 0.01,
    },
    curvatureBias: {
      label: 'Gradient Bias',
      value: p.curvatureBias ?? 0,
      min: -1,
      max: 1,
      step: 0.01,
    },
    gradientBlur: {
      label: 'Gradient Blur',
      value: p.gradientBlur ?? 0.35,
      min: 0,
      max: 1,
      step: 0.01,
    },
    thicknessMin: {
      label: 'Thickness Min (tube)',
      value: p.thicknessMin ?? 1,
      min: 0.1,
      max: 10,
      step: 0.1,
    },
    thicknessMax: {
      label: 'Thickness Max (tube)',
      value: p.thicknessMax ?? 3,
      min: 0.1,
      max: 10,
      step: 0.1,
    },
    thicknessSeed: {
      label: 'Thickness Seed (tube)',
      value: p.thicknessSeed ?? 7,
      min: 0,
      max: 9999,
      step: 1,
    },
    pointSize: {
      label: 'Point Size (points)',
      value: p.pointSize ?? 0.045,
      min: 0.005,
      max: 0.3,
      step: 0.005,
    },
    emissiveIntensity: {
      label: 'Emissive Intensity (tube)',
      value: p.emissiveIntensity ?? 1.2,
      min: 0,
      max: 5,
      step: 0.05,
    },
    roughness: {
      label: 'Roughness (tube)',
      value: p.roughness ?? 0.5,
      min: 0,
      max: 1,
      step: 0.01,
    },
    metalness: {
      label: 'Metalness (tube)',
      value: p.metalness ?? 0.1,
      min: 0,
      max: 1,
      step: 0.01,
    },
    opacity: {
      label: 'Opacity',
      value: p.opacity ?? 1,
      min: 0,
      max: 1,
      step: 0.01,
    },
  });
}
