// Preset snapshots — keys match the Leva schema 1:1 (docs/scene-conventions.md
// §9). Every preset spreads BASE, so all of them carry the full key set and
// switching between them never leaks a stale value from the previously
// selected one.
//
// BASE is the scene at rest AND the parameter bank: it holds a tuned baseline
// for every technique at once, with all of them switched off. Every preset
// after Pristine is BASE with exactly one toggle flipped on, and the spread is
// what enforces that — a technique's look can only be defined in BASE, so
// retuning it there is the only way to change it and no preset can silently
// carry a stale copy. A technique's parameters are inert while it is disabled,
// which is what lets all fourteen baselines coexist in one snapshot.
//
// The last two entries are the exceptions to the one-toggle rule: Slit Scan &
// Pixel Bleed is a deliberate combination, and Theatre hands the scene (and the
// camera) to the sequencer rather than enabling an effect.

export const DEFAULT_PRESET = 'Pristine';
const BASE = {
  cameraMode: 'orbit',
  cameraAutoFit: true,
  fixedBehavior: 'single',
  fixedShotDefaultDesktopPosition: {
    x: 0,
    y: 0,
    z: 5,
  },
  fixedShotDefaultDesktopTarget: {
    x: 0,
    y: 0,
    z: 0,
  },
  fixedShotDefaultDesktopFov: 50,
  fixedShotDefaultMobilePosition: {
    x: 0,
    y: 0,
    z: 5,
  },
  fixedShotDefaultMobileTarget: {
    x: 0,
    y: 0,
    z: 0,
  },
  fixedShotDefaultMobileFov: 50,
  orbitAutoRotate: false,
  orbitAutoRotateSpeed: 2,
  orbitEnablePan: true,
  orbitMinPolarAngle: 0,
  orbitMaxPolarAngle: 180,
  orbitAzimuthUnlimited: true,
  orbitMinAzimuthAngle: -180,
  orbitMaxAzimuthAngle: 180,
  orbitMinDistance: 0,
  orbitMaxDistanceUnlimited: true,
  orbitMaxDistance: 100,
  orbitDesktopPosition: {
    x: 3.6,
    y: 2.6,
    z: 2.75,
  },
  orbitDesktopTarget: {
    x: -1.2,
    y: 0.5,
    z: 0,
  },
  orbitDesktopPivot: {
    x: -1.2,
    y: 0.5,
    z: 0,
  },
  orbitDesktopFov: 50,
  orbitMobilePosition: {
    x: 4.4,
    y: 3,
    z: 3.2,
  },
  orbitMobileTarget: {
    x: -1.2,
    y: 0.5,
    z: 0,
  },
  orbitMobilePivot: {
    x: -1.2,
    y: 0.5,
    z: 0,
  },
  orbitMobileFov: 50,
  splinePreset: 'Loop de Loop',
  splineDesktopTarget: {
    x: 0,
    y: 0,
    z: 0,
  },
  splineDesktopFov: 50,
  splineMobileTarget: {
    x: 0,
    y: 0,
    z: 0,
  },
  splineMobileFov: 50,
  splineOrientationMode: 'target',
  splineForwardDistance: 1,
  splinePosition: {
    x: 0,
    y: 0,
    z: 0,
  },
  splineScale: {
    x: 1,
    y: 1,
    z: 1,
  },
  splineDuration: 30,
  splineTension: 0.5,
  splineClosed: true,
  splineShowPath: false,
  operatorMoveSpeed: 6,
  operatorLiftSpeed: 6,
  operatorBoostMultiplier: 2,
  operatorPointerLookSensitivity: 0.003,
  operatorStickLookSpeed: 2.5,
  operatorZoomSpeed: 24,
  operatorMinFov: 20,
  operatorMaxFov: 80,
  lightEnabled: true,
  lightAmbientEnabled: true,
  lightAmbientColor: '#20293a',
  lightAmbientIntensity: 0.25,
  lightKeyEnabled: false,
  lightKeyColor: '#fff4e6',
  lightKeyIntensity: 2.2,
  lightKeyAzimuth: 40,
  lightKeyElevation: 55,
  lightKeyRadius: 12,
  lightKeyTarget: {
    x: 0,
    y: 0,
    z: 0,
  },
  lightKeyCastShadow: true,
  lightKeyShadowMapSize: 2048,
  lightKeyShadowBias: -0.0005,
  lightKeyShadowNormalBias: 0,
  lightKeyShadowFar: 25,
  lightKeyShadowExtent: 8,
  lightKeyDebug: false,
  lightSpotEnabled: true,
  lightSpotColor: '#ffe7c2',
  lightSpotIntensity: 220,
  lightSpotPosition: {
    x: 1.5,
    y: 7,
    z: 2.5,
  },
  lightSpotTarget: {
    x: 0,
    y: 0.4,
    z: 0,
  },
  lightSpotAngle: 30,
  lightSpotPenumbra: 0.6,
  lightSpotDistance: 0,
  lightSpotDecay: 2,
  lightSpotCastShadow: true,
  lightSpotShadowMapSize: 2048,
  lightSpotShadowBias: -0.0005,
  lightSpotShadowNormalBias: 0,
  lightSpotShadowFar: 30,
  lightSpotDebug: false,
  lightGodrayEnabled: true,
  lightGodrayColor: '#ffe7c2',
  lightGodrayIntensity: 12,
  lightGodrayPosition: {
    x: 1.5,
    y: 7,
    z: 2.5,
  },
  lightGodrayDistance: 0,
  lightGodrayDecay: 2,
  lightGodrayCastShadow: true,
  lightGodrayShadowMapSize: 1024,
  lightGodrayShadowBias: -0.0005,
  lightGodrayShadowNormalBias: 0,
  lightGodrayShadowFar: 18,
  lightGodrayDebug: false,
  glitchCutPasteEnabled: false,
  glitchCutPasteDensity: 0.25,
  glitchCutPasteBlockSize: 60,
  glitchCutPasteShift: 3,
  glitchHopscotchEnabled: false,
  glitchHopscotchDensity: 0.25,
  glitchHopscotchOrigin: 'center',
  glitchHopscotchStride: 900,
  glitchFindReplaceEnabled: false,
  glitchDensity: 0.09,
  glitchMagnitude: 1.3,
  glitchSignFlipChance: 0.4,
  glitchUvEnabled: false,
  glitchUvBlockSize: 40,
  glitchUvShift: 8,
  glitchUvBlend: 0.04,
  glitchSlitScanEnabled: false,
  glitchSlitScanAxis: 'x',
  glitchSlitScanPosition: 0.51,
  glitchSlitScanWidth: 0.01,
  glitchSlitScanStretch: 0.2,
  glitchSlitScanCount: 2,
  glitchSlitScanSpread: 1,
  glitchModelChromaticEnabled: false,
  glitchModelChromaticAmount: 0.06,
  glitchModelChromaticSpread: 1,
  glitchScrollTearEnabled: false,
  glitchScrollTearPosition: 0.65,
  glitchScrollTearRange: 0.2,
  glitchScrollTearStrength: 1,
  glitchRowJitterEnabled: false,
  glitchRowJitterAxis: 'x',
  glitchRowJitterBands: 40,
  glitchRowJitterStrength: 0.08,
  glitchDegradeEnabled: false,
  glitchDegradeDensity: 0.76,
  glitchDegradeBlockCount: 41,
  glitchTornEnabled: false,
  glitchTornDensity: 0.46,
  glitchTornCellFrequency: 1,
  glitchTornWireframeWidth: 0.8,
  glitchTornWireColor: '#414141',
  glitchTornWireIntensity: 6,
  glitchBlockDeconstructEnabled: false,
  glitchBlockDeconstructAmount: 0.7,
  glitchBlockDeconstructTransition: 0.43,
  glitchBlockDeconstructBandwidth: 0.01,
  glitchBlockDeconstructAxis: 'y',
  glitchBlockDeconstructChaos: 0,
  glitchBlockDeconstructSize: 0.05,
  glitchBlockDeconstructCellAlpha: 0,
  glitchSliceSuiteEnabled: false,
  glitchSliceSuiteAmount: 0.8,
  glitchSliceSuiteTransition: 0.2,
  glitchSliceSuiteBandwidth: 0.5,
  glitchSliceSuiteAxis: 'x',
  glitchSliceSuiteRevealAxis: 'x',
  glitchSliceSuiteCount: 18,
  glitchSliceSuitePushApart: 0.15,
  glitchSliceSuiteTwistMax: 25,
  glitchSliceSuiteTwistSnap: 15,
  glitchSliceSuiteJitterMax: 0.05,
  glitchSliceSuiteSliceAlpha: 0.85,
  glitchVoxelSnapEnabled: false,
  glitchVoxelSnapAmount: 1,
  glitchVoxelSnapTransition: 0.36,
  glitchVoxelSnapBandwidth: 0.01,
  glitchVoxelSnapAxis: 'x',
  glitchVoxelSnapChaos: 0,
  glitchVoxelSnapSize: 0.2,
  glitchInnerStretchEnabled: false,
  glitchInnerStretchDensity: 0.25,
  glitchInnerStretchStretch: 0.35,
  glitchInnerStretchCellFrequency: 1.25,
  glitchInnerStretchSharpness: 0,
  glitchInnerStretchChaos: 0,
  glitchWarpFieldEnabled: false,
  glitchWarpFieldAmount: 0.5,
  glitchWarpFieldFrequency: 1.2,
  glitchWarpFieldSpeed: 0.4,
  glitchWireframe: false,
  vehicleCarEnabled: true,
  vehicleCarGlitch: true,
  vehicleCarPosition: {
    x: -1.2,
    y: 0,
    z: 0,
  },
  vehicleCarRotation: 60,
  vehicleVanEnabled: false,
  vehicleVanGlitch: true,
  vehicleVanPosition: {
    x: 2.6,
    y: 0,
    z: -5.5,
  },
  vehicleVanRotation: 90,
  vehicleSedanEnabled: false,
  vehicleSedanGlitch: true,
  vehicleSedanPosition: {
    x: -2.4,
    y: 0,
    z: 6.5,
  },
  vehicleSedanRotation: 4,
  backgroundColor: '#05070c',
  groundEnabled: true,
  groundSize: 90,
  groundBlockSize: 30,
  groundStreetWidth: 12,
  groundPaintColor: '#d0ccc0',
  groundPaintWidth: 1,
  groundPaintWear: 1,
  groundDashPeriod: 7,
  groundCrosswalkWidth: 5,
  groundColorDark: '#24262b',
  groundColorLight: '#3b3f46',
  groundPatchScale: 0.2,
  groundRoughness: 0.95,
  groundBump: 1,
  groundGritScale: 7,
  groundGritAmount: 0.22,
  groundStainScale: 0.45,
  groundStainAmount: 0.5,
  groundCrackScale: 1.1,
  groundCrackAmount: 0.5,
  groundWetScale: 0.14,
  groundWetAmount: 1,
  groundWetRoughness: 0.32,
  groundDetailNear: 25,
  groundDetailFar: 240,
  fogEnabled: true,
  fogColor: '#0b0f16',
  fogDensity: 0.55,
  fogNear: 4,
  fogFar: 45,
  fogBottom: -0.5,
  fogTop: 6,
  floorEnabled: false,
  floorColor: '#000000',
  floorOpacity: 0.35,
  floorSize: 20,
  postGodraysEnabled: false,
  postGodraysDensity: 1.2,
  postGodraysMaxDensity: 0.55,
  postGodraysDistanceAttenuation: 1.2,
  postGodraysRaymarchSteps: 60,
  postGodraysBlendColor: '#ffe7c2',
  postGodraysEdgeRadius: 2,
  postGodraysEdgeStrength: 2,
  postGodraysBlur: true,
  postDatamoshEnabled: false,
  postDatamoshCorruption: 0.77,
  postDatamoshDisplace: 10,
  postDatamoshBlockSize: 40,
  postDatamoshResidual: 2.17,
  postDatamoshResidualSteps: 40,
  postDatamoshVectorSnap: 4,
  postDatamoshSkipThreshold: 2.15,
  postDatamoshWrongVectors: 0.6,
  postDatamoshLossLayers: 4,
  postDatamoshLossCell: 72,
  postDatamoshLossLife: 1.27,
  postDatamoshLossChance: 0.43,
  postPixelBleedEnabled: false,
  postPixelBleedReach: 0.9,
  postPixelBleedStrength: 0.89,
  postPixelBleedAngle: 90,
  postPixelBleedOffsetR: 6,
  postPixelBleedOffsetG: 1,
  postPixelBleedOffsetB: 0.17,
  postPixelBleedHighlights: 0,
  postPixelBleedTint: '#ffffff',
  postPixelBleedTintAmount: 0,
  postPixelBleedQuality: 'full',
  postPixelBleedMotionSmear: false,
  postPixelBleedSmear: 0.85,
  postPixelBleedOrder: 'after',
  postChromaticAberrationEnabled: false,
  postChromaticAberrationStrength: 1,
  postChromaticAberrationScale: 1.5,
  postPixelSortEnabled: false,
  postPixelSortDirection: 'vertical',
  postPixelSortThreshold: 0.5,
  postPixelSortSteps: 28,
  postPixelSortStepSize: 0.005,
  postPixelSortLengthJitter: 0.5,
  postPixelSortChunkMode: 'bands',
  postPixelSortChunkAxis: 'horizontal',
  postPixelSortChunkCount: 14,
  postPixelSortChunkCross: 8,
  postPixelSortChunkCoverage: 0.45,
  postPixelSortChunkSpeed: 0,
  postPixelSortChunkSeed: 0,
  postSlitScanEnabled: false,
  postSlitScanAngle: 45,
  postSlitScanAngleJitter: 0,
  postSlitScanPosition: 0.3,
  postSlitScanWidth: 0.004,
  postSlitScanStretch: 0.45,
  postSlitScanPush: 0,
  postSlitScanSpeed: 0,
  postSlitScanJitter: 0,
  postSlitScanCount: 1,
  postSlitScanSpread: 1,
  postSlitScanChunkMode: 'bands',
  postSlitScanChunkAxis: 'horizontal',
  postSlitScanChunkCount: 8,
  postSlitScanChunkCross: 6,
  postSlitScanChunkCoverage: 0.5,
  postSlitScanChunkSpeed: 0,
  postSlitScanChunkSeed: 0,
  theatreEnabled: false,
  theatreStudioVisible: true,
  theatreHideUi: true,
  theatrePlaying: false,
  theatreLoop: true,
  theatreRate: 1,
  theatreTime: 0,
};

export const PRESETS = {
  Pristine: BASE,
  'Cut & Paste': { ...BASE, glitchCutPasteEnabled: true },
  Hopscotch: { ...BASE, glitchHopscotchEnabled: true },
  'Find & Replace': { ...BASE, glitchFindReplaceEnabled: true },
  'Texture Scramble': { ...BASE, glitchUvEnabled: true },
  'Slit Scan': { ...BASE, glitchSlitScanEnabled: true },
  'Scroll Tear': { ...BASE, glitchScrollTearEnabled: true },
  'Row Jitter': { ...BASE, glitchRowJitterEnabled: true },
  'Resolution Loss': { ...BASE, glitchDegradeEnabled: true },
  'Torn Open': { ...BASE, glitchTornEnabled: true },
  'Block Deconstruct': { ...BASE, glitchBlockDeconstructEnabled: true },
  'Slice Suite': { ...BASE, glitchSliceSuiteEnabled: true },
  'Voxel Snap': { ...BASE, glitchVoxelSnapEnabled: true },
  'Inner Stretch': { ...BASE, glitchInnerStretchEnabled: true },
  'Warp Field': { ...BASE, glitchWarpFieldEnabled: true },
  Godrays: { ...BASE, postGodraysEnabled: true },
  'Chromatic Aberration': { ...BASE, postChromaticAberrationEnabled: true },
  'Chromatic Aberration (Model)': {
    ...BASE,
    glitchModelChromaticEnabled: true,
  },
  'Pixel Sort': { ...BASE, postPixelSortEnabled: true },
  'Screen Slit Scan': { ...BASE, postSlitScanEnabled: true },
  Datamosh: { ...BASE, postDatamoshEnabled: true },
  'Pixel Bleed': { ...BASE, postPixelBleedEnabled: true },
  'Slit Scan & Pixel Bleed': {
    ...BASE,
    glitchSlitScanEnabled: true,
    postPixelBleedEnabled: true,
  },
  Theatre: { ...BASE, theatreEnabled: true },
};

export function getPresetControls({ presetSnapshot }) {
  return { ...presetSnapshot };
}
