const PRESETS = {
  Default: {
    ambientIntensity: 0,
    ambientColor: '#8e7b69',
    ambientDebug: false,
    keyIntensity: 0.28,
    keyColor: '#ffd7b4',
    keyPosition: { x: -2.2, y: 3.8, z: 2.6 },
    keyTarget: { x: 0, y: 0, z: 3 },
    keyDebug: false,
    floorFillIntensity: 0,
    floorFillColor: '#f1dcc1',
    floorFillPosition: { x: 0, y: 0.4, z: 4.6 },
    floorFillTarget: { x: 0, y: 0, z: 5.4 },
    floorFillDebug: false,
    spotIntensity: 0.16,
    spotColor: '#b88a65',
    spotPosition: { x: 2.8, y: 3.2, z: 2.2 },
    spotTarget: { x: 0, y: 0, z: 3 },
    spotAngle: 28,
    spotPenumbra: 0.8,
    spotDecay: 2,
    spotDistance: 0,
    spotDebug: false,
    projectorColor: '#d1b482',
    projectorIntensity: 280,
    projectorPosition: { x: 0, y: 4.5, z: 7 },
    projectorTarget: { x: 0, y: 2, z: 2 },
    projectorAngle: 44,
    projectorPenumbra: 0.43,
    projectorDecay: 2,
    projectorDistance: 12,
    projectorFocus: 0.47,
    projectorRepeat: { x: 2, y: 2 },
    projectorCastShadow: true,
    projectorDebug: false,
    skullPosition: { x: 0, y: 0.7, z: 0.8 },
    skullRotation: { x: 0, y: 0, z: 0 },
    leftFemurPosition: { x: 0, y: 0.45, z: 0 },
    leftFemurRotation: { x: 98, y: 3, z: 35 },
    rightFemurPosition: { x: 0, y: 0.5, z: 0 },
    rightFemurRotation: { x: -98, y: -7, z: -142 },
    desktopCameraFov: 34,
    desktopCameraPosition: { x: 0, y: 2, z: 5.6 },
    desktopCameraTarget: { x: 0, y: 0.75, z: 0.4 },
    mobileCameraFov: 55,
    mobileCameraPosition: { x: 0, y: 2.1, z: 8.6 },
    mobileCameraTarget: { x: 0, y: 0.55, z: 0.35 },
  },
};

export default PRESETS;
