/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React from 'react';

import { useGLTF } from '@react-three/drei';

import { modelFile } from '../../../utils/appUtils';

export function WhiskeyBottle(props) {
  const { nodes, materials } = useGLTF(modelFile('/whiskeyBottle.glb'));
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_114001.geometry}
        material={materials.sm32_163_DrinkBottle02A_A_Mat}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.013}
      />
    </group>
  );
}

export function BeerBottle1(props) {
  const { nodes, materials } = useGLTF(modelFile('/beerBottle1.glb'));
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_138.geometry}
        material={materials['sm32_159_DrinkBottle01A_A_Mat.001']}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.02}
      />
    </group>
  );
}

export function BeerBottle2(props) {
  const { nodes, materials } = useGLTF(modelFile('/beerBottle2.glb'));
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_140.geometry}
        material={materials['sm32_159_DrinkBottle01A_A_Mat.002']}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.018}
      />
    </group>
  );
}

useGLTF.preload(modelFile('/whiskeyBottle.glb'));
useGLTF.preload(modelFile('/beerBottle1.glb'));
useGLTF.preload(modelFile('/beerBottle2.glb'));
