/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { useEffect, useMemo } from 'react';

import { createInstances, useGLTF } from '@react-three/drei';

import { modelFile } from '../../../utils/appUtils';
import bakeInstancedGeometry from '../../../utils/instancedGeometry';

const WHISKEY_BOTTLE_MODEL_PATH = '/whiskeyBottle.glb';
const WHISKEY_BOTTLE_ROTATION = [Math.PI / 2, 0, 0];
const WHISKEY_BOTTLE_SCALE = 0.013;
const WHISKEY_BOTTLE_MATERIAL_NAME = 'sm32_163_DrinkBottle02A_A_Mat';
const WHISKEY_BOTTLE_TRANSFORM_CHAIN = [
  { rotation: WHISKEY_BOTTLE_ROTATION, scale: WHISKEY_BOTTLE_SCALE },
];

const BEER_BOTTLE_1_MODEL_PATH = '/beerBottle1.glb';
const BEER_BOTTLE_1_ROTATION = [Math.PI / 2, 0, -Math.PI / 2];
const BEER_BOTTLE_1_SCALE = 0.02;
const BEER_BOTTLE_1_MATERIAL_NAME = 'sm32_159_DrinkBottle01A_A_Mat.001';
const BEER_BOTTLE_1_TRANSFORM_CHAIN = [
  { rotation: BEER_BOTTLE_1_ROTATION, scale: BEER_BOTTLE_1_SCALE },
];

const BEER_BOTTLE_2_MODEL_PATH = '/beerBottle2.glb';
const BEER_BOTTLE_2_ROTATION = [Math.PI / 2, 0, -Math.PI / 2];
const BEER_BOTTLE_2_SCALE = 0.018;
const BEER_BOTTLE_2_MATERIAL_NAME = 'sm32_159_DrinkBottle01A_A_Mat.002';
const BEER_BOTTLE_2_TRANSFORM_CHAIN = [
  { rotation: BEER_BOTTLE_2_ROTATION, scale: BEER_BOTTLE_2_SCALE },
];

const [WhiskeyBottleInstancesRoot, WhiskeyBottleInstanceRoot] =
  createInstances();
const [BeerBottle1InstancesRoot, BeerBottle1InstanceRoot] = createInstances();
const [BeerBottle2InstancesRoot, BeerBottle2InstanceRoot] = createInstances();

export function WhiskeyBottleInstances({ children, material, ...props }) {
  const { nodes, materials } = useGLTF(modelFile(WHISKEY_BOTTLE_MODEL_PATH));
  const baseGeometry = nodes.Object_114001.geometry;
  const sourceMaterial = materials[WHISKEY_BOTTLE_MATERIAL_NAME];
  const geometry = useMemo(
    () => bakeInstancedGeometry(baseGeometry, WHISKEY_BOTTLE_TRANSFORM_CHAIN),
    [baseGeometry]
  );
  const instanceMaterial = useMemo(
    () => material ?? sourceMaterial.clone(),
    [material, sourceMaterial]
  );

  useEffect(() => {
    return () => {
      geometry.dispose?.();
    };
  }, [geometry]);

  useEffect(() => {
    if (material) {
      return undefined;
    }

    return () => {
      instanceMaterial.dispose?.();
    };
  }, [instanceMaterial, material]);

  return (
    <WhiskeyBottleInstancesRoot
      geometry={geometry}
      material={instanceMaterial}
      {...props}
    >
      {children}
    </WhiskeyBottleInstancesRoot>
  );
}

export function WhiskeyBottleInstance(props) {
  return <WhiskeyBottleInstanceRoot {...props} />;
}

export function BeerBottle1Instances({ children, material, ...props }) {
  const { nodes, materials } = useGLTF(modelFile(BEER_BOTTLE_1_MODEL_PATH));
  const baseGeometry = nodes.Object_138.geometry;
  const sourceMaterial = materials[BEER_BOTTLE_1_MATERIAL_NAME];
  const geometry = useMemo(
    () => bakeInstancedGeometry(baseGeometry, BEER_BOTTLE_1_TRANSFORM_CHAIN),
    [baseGeometry]
  );
  const instanceMaterial = useMemo(
    () => material ?? sourceMaterial.clone(),
    [material, sourceMaterial]
  );

  useEffect(() => {
    return () => {
      geometry.dispose?.();
    };
  }, [geometry]);

  useEffect(() => {
    if (material) {
      return undefined;
    }

    return () => {
      instanceMaterial.dispose?.();
    };
  }, [instanceMaterial, material]);

  return (
    <BeerBottle1InstancesRoot
      geometry={geometry}
      material={instanceMaterial}
      {...props}
    >
      {children}
    </BeerBottle1InstancesRoot>
  );
}

export function BeerBottle1Instance(props) {
  return <BeerBottle1InstanceRoot {...props} />;
}

export function BeerBottle2Instances({ children, material, ...props }) {
  const { nodes, materials } = useGLTF(modelFile(BEER_BOTTLE_2_MODEL_PATH));
  const baseGeometry = nodes.Object_140.geometry;
  const sourceMaterial = materials[BEER_BOTTLE_2_MATERIAL_NAME];
  const geometry = useMemo(
    () => bakeInstancedGeometry(baseGeometry, BEER_BOTTLE_2_TRANSFORM_CHAIN),
    [baseGeometry]
  );
  const instanceMaterial = useMemo(
    () => material ?? sourceMaterial.clone(),
    [material, sourceMaterial]
  );

  useEffect(() => {
    return () => {
      geometry.dispose?.();
    };
  }, [geometry]);

  useEffect(() => {
    if (material) {
      return undefined;
    }

    return () => {
      instanceMaterial.dispose?.();
    };
  }, [instanceMaterial, material]);

  return (
    <BeerBottle2InstancesRoot
      geometry={geometry}
      material={instanceMaterial}
      {...props}
    >
      {children}
    </BeerBottle2InstancesRoot>
  );
}

export function BeerBottle2Instance(props) {
  return <BeerBottle2InstanceRoot {...props} />;
}

export function WhiskeyBottle(props) {
  const { nodes, materials } = useGLTF(modelFile(WHISKEY_BOTTLE_MODEL_PATH));
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_114001.geometry}
        material={materials[WHISKEY_BOTTLE_MATERIAL_NAME]}
        rotation={WHISKEY_BOTTLE_ROTATION}
        scale={WHISKEY_BOTTLE_SCALE}
      />
    </group>
  );
}

export function BeerBottle1(props) {
  const { nodes, materials } = useGLTF(modelFile(BEER_BOTTLE_1_MODEL_PATH));
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_138.geometry}
        material={materials[BEER_BOTTLE_1_MATERIAL_NAME]}
        rotation={BEER_BOTTLE_1_ROTATION}
        scale={BEER_BOTTLE_1_SCALE}
      />
    </group>
  );
}

export function BeerBottle2(props) {
  const { nodes, materials } = useGLTF(modelFile(BEER_BOTTLE_2_MODEL_PATH));
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_140.geometry}
        material={materials[BEER_BOTTLE_2_MATERIAL_NAME]}
        rotation={BEER_BOTTLE_2_ROTATION}
        scale={BEER_BOTTLE_2_SCALE}
      />
    </group>
  );
}

useGLTF.preload(modelFile(WHISKEY_BOTTLE_MODEL_PATH));
useGLTF.preload(modelFile(BEER_BOTTLE_1_MODEL_PATH));
useGLTF.preload(modelFile(BEER_BOTTLE_2_MODEL_PATH));
