export const DEFAULT_PRESET = 'Rock Break';

// Everything under "the coast itself" is held identical across presets on
// purpose: those keys rebake the coastline and relay half a million grains,
// and a preset switch should change the weather, not the place.
const BASE = {
  cameraMode: 'orbit',
  orbitAutoRotate: false,
  orbitDesktopPosition: [0, 40, -3],
  orbitDesktopTarget: [0, 0, -6],
  orbitDesktopPivot: [0, 0, -6],
  orbitDesktopFov: 33,

  // The coast itself.
  shoreSeed: 12,
  coastLine: 0.72,
  coastTilt: 0.22,
  coastRagged: 0.34,
  deepDepth: 2.2,
  shelfWidth: 16,
  slopeCurve: 1,
  rockHeight: 2.4,
  rockRise: 13,
  rockRelief: 1.6,
  reefRelief: 1.1,
  stackCount: 24,
  stackSize: 1.8,
  waterline: 0.26,
  roleFeather: 0.55,
  grainCount: 500000,
  grainJitter: 1,
  solverResolution: 384,

  swellAmplitude: 0.7,
  swellPeriod: 2.6,
  swellAngle: 26,
  swellGroupRate: 0.12,
  swellDrive: 0.8,
  tideAmplitude: 0.55,
  tidePeriod: 48,

  breakLow: 0.2,
  breakHigh: 0.7,
  breakWeight: 1.4,
  steepWeight: 1.6,
  shallowDepth: 2.2,
  aerationBirth: 0.7,
  aerationDecay: 0.5,
  churnStrength: 1.8,
  churnScale: 0.5,
  churnEvolve: 0.35,
  wetDepth: 0.08,
  pipeArea: 1,
  friction: 0.03,
  bedDrag: 0.02,

  foamBirth: 0.13,
  foamDecay: 0.35,
  foamAdvect: 1,
  foamReaction: 28,
  foamSmooth: 20,
  foamJitter: 1,
  foamSpread: 2,
  foamGrain: 0.55,
  foamGrainScale: 1.3,
  foamAging: 0.3,
  foamSink: 0.45,
  foamSinkDepth: 1.5,

  waterGrainSize: 0.125,
  rockGrainSize: 0.21,
  grainSizeMin: 0.6,
  grainSizeMax: 1.5,
  flowGain: 1,
  grainResponse: 8,
  grainLife: 5,
  grainFade: 0.08,
  grainSettle: 14,
  churnLift: 0.05,
  churnRate: 2.5,
  foamLift: 0.05,
  shoreDrying: 0.35,
  foamMemory: 1.2,
  foamPickup: 12,
  flowTip: 0.18,
  rockTip: 0.9,
  tipLimit: 1.2,
  rockJag: 0.35,
  rockDepth: 0.28,

  deepColor: '#06232e',
  shallowColor: '#17707d',
  aeratedColor: '#4fc9c2',
  absorption: 0.75,
  aerationTint: 0.85,
  reefColor: '#04120f',
  reefDepth: 3.4,
  reefStrength: 0.7,
  foamColor: '#eefaf8',
  foamOldColor: '#c8e2e0',
  foamThreshold: 0.2,
  foamSoftness: 0.26,
  foamBreakup: 0.55,
  foamSwell: 1.35,
  waterRoughness: 0.14,
  foamRoughness: 0.92,
  rockDryColor: '#151a1e',
  rockWetColor: '#05080a',
  rockMottle: 0.4,
  rockRoughness: 0.9,
  grainVariance: 0.26,

  runSimulation: true,
  timeScale: 1,
  substeps: 4,
  renderScale: 1,
  backgroundColor: '#02070a',
  fogNear: 40,
  fogFar: 160,
};

export const PRESETS = {
  'Rock Break': { ...BASE },

  // Short period, hard drive, foam that outlives the wave that made it.
  'Storm Surge': {
    ...BASE,
    swellAmplitude: 1,
    swellPeriod: 2.2,
    swellGroupRate: 0.07,
    swellDrive: 0.82,
    breakWeight: 1.8,
    aerationBirth: 3.6,
    aerationDecay: 0.5,
    churnStrength: 2.6,
    foamBirth: 0.6,
    foamDecay: 0.28,
    foamSink: 0.3,
    foamThreshold: 0.08,
    flowGain: 1.25,
    grainLife: 6.5,
    tideAmplitude: 0.9,
    timeScale: 1.15,
  },

  // Long, low swell that never really breaks. The reef reads through the water
  // because there is no whitewater left covering it.
  'Slack Water': {
    ...BASE,
    swellAmplitude: 0.3,
    swellPeriod: 4.5,
    swellGroupRate: 0.06,
    aerationBirth: 1.2,
    aerationDecay: 1.1,
    churnStrength: 0.6,
    foamBirth: 0.16,
    foamDecay: 0.7,
    foamReaction: 12,
    flowGain: 0.75,
    grainLife: 8,
    tideAmplitude: 0.3,
    absorption: 0.22,
    reefStrength: 0.95,
    waterRoughness: 0.06,
    foamThreshold: 0.16,
  },

  // The reaction term driven well past what the water alone would sustain, so
  // the foam stops behaving like spray and starts behaving like the pattern in
  // PetriDish -- cells, fronts and holes holding their shape for whole sets.
  'Petri Bloom': {
    ...BASE,
    foamBirth: 0.5,
    foamDecay: 0.16,
    foamAdvect: 0.55,
    foamReaction: 52,
    foamSmooth: 22,
    foamSpread: 4,
    foamGrain: 0.75,
    foamGrainScale: 2.1,
    foamSink: 0.2,
    foamAging: 0.18,
    aerationDecay: 0.28,
    churnStrength: 3.2,
    churnScale: 0.75,
    foamThreshold: 0.1,
    foamSoftness: 0.16,
    foamBreakup: 0.3,
    aeratedColor: '#63d9cd',
  },
};

export function getPresetControls({ presetSnapshot }) {
  return { ...presetSnapshot };
}
